### PR TITLE
Add conda search --reverse-dependency

### PR DESCRIPTION
**Pull request by asmeurer**
Should provide a reasonable fix for #1378.

### CODE REVIEW

**Comment by asmeurer** [comment]
Example:

```
$conda search -f --reverse-dependency sympy
Fetching package metadata: ..............................
anaconda                     1.6.0                np17py33_0  defaults
                             1.6.0                np17py27_0  defaults
                             1.6.0                np17py26_0  defaults
                             1.6.0                np16py27_0  defaults
                             1.6.0                np16py26_0  defaults
                             1.6.1                np17py33_0  defaults
                             1.6.1                np17py27_0  defaults
                             1.6.1                np17py26_0  defaults
                             1.6.1                np16py27_0  defaults
                             1.6.1                np16py26_0  defaults
                             1.7.0                np17py33_0  defaults
                             1.7.0                np17py27_0  defaults
                             1.7.0                np17py26_0  defaults
                             1.7.0                np16py27_0  defaults
                             1.7.0                np16py26_0  defaults
                             1.8.0                np17py33_0  defaults
                             1.8.0                np17py27_0  defaults
                             1.8.0                np17py26_0  defaults
                             1.8.0                np16py27_0  defaults
                             1.8.0                np16py26_0  defaults
                             1.9.0                np18py33_0  defaults
                             1.9.0                np18py27_0  defaults
                             1.9.0                np18py26_0  defaults
                             1.9.1                np18py33_0  defaults
                             1.9.1                np18py27_0  defaults
                             1.9.1                np18py26_0  defaults
                             1.9.2                np18py33_0  defaults
                             1.9.2                np18py27_0  defaults
                             1.9.2                np18py26_0  defaults
                             2.0.0                np18py34_0  defaults
                             2.0.0                np18py33_0  defaults
                             2.0.0                np18py27_0  defaults
                             2.0.0                np18py26_0  defaults
                             2.0.1                np18py34_0  defaults
                             2.0.1                np18py33_0  defaults
                             2.0.1                np18py27_0  defaults
                             2.0.1                np18py26_0  defaults
                             2.1.0                np19py34_0  defaults
                             2.1.0                np19py33_0  defaults
                             2.1.0                np19py27_0  defaults
                             2.1.0                np19py26_0  defaults
                             2.2.0                np19py34_0  defaults
                             2.2.0                np19py33_0  defaults
                             2.2.0                np19py27_0  defaults
                             2.2.0                np19py26_0  defaults
yt                           3.0                  np18py27_0  asmeurer
                             3.0.1                np19py27_0  defaults
                             3.0.1                np18py27_0  defaults
                             3.0.2                np19py27_0  defaults
                             3.1                  np19py27_0  defaults
```

**Comment by jakirkham** [comment]
Good idea. What still remains for this to be completed?

**Comment by asmeurer** [comment]
I think it is ready to go. The Travis tests were failing because of a bug in py.test. I merged with master so they would rerun. If they pass, I will merge this.

**Comment by jakirkham** [comment]
Cool, looks like it passed.

**Comment by j9ac9k** [comment]
Thanks for adding this feature, was pulling my hair out trying to figure out what package was trying to downgrade my ipython install.

**Pull request merged**
