### PR TITLE
avoid function redefinition upon resourcing conda.fish

### PR DESCRIPTION
**Pull request by jhultman**
Addresses #9443.

### CODE REVIEW

**Comment by jhultman** [comment]
Is there no way to verify CLA without requiring contributors to expose private email address? I have github configured to "Block command line pushes that expose my email."

**Comment by msarahan** [comment]
confirmed CLA.  You're good.  It's a part-manual process.  I had to manually add your name to the special list.

@cla-bot check

**Comment by msarahan** [comment]
whatever.  Just ignore it.  I'll wait on CI here, but I think your change is fine.

**Comment by msarahan** [comment]
There are a few failures on master with the output from `conda run`.  Those are not related to your change here and are OK to ignore.

**Comment by msarahan** [comment]
Thanks @jhultman

**Pull request merged**
