### PR TITLE
Fix warnings & errors related to artifact verification

### PR DESCRIPTION
**Pull request by chenghlee**

### CODE REVIEW

**Review by jezdez — APPROVED** [review]
I would say this needs tests, but then again, I'm on them and this'll be easy to cover. 😬

**Comment by chenghlee** [comment]
Think I'm going to merge PR #10627 into this branch, fix the merge conflict, and pull in the tests from there.

**Comment by jezdez** [comment]
> Think I'm going to merge PR #10627 into this branch, fix the merge conflict, and pull in the tests from there.

Good idea.

**Comment by chenghlee** [comment]
Should address Anaconda (internal) tickets: DSNC-3276, DSNC-3303, CON-756

**Pull request merged**
