### PR TITLE
resolve #5411 add 'conda config --write-default'

### LINKED ISSUE #5411: Create a conda command to write default config values and info to condarc
It would be nice to have a way to materialize the whole spectrum of configuration options for conda in the user condarc (if empty).

`conda config --write-defaults` 

I guess this could also be used for other locations
`conda config --write-defaults --sytem` 

Something like:

image

### PR DESCRIPTION
**Pull request by kalefranz**
resolve #5411 

Adds a command `conda config --write-defaults` that creates a default, descriptive `~/.condarc` file.  The contents of the file are identical to `conda config --describe`.

### CODE REVIEW

**Comment by kalefranz** [comment]
Decided that this should go into 4.4.x instead of 4.3.x.  Don't want to rock the boat with 4.3 here.

**Comment by kalefranz** [comment]
Want to formally approve the PR? 😁

**Comment by goanpeca** [comment]
And the test :-p ?

**Comment by kalefranz** [comment]
Most of it should be covered already. Was waiting to see what the coverage looked like.

**Pull request merged**
