### PR TITLE
Update --all fixes

### PR DESCRIPTION
**Pull request by asmeurer**
@ilanschnell @teoliphant this should fix the most common issues that come up with conda update --all. Since it's such a simple change, I suggest we play around with it a little, and then just release it, and see if we still have issues.

### CODE REVIEW

**Comment by asmeurer** [comment]
A crap I committed this on top of my windows branch. Let me rebase real quick.

**Comment by asmeurer** [comment]
Let's give this a go.

**Comment by jinhw1989** [comment]
I try to update packages under windows platform, both windows 7 & 8.1 get error like
```
C:\WINDOWS\system32>conda update --all
Fetching package metadata: ....
Solving package specifications: ..
Error: Unsatisfiable package specifications
```
While it works fine under Linux platform.

In addition, I tried `conda update conda` to get the latest version 3.9 and both Linux and Windows come with Python 2.7.

**Comment by asmeurer** [comment]
This fix hasn't been released yet.

**Comment by ilanschnell** [comment]
It has been release now.  Conda 3.9.1 is available in the default channels.

**Comment by asmeurer** [comment]
So to clarify, run 

```
conda update conda
conda update --all
```

If that still doesn't work, please post the error here.

**Comment by jinhw1989** [comment]
Unfortunately, still doesn't work. 
To be specified:
`conda update conda` works well to get 3.9.1 along with other updated packages requests, pip, setuptools.
`conda update --all` gets the same error: `Error: Unsatisfiable package specifications`

**Comment by asmeurer** [comment]
Can you paste the output of `conda list`?

**Comment by jinhw1989** [comment]
```
# packages in environment at C:\Program Files\Anaconda:
#
_license                  1.1                      py27_0  
anaconda                  2.1.0                np19py27_0  
apptools                  4.2.1                    py27_0  
argcomplete               0.8.1                    py27_0  
astropy                   0.4.2                np19py27_0  
atom                      0.3.9                    py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
beautiful-soup            4.3.2                    py27_0  
beautifulsoup             3.2.1                     <pip>
beautifulsoup4            4.3.2                     <pip>
binstar                   0.7.1                    py27_0  
biopython                 1.63                 np18py27_0  
bitarray                  0.8.1                    py27_1  
blaze                     0.6.3                np19py27_0  
blz                       0.6.2                np19py27_0  
bokeh                     0.6.1                np19py27_0  
boto                      2.32.1                   py27_0  
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_1  
certifi                   14.5.14                   <pip>
cffi                      0.8.6                    py27_0  
chaco                     4.4.1                np19py27_0  
colorama                  0.3.1                    py27_0  
conda                     3.9.1                    py27_0  
conda-env                 2.1.3                    py27_0  
configobj                 5.0.6                    py27_0  
coopr                     3.5.8787                  <pip>
coopr.age                 1.1.4                     <pip>
coopr.bilevel             1.0                       <pip>
coopr.core                2.0.4                     <pip>
coopr.dae                 1.2                       <pip>
coopr.environ             1.0.1                     <pip>
coopr.gdp                 1.2                       <pip>
coopr.misc                2.8.2                     <pip>
coopr.mpec                1.0                       <pip>
coopr.neos                1.1.2                     <pip>
coopr.openopt             1.1.3                     <pip>
coopr.opt                 2.12.2                    <pip>
coopr.os                  1.0.4                     <pip>
coopr.plugins             3.1                       <pip>
coopr.pyomo               3.6.4                     <pip>
coopr.pysos               2.0.9                     <pip>
coopr.pysp                3.5.5                     <pip>
coopr.solvers             3.2.1                     <pip>
coopr.sucasa              3.0                       <pip>
coursera-dl               3.1.1                     <pip>
cryptography              0.5.4                    py27_0  
cubes                     0.10.2                   py27_4  
cython                    0.21                     py27_0  
cytoolz                   0.7.0                    py27_0  
datashape                 0.3.0                np19py27_1  
dateutil                  2.1                      py27_2  
decorator                 3.4.0                    py27_0  
distribute                0.6.45                   py27_0  
django                    1.7                       <pip>
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
enable                    4.3.0                np19py27_2  
enaml                     0.9.8                    py27_0  
envisage                  4.4.0                    py27_1  
flask                     0.10.1                   py27_1  
flask-login               0.2.9                     <pip>
future                    0.13.1                   py27_0  
futures                   2.1.6                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
gevent-zeromq             0.2.2                     <pip>
gevent_zeromq             0.2.5                    py27_3  
greenlet                  0.4.4                    py27_0  
grin                      1.2.1                    py27_2  
h5py                      2.3.1                np19py27_0  
html5lib                  0.999                     <pip>
httplib2                  0.9                       <pip>
imaging                   1.1.7                    py27_2  
ipython                   2.2.0                    py27_0  
ipython-notebook          2.2.0                    py27_0  
ipython-qtconsole         2.2.0                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jinja2                    2.7.3                    py27_1  
jsonschema                2.4.0                     <pip>
keyring                   3.3                      py27_0  
kiwisolver                0.1.3                    py27_0  
launcher                  1.0.0                         1  
libpython                 1.0                      py27_1  
llvmmath                  0.1.1                np16py27_2  
llvmpy                    0.12.7                   py27_0  
lxml                      3.4.0                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_0  
mayavi                    4.3.1                np18py27_0  
mdp                       3.3                  np18py27_0  
mechanize                 0.2.5                     <pip>
menuinst                  1.0.4                    py27_0  
meta                      0.4.2.dev                py27_0  
mingw                     4.7                           1  
mock                      1.0.1                    py27_0  
multipledispatch          0.4.7                    py27_0  
netaddr                   0.7.12                    <pip>
networkx                  1.9.1                    py27_0  
nltk                      3.0.0                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.4                    py27_0  
numba                     0.14.0               np19py27_0  
numexpr                   2.3.1                np19py27_0  
numpy                     1.9.1                    py27_0  
openpyxl                  1.8.5                    py27_0  
pandas                    0.14.1               np19py27_0  
passlib                   1.6.2                     <pip>
patsy                     0.3.0                np19py27_0  
pep8                      1.5.7                    py27_0  
pil                       1.1.7                    py27_0  
pip                       6.0.8                    py27_0  
ply                       3.4                      py27_0  
psutil                    0.7.1                    py27_0  
pulp                      1.5.6                     <pip>
py                        1.4.25                   py27_0  
pycosat                   0.6.0                    py27_0  
pycparser                 2.10                     py27_0  
pycrypto                  2.6.1                    py27_2  
pyface                    4.4.0                    py27_0  
pyflakes                  0.8.1                    py27_0  
pygments                  1.6                      py27_0  
pykit                     0.2.0                np18py27_0  
pylink                    0.3.1                     <pip>
pyodbc                    3.0.7                    py27_0  
pyopenssl                 0.14                     py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.10.4                   py27_0  
pyreadline                2.0                      py27_0  
pysal                     1.6.0                np18py27_1  
pyserial                  2.7                       <pip>
pyside                    1.2.1                    py27_0  
pytables                  3.1.1                np19py27_1  
pytest                    2.6.3                    py27_0  
python                    2.7.5                         2  
python-dateutil           2.2                       <pip>
pytz                      2014.9                   py27_0  
pyutilib                  4.7.3340                  <pip>
pyutilib.autotest         2.0.1                     <pip>
pyutilib.common           3.0.7                     <pip>
pyutilib.component.app    3.2                       <pip>
pyutilib.component.config 3.8                       <pip>
pyutilib.component.core   4.6.4                     <pip>
pyutilib.component.executables 3.5                       <pip>
pyutilib.component.loader 3.4.1                     <pip>
pyutilib.dev              2.5                       <pip>
pyutilib.enum             1.2                       <pip>
pyutilib.excel            3.1.2                     <pip>
pyutilib.math             3.3.1                     <pip>
pyutilib.misc             5.9.1                     <pip>
pyutilib.ply              3.0.8                     <pip>
pyutilib.pyro             3.6.1                     <pip>
pyutilib.r                3.1                       <pip>
pyutilib.services         3.4                       <pip>
pyutilib.subprocess       3.6.2                     <pip>
pyutilib.svn              1.5.1                     <pip>
pyutilib.th               5.5                       <pip>
pyutilib.virtualenv       4.3.4                     <pip>
pyutilib.workflow         3.5.1                     <pip>
pywin32                   219                      py27_0  
pyyaml                    3.11                     py27_0  
pyzmq                     14.3.1                   py27_0  
requests                  2.5.3                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.1                    py27_0  
scikit-image              0.10.1               np19py27_0  
scikit-learn              0.15.2               np19py27_0  
scipy                     0.15.1               np19py27_0  
setuptools                12.2                     py27_0  
six                       1.9.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
south                     1.0                       <pip>
speedtest-cli             0.3.1                     <pip>
sphinx                    1.2.3                    py27_0  
spyder                    2.3.1                    py27_0  
spyder-app                2.3.1                    py27_0  
sqlalchemy                0.9.7                    py27_0  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.5.0                np19py27_2  
svgwrite                  1.1.6                     <pip>
sympy                     0.7.5                    py27_0  
tables                    3.1.1                     <pip>
tablib                    0.10.0                    <pip>
toolz                     0.7.0                    py27_0  
tornado                   4.0.2                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
virtualenv                1.11.6                    <pip>
vtk                       5.10.1                   py27_0  
web.py                    0.37                      <pip>
werkzeug                  0.9.6                    py27_1  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.5.7                    py27_0  
xlwings                   0.2.2                    py27_0  
xlwt                      0.7.5                    py27_0  
youtube-dl                2015.2.11                 <pip>
```

**Comment by asmeurer** [comment]
I think the problem is with `gevent_zeromq`, which depends on a too old version of `pyzmq` (whereas `runipy` depends on a newer one). If you don't need it, I would `conda remove gevent_zeromq`.

**Comment by hhuuggoo** [comment]
Gevent zeromq is deprecated that functionality is built in to pyzmq now. So
removing and upgrading pyzmq should be enough

**Comment by asmeurer** [comment]
I verified with your list of packages on windows that removing gevent_zeromq makes conda update --all work.

**Comment by asmeurer** [comment]
Hmm, well it sort of works. It looks like it has to find some really old versions to work, and my VM eventually ran out of memory. I'd have to have it finish to figure out why, though.

**Comment by jinhw1989** [comment]
Yep, thanks a lot.

**Pull request merged**
