### PR TITLE
Require `pycrypto` as an install dependency

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes conda/conda#1434.

### CODE REVIEW

**Comment by asmeurer** [comment]
I don't think we should make it a hard dependency. We should make `conda sign --help` not require pycrypto.

**Comment by jakirkham** [comment]
Where else is `pycrypto` required in `conda`?

**Comment by groutr** [comment]
It's not required anywhere else in conda.  Only `conda sign` uses it.

**Comment by ilanschnell** [comment]
However, we should add `pycrypto` to Miniconda (in case someone has all packages (including `pycrpto` itself) signed).

**Comment by bkreider** [comment]
Shouldn't this be a requirement to conda-build instead since it is a conda-sign problem?

**Comment by jakirkham** [comment]
`pycrypto` appears to be also used in verification in `conda` proper.

**Comment by msarahan** [comment]
@ilanschnell where does this stand?  Can we merge it?

**Comment by ilanschnell** [comment]
`pycrypto` is an optional dependency of `conda`, only the sign verification uses it (which is not used a lot).

**Comment by jakirkham** [comment]
Yet, I am still seeing this error ( https://github.com/conda/conda/issues/1434 ) when running `--help`.

This block ( https://github.com/conda/conda/blob/ae721928109eb973b45614b790c36aca43618f65/conda/signature.py#L5-L15 ) effectively makes this non-optional.

If it is optional, can we at least use a similar imports within the function scopes? This way, trivial things like `--help` will work without generating lots of noise.

**Pull request closed without merging**
