### PR TITLE
Fix empty environment.yml

### LINKED ISSUE #11542: conda crashes on empty environment.yml
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I accidentally had an empty `environment.yml` file when running `conda env create`, which led to the error below.

The error is a bit cryptic, so it took me a while to track the problem down. Maybe some sanity checks on `environment.yml` would be good.

<details>
<summary>Error report</summary>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 144, in from_yaml
        data = validate_keys(data, kwargs)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 38, in validate_keys
        for key in data.keys():
    AttributeError: 'NoneType' object has no attribute 'keys'
```

</details>

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /usr/local/miniconda3
            shell level : 1
       user config file : /home/jussi/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/miniconda3  (read only)
      conda av data dir : /usr/local/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /home/jussi/.conda/pkgs
       envs directories : /home/jussi/.conda/envs
                          /usr/local/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.1 Linux/5.15.0-37-generic ubuntu/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

### PR DESCRIPTION
**Pull request by dogukanteber**
Resolves #11542

### CODE REVIEW

**Comment by dogukanteber** [comment]
@kenodegard I signed the CLA but it seems I cannot pass that check. Could you manually verify my signature?

**Comment by dogukanteber** [comment]
I have signed the document @jezdez. However, I am not sure if I enter the right information into Github User ID's field. Can you check again? If I entered the wrong information, how can I get Github User ID's?

**Comment by travishathaway** [comment]
Hi @dogukanteber ,

As of now, I can see your GH username in our list of signatories (https://github.com/conda/infra/blob/main/.clabot) and can confirm that you have indeed signed our CLA. Thank you!

Right now, we are actually running two CLA checks. The failing check you are seeing is our old system. We are currently transitioning from one system to another and want to keep running both check simultaneously for a bit. You can just ignore the errors on the old system.

**Comment by dogukanteber** [comment]
Thanks for the info @travishathaway. I am waiting the code review then.

**Comment by travishathaway** [comment]
@dogukanteber, I had the chance to take a look at this pull request

**Review by travishathaway — CHANGES_REQUESTED** [review]
I like this contribution, but it does need at least one test before we are able to accept it.

A good place to put this test would be in the following file at the following line: https://github.com/conda/conda/blob/da07eb1bbeef1b942fdd9c9b930158e531b9c934/tests/conda_env/test_cli.py#L665

The test could look something like the following:

```python
    def test_empty_file(self):
        with self.assertRaises(EnvironmentFileEmpty),\
                tempfile.NamedTemporaryFile(suffix='.yml') as tmp_file:
            run_env_command(Commands.ENV_CREATE, None, "--file", tmp_file.name)
```

If you need more help, feel free to get in touch with us on our Gitter chat room (https://gitter.im/conda/conda). I'd be happy to walk you through it.

**Comment by travishathaway** [comment]
Hi @dogukanteber, we had an issue with rebasing this branch to bring in the most recent changes from master and unfortunately had to open up a new pull request: https://github.com/conda/conda/pull/11630

Really sorry about that, but we are actively working to integrate this change to conda.

Thank you for your contribution.

**Comment by dogukanteber** [comment]
No problem at all @travishathaway. 

Thank you for your guidance.

**Pull request closed without merging**
