### PR TITLE
WIP: Simplified remove logic: performs *only* removals

### PR DESCRIPTION
**Pull request by mcg1969**
Needless to say I'm a big fan of the new conda solver logic. But one area where it seems suboptimal to me is with `conda remove`.

Previous versions of `conda remove` would do nothing but remove the requested packages. If other packages in the environment depended on those packages, they would be left in a broken state. That needed to be changed. With 4.x, the new solver performs a full dependency analysis, and will schedule additional packages for removal if they depend on the specified packages. This alone seems sensible. 

But in fact, the solver can sometimes go _further_, as is the case in #2360 (among others). In that issue, `conda remove numba` caused 3 new packages to be *installed*, several packages to be *downgraded*, and a lot of others to be updated. Here's why:

- the most recent version of `blaze` depends on `numba`. 
- asking to remove `numba`, therefore, required removing that particular version of `blaze` as well.
- however, `conda` tries to minimize the number of packages removed; and sure enough, there's an _older_ version of `blaze` that doesn't require `numba`. So instead of removing `blaze` completely, it downgraded it.
- the replacement version of `blaze` doesn't support NumPy 1.10, so `numpy` was downgraded as well.
- a lot of packages that link against a particular version of NumPy must then be replaced with builds that are compatible with NumPy 1.9. These aren't downgrades, but they are "updates" nonetheless.
- the older version of `blaze` also had some additional dependencies, which is why they were scheduled for *install*.

There's no way that's a good user experience.

This PR makes things simpler, by adopting a simple principle: `conda remove` *should do nothing but remove.* If it has to do *additional* removals, due to dependencies, so be it, but it shouldn't be installing new packages or downgrading others. I think this results in far simpler results for the user.

I would say this PR isn't quite done, however. One nice thing about this `conda remove` logic is that *it no longer requires downloading the index*. Unfortunately, that download happens further up the processing chain. `cli/main_remove.py` can be simplified significantly here. But I didn't want to do that until we get some feedback as to whether this is a good idea. @groutr @ilanschnell @kalefranz

### CODE REVIEW

**Comment by kalefranz** [comment]
> conda remove should do nothing but remove. If it has to do additional removals, due to dependencies, so be it, but it shouldn't be installing new packages or downgrading others.

Yeah, I think I'm on board with this.  

So in your example, `conda remove numba` would now just also remove blaze because the installed blaze depends on numba?

**Comment by mcg1969** [comment]
That's right. In fact if you look at #2360 that's the fix I offered: `conda remove numba blaze` just removes those two packages.

**Comment by davidedelvento** [comment]
I think this PR is the way to go. The "minimize packages to be removed" sounds like a good idea and I would have bought it "on paper", but in use it has been very confusing. 

If the user is not satisfied with an additional removal due to dependencies, they can manually decide how to proceed, e.g. not remove anything, downgrade or whatever. 

If you wish conda to keep some of the current behavior (which admittedly can be useful in some circumstances), you may make it spit an additional message about the possible downgrade, so the user doesn't have to check it themselves. In the case of your example, the message could say "removing blaze version such-and-such because it requires numba, you may install older blaze version older-such-and-such which doesn't". In my opinion, the `conda remove` does not need to do the full dependency analysis for this message, it's enough to check just if an older version of the removed packages lacks the dependency of the asked-to-be-removed package. If the user care, they will run `conda install` and the full dependency analysis will be run there.

**Comment by mcg1969** [comment]
The one wrinkle I can think of here concerns features. If one of the packages being removed contains a `track_feature`, we may want to invoke the `plan.remove_features_actions` behavior which requires a fuller dependency analysis

**Comment by kalefranz** [comment]
Features strike again

**Comment by mcg1969** [comment]
Yep, damn features. I think this particular approach is a bust. 

The good news is I can use the solver to enforce a simple rule: *no installations*, *no downgrades*. So:

- Specified package: add to the remove list
- Non-specified, non-installed package: add to the remove list (The solver doesn't care that they are not already installed---but this will prevent them from _being_ installed.)
- Non-specified, installed package: enforce a `>=`*ver* constraint, where *ver* is the current version. Also set its "target" so that the current package and version is the "best" choice. So in theory, it's still possible for the package to be *upgraded*, but not downgraded; and it will only be upgraded if it *has* to be.

That last behavior might actually be rather nice. Consider a package that has been modified so that it no longer needs a dependency. Removing the dependency would force the to be upgraded.

I'll close this PR when I have one that supercedes it.

**Comment by mcg1969** [comment]
Actually, I don't need to prevent installs; I _just_ need to prevent downgrades.

**Comment by mcg1969** [comment]
Superceded by #2394.

**Pull request closed without merging**
