### PR TITLE
channel priority integration test

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by kalefranz** [comment]
@mcg1969 These are the tests for #2779 I mentioned earlier today that I think should pass, but currently don't.  Could you review and see if you agree?

**Comment by mcg1969** [comment]
No, I disagree. Reproducing this test manually, I get this for the first conda update --all:
```
The following NEW packages will be INSTALLED:

    ca-certificates: 2016.2.28-0  conda-forge
    ncurses:         5.9-7        conda-forge

The following packages will be UPDATED:

    sqlite:          3.13.0-0                 --> 3.13.0-1     conda-forge
    tk:              8.5.18-0                 --> 8.5.19-0     conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    openssl:         1.0.2h-1                 --> 1.0.2h-0     conda-forge
    pycosat:         0.6.1-py35_1             --> 0.6.1-py35_0 conda-forge
    readline:        6.2-2                    --> 6.2-0        conda-forge
    xz:              5.0.5-1                  --> 5.0.5-1      conda-forge
    zlib:            1.2.8-3                  --> 1.2.8-3      conda-forge
```
That looks good. In particular, it is fine that the build numbers decrease in the SUPERCEDED list. Now we turn channel priority off, and we get this:
```
The following NEW packages will be INSTALLED:

    ca-certificates: 2016.2.28-0  conda-forge
    ncurses:         5.9-7        conda-forge

The following packages will be UPDATED:

    sqlite:          3.13.0-0                 --> 3.13.0-1     conda-forge
    tk:              8.5.18-0                 --> 8.5.19-0     conda-forge
    xz:              5.0.5-1                  --> 5.0.5-1      conda-forge
    zlib:            1.2.8-3                  --> 1.2.8-3      conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    openssl:         1.0.2h-1                 --> 1.0.2h-0     conda-forge
    pycosat:         0.6.1-py35_1             --> 0.6.1-py35_0 conda-forge
    readline:        6.2-2                    --> 6.2-0        conda-forge
```
_This is also correct_. Remember, _build numbers cannot be compared across channels._ You do not know if build 0 of conda-forge is newer or older than build 1 in defaults. Therefore, the sort order is version, _then_ channel priority, then build.

**Comment by kalefranz** [comment]
In your first output, shouldn't

    sqlite:          3.13.0-0                 --> 3.13.0-1     conda-forge

be in the SUPERCEDED group?  Because build number doesn't count, and so the higher-priority conda channel is replacing a less-than-or-equal-to `sqlite` package?

**Comment by kalefranz** [comment]
In the second output, I argue that `pycosat` shouldn't be touched at all.  Not upgraded, superseded, or anything.  It shouldn't be *in* the output.  That's because `pycosat` version `0.6.1` is already installed from defaults.  

According to https://github.com/conda/conda/issues/2779#issuecomment-228570811, hen I set `channel_priority: false`, the sort order is:
1. version
2. channel priority
3. build number

I think I agree.  And here, `pycosat` is already installed with the highest version.  The search should end here and channel priority shouldn't be considered.  In this example in particular, build number is irrelevant.

**Comment by mcg1969** [comment]
> In your first output, shouldn't
>
>    sqlite:          3.13.0-0                 --> 3.13.0-1     conda-forge
>
> be in the SUPERCEDED group?  Because build number doesn't count, and so the higher-priority conda channel is replacing a less-than-or-equal-to `sqlite` package?

Good point, I agree.

**Comment by mcg1969** [comment]
> In the second output, I argue that pycosat shouldn't be touched at all. Not upgraded, superseded, or anything. It shouldn't be in the output. That's because pycosat version 0.6.1 is already installed from defaults.

I'm not sure there is a way to make the solver do this.

Keep in mind: if you do, say, `conda update conda`, and `pycosat` doesn't *need* to be updated, it will stay exactly as it is: the current channel, version, and build.

But once we mark a `pycosat` update as *necessary*---by dependency constraints or by `conda update --all`---then basically the currently installed version is irrelevant.

**Comment by kalefranz** [comment]
> But once we mark a `pycosat` update as *necessary*, then basically the currently installed version is irrelevant

Yes, I understand now.  And now I agree that the second output is correct for `pycosat` according to

1. version
2. channel priority
3. build number

For the sake of https://github.com/conda/conda/pull/2853, I still wonder if there isn't value in making a flag that removes channel priority from the calculation altogether.  So basically just back to 

1. version
2. build number

I'm also open to backporting major fixes to 4.0.x until we build out more tools for users to get channel priority just right.

**Comment by kalefranz** [comment]
For the sake of getting one of these tests in, I'm going to go ahead and merge this.  This doesn't though exactly resolve #2779

**Pull request closed without merging**
