### PR TITLE
UTF 16 and UTF 32 fixes

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes: https://github.com/conda/conda/issues/4298

Needs tests for string replacement tests

I tested this locally to install hugin, which uses wide chars.

### CODE REVIEW

**Comment by wojdyr** [comment]
It was discussed in #4307 - scanning each file three or five times during installation may not be optimal.

**Comment by wojdyr** [comment]
@mingwandroid I don't quite get your comment, although I only vaguely remember how conda works.
If the path is up to 255 bytes in utf8, it obviously can be longer than 255 in utf32.

**Comment by mingwandroid** [comment]
That's not what I'm talking about here. We can replace 255 bytes. What those bytes contain is irrelevant.

**Comment by hmaarrfk** [comment]
@mingwandroid thanks for chiming in.
I think the key is that the 255 character string, can be stored as more than 255bytes.

Finding that PR from 2017 would have saved me lots of frustration. Not sure why I didn't click the link on the issue.

I don't think there is a way around scanning files multiple times unless conda build pre-scans them for us telling us which files are encoded in which way (binary files may have multiple encodings)

I'm not really a regex master, so if you could help, that would be appreciated it, but the operating system will cache the files, so it shouldn't be a big deal to scan them 5 times.

And for conda to be cross platform, you might need all 5 encodings, not just the 3 from your platform.

**Comment by hmaarrfk** [comment]
Ok, using your tip above to combine a few different regex into one. Lets see if this works. Hopefully this strategy can be accepted in.

**Comment by hmaarrfk** [comment]
Sorry, testing this locally is a little annoying, hopefully it is OK if i test on CIs, sorry for the notification noise.

**Comment by hmaarrfk** [comment]
@wojdyr I don't know if this is accetable. I had to change the tests. But seeing as it is only an internal function, I also changed the the one internal call accordingly as well.

Let me know if that is ok.

**Comment by hmaarrfk** [comment]
I don't understand why there is some branchign logic between text files and non text files

image

if somebody could help explain that then maybe we can work together to get rid of the for loop.

@mingwandroid

**Comment by hmaarrfk** [comment]
Kind ping to move this forward somehow.

It would be greatly appreciated to have this included as a core conda component.

I don't particularly understand why `FileMode` needs to be tested against. This seems to be some integration challenge, but I left it as it for this first version.

The large binary files are only scanned once in this implementation.

**Comment by mingwandroid** [comment]
Hi @hmaarrfk, sorry, we've all been especially busy lately, though I've had to take a bit of a break.

Can you add a test, involving a package which contains files containing each of the prefix encoded in each of the, err, encodings as a separate PR to conda-build that's marked as xfail, I am happy to work with you on a solution for this, but I still don't think we're on the right path yet. I still see an un'for'tunate loop here: https://github.com/conda/conda/pull/9946/files#diff-827c3c3f848db24eacfc18b94aead92aR72

Although nothing to be especially proud about, this recipe might be a useful starting point: 
https://github.com/conda/conda-build/tree/master/tests/test-recipes/metadata/_binary_has_prefix_files

Cheers!

**Comment by mingwandroid** [comment]
FWIW, I believe the design is wrong. These replacement locations should be pre-computed in their entirety by conda-build and conda should dumbly replace X with Y as instructed by conda-build via paths.json. Your current implementation will not, for example, work for a file that contains only one instance of the prefix, encoded in some exotic encoding that conda-build didn't detect in the first place, unless I am mistaken?

**Comment by hmaarrfk** [comment]
Thanks for chiming in @mingwandroid 

> I still see an un'for'tunate loop here: https://github.com/conda/conda/pull/9946/files#diff-827c3c3f848db24eacfc18b94aead92aR72

Right. I don't personally understand the decision to have the original if statement myself.

> dumbly replace X with Y as instructed by conda-build via paths.json

This might very well be the right approach. I totally don't have a full picture of conda-build + conda.

I think i should be able to create a pretty simple conda recipe

```python
for encoding in common_encodings:
    with open(f'file_{encoding}.data', 'wb') as f:
          f.write(os.environ['PREFIX'].encode(encoding))
```

should do the trick.

**Review by jezdez — COMMENTED** [review]
Thanks @travishathaway for updating the PR.

@hmaarrfk Do you happen to remember if [this comment](https://github.com/conda/conda/pull/9946#issuecomment-643687580) was fully handled since the patch in conda-forge was applied?

**Review by dholth — APPROVED** [review]
LGTM. The code will look for any of POPULAR_ENCODINGS-encoded placeholders in binaries.

**Pull request merged**
