### PR TITLE
Workaround for issue 8311

### PR DESCRIPTION
**Pull request by analog-cbarber**
Since it is clear that Artifactory is no hurry to fix their broken conda repository indexing, I am submitting my proposed workaround for for issue #8311.

I only changed one place in `path_actions.py` that was accessing noarch from the package metadata. It is possible that the two other locations may be needed for other uses cases.

### CODE REVIEW

**Comment by analog-cbarber** [comment]
I have signed the CLA. I guess it takes a little while for it to show up in the check?

I think that the remaining failures are in previous pull requests so probably not related to my change.

**Comment by msarahan** [comment]
The CLA is manual.  I'll add you, but it probably won't every show green on this PR.  Just ignore it.

We'll look at the tests as time allows.  Right now, we are completely tied up with preparing for AnacondaCon in 2 weeks or so.  It will take us time to review this, but we should definitely be faster than the Q3/Q4 that artifactory has estimated.

**Comment by Bezier89** [comment]
@msarahan Congrats on a successful AnacondaCon!

Now that it's over and this PR has sat for a couple weeks, think anyone could take a look at it? We're also stuck on conda 4.5 until this is resolved :(

**Comment by msarahan** [comment]
CI fails look unrelated.  Looks fine.  Is there a test that could be added to prevent future regressions?

**Comment by analog-cbarber** [comment]
There should be a way to add a test, but I won't be able to work on this until I get back from vacation in ten days.


On Apr 8, 2019 4:22 PM, Mike Sarahan <notifications@github.com> wrote:
[External]


CI fails look unrelated. Looks fine. Is there a test that could be added to prevent future regressions?

**Comment by Bezier89** [comment]
@msarahan @analog-cbarber 

Created https://github.com/conda/conda/pull/8523/files that adds a simple test.

**Pull request merged**
