### PR TITLE
Make an attempt to format the correct URL with the `--explicit` flag on conda list

### PR DESCRIPTION
**Pull request by ericdill**
Create a minimal environment

```
$ conda create -p /tmp/foo python=3.4
Fetching package metadata: ..........
Solving package specifications: .........
Package plan for installation in environment /tmp/foo:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0      defaults
    pip:        7.1.2-py34_0  defaults
    python:     3.4.3-2       defaults
    readline:   6.2-2         defaults
    setuptools: 18.4-py34_0   defaults
    sqlite:     3.8.4.1-1     defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py34_1 defaults
    xz:         5.0.5-0       defaults
    zlib:       1.2.8-0       defaults

Proceed ([y]/n)? y

Linking packages ...
#
# To activate this environment, use:
# $ source activate /tmp/foo
#
# To deactivate this environment, use:
# $ source deactivate
#
```

activate the environment and install a package from my anaconda channel

```
edill$ sa /tmp/foo
discarding /Users/edill/mc/bin from PATH
prepending /tmp/foo/bin to PATH

(/tmp/foo)edill$ conda install -c ericdill boltons
Fetching package metadata: ............
Solving package specifications: ............
Package plan for installation in environment /tmp/foo:

The following NEW packages will be INSTALLED:

    boltons: 15.0.0-py34_0 ericdill

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
```

List the packages that are installed with the `--explicit` flag
```
(/tmp/foo)10-4-24-242:info edill$ conda list --explicit
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
file:///Users/edill/mc/conda-bld/osx-64/boltons-15.0.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/openssl-1.0.2d-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pip-7.1.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/python-3.4.3-2.tar.bz2
# no URL for: readline-6.2-2
https://repo.continuum.io/pkgs/free/osx-64/setuptools-18.4-py34_0.tar.bz2
# no URL for: sqlite-3.8.4.1-1
# no URL for: tk-8.5.18-0
https://repo.continuum.io/pkgs/free/osx-64/wheel-0.26.0-py34_1.tar.bz2
# no URL for: xz-5.0.5-0
# no URL for: zlib-1.2.8-0
```

Note specifically that there are number of failures here:
- There is apparently no url for many of the packages that are, in theory, shipped by Continuum
- The url for my custom package is a file that is local to this computer. That is not at all
  helpful if I want to send list to someone else and expect them to install this list of packages.

However, the metadata that conda has access to contains all of the information that is needed to
rebuild that url where the conda package was originally obtained from.  With this PR, the `--explicit`
flag now shows the following: 

```
(/tmp/foo)10-4-24-242:info edill$ conda list --explicit
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/ericdill/osx-64/boltons-15.0.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/openssl-1.0.2d-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pip-7.1.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/python-3.4.3-2.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/setuptools-18.4-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/sqlite-3.8.4.1-1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/wheel-0.26.0-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/xz-5.0.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/zlib-1.2.8-0.tar.bz2
```

### CODE REVIEW

**Comment by ericdill** [comment]
I suppose another way to get around this would be to format the url correctly when the package is installed the first time, but I am not sure (1) where in the code base that json file gets written on install and (2) if the value of `url` being `None` in some of these packages is a feature or a bug.

The readline 6.2-2 package for osx can serve as an example package here, as it has all of the metadata required to reformat the original url but the value of the `url` key in the metadata is `None`:

```
{'arch': 'x86_64',
 'build': '2',
 'build_number': 2,
 'channel': 'https://repo.continuum.io/pkgs/free/osx-64/',
 'date': '2014-08-22',
 'depends': [],
 'files': ['include/readline/chardefs.h',
           'include/readline/history.h',
           'include/readline/keymaps.h',
           'include/readline/readline.h',
           'include/readline/rlconf.h',
           'include/readline/rlstdc.h',
           'include/readline/rltypedefs.h',
           'include/readline/tilde.h',
           'lib/libhistory.6.2.dylib',
           'lib/libhistory.6.dylib',
           'lib/libhistory.a',
           'lib/libhistory.dylib',
           'lib/libreadline.6.2.dylib',
           'lib/libreadline.6.dylib',
           'lib/libreadline.a',
           'lib/libreadline.dylib',
           'share/info/dir',
           'share/info/history.info',
           'share/info/readline.info',
           'share/info/rluserman.info'],
 'license': 'GPL3',
 'link': {'source': '/Users/edill/mc/pkgs/readline-6.2-2',
          'type': 'hard-link'},
 'md5': '0801e644bd0c1cd7f0923b56c52eb7f7',
 'name': 'readline',
 'platform': 'osx',
 'requires': [],
 'size': 281004,
 'url': None,
 'version': '6.2'}
```

**Comment by ericdill** [comment]
I'll take the silence to mean that there is no interest in this.  Should I go ahead and close this PR then?

**Comment by msarahan** [comment]
Fwiw, I think this PR is a good thing. We are swamped, and this got lost.  Pinging @kalefranz for further discussion.

**Comment by ericdill** [comment]
Thanks for the response.  I'll keep an eye on this thread and engage whenever you all have time :smile:

**Comment by kalefranz** [comment]
@ericdill Can you rebase against master to pull in the latest test configuration?  Looks fine to me if tests pass.

**Comment by ericdill** [comment]
@kalefranz Thanks for the ping. Rebased and tests are running now

**Comment by ericdill** [comment]
Thanks @kalefranz @msarahan !

**Pull request merged**
