### PR TITLE
Alias `conda env list` command to `conda info --envs`

### PR DESCRIPTION
**Pull request by beeankha**
This PR targets Step 2 (removing duplicate subcommands) of the ["refactoring and deprecating `conda env`-related commands and modules"](https://github.com/conda/conda/issues/11633) epic. Specifically, this PR aliases the `conda env list` command to `conda info --envs`; this means that even though the execution of the command is mostly reliant on `main_info.py`, anyone who uses/prefers the older `conda  env list` command will still be able to get the output that they expect.

Depends on: https://github.com/conda/conda/pull/14004

### CODE REVIEW

**Review by travishathaway — COMMENTED** [review]
One thing I noticed about this change is that it changes the output of `conda env list -v`.

Before:

```
# conda environments:
#
base                  *  /Users/username/opt/conda
conda-reporters          /Users/username/opt/conda/envs/conda-reporters
pypi                     /Users/username/opt/conda/envs/pypi
tester                   /Users/username/opt/conda/envs/tester
```

After:

```

     active environment : base
    active env location : /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c
            shell level : 1
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 24.5.1.dev48+gb9556ffe7
    conda-build version : 24.5.0
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.1.dev48+gb9556ffe7=0
                          __osx=14.4.1=0
                          __unix=0=0
       base environment : /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c  (writable)
      conda av data dir : /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs
                          /Users/username/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.1.dev48+gb9556ffe7 requests/2.32.2 CPython/3.10.14 Darwin/23.4.0 OSX/14.4.1 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False


# conda environments:
#

base                  *  /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c
blorp                    /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/blorp
conda-build-dev          /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/conda-build-dev
pandas                   /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/pandas


sys.version: 3.10.14 (main, May  6 2024, 14:42:37) [C...
sys.prefix: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c
sys.executable: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/python
conda location: /Users/username/dev/conda/conda
conda-build: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-build
conda-content-trust: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-content-trust
conda-convert: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-convert
conda-debug: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-debug
conda-develop: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-develop
conda-env: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-env
conda-inspect: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-inspect
conda-metapackage: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-metapackage
conda-render: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-render
conda-server: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-server
conda-skeleton: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda-skeleton
user site dirs: ~/.local/lib/python3.11
                ~/.local/lib/python3.12

CIO_TEST: <not set>
CONDA_ALLOW_SOFTLINKS: false
CONDA_DEFAULT_ENV: base
CONDA_EXE: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/conda
CONDA_PREFIX: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c
CONDA_PROMPT_MODIFIER: (base)
CONDA_PYTHON_EXE: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/python
CONDA_ROOT: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c
CONDA_SHLVL: 1
CURL_CA_BUNDLE: <not set>
LD_PRELOAD: <not set>
PATH: /Users/username/dev/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin:/Users/username/micromamba/condabin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Applications/VMware Fusion.app/Contents/Public:/Users/username/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/username/Library/Application Support/JetBrains/Toolbox/scripts:/Users/username/bin:/Users/username/.local/bin:/Users/username/.pixi/bin:/opt/homebrew/opt/fzf/bin
PYTHONPATH: /Users/username/dev/conda:
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
```

This might be a problem for scripts that parse the output. Is there anyway we could preserve the old output?

**Comment by beeankha** [comment]
Per @travishathaway 's [comment](https://github.com/conda/conda/pull/13972#pullrequestreview-2130644645), it appears that the `--all` flag being deprecated in favor of verbosity level does not make sense for the `conda env list` / `conda info --envs` commands. PR #14004 reverts that deprecation and will result in identical output for the non-aliased `conda env list -v` command as what is output for `conda info --envs -v` once it is merged.

**Review by travishathaway — APPROVED** [review]
Tests passing. Looks good.

**Comment by zarbex** [comment]
> Tests passing. Looks good.

Performance tests do not include `conda env list`. I belive this PR results in major performance issues when using `conda env list`.
With conda 24.5.0 I need 0,24s and using conda 24.7.1 around 30s.

**Pull request merged**
