### PR TITLE
Disable autofix for pre-commit.ci.

### PR DESCRIPTION
**Pull request by jezdez**
This is to help #10881 et al.

### CODE REVIEW

**Review by beeankha — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]
This is fine, do we intend for this to be a short term or long term change?

**Comment by jaimergp** [comment]
Short term I'd say. One can comment `pre-commit.ci` immediately followed by `autofix` to run it manually (not typing it here so it's not triggered) if needed. Once the successor to 10881 is merged we can restore it.

**Comment by jezdez** [comment]
Yeah, we'll circle back to it after the solver release.

**Comment by jaimergp** [comment]
Can we get this merged? I need to push the new branch and don't want to run into accidental autofixes :D

**Comment by jaimergp** [comment]
Thanks!

**Pull request merged**
