### PR TITLE
added exception handling for permissions

### PR DESCRIPTION
**Pull request by rafaelhbarros**
Closes issue #1751 

I only added an exception handling for the permission issue.

### CODE REVIEW

**Comment by srossross** [comment]
@rafaelhbarros did you see [this commit](https://github.com/vestuto/conda/commit/875dde1898ccb9222f710b622d7977d1f9db2f5b) that was tagged in #1751?

**Comment by srossross** [comment]
Also, can you confirm that conda does not cache files in the user directory? If conda does, this will not fix the build issues. The cached files will eventually swamp the disk.

**Comment by srossross** [comment]
This is related to PR #1796

**Comment by rafaelhbarros** [comment]
I didn't see that PR.
Thanks for pointing out, I'll have to do more work on this.

**Pull request closed without merging**
