### PR TITLE
require requests >=2.20.1, drop monkeypatch

### PR DESCRIPTION
**Pull request by dholth**
Updates requests to the first version after the one that includes the monkeypatch.

https://github.com/psf/requests/blob/main/HISTORY.md#2200-2018-10-18

### Tasks

- [X] open PR for defaults: https://github.com/AnacondaRecipes/conda-feedstock/pull/7
- [X] open PR for conda-forge: https://github.com/conda-forge/conda-feedstock/pull/169

### CODE REVIEW

**Comment by jezdez** [comment]
Good idea, this will also need patches for the recipes for defaults and conda-forge though.

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Comment by dholth** [comment]
> pre-commit.ci autofix

Meh

**Review by dholth — COMMENTED** [review]
ok

**Comment by dholth** [comment]
pre-commit.ci autofix

**Review by kenodegard — APPROVED** [review]
Since both https://github.com/AnacondaRecipes/conda-feedstock/pull/7 and https://github.com/conda-forge/conda-feedstock/pull/169 have been opened this appears good to go!

**Pull request merged**
