### PR TITLE
push PATH, PS1 manipulation into shell scripts

### PR DESCRIPTION
**Pull request by msarahan**
* Python no longer does the path concatenation.  Instead, it returns only its new part.  This is intended to fix some of the more mysterious path duplication that has been cropping up.
* The new part is always prepended, and the old environment, if any, is never removed.
* ```(( env ))```  =>  ```<env>```
* Only adds PS1 when CONDA_DEFAULT_ENV does not appear in $PS1 (to allow easier override)
* Restores CONDA_DEFAULT_ENV to varying between full path and env name, depending on how env is specified to activate
* Adds CONDA_ENV_PATH that is always a full path to the root of the active environment
* Makes backup variable naming more consistent

CC @kalefranz @asmeurer

### CODE REVIEW

**Comment by msarahan** [comment]
@kalefranz, <> seems to be unfriendly on Windows.  Works fine on my computer, but breaks on Appveyor.  If I add escaping, then that escaping shows up in the prompt.  Do you have a second choice for the default prompt appearance?

https://ci.appveyor.com/project/ContinuumAnalytics/conda/build/1.0.231/job/m021we7k22vtk1ud#L512

**Comment by asmeurer** [comment]
Thanks.

**Comment by msarahan** [comment]
Thanks for raising the issue.  This was a good opportunity for improvement, now that I understand the use cases better.

**Comment by msarahan** [comment]
Travis failure was an Anaconda.org hiccup.

**Comment by kalefranz** [comment]
>  Do you have a second choice for the default prompt appearance?

We should keep it the same for 4.1.x.  If we think of something better, let's save it for 4.2.

**Pull request merged**
