### PR TITLE
Add conda-bash.sh

### PR DESCRIPTION
**Pull request by asmeurer**
This can be source in your profile to allow you to type "conda activate" and
"conda deactivate" instead of "source activate" and "source deactivate". The 
latter will still work.

### CODE REVIEW

**Comment by pelson** [comment]
Interesting reading regarding activate (in this case for virtualenv): https://gist.github.com/datagrok/2199506

**Comment by jni** [comment]
@asmeurer has already linked to my comments, but I'm going to :+1: this again. I just introduced a new user to `conda` and the first thing they said was how unintuitive "source activate" is. FWIW their expectation was something along the lines of `conda env use env-name`.

**Comment by ccordoba12** [comment]
+1 from me too, if that counts. If find more intuitive activating/deactivating envs thtough conda itself.

**Comment by jairideout** [comment]
:+1: for `conda activate` over `source activate`. I recently switched to conda from virtualenvwrapper and found `source activate` to be unintuitive.

**Comment by wasade** [comment]
:+1: for `conda activate` and for tab completion

**Comment by asmeurer** [comment]
I still think this is a good idea. The main issue is if it can be done on Windows.

**Comment by kalefranz** [comment]
Basically equivalent to #2080, which is WIP. Definitely the right way to go I think.

**Pull request closed without merging**
