### PR TITLE
Some work on allowing channels in specs

### PR DESCRIPTION
**Pull request by asmeurer**
Support still needs to be added in the plan module to grab the package from
the correct channel when it is specified, and to download extract the package so that
it doesn't conflict with other packages with the same name.

See #988.

### CODE REVIEW

**Comment by ijstokes** [comment]
What can I do to help progress this PR?  It sounds like it *may* be exactly what I was asking for in #1504

**Comment by asmeurer** [comment]
This really has to be done in the solver to be done "right". What if one package depends on some dependency from one channel and another package depends on the same dependency from another channel?

**Comment by asmeurer** [comment]
A suggestion was made to only do this in the explicit solver, so that people can at least `conda list --export ` and `conda install --file` and get the same packages from the same channels. That would be much simpler and might solve many people's real problem.

**Comment by kalefranz** [comment]
resolve.py has major changes with @mcg1969's work. Will implement in spirit going forward.

**Comment by Korijn** [comment]
Any plans/news?

**Comment by mayou36** [comment]
Are there any news on this?

**Pull request closed without merging**
