### PR TITLE
Enable sphinx nitpicky mode + turn warnings into errors to find broken refs

### PR DESCRIPTION
**Pull request by dbast**
`fail_on_warning: true` is equivalent to `-W --keep-going`.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by travishathaway** [comment]
@dbast,

I would most, if not all, of these warnings are coming from `autoapi`. I wonder if there is a way to allow warnings from this extension and disallow them from others.

**Comment by travishathaway** [comment]
Nevermind,

It looks like this can be configured.

**Comment by travishathaway** [comment]
Yes, I looked at those. These are going to be pretty tricky ignore. We'd most likely have to come up with some regex to do that for us.

It might be better to just build the theme, start some background Python HTTP server and then manually check the redirects? 🤷

**Comment by dbast** [comment]
yeah. closing the PR... was interesting to see all the warnings... such checks have to be in place when a project starts, as later nobody wants to fix that many findings ... :/

**Pull request closed without merging**
