### PR TITLE
Test suite improvements for usability, correctness and performance

### LINKED ISSUE #10846: Improve CI speed by using more GitHub actions jobs
There are a number of pytest plugins to better distribute the tests, e.g.:

- https://github.com/jerry-git/pytest-split
- https://github.com/mark-adams/pytest-test-groups

### PR DESCRIPTION
**Pull request by dbast**
NOTE: This was previous opened in #10854 but got closed accidentally.

This does a number of things:
- Use more runners for the integration tests by splitting the tests into groups
- Fix Codecov reporting on Windows
- Separates the documentation build into own workflow (only triggered upon changes to docs files)
- Combine various requirements files.
- Add pytest-rerunfailures to be able to rerun flaky tests.
- Refactor a few unittest style tests to be pytest tests to reduce flakiness.
- Move pytest config file and fixtures in better places.
- Fix temp folder issue on Windows.
- Cleanup Makefile.
- Lint on all platforms, in an own workflow file.

Fix #10846.

### CODE REVIEW

**Comment by jezdez** [comment]
Seems like 3 test groups per platform and test type is the sweet spot, we're well below one hour now. I'm gonna have to debug the macos config tomorrow again..

**Comment by jezdez** [comment]
I think that did the trick, @chenghlee how do you want to review this, should I rebase the commits and collapse all those commits into easier to review chunks?

**Comment by jezdez** [comment]
I've moved the work on adding macOS to a separate branch since it'll need more work: https://github.com/conda/conda/pull/10875

**Comment by jezdez** [comment]
All Linux and Windows tests pass now, with ~30 mins runtime.

**Comment by jezdez** [comment]
The required checks in the protected branch settings will need to be updated for this to be easily merged.

**Review by chenghlee — APPROVED** [review]

**Pull request merged**
