### PR TITLE
Add __unix and __win virtual packages to docs

### PR DESCRIPTION
**Pull request by BastianZim**
This PR adds the virtual packages introduced in #10214 to the docs.

Let me know if you'd like a different phrasing for the explanation.

### CODE REVIEW

**Comment by BastianZim** [comment]
CLA has been signed.

**Comment by cjmartian** [comment]
@anaconda-issue-bot check

**Comment by cjmartian** [comment]
Hey again @BastianZim! I'll review this today. Thanks for signing the CLA and getting this one in. Documentation is always welcome.

**Review by cjmartian — APPROVED** [review]

**Comment by BastianZim** [comment]
Hi again 😄 
Thanks for merging!

**Pull request merged**
