### PR TITLE
Xonsh activate & deactivate

### PR DESCRIPTION
**Pull request by scopatz**
This provides conda activate and deactivate scripts for xonsh. Please let me know if there is anything else that needs to be done here. If you would like to test these locally, these require the improvements in xonsh/xonsh#2072

### CODE REVIEW

**Comment by njalerikson** [comment]
hm fascinating, there's never too many shells ;)

my only 2 cents:

since `xonsh` is an exotic shell spawning from python we should be able to do some nifty tricks to get the `activate`/`deactivate` scripts to properly recognize `xonsh` or otherwise bourne-shells vs c-shells:

```
''':'
# 
# bourne- and c- shell detection code that sources the appropriate scripts
#

exit 0
#'''

#
# xonsh detection code that sources the xonsh scripts
#
```

if the above is possible then it may make sense to rethink the `xonsh` code a little to make it parallel the code for bourne- and c- shells in order to decrease longterm code maintenance costs

otherwise if `xonsh` detection cannot be bundled into `activate`/`deactivate` then it would make more sense to make it match the design of the fish support (especially since `xonsh` supports methods)

also it would be ideal to include the `$CONDA_INSTALL_PREFIX` from  #3959

**Comment by scopatz** [comment]
Thanks for the feedback @njalerikson. I think that rewriting activate/deactivate to be both sh- and xonsh-compatible might be too fragile. This is especially true because of the she-bang line, even though it says to ignore it. 

I think the right approach is more fish-like.  xonsh has an plugins system and so there is natural place for an extension like this to be installed to. I'll try to refactor in the next day or so.

**Comment by scopatz** [comment]
Ok I have updated this to be more like the fish implementation! I don't think that the `$CONDA_INSTALL_PREFIX` is really needed here since we no longer rely on sourcing de/activate scripts. xonsh will find the hooks in the usual xontrib location without going through the PATH

**Comment by scopatz** [comment]
Any pointers here @njalerikson? The errors seem totally unrelated to anything I added. I have been over it a few times and checked for syntax errors and there don't seem to be any.

**Comment by kalefranz** [comment]
Hey, going to try circling back here soon.  4.3 is about to drop in defaults at any point, and then I'll have some time.  There are a lot of failing tests in master right now.  Test failures here might not be your fault.

**Comment by scopatz** [comment]
Ahh OK, thanks!

**Comment by njalerikson** [comment]
Not an error item but I do see that you have attempted to install the `xonsh` scripts via the `setup.py` file.

This is no longer the `conda` way. `conda` installs itself using the recipe defined in `conda.recipe`. The `setup.py` file exists only to allow the `conda` **library** to be installed via `pip`.

I must admit though that I have not been able to keep up with all of the changes made in the last month regarding the recipe and how `conda` is installed. Probably the best way to see where things may need to go is to search for references to `conda.fish` and compare that with references to `activate.csh`.

**Comment by scopatz** [comment]
Thanks for the hint @njalerikson. I have updated the PR to reflect this.

**Comment by scopatz** [comment]
Pinging this!

**Comment by scopatz** [comment]
Ping @njalerikson @kalefranz

**Comment by scopatz** [comment]
Ping again!

**Comment by scopatz** [comment]
@msarahan @ilanschnell - who should I talk to about having this looked at? Thanks in advance

**Comment by msarahan** [comment]
@kalefranz is the right person.  I'll try to bring this up on his radar.

**Comment by scopatz** [comment]
Thanks @msarahan! I *really* appreciate it

**Comment by scopatz** [comment]
Hello All, it has been another week and it has now been a months since I opened this. Can this please be reviewed, @kalefranz. I really would appreciate it

**Comment by msarahan** [comment]
@scopatz, I will remind Kale about this in person today.

**Comment by scopatz** [comment]
Thanks again @msarahan!

**Comment by kalefranz** [comment]
Sorry I've been tardy on this PR.  @msarahan just got my attention, so thanks.  After a first review, I think it's good you're following the fish model.  I think that's generally the right direction for activate and deactivate to be going.  I do plan for `conda` to become a shell command everywhere in front of the normal bin/conda executable, hopefully in the near term future.

The biggest pain point I see right now is the root-prefix-level `xontribs` directory.  We generally try to follow FHS, and that side-steps the FHS scheme.  I'm especially thinking here the case of enterprise sysadmins, and when we move most all of conda to a private environment.  In that case, at least currently, the only files created in the root prefix and conda's initial install time will be an empty `conda-meta/history` file, symlinks for `bin/activate`, `bin/conda`, and `bin/deactivate` to `envs/_conda_/bin` and I guess `etc/fish.d/conf.d/conda.fish`.  That last file is one I think enterprise sysadmins will understand and be fine with.  It'll probably map eventually to similar `etc/profile.d/conda.sh` file for bourne shells and `etc/profile.d/conda.csh` for c shells.  I guess the `etc/` directory is the important part for configuration here, following FHS.

Are there any workable alternatives to that root-level `xontribs` directory for conda installs?

**Comment by scopatz** [comment]
Thanks for the review @kalefranz! Could you clarify what you mean by a root-level prefix `xonrtibs` directory?  The current implementation sticks the `xontrib` dir in the site-packages directory.  `xontrib` is an implicit namespace package by design. So I think it could go anywhere that is on the PYTHONPATH. I thought site-packages would be correct place for this, but if there is alternative preferred locations, please let me know.

**Comment by kalefranz** [comment]
It does!
https://github.com/conda/conda/pull/4227/files#diff-4d5085f0c17bf23334372effd03a4317R22

My bad.  Somehow my brain just that that was $PREFIX.

**Comment by scopatz** [comment]
@kalefranz - so is there anything else that needs to be modified here?

**Comment by kalefranz** [comment]
Looks fine to me.  I'll make sure it gets merged for 4.4.0.  I don't have a timeline yet though for the 4.4.0 release.  Doing a review with Crystal tomorrow.

**Comment by scopatz** [comment]
Sounds good! Just please let me know if you need anything else.

**Comment by kalefranz** [comment]
Hey Anthony, apologies that it's been so long.  But now we have real progress I think.  PR #5044 changes out a lot of the python guts that make activate and deactivate work.  And while the old guts are still there, they'll probably go away at some point.  The new code is much more streamlined.  The reason I had this on hold is because I knew that something like #5044 was going to be happening at some point, and it finally did.

I don't at all mind merging this as is (or cherry-picking back onto the 4.4.x feature branch), but would you want to go through and take a stab at using the new framework in #5044?  I think you could limit yourself to reviewing how the [`conda.sh`](https://github.com/conda/conda/pull/5044/files#diff-51b65967f96649e3a87b2a8d2ad0f62c) file interacts with three `conda shell.{activate,deactivate,reactivate}` commands, and then adding a small section for xonsh in the [`conda/activate.py`](https://github.com/conda/conda/pull/5044/files#diff-a871ac4214094e0e18e2c240a36dcab3R51) file.

#5044 solves a lot of problems for us, as I outlined in the PR description.  I'm hopeful a few small tweaks can make this work here compatible.

**Comment by scopatz** [comment]
Hi @kalefranz, I don't have time in the next couple of weeks (it is finals week here now) to try to scrap this and rebuild from scratch. If merging in is fine, that would be my preferred option. Also, I am not opposed to you or someone else trying to take a stab at xonsh support in the new framework. I just want xonsh support in 4.4 :)

**Comment by kalefranz** [comment]
Ok spent a few hours working through #5157 today.  It's not perfect yet, but I think it's a functional start.

Going to close this PR now.  I tried cherry-picking back into 4.4.x, but it doesn't really work.  I think #5157 will get us covered though.  And after things slow for you a bit, you'll definitely want to look over what I've done.  You'll probably have several easy improvements, knowing tools and such that you've already got built into xonsh that you can import from.

**Pull request closed without merging**
