### PR TITLE
improve listing pip installed packages

### LINKED ISSUE #2754: conda list misses pip-installed wheels
As of conda 4.1, `conda list` no longer captures python packages that were pip-installed and were installed from wheels.

https://www.python.org/dev/peps/pep-0427/#id14

CC @ilanschnell

### PR DESCRIPTION
**Pull request by kalefranz**
fixes #2754 

Supersedes #2870 

Here, we add reading METADATA files in .dist-info directories, see PEP 427.

### CODE REVIEW

**Comment by kalefranz** [comment]
@ilanschnell Github is in the stone age still in a lot of ways compared to GitLab and Bitbucket.  I needed to change the target branch of #2870 to `4.1.x` because `master` is now `4.2.x`.  Alas, https://github.com/isaacs/github/issues/18.  Issue open since 2013--over three years! 😠

**Comment by ilanschnell** [comment]
@kalefranz can we please go back to a development model where all PR are against `master`?  And where `master` is *the* development branch.
This also applies to conda-build.  I'm looking at you @msarahan .

**Comment by kalefranz** [comment]
@ilanschnell We're starting to move too fast in conda to have master be the branch for everything.  I need to separate code that is a bugfix for one release from code that is a new feature for the next.  Here, I needed to start merging 4.2.x PRs so they're tested with each other and don't diverge, get stale, or create merge conflicts with each other.  I messaged several times in the conda flow with "\@team" tag that master was becoming the release branch for 4.2, and the 4.1.x branch should now be used for bug fixes.  (I don't mind at all fixing something small though if some communication gets lost, like just moving the target branch of your PR here.)

**Comment by ilanschnell** [comment]
Ok, as long as you can keep track of all those branches.  Is it fine, if I continue to create PR's against `master`?

**Comment by kalefranz** [comment]
Yup! No problem.  If it needs to go elsewhere, I'll fix it for you.

On Sun, Jun 26, 2016 at 2:41 PM, Ilan Schnell <notifications@github.com>
wrote:

> Ok, as long as you can keep track of all those branches. Is it fine, if I
> continue to create PR's against master?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/conda/conda/pull/2873#issuecomment-228618491>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABWks_nqTNomAVExb9MUQ2sk7v7A2gjxks5qPtXdgaJpZM4I-nuT>
> .
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Pull request merged**
