### PR TITLE
Remove expensive deepcopy call from resolve

### PR DESCRIPTION
**Pull request by bnemanich**
Profiling of some of my `conda create --dry-run` runs was showing that around 45% of the time was being spent in the `deepcopy` call within `get_reduced_index` in `resolve.py`. This PR removes the `deepcopy` call and replaces it with a dictionary containing only the values within `specs_by_name` that are different than the values in `specs_by_name_seed`. This has lead to the time it took to call `conda create --dry-run` being cut almost in half.

### CODE REVIEW

**Comment by bnemanich** [comment]
@chenghlee What do you think about this?

**Comment by chenghlee** [comment]
@bnemanich this looks like a good suggestion; but I need to do some digging to determine why `deepcopy` was used in the first place and whether this change will break things.

**Comment by bnemanich** [comment]
@chenghlee Have you had anytime to look at this one?

**Comment by jezdez** [comment]
Sorry for the slow response @bnemanich, it took a while to review this and sadly we found a change of using deepcopy in this part of the solver to be too high of a risk since it could have undesirable side-effects in resolving a lazy dependency trees. Conda's solver has lots of implicit behavior when creating solutions and the deepcopy here is to my knowledge needed to force the spec map to be built in-place.

That said, we're ARE working currently on a different project to integrate a [faster solver based on libmamba/libsolv](https://github.com/conda/conda/pull/10881) that will make this type of performance bottleneck moot/ We currently plan to release it as an opt-in feature in Q1/22. It would be great if you'd take a look at that when the time comes. Thanks!

**Pull request closed without merging**
