### PR TITLE
fix ps1 on OSX bash

### PR DESCRIPTION
**Pull request by kalefranz**
CC @msarahan

### CODE REVIEW

**Comment by msarahan** [comment]
LGTM

**Comment by kalefranz** [comment]
fixes #2432

**Comment by msarahan** [comment]
I had the same appveyor failures in conda-build.  It came from perfectly valid continuation lines, like:

print(message,
        file=sys.stderr)

but for some reason, python3 on win does not like it.  I ended up just running the lines together and doing a #noqa - not pretty, but I don't want to kill time on this.

**Comment by kalefranz** [comment]
Appveyor is a mess right now.

**Pull request merged**
