### PR TITLE
fix #6914, #6691 conda can fail to update packages even though newer versions exist

### LINKED ISSUE #6691: Upgrading from conda 4.3 to 4.4 with certain dependency specifications in conda's history can lead to a broken conda
Conda updated itself from 4.3 to 4.4. Since then, my conda installation appears to be broken. I now get the following for many conda operations (e.g. `conda update conda`, `conda install numpy`, etc):

```
Solving environment: failed

CondaValueError: Invalid MatchSpec: <2.0
```

More info...

```
$ conda --version
conda 4.4.7
$ conda install -vvv numpy
DEBUG conda.gateways.logging:set_verbosity(148): verbosity set to 3
Solving environment: ...working... DEBUG conda.core.solve:solve_final_state(140): solving prefix /scratch/mc3
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec(name=LowerStrMatch('numpy'))})
  prune: False
TRACE conda.core.linked_data:_load_single_record(113): loading prefix record /scratch/mc3/conda-meta/appnope-0.1.0-py36hf537a9a_0.json
TRACE conda.core.linked_data:_load_single_record(113): loading prefix record /scratch/mc3/conda-meta/asn1crypto-0.23.0-py36h782d450_0.json
TRACE conda.core.linked_data:_load_single_record(113): loading prefix record /scratch/mc3/conda-meta/bleach-2.1.1-py36h27c13d8_0.json
[...]
TRACE conda.core.linked_data:_load_single_record(113): loading prefix record /scratch/mc3/conda-meta/zeromq-4.2.2-ha360ad0_2.json
TRACE conda.core.linked_data:_load_single_record(113): loading prefix record /scratch/mc3/conda-meta/zlib-1.2.11-hf3cbc9b_2.json
failed
Traceback (most recent call last):
  File "/scratch/mc3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/scratch/mc3/lib/python3.6/site-packages/conda/cli/install.py", line 236, in install
    force_reinstall=context.force,
  File "/scratch/mc3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/core/solve.py", line 146, in solve_final_state
    specs_from_history_map = History(self.prefix).get_requested_specs_map()
  File "/scratch/mc3/lib/python3.6/site-packages/conda/history.py", line 187, in get_requested_specs_map
    spec_map.update(((s.name, s) for s in update_specs))
  File "/scratch/mc3/lib/python3.6/site-packages/conda/history.py", line 187, in <genexpr>
    spec_map.update(((s.name, s) for s in update_specs))
  File "/scratch/mc3/lib/python3.6/site-packages/conda/history.py", line 186, in <genexpr>
    update_specs = (MatchSpec(spec) for spec in request.get('update_specs', ()))
  File "/scratch/mc3/lib/python3.6/site-packages/conda/models/match_spec.py", line 39, in __call__
    parsed = _parse_spec_str(spec_arg)
  File "/scratch/mc3/lib/python3.6/site-packages/conda/models/match_spec.py", line 556, in _parse_spec_str
    raise CondaValueError("Invalid MatchSpec: %s" % spec_str)
conda.exceptions.CondaValueError: Invalid MatchSpec: <2.0
```

### LINKED ISSUE #6914: Conda update working differently
If a user installs the latest Anaconda 5.1 and then they try to update anaconda-client:

```
conda install anaconda=5.1.0
conda update anaconda-client 
```

Conda will say everything is up to date and will not attempt to update to 1.6.11 from 1.6.9.

This issue seems to be another manifestation of it:
- https://github.com/ContinuumIO/anaconda-issues/issues/8603
- https://github.com/ContinuumIO/navigator/issues/1437

Seems to be related with the Anaconda metapackage and how its handling changed from  4.3.x?

### LINKED ISSUE #6920: conda 4.4 can fail to update packages
For example, start with a fresh install of Anaconda3, and then `conda update anaconda-client` doesn't update, even though a new anaconda-client package exists.

### PR DESCRIPTION
**Pull request by kalefranz**
fix #6920
fix #6914
fix #6691

### CODE REVIEW

**Comment by jjhelmus** [comment]
Would be nice to have this behavior checked by a test.

**Comment by kalefranz** [comment]
Just added one

**Comment by jjhelmus** [comment]
Just for my own knowledge, was the issue here that `conda-meta/history` is not written by the Anaconda installer and so those package were not added to the index passed to the Resolver?

**Comment by kalefranz** [comment]
The issue here was that, because the anaconda metapackages wasn't registered as a user-requested spec (constructor doesn't have that capability yet, see https://github.com/conda/constructor/issues/138), the only `anaconda` package that was made available to the solver was the one that was already installed in the prefix.  So, obviously enough, that's the package it chose.

**Comment by mbargull** [comment]
Nice, also fixes #6691!

**Comment by kalefranz** [comment]
@jjhelmus @goanpeca Could I get one of you to merge this PR?  Our CI is pretty backed up right now, but I vouch that the tests will all pass now.

This is the last PR before cutting conda 4.4.11.

**Pull request merged**
