### PR TITLE
Drop Python 3.8

### LINKED ISSUE #14201: Drop Python 3.8
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Python 3.8 EOL is approaching (Oct 31st). conda-forge [has already dropped it](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5013) in preparation of the Python 3.13 migration. As a result, the libmamba builds only ship Python 3.9 and above variants, so I had to bump the CI at https://github.com/conda/conda-libmamba-solver/pull/457/.

It's a matter of time until we start missing key packages in our dependency tree for Python 3.8, so I'm asking whether we should also follow trend and drop it here.

### Why is this needed?

Offer the same level of support across all allowed Python versions and supported channels.

### What should happen?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

- Closes #14201 

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
pre-commit.ci autofix

**Review by travishathaway — APPROVED** [review]
🚀  A new era has begun 😌 🤌  3️⃣ 9️⃣

**Review by ForgottenProgramme — APPROVED** [review]
Why I approved this PR: 
- python-version 3.8 is replaced by 3.9. 
- A lot of classes that were being imported from `typing` are now being imported from `collections.abc`. 
- `@lru_cache` is replaced by `@cache`
- all `with` blocks are now using parenthesis to contain multiple context managers.

**Review by ForgottenProgramme — APPROVED** [review]

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
FTR the upstream support window for 3.8 ended 4 weeks ago: https://endoflife.date/python

**Pull request merged**
