### PR TITLE
make subdir configurable

### PR DESCRIPTION
**Pull request by kalefranz**
CC @msarahan @mingwandroid

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks.  Just so I understand correctly, I want to be changing the _subdir attribute, or will the subdir (no underscore) also work, due to your alias?

**Comment by kalefranz** [comment]
If you set the parameter in a condarc or config file, you set it as, e.g.

    subdir: osx-32

If you want to use it as an environment variable, you could do something like

    CONDA_SUBDIR=osx-32 conda create -n py34 python=3.4

The `_subdir` in the code let's me make a `context.subdir` property where I can do more logic to customize the default value if `subdir` isn't set via configuration anywhere.

Technically you could also set `_subdir: osx-32` or `CONDA__SUBDIR=osx-32` I guess, but the alias part allows you to use subdir in the more natural way.

**Comment by msarahan** [comment]
So in conda-build, if I set the context.subdir attribute, that's a third
way to do it?

**Comment by kalefranz** [comment]
And actually, the correct thing to do is set `subdir` and not `_subdir`, because I could probably refactor the `_subdir` part out in the future.

**Comment by kalefranz** [comment]
`context.subdir` is currently a property without a set descriptor defined, so I don't think you can set it directly.  I've been using https://github.com/conda/conda/blob/4.3.x/conda/common/io.py#L19-L36 a lot for tests and such to set these one-off config values.

**Comment by msarahan** [comment]
OK, thanks.  That context manager should work fine.

**Comment by msarahan** [comment]
Thanks, I think this is working.

Side note: to make this work better, and to reduce the conda-build-using-conda-internals problem, conda-build now creates its environments by just calling the Conda CLI functions to create the environments.

**Comment by kalefranz** [comment]
You mean something like this? https://github.com/conda/conda/blob/master/conda/cli/python_api.py

**Comment by kalefranz** [comment]
BTW, just waiting for tests to pass.  Then merging and cutting both 4.2.14 and 4.3.2.

**Comment by msarahan** [comment]
@kalefranz, sorry, this is not quite enough.  It mostly works, but the package_cache still points at the native system packages, not the new subdir.  I'll see about a PR if it doesn't get too hairy.

**Comment by msarahan** [comment]
More info:

```
CONDA_CHANNELS=file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0 conda create -n imxtest _cross_libgreeting
Fetching package metadata .....
Solving package specifications: ..........

Package plan for installation in environment /opt/miniconda/envs/imxtest:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _cross_libgreeting-1.0     |          h3473_0           3 KB  file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0

The following NEW packages will be INSTALLED:

    _cross_libgreeting: 1.0-h3473_0 file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
_cross_libgree 100% |####################################################################| Time: 0:00:00   5.38 MB/s
Extracting packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-imx351uc
          conda version : 4.2.4.dev405+b756600
       conda is private : False
      conda-env version : 4.2.4.dev405+b756600
    conda-build version : 2.1.0+37.gc1f634f.dirty
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /opt/miniconda  (writable)
    default environment : /opt/miniconda
       envs directories : /opt/miniconda/envs
          package cache : /opt/miniconda/pkgs
           channel URLs : file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0/linux-imx351uc
                          file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0/noarch
            config file : None
           offline mode : False



`$ /opt/miniconda/bin/conda create -n imxtest _cross_libgreeting`




    Traceback (most recent call last):
      File "/home/dev/code/conda/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/dev/code/conda/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/dev/code/conda/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/dev/code/conda/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/dev/code/conda/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/dev/code/conda/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/dev/code/conda/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/home/dev/code/conda/conda/install.py", line 800, in extract
        rec = package_cache()[dist]
    KeyError: u'file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0::_cross_libgreeting-1.0-h3473_0'
```

**Pull request merged**
