### PR TITLE
conda-build dist compatibility: make tests past

### PR DESCRIPTION
**Pull request by soapy1**
supersedes: https://github.com/conda/conda/pull/3905

### CODE REVIEW

**Comment by soapy1** [comment]
There are some conda-build tests that are failing, but I don't think they are related to Dist (though these are not the same tests that are failing on conda-build's CI). What do you think about these failures @kalefranz

**Comment by kalefranz** [comment]
This is awesome work @soapy1

**Comment by kalefranz** [comment]
@soapy1 

Looks like there are

* 5 failures for CONDA_BUILD=1.21.14
* 2 failures for CONDA_BUILD=2.0.1
* 2 failures for CONDA_BUILD=2.0.10

I'm going to merge this PR.  But then let's try to understand where those failures are coming from and if there's something we can do in conda code to fix them.  If they're failures that conda-build has itself in tests in its own repo, then I'm fine ignoring them.

**Comment by soapy1** [comment]
For conda-build=1.21.14 (8 failures instead of 5 https://travis-ci.org/conda/conda/builds/177729453):
- git submodule clone test failed - this is also happening on conda-build master
- test skeleton pypi test was failing - also on conda-build
- tests are failing because they can not run some shell scripts. Some of these look a tad suspicious, will look into them more

For conda-build=2.0.1:
- shell script for activate test isn't passing - I don't think this is related to dist
- post link script for open ssl is failing - also not related to dist

For conda-build=2.0.10:
- shell script for activate test isn't passing - I don't think this is related to dist
- the conda version is wrong, because conda is being setup with `python setup.py develop` which appends `dev-xxx` to the end of the version number - also not dist related

**Comment by kalefranz** [comment]
The activate failure I'm sure is related to #3175. We'll take care of that elsewhere.

**Comment by soapy1** [comment]
I ran the tests locally for conda-build=1.21.x and conda=4.2.x and the failures look similar. So, I think this is ok

**Pull request merged**
