### PR TITLE
respect info/link.json

### PR DESCRIPTION
**Pull request by kalefranz**
As proposed for https://github.com/conda/conda/issues/4481

CC @ilanschnell

### CODE REVIEW

**Comment by ilanschnell** [comment]
+1

More importantly, is that `conda-build` creates packages with `info/link.json`.  Hopefully nobody has created packages using `info/package_metadata.json` yet, so that we can ignore it!

**Comment by kalefranz** [comment]
I'm guessing they're in the wild already.  We should get a compatible PR for conda-build ASAP.  But I think we need conda itself working here first, otherwise conda-build tests won't pass.

In the conda-build PR, we should also not be making the file at all if there's no useful information in it, as you said in #4481

**Comment by kalefranz** [comment]
If I otherwise hear no objections, I'll be merging this for the pending 4.3.9.

**Comment by ilanschnell** [comment]
Cool!  We agree on most things.

**Comment by kalefranz** [comment]
ok merging for 4.3.9 now...

**Pull request merged**
