### PR TITLE
Allow explicit file to contain MD5 hashsums

### PR DESCRIPTION
**Pull request by ilanschnell**

### CODE REVIEW

**Comment by msarahan** [comment]
Looks good.  Thanks!

**Comment by ilanschnell** [comment]
Oh, this wasn't ready yet.

**Comment by ilanschnell** [comment]
Now, with my latest change to `conda list` it should be ready.

**Comment by msarahan** [comment]
OK.  Please tag with WIP if you're not ready.

**Comment by ilanschnell** [comment]
Ok, will do in the future.  I merge test last commit as well.

**Pull request merged**
