### PR TITLE
Fix for "conda update" that ensures dependencies don't break.

### PR DESCRIPTION
**Pull request by mcg1969**
Initial PR to fix https://github.com/conda/conda/issues/1967 and who knows what else.

### CODE REVIEW

**Comment by mcg1969** [comment]
Fixing the test failures, but feel free to comment.

**Comment by msarahan** [comment]
+1 from me, once Travis is happy again.

**Comment by mcg1969** [comment]
One of the test failures was trivial. The other failure is in `test_install_package_with_feature` in `test_resolve.py`, and I think that test is broken. [Here is a link to that test](https://github.com/conda/conda/blob/master/tests/test_resolve.py#L1439-L1461).

I think what is _supposed_ to happen is that it installs `mypackage` successfully because the already-installed `feature` package provides the desired feature. But if you look at the record for the `feature` package, its `name` field is set to `mypackage`!'

This points to a flaw in our current design, that @kalefranz and I have talked about recently: despite the claims of the documentation, `conda` currently expects the filename to adhere to the the convention _name_`-`_version_`-`_buildstring_`.tar.bz2`. If there is a difference between the `name` field in the JSON data and the name of the file, weird things can happen. To be fair, it's *my code* that was making the assumption that the JSON data was consistent with the filename, but the JSON data should control: _we shouldn't be depending on the filename at all_.

Still, that is a fix for another day. For now I'm going to modify my code to rely upon the filename, and confirm the test passes. Then I'll change the test itself to be consistent.

**Comment by kalefranz** [comment]
@mcg1969, from #1967 

> In my view, the ideal behavior is this:
> --- First, we test to see if pandas and numpy can be updated to their latest versions > without updating any other packages. If so, pull the trigger.

100% yes

> --- Second, we effectively do a conda update --all, but we change the solver weights > to prefer packages closest to the installed versions.

I actually don't like this behavior.  I would prefer in this case that `conda update` just refuse to do anything, and we notify the user that what they've requested isn't possible.  We tell the user, "by all means, go ahead and run `conda update --all`," but we make the user do that explicitly instead of us magically doing it for them.

**Comment by mcg1969** [comment]
> But we also do tell the user, "by all means, go ahead and run conda update --all." We just make the user do that explicitly instead of us magically doing it for them.

Ah, but what I this PR does---and actually, what was already implemented in conda, though not properly activated---is a third option. `conda update --all` updates *everything*, whether you need it to or not. This code updates dependencies *as little as necessary* to get the latest valid versions of the requested packages.

And of course, keep in mind if someone does `conda update A B`, it won't be hard for them to understand why it's proposing to update `C` as well.

**Comment by JanSchulz** [comment]
@kalefranz 
> I actually don't like this behavior. I would prefer in this case that conda update just refuse to do anything, and we notify the user that what they've requested isn't possible (and maybe we can even tell them why?). But we also do tell the user, "by all means, go ahead and run conda update --all." We just make the user do that explicitly instead of us magically doing it for them.

I don't agree: if I want to update seaborn and seabon requests a new pandas, then conda shoudl update pandas and seaborn (and whatever in the dependency tree also needs updating), but no unrelated packages. IMO ever action should be resolved with the minimum of changed packages and conda should do it for the user and not let the user do it manually (going through the dependency graph one by one and update from the bottom up)

That's AFAIK also the way it works with apt-get/aptitude (debian package manager) when requested to update debian packages. It will present you with solutions (e.g. "I can install this packages, but I would have to deinstall these other packages" when they conflict or "I can install that package, but also need to update these other packages" and the user can agree or ask for a different solution (if another one exists). But it's usually only the smallest amount of change to make that install/update (and removal) happen

**Comment by kalefranz** [comment]
Actually, I think we're all on the same page.  Misunderstood about the third option as @mcg1969 mentions.  That's the behavior I would intuitively expect too.

**Comment by mcg1969** [comment]
:+1:

**Comment by kalefranz** [comment]
LGTM

@mcg1969 ready to merge?

**Comment by stuarteberg** [comment]
This is a pretty major change in conda's behavior, so I humbly suggest that you edit the CHANGELOG text as part of this PR....

**Comment by mcg1969** [comment]
I'm wondering if we ought to be creating a new test to exercise the update behavior before we do so. @stuarteberg's idea of a CHANGELOG update is good too, I can work on the language.

**Comment by mcg1969** [comment]
`test_update_deps` provides good coverage already.

**Comment by mcg1969** [comment]
Cleaned up a bit further. The pruning functionality is now integrated fully into `get_dists`, removing a lot of duplicated code. The `max_only` offerings have been removed; we don't use them, and they were there only to compensate for performance issues we no longer have. (Not that there aren't _other_ performance issues.) Most importantly, the solver pulls the package name, version, and build from the metadata, not the filename, making it consistent with the documentation, and freeing us up for some future enhancement (better handling of channel conflicts, for instance)

**Comment by mcg1969** [comment]
@kalefranz, I don't know why appveyor is failing here. Can you investigate?

**Comment by mcg1969** [comment]
@msarahan, @kalefranz, what should we do with this one? appveyor is breaking but I have no idea why. travis is fine. I'd like to work on the feature fix from this code instead of a separate branch.

**Comment by msarahan** [comment]
Appveyor is breaking because it is not completely set up.  I'd say just ignore it for now until Kale finishes with it.

**Comment by mcg1969** [comment]
OK. I went ahead and rebased against the current master to make sure I didn't stomp on anything. Once Travis passes again I'm going to branch off of this for the feature fix.

**Comment by megies** [comment]
I'm assuming this PR is concerned with all those broken dependencies when numpy version gets changed.. :+1:  in that case, I most frequently end up with a broken environment.

**Comment by ijstokes** [comment]
Ooops, I think I put my comment in the wrong PR.  Please read the comment I just added to #2000 https://github.com/conda/conda/pull/2000#issuecomment-180307084 regarding #1967 (where I also added an extended comment on this situation).  Also mention @kalefranz

**Comment by mcg1969** [comment]
@ijstokes, I responded in the other thread.

**Comment by mcg1969** [comment]
Superceded by #2000.

**Pull request closed without merging**
