### PR TITLE
Ask at the end of conda install to add channels to condarc

### PR DESCRIPTION
**Pull request by asmeurer**
For example:

```
$conda install -c asmeurer -c ilan -c travis spoofmac
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /Users/aaronmeurer/anaconda:

The following NEW packages will be INSTALLED:

    spoofmac: 2.0.4-py34_0 https://conda.binstar.org/asmeurer/osx-64/

Linking packages ...
[      COMPLETE      ] |######################################################################################################################################################################################| 100%

Do you want to add 'asmeurer', 'ilan', and 'travis' to your condarc
file? If you do not, you will need to use '-c asmeurer', '-c ilan',
and '-c travis' in the future to install or update packages from these
channels. ([y]/n)?
```

If you choose no, you get a message like 

```
You can use 'conda config --add channels asmeurer --add channels ilan --add channels travis' if you decide to add it later.
```

Note that this pull request depends on https://github.com/conda/conda/pull/1240.

TODOS:

- [x] Add config options to always answer yes or no to this
- [ ] Make this more robust against unreadable condarc files
- [ ] Make this more robust against permissions issues writing to condarc?

### CODE REVIEW

**Comment by mrocklin** [comment]
Personally I love the "You can do this thing in the future to make this default <explicit code snippet>" message but don't want to be prompted every time I use a channel.  If the prompting does get in then I would prefer to have all of the prompts at the same time if possible.

**Comment by openvest** [comment]
I absolutely understand and even empathize with the motivation for this.

My gut reaction is that if I say "No", I should be given a "don't as me again" option.  There are plenty of users/workflows that would NOT want this and being presented with this question is not a big deal but I'd find it's level of annoyance to be linearly increasing over time.

**Comment by pitrou** [comment]
I don't think the prompting at the end is a good idea; *especially* if the default is "yes", since it's too easy to just press enter without noticing. Just add the informational message without adding any interaction.

**Comment by tswicegood** [comment]
What's the motivation here?  I like the idea of guiding users through configuration, but I'm not sure I understand the motivations here.

I'm imagining this scenario with a new user:

* They read an installation instruction and see that it requires a channel
* They type `conda install -c some-channel some-package`
* They're prompted to confirm the installation
* They're prompted to add a channel

I'm not a fan of the double prompt.  It's extra cognitive overhead -- the new user doesn't appreciate the implications of what they're doing.  They're just following directions.  It also increases the time it takes to get to a working state.

Another scenario is when the user installs with `--yes`.  I do this all the time when testing and have no desire to automatically add channels.  To me, I'm saying yes to the single action of installing.  This changes that dynamic to installing and possibly changing configuration.  Changing the implications of what `conda install` does is a pretty big shift and not something I'd be in favor of (crazy, right?  I like to change stuff all the time!) unless there's a pretty significant use case.

**Comment by gmarkall** [comment]
I've seen in a few cases people distribute scripts to install various dependencies of their software using conda (e.g. adding an install.sh script that among other things, calls "conda install"), and tell their users to "just run install.sh to install all dependencies" for example - would this lead to the users of those scripts getting asked "Do you want to add... ?" when running install.sh (or whatever other installation script)?

**Comment by asmeurer** [comment]
The motivation of this is that people are being recommended all over the place to install things with `-c binstar_user`. But once you install a package this way, conda cannot find those packages again thereafter, unless they are added to the configuration file. 

I suspect what most people really want when they do this is to add the channel to their configuration, so that they can always stay up-to-date on those packages that they installed with `conda update`.

To answer some specific questions:

- If you use the `--quiet` flag (also if you use `--json` or `--dry-run`), this will not be shown. People running conda in scripts should probably use `--quiet`. There is also https://github.com/conda/conda/pull/1124, which would make this happen automatically (there are some test failures which is why it hasn't been merged yet).

- I plan to add a configuration option to always say yes or no to this prompt. 

- Just telling users that they ought to so something at the end is not as good as asking them if they want to. Most users, or at least a good number, do not read any output of a command unless it requires user interaction. The default being yes is very intentional, as most users should want to answer yes here.

**Comment by asmeurer** [comment]
OK, now there is a configuration option for this (`auto_add_channels`). The default (None) will be to ask. If it is true it will do it without asking and if it is false it will not do it (with no messages). If you answer no, it will suggest how to set it to no.

**Comment by tswicegood** [comment]
> The motivation of this is that people are being recommended all over the place to install things with -c binstar_user. But once you install a package this way, conda cannot find those packages again thereafter, unless they are added to the configuration file.

That makes sense, but let's unpack this.  The main motivating thing here is that Conda doesn't know where packages that were installed from a channel came from.  What's the situation where that is important?  Checking updates comes to mind.  Something like this could potentially fail:

```console
$ conda install -c tswicegood foobar
# I update foobar to v2
$ conda update foobar # <-- fails
```

Is that right?  Can we tackle that problem at the conda level?  `conda update` could look at the current packages that are being updated and check to see if any of them are from specific channels, then add those unless `-c` was specified in the update.

Admitting that my own workflow is probably biasing my thoughts here I'm :-1: on this change as it exists.  I love the idea of Conda being more aware of where a package came from and being intelligent about interacting with those packages later on, but don't like the idea of adding channels to the config at install time.  I keep coming back to it changing `conda install` from simply installing packages to installing packages and modifying your configuration in a way that's going to effect every future invocation of `conda`.

**Comment by pitrou** [comment]
Rather than add configuration options and whatnot, why not make it simpler to add channels in the first place? Adding UI options for everything tends to make things unapproachable for the casual user.

The recommended way to install a package could be:
```
$ conda channels add ameurer
$ conda install newpackage
```

**Comment by asmeurer** [comment]
> Is that right? Can we tackle that problem at the conda level? conda update could look at the current packages that are being updated and check to see if any of them are from specific channels, then add those unless -c was specified in the update.

I had thought about this as well. This in many ways is more intrusive than this change, though, as conda could end up adding potentially a lot of channels without the user even realizing it.

**Comment by almarklein** [comment]
>>    Is that right? Can we tackle that problem at the conda level? conda update could look at the current packages that are being updated and check to see if any of them are from specific channels, then add those unless -c was specified in the update.

> I had thought about this as well. This in many ways is more intrusive than this change, though, as conda could end up adding potentially a lot of channels without the user even realizing it.

What about `conda update X` will look for X in both the official channels as well as the channel that it's originally from?

**Comment by almarklein** [comment]
> Rather than add configuration options and whatnot, why not make it simpler to add channels in the first place? Adding UI options for everything tends to make things unapproachable for the casual user.

+1 And when using the `-c` option, you could show a message at the end how the channel can be added.

**Comment by tswicegood** [comment]
> What about conda update X will look for X in both the official channels as well as the channel that it's originally from?

@almarklein that's what I proposed.

> I had thought about this as well. This in many ways is more intrusive than this change, though, as conda could end up adding potentially a lot of channels without the user even realizing it.

@asmeurer -- I think it's a reasonable expectation, however.  This should be limited to the environment that it's running in.  Of course, that does cause issues when someone uses one environment or installs everything into the root, but that's not something we can actually control.  Given that people are confused by the current workflow, I think this is a better flow instead of prompting user to change a configuration that they don't full appreciate yet.

Imagine this scenario:

```console
$ conda create -n scrapper -c tswicegood lxml
$ source activate scrapper
# do my work in my environment with lxml because I hate my life and am not using one of the other libraries on top of lxml that's nice... :-)
# realize I need to put together a django site for my scrapper
$ conda create -n web django
```

At this point if I added `tswicegood` to my channels for the `lxml` package and I had released a dev build of Django 1.9 in my main channel I just accidentally installed it into my `web` environment.  For me managing my own channels that's one thing, but what about every random channel maintainer for packages I installed?

In the context of the `scrapper` environment above, I fully expect `tswicegood` to be checked when upgrading `lxml`.  I don't expect that to effect anything in the `web` environment.  Modifying the user's Conda config does that, however.

---

I appreciate the desire to remove confusion here.  I'm afraid this particular implementation, however, has the potential to add more.

**Comment by almarklein** [comment]
@tswicegood ah sorry, I thought that with "add those" you meant to add them to the config. 

What about this scenario:

    $ conda create -n myenv python=3.4
    $ conda install -n myenev foo
    $ conda install -n myenev -c tswicegood bar
    ...
    $ conda update foo bar

Would `foo` and `bar` both get the package from `tswicegood` if its available, or only `bar`? I think the latter, but can we even do that?

**Comment by ccordoba12** [comment]
I don't agree too much with this idea. Users could end up with a lot of channels added to their `condarc` just by trying several versions of the same package uploaded to Binstar.

I like better @pitrou's idea of adding a `conda channels` subcommand.

**Comment by almarklein** [comment]
To clarify, I mean not to add the channels to the `condarc`, but only to remember the channel where individual packages came from, and reusing it (for *that* package only) when updating.

**Comment by ccordoba12** [comment]
@almarklein, I meant the idea of this PR ;-)

**Comment by asmeurer** [comment]
Sounds like people don't like this. Probably conda should just have some way of adding environment channels automatically.

**Pull request closed without merging**
