### PR TITLE
allow enhancement of info/files with extra information

### PR DESCRIPTION
**Pull request by kalefranz**
Starting in 4.3--and an upcoming conda-build release--I'd like to add additional information to `info/files`.  

First, this proposal would break every old version of conda.  We're potentially doing that anyway though by enhancing the specification of a package to support python noarch.  Tracked by https://github.com/conda/conda/issues/3692, I intend to make an updated release of every conda version going back to the latest 3.x.  (i.e. there will be a 3.19.4 release)  For python noarch, the patch refuse to install the package, saying you need to upgrade to 4.3 or later.  For the proposal in this PR, I'd just patch old releases to only use the first column of data.

On to this proposal...

Looking forward to implementing TUF, we'll want hashes for each individual file in `info/files`.  It's very similar to the `RECORD` specification for wheels.
https://www.python.org/dev/peps/pep-0427/#id16

> ## Signed wheel files
> 
> Wheel files include an extended RECORD that enables digital signatures. PEP 376 's RECORD is altered to include a secure hash `digestname=urlsafe_b64encode_nopad(digest)` (urlsafe base64 encoding with no trailing = characters) as the second column instead of an md5sum. All possible entries are hashed, including any generated files such as .pyc files, but not RECORD which cannot contain its own hash. For example:
> 
> ```
> file.py,sha256=AVTFPZpEKzuHr7OvQZmhaU3LvwKz06AJw8mT\_pNh2yI,3144
> distribution-1.0.dist-info/RECORD,,
> ```
> 
> The signature file(s) RECORD.jws and RECORD.p7s are not mentioned in RECORD at all since they can only be added after RECORD is generated. Every other file in the archive must have a correct hash in RECORD or the installation will fail.

I propose adding one additional column right now, which is the file type.  Doing this will actually enable us to move forward on our oldest open PR https://github.com/conda/conda/pull/623.  (That is, record "hard links"--two or more files with the same inode--at build time.)

Furthermore, as long as we forbid `,` comma characters in any of this content (including in filenames), then this csv format is extensible to additional metadata in the future.  Unless there are other file formats we'd prefer?  TSV (tab-separated) would be even safer than CSV, but it's always such a PITA for me to work with by hand because I map tabs to spaces in almost every editor.  Maybe PSV (pipe-separated)?

Would like input from @msarahan, @mingwandroid, @ilanschnell, @mcg1969

### CODE REVIEW

**Comment by kalefranz** [comment]
CC @dan-blanchard

**Comment by ilanschnell** [comment]
> First, this proposal would break every old version of conda.

Is there no way to do this in a backwards compatible way?  Breaking every old version of conda is not an option.
Also, why do we need this filetype information?  As we are already using tar files, the information is already stored as part of the `tar` archive format.

**Comment by kalefranz** [comment]
> Is there no way to do this in a backwards compatible way?

There would have been if `info/files` was designed in a more extensible way.  Another option I guess would be renaming the file.

> Also, why do we need this filetype information?

I'd rather scan the package once, at build time, and collect all of this information, rather than having to scan the full package structure for inode matches at ever install.  That's what https://github.com/conda/conda/pull/623 does.  And we could also avoid the `os.path.islink` call on every file in the package at install time.

**Comment by ilanschnell** [comment]
I'm still not really sure why this new information is needed, but changing the simple format of `info/files` would probably cause problems.  If this new information is necessary, I would suggest adding a new additional file, e.g. `info/record.txt` (while keeping the existing `info/files` as is).

**Comment by kalefranz** [comment]
I'm closing this PR.  @soapy1 should open a new one following https://github.com/conda/conda-build/pull/1501

**Pull request closed without merging**
