### PR TITLE
Use Response.iter_content rather than Response.raw

### PR DESCRIPTION
**Pull request by petercable**
When downloading a file, the Content-Encoding is unrelated to the internal formatting of the file itself. When attempting to download a file which is being compressed by the web server we will obtain a compressed version of the file which does not match the MD5 sum of the original file.

For example:

```
➜  ~ curl -v http://dist.schmorp.de/libev/Attic/libev-4.22.tar.gz > libev-4.22.tar.gz
* Connected to dist.schmorp.de (5.9.56.12) port 80 (#0)
> GET /libev/Attic/libev-4.22.tar.gz HTTP/1.1
> Host: dist.schmorp.de
> User-Agent: curl/7.43.0
> Accept: */*
>
< Date: Fri, 17 Jun 2016 20:37:18 GMT
< Server: Apache/2.4.10 (Debian) OpenSSL/1.0.1k mod_perl/2.0.9dev Perl/v5.20.2
< Last-Modified: Sun, 20 Dec 2015 21:12:53 GMT
< ETag: "81c4d-5275ad5ee54d8"
< Accept-Ranges: bytes
< Content-Length: 531533
< Vary: Accept-Encoding
< Content-Type: application/gzip
<
```

The file is a gzipped tarball:

```
➜  ~ file libev-4.22.tar.gz
libev-4.22.tar.gz: gzip compressed data, from Unix, last modified: Sun Dec 20 13:12:53 2015, max compression
➜  ~ md5 libev-4.22.tar.gz
MD5 (libev-4.22.tar.gz) = bf0007e37240103d3c2be80ca9bee3f9
```

This file is being gzip-encoded by the web server, but the file itself is also compressed. Requests does not remove this internal compression when fetching.

If we download the same file with conda, using the following meta.yml:

```
➜  libev git:(temp) ✗ cat meta.yaml
package:
  name: libev
  version: 4.22

source:
  fn: libev-4.22.tar.gz
  url: http://dist.schmorp.de/libev/Attic/libev-4.22.tar.gz
  md5: bf0007e37240103d3c2be80ca9bee3f9

build:
  number: 0

about:
  home: http://software.schmorp.de/pkg/libev.html
  license: BSD
  summary: A full-featured and high-performance event loop that is loosely modeled after libevent, but without its limitations and bugs.
```

We get the following error:

```
➜  libev git:(temp) ✗ conda build .
Removing old build environment
BUILD START: libev-4.22-0
Source cache directory is: /Users/petercable/miniconda2/conda-bld/src_cache
Downloading source to cache: libev-4.22.tar.gz
Downloading http://dist.schmorp.de/libev/Attic/libev-4.22.tar.gz
Success
Error: MD5 mismatch: 'e0ed1112eb7e7d8eaaed2852c074a3a6' != 'bf0007e37240103d3c2be80ca9bee3f9'
```

If we take a look at the file conda produced, we'll see that it's actually the file we want, but with an extra layer of gzip encoding around it:

```
➜  libev git:(temp) ✗ file libev-4.22.tar.gz
libev-4.22.tar.gz: gzip compressed data, from Unix
➜  libev git:(temp) ✗ gzcat libev-4.22.tar.gz > libev-4.22.tar
➜  libev git:(temp) ✗ file libev-4.22.tar
libev-4.22.tar: gzip compressed data, from Unix, last modified: Sun Dec 20 13:12:53 2015, max compression
```

And this file has the MD5 sum we're looking for:

```
➜  libev git:(temp) ✗ md5 libev-4.22.tar
MD5 (libev-4.22.tar) = bf0007e37240103d3c2be80ca9bee3f9
```

Finally, even if we ask the web server to not gzip encode the file when sending it to us, requests still does the right thing:

```
import requests
import hashlib
​
url = 'http://dist.schmorp.de/libev/Attic/libev-4.22.tar.gz'
headers = {'Accept-Encoding': 'identity'}
h = hashlib.new('md5')
response = requests.get(url, headers=headers)
h.update(response.content)
print response.headers
print h.hexdigest()
```

Returns:

```
{'Content-Length': '531533', 'Accept-Ranges': 'bytes', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=2, max=100', 'Server': 'Apache/2.4.10 (Debian) OpenSSL/1.0.1k mod_perl/2.0.9dev Perl/v5.20.2', 'Last-Modified': 'Sun, 20 Dec 2015 21:12:53 GMT', 'Connection': 'Keep-Alive', 'ETag': '"81c4d-5275ad5ee54d8"', 'Date': 'Fri, 17 Jun 2016 21:02:13 GMT', 'Content-Type': 'application/gzip'}
bf0007e37240103d3c2be80ca9bee3f9
```

Given this, this code can be simplified to just call Response.iter_content, which will return the data we need.

### CODE REVIEW

**Comment by kalefranz** [comment]
Wow awesome PR. Thanks!

The test failure is just one flake8 error

    ./conda/fetch.py:398:9: F841 local variable 'n' is assigned to but never used

**Comment by petercable** [comment]
Do you prefer a second commit or a squash commit on the first?

**Comment by kalefranz** [comment]
Doesn't matter to me either way.  I'm not that picky about a pristine commit history at this point.

**Comment by kalefranz** [comment]
@petercable  Mind clicking that **clahub** Details link and filling that out?  It's new as of today, so you didn't miss anything.  Have a lot of work to go back and get agreement from previous contributors.  Have to start somewhere though.

**Pull request merged**
