### PR TITLE
no_proxy environment variable support (issue #1094)

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by openvest** [comment]
Thanks for the quick response on this.  I'd like some time to test this first.  I want to make sure that this doesn't change some default behaviors that would upset current users.

**Comment by asmeurer** [comment]
Yeah, I definitely don't plan to merge this until someone who is behind an actual proxy tests it.

**Comment by amccarty** [comment]
@asmeurer I was able to test this tonight behind a proxy and was successful. Before patching, conda ignored my no_proxy ENV var but post-patch it was obeyed as intended. I did some basic package installs: nothing fancy, but didn't encounter any problems.

**Comment by toasteez** [comment]
I may be able to test this is someone can give me the steps.  I am behind firewall with proxy and can see all repos from browser but conda only connects via Http not HTTPS.

**Comment by amccarty** [comment]
@toasteez here's what I did:

1. Set proxy ENV vars to send all http/https traffic through my proxy server:
  ```
  export http_proxy=http://<my_proxy_server:port>/
  export https_proxy=https://<my_proxy_server:port>/
  ```
Verify that `conda install <pkg_name>` hits my proxy server instead of repo.continuum.io and conda.binstar.org directly

2. Set no_proxy ENV var to bypass the proxy for repo.continuum.io and conda.binstar.org:

  ```
  export no_proxy="repo.continuum.io,conda.binstar.org"
  ```
Verify that `conda install <pkg_name>` bypasses my proxy server

**Note:** I used a basic Squid proxy on CentOS and tailed /var/log/squid/access.log to verify hits on the proxy server.

**Comment by asmeurer** [comment]
Thanks for testing this.

**Pull request merged**
