### PR TITLE
maintain download() interface in conda.exports

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by soapy1** [comment]
I believe the conda-build test failures are not a result of the changes in this PR

**Comment by msarahan** [comment]
The tests are a mess because the new format stuff is way off.  I'm working on it.  I'm pretty sure this PR is fine, but it would be nice to clarify without the new format mess, just in case.

**Comment by msarahan** [comment]
index is back in shape.  Cycling...

**Comment by msarahan** [comment]
Note: most of the changes here com from #8738 - I've rebased on that so that I can test this PR with the fixes from #8738 until that PR is merged.

**Pull request merged**
