### PR TITLE
remove deprecated and old experimental code

### PR DESCRIPTION
**Pull request by ilanschnell**
Removes:
  * the deprecated `conda.share` module
  * the deprecated and undocumented  `conda share --json --prefix` command
  * the deprecated and undocumented  `conda clone --json --prefix` command
  * remove experimental `conda package --ls-files`

All the code which is about to be removed here is really old (at least 2 years), and has not been used.

### CODE REVIEW

**Comment by asmeurer** [comment]
I use conda package -r all the time. Why is it being removed?

**Comment by ilanschnell** [comment]
I agree, `conda package --reset` and `conda package --ls-files` shouldn't be removed.  My main point was to remove the `conda.share` and `conda.packup` modules.

**Comment by ilanschnell** [comment]
I've made the PR less aggressive, and updated the description.

**Comment by ilanschnell** [comment]
@kalefranz If you don't have any objections, this can be merged.

**Pull request merged**
