### PR TITLE
Fixing Travis CI

### PR DESCRIPTION
**Pull request by tswicegood**

### CODE REVIEW

**Comment by tswicegood** [comment]
This is an attempt to fix #1077.

**Comment by asmeurer** [comment]
I think you'll need to install requests, not update it.

**Comment by tswicegood** [comment]
@asmeurer yeah, I need to install it but I can't because conda 3.0 can't actually install things because somewhere along the line there's a BC break in the 3.x series.  I'm trying to do a force install from source to see if that solves issues.

This is a chicken and egg problem though -- requests is required to run in newer versions of conda.  Older versions of conda can't deal with new code.  It *appears* that installing from source and doing a force install of requests and conda solves the issue.  That said, there's an entire potential class of our users who now can't update conda which jumping through some serious hoops. :-(

**Comment by tswicegood** [comment]
Gotcha.  The commit I merged seems to have gotten everything fixed.  If there's something I can do differently or better, please let me know.

**Pull request merged**
