### PR TITLE
Support resuming downloads.

### LINKED ISSUE #8695: resume download for big packages
I am trying to set up an environment for [pytorch](https://pytorch.org) in my machine with cuda support using 
`conda install pytorch -c pytorch` 
the package size quiet big for my conection speed (100 KB/s)
```
pytorch-1.1.0              |py3.7_cuda10.0.130_cudnn7.5.1_0       455.0 MB  
```
when ever i download it pass about 40% or something similar then the download stops with error
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://anaconda.org/pytorch/pytorch/1.1.0/download/linux-64/pytorch-1.1.0-py3.7_cuda10.0.130_cudnn7.5.1_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

if I run the command again for installing the package it start over form zero 

so it would be great if you support download resuming like that in apt 

**I tried to download it manually  and fixing the dependency but this result another error when downloading another package that depend in it (`torchvision`), conda will redownload the whole package from higher priority mirror `pytorch` instead of using my local version**
```
 The following packages will be SUPERSEDED by a higher-priority channel:

  pytorch            <unknown>/linux-64::pytorch-1.1.0-py3.7~ --> pytorch/linux-64::pytorch-1.1.0-py3.7_cuda10.0.130_cudnn7.5.1_0
```

### PR DESCRIPTION
**Pull request by el-g-1**
Fixes #8695.
This PR adds support for resuming downloads of packages (eg, for someone with a slower connection).

When attempting to download a file, a .part file is created to enable partial downloads. When the whole package is successfully downloaded, it is renamed to the target package name. 
Note, if `Range` is not supported by the server, the code doesn't attempt to resume download.
Also, the `conda clean -t` command already takes care of .part files.

### CODE REVIEW

**Comment by jezdez** [comment]
@anaconda-issue-bot check

**Comment by jezdez** [comment]
Hey @wolfv, this is the PR I mentioned in the conda community meeting this week. Maybe we could compare notes between your work in [powerloader](https://github.com/wolfv/powerloader) and this PR?

I'd really love to end up with a similar behavior between this and what mamba may end up using.

**Comment by therc** [comment]
What happens if two concurrent commands try to download the same package(s)? I have scenarios like https://github.com/conda/conda/issues/11078 in mind

**Comment by colindean** [comment]
I'm hitting against a repeating connectivity problem that this functionality would handle properly.

@el-g-1, do you have the bandwidth to update this PR to resolve the conflicts?

**Comment by wolfv** [comment]
@jezdez sorry for replying really late :) What powerloader does is very similar -- it saves to a `.pdpart` file first, and then resumes from there. 

`librepo` has a neat trick (it stores the original URL and SHA256 of the partial file in the xattr's of the file, as well that it's a "donwload in progress"). Unfortunately xattr only work on Linux and maybe macOS.

**Comment by jezdez** [comment]
@dholth do you feel like this could be another performance boost for conda, and shippable in the July release?

**Comment by kaanchan** [comment]
Please let me know what I can do to help with testing or supporting this issue. 

> @el-g-1, do you have the bandwidth to update this PR to resolve the conflicts?

@el-g-1 If you are able to provide some guidance, I can help update your PR to help resolve the conflicts. Sounds like you've come up with a solution.

**Comment by kaanchan** [comment]
@el-g-1 Regarding the error in https://github.com/conda/conda/actions/runs/5225743212/jobs/9435608750?pr=10913, I saw it related to file already existing and the process/procedure not willing to overwrite it. Does the following comment relate to that: https://stackoverflow.com/questions/22894211/how-to-resume-file-download-in-python#comment46329844_22894873

**Comment by mitradranirban** [comment]
This issue is essential for us in places with low bandwidth issues

**Comment by dholth** [comment]
Superceded by #13231

**Pull request closed without merging**
