### PR TITLE
Remove five.py and update metaclass definitions

### PR DESCRIPTION
**Pull request by erykoff**
This PR will remove five.py and replace `@with_metaclass` with proper python3 metaclass syntax.

It also removes the `StringIO` import from `five.py`.

### CODE REVIEW

**Comment by erykoff** [comment]
This was a fairly easy targeted removal, which I hope is useful as an atomic change.  Removing vendored `six.py` properly would require much greater surgery.

**Comment by jezdez** [comment]
> This was a fairly easy targeted removal, which I hope is useful as an atomic change. Removing vendored `six.py` properly would require much greater surgery.

I'm surprised about this myself, thank you for trying! I'll take a look at it closely soon.

**Comment by erykoff** [comment]
As a small follow-up, most of the changes in this PR are removing use of the compatibility decorator `@with_metaclass` and replacing with proper python3 `metaclass=` syntax.  But this didn't actually touch on `five.py` because conda compat had copied out the vendored `@with_metaclass` decorator from `five.py`.

**Review by kenodegard — APPROVED** [review]

**Review by jezdez — APPROVED** [review]
Hurray 🥇

**Pull request merged**
