### PR TITLE
Use maintained `ruamel.yaml`

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Continuation of https://github.com/conda/conda/pull/11014 and https://github.com/conda/conda/pull/11632

Reopening as a local branch so we can build/push images and run the review build workflow.

Depends on #11868
Resolves https://github.com/conda/conda/issues/10691

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kenodegard** [comment]
The build is failing due to the same issues we've encountered with the toolz/cytoolz work. `conda-build` is somehow invoking the conda source code while trying to build the conda package (instead of using the installed conda). This means that the dependencies we are attempting to introduce must already exist in the prior conda package before we can use it.

Xref: https://github.com/conda/conda-build/issues/4572

**Review by travishathaway — APPROVED** [review]
Looks good. Don't forget to edit the lines in `.github/workflows/*.yml` again! (I assume that was done just for the CI runners).

**Review by jezdez — APPROVED** [review]
Let's do it! \o/

**Comment by jezdez** [comment]
@kenodegard Just to confirm, have we looked through the things in https://github.com/AnacondaRecipes/ruamel_yaml-feedstock/blob/master/recipe/prepare.bash that may have surprises for us?

**Comment by kenodegard** [comment]
@jezdez just reviewed it and I don't see anything concerning

I've also walked through the blame history and still don't see why conda ended up using `ruamel_yaml` and `ruamel_yaml_conda` instead of `ruamel.yaml`.

I've been able to successfully install conda as an editable install:

```bash
$ conda create -n c11837 python
$ conda activate c11837
(c11837) $ cd <path/to/conda/source>
(c11837) $ pip install toolz
(c11837) $ pip install -e .
```

<details>
<summary><code>pip install -e .</code></summary>

Screen Shot 2022-09-23 at 10 04 32 AM

</details>

<details>
<summary><code>$CONDA_PREFIX/bin/conda info</code></summary>

Screen Shot 2022-09-23 at 10 05 26 AM

</details>

**Comment by jezdez** [comment]
> @jezdez just reviewed it and I don't see anything concerning
> 
> I've also walked through the blame history and still don't see why conda ended up using `ruamel_yaml` and `ruamel_yaml_conda` instead of `ruamel.yaml`.
> 
> I've been able to successfully install conda as an editable install:
> 
> ```shell
> $ conda create -n c11837 python
> $ conda activate c11837
> (c11837) $ cd <path/to/conda/source>
> (c11837) $ pip install toolz
> (c11837) $ pip install -e .
> ```
> 
> `pip install -e .`
> Screen Shot 2022-09-23 at 10 04 32 AM
> `$CONDA_PREFIX/bin/conda info`
> Screen Shot 2022-09-23 at 10 05 26 AM

Awesome work, let's 🚀

**Review by travishathaway — APPROVED** [review]

**Comment by opoplawski** [comment]
Thanks for doing this, helps us Fedora packagers.

**Comment by jaimergp** [comment]
Hi team, is there any reason `ruamel.yaml` is still pinned to `<0.17`. It's a bit old and [conda-forge doesn't have builds for `python 3.10`](https://anaconda.org/conda-forge/ruamel.yaml/files?version=0.16.12) :/

**Comment by dholth** [comment]
We should drop the pin. It was probably pinned because of this ruamel release note, but we don't support Python 2.7 anymore either.

```
The 0.16.13 release was the last that will tested to be working on Python 2.7.
The 0.17 series will still be tested on Python 3.5, but the 0.18 will not. The
0.17 series will also stop support for the old PyYAML functions, so a `YAML()` instance
will need to be created.
```

**Pull request merged**
