### PR TITLE
Allow channel_alias to be different than binstar

### PR DESCRIPTION
**Pull request by mcg1969**
Addresses #2556 and #1911, I think. Let's check this out.

The scenario: user redefines `channel_alias` to something _other_ than their binstar server, and `add_anaconda_token` is set to `True` (or left to its default value of `True`). Then `normalize_urls` *replaces* the channel alias with the binstar alias plus the token. It shouldn't do this.

I _think_ that the design of the code is assuming that a redefined `channel_alias` always points to a binstar server if `anaconda_client` is installed.

As a side benefit, I'm delaying the call to `get_binstar` until the first time that it is needed. So if the user has no channels at all that call out to an Anaconda server, it won't even try.

@bkreider, @ilanschnell, need your feedback here. Studying the code here it looks like this has been a longstanding assumption, so I am reluctant to declare this a proper fix.

### CODE REVIEW

**Comment by mcg1969** [comment]
@ilanschnell have you had a chance to look at this? Any thoughts?

**Comment by ilanschnell** [comment]
@mcg1969 Hmm, I'm not very familiar with this piece of conda, and I don't quite understand the issue here.  I think we should talk in person about this on Tuesday.

**Comment by mcg1969** [comment]
Sure, no problem. @bkreider, @kalefranz, your input is welcome too. Honestly I think this code is in need of a more complete refactor but this fix should do for now. Here is the basic problem, and yes, we can talk about it on Tuesday.

When we are _normalizing_ channels---that is, going from a "short" channel names to full channel URLs---we need to add the binstar token whenever `add_anaconda_token` is True (by default). This allows users to enter _just_ the short channel name into their `.condarc`, even if it's a private channel that requires a login to access. In the opposite direction, whenever we are _canonicalizing_ channels---that is, going from the full URL to a "short" channel name---we need to _strip off_ the binstar tokens. 

Both of these token operations should take applied _only_ to `anaconda.org`; or, if the user is connecting to the enterprise product, to the domain name they've given to their local repository.

Unfortunately, it looks like there is a baked-in assumption in `normalize_channels` that `channel_alias`, if specified, refers to the token-enabled repository. But in theory, it doesn't need to be. A user could construct a local, token-free repository, point `channel_alias` to that, and *still* use Anaconda. But if they do that, then the tokenization process clobbers `channel_alias`.

The fix I've proposed here takes care of that. But what we really need to do here is strip out the explicit references to `binstar.org` and `anaconda.org` from this file altogether. The repository domain name is going to be returned by `get_binstar().domain` anyway, so there's no need for that anymore.

**Comment by kalefranz** [comment]
> Honestly I think this code is in need of a more complete refactor

`conda/config.py` is getting a complete refactor in 4.2.  The WIP PR is https://github.com/conda/conda/pull/2537.  There's also a WIP CEP that will be posted publicly soon.

**Comment by kalefranz** [comment]
I don't mind merging this for 4.1 though if you'd like to @mcg1969

**Comment by kalefranz** [comment]
Going to rebase and force-push here as well

**Pull request merged**
