### PR TITLE
fix #6283 no-deps for conda update case

### LINKED ISSUE #6283: conda update .. --no-deps wants to remove dependencies
Using conda 4.4rc, when trying to update a single package with `--no-deps`, it actually wants to remove a whole lot of (unrelated) packages:

```
joris@joris-XPS-13-9350:~/scipy$ conda update shapely --no-deps
Solving environment: done

## Package Plan ##

  environment location: /home/joris/miniconda3

  added / updated specs: 
    - shapely


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    shapely-1.6.2              |           py35_1         703 KB  conda-forge

The following packages will be REMOVED:

    bottleneck:    1.2.1-np113py35_0                 conda-forge
    fiona:         1.7.9-py35_0                      conda-forge
    geos:          3.5.1-1                           conda-forge
    h5py:          2.7.0-np113py35_1                 conda-forge
    libgdal:       2.1.4-2                           conda-forge
    libspatialite: 4.3.0a-15                         conda-forge
    mahotas:       1.4.3-np113py35_1                 conda-forge
    numba:         0.34.0-np113py35_0                           
    numexpr:       2.6.2-np113py35_0                 conda-forge
    numpy:         1.13.1-py35_blas_openblas_200     conda-forge [blas_openblas]
    opencv:        3.2.0-np113py35_blas_openblas_204 conda-forge [blas_openblas]
    pytables:      3.4.2-np113py35_1                 conda-forge
    pywavelets:    0.5.2-np113py35_0                 conda-forge
    statsmodels:   0.8.0-np113py35_0                 conda-forge
    turbodbc:      2.2.0-np113py35_0                 conda-forge

The following packages will be UPDATED:

    shapely:       1.6.0-py35_0                      conda-forge --> 1.6.2-py35_1 conda-forge

Proceed ([y]/n)?
```

I don't see this behaviour when downgrading conda to 4.3

(see also discussion on gitter: https://gitter.im/conda/conda?at=5a01863532e080696e74a5aa)

I am using conda-forge as default channel:

```
joris@joris-XPS-13-9350:~/scipy$ conda info

     active environment : None
            shell level : 0
       user config file : /home/joris/.condarc
 populated config files : /home/joris/.condarc
          conda version : 4.4.0rc1
    conda-build version : 3.0.1
         python version : 3.5.4.final.0
       base environment : /home/joris/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/joris/miniconda3/pkgs
                          /home/joris/.conda/pkgs
       envs directories : /home/joris/miniconda3/envs
                          /home/joris/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.0rc1 requests/2.13.0 CPython/3.5.4 Linux/4.4.0-97-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by kalefranz**
fix #6283

### CODE REVIEW

**Comment by goanpeca** [comment]
@kalefranz based on https://github.com/conda/conda/pull/6447, what is now the meaning of --no-deps for install, remove, and update?

**Comment by kalefranz** [comment]
You mean based on #6283?  I'm not sure what the context is for #6447

**Comment by kalefranz** [comment]
Honestly, don't merge this PR yet...  It's going to create broken environments.  So maybe we want to fix the issue as reported just with documentation?

**Comment by goanpeca** [comment]
>It's going to create broken environments. So maybe we want to fix the issue as reported just with documentation?

Well... I don't know the real use case of --no-deps tbh. I normally use force which is like --no-deps in my head but has a very specific use case. Some package is broken I wan to force install it just that package...

On remove this does not make a lot of sense... unless I really know what I am doing.

Maybe `--no-deps` does not make sense for remove? but only for install?

**Comment by kalefranz** [comment]
FWIW, since you brought it up, the `--force` flag has a lot of problems.  It has different meanings in different contexts, and often it means more than one thing in the same context.  It's overloaded to do a bunch of different things.

**Comment by kalefranz** [comment]
Let's punt on this and come back to it.  I need to think more.  I don't like this solution at the moment though.

**Comment by kalefranz** [comment]
I updated the help information here.  I guess this is something we've always supported.  So probably this is the best we can do.

@goanpeca is there anything you would add to the help descriptions?

**Comment by kalefranz** [comment]
Let's go ahead and merge then.  Think we might as well.

**Pull request merged**
