### PR TITLE
change pip_subprocess from "pip <cmd>" to "python pip-script.py <cmd>" on windows

### PR DESCRIPTION
**Pull request by zdog234**
Hello all,

This is motivated by #8346. Prior to 4.6.7, the generated syntax for pip commands had been `/path/to/venv/python.exe /path/to/venv/Scripts/pip-script.py <cmd>` but was changed to  `pip <cmd>`.

I don't know how this could've been caught -- it seems like `utils.wrap_subprocess` should have kept this from happening -- but this particular change has caused `pip` dependencies in `environment.yml` to not properly install into new environments when running `conda env create -f environment.yml`. It seems like they're instead being installed into the `base` environment.

A bunch of unit tests are failing, but it seems like they're the same as the ones on master.

It's totally possible that this is the wrong fix. I just figured I'd submit this PR as a conversation starter/to get help from people who know what they're doing :)

Also, this probably deserves a unit test, but I haven't taken the time yet to figure out how the test framework works for this project.

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks for your efforts here.  Indeed, we've been very confused how the tests didn't catch this.  We've done a lot of work on fixing activation and running things in activated envs.  Unfortunately, it spiraled out of control and has become a much larger body of work in #8435.

If you could please keep an eye out for when we release 4.6.9 into canary - ideally in the next 1-2 days - we'd really appreciate your confirmation that our efforts have addressed the issue for you.

**Comment by zdog234** [comment]
Thanks! I can see that you guys are putting in a lot of work there. The new implementation of `pip_subprocess` looks really neat!

**Comment by msarahan** [comment]
@zdog234 conda 4.6.9 has been released to the conda-canary channel.  Any feedback you have for us would be most appreciated.  I'm closing this PR as I hope this issue is fixed.

**Comment by zdog234** [comment]
Sweet! I'll try to check some time this weekend :)

**Pull request closed without merging**
