### PR TITLE
remove unused check_install function

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by kalefranz** [comment]
@ilanschnell any objections?

**Comment by ilanschnell** [comment]
Nope

**Comment by kalefranz** [comment]
@msarahan Looks like this is used in conda-build.  Want to move it there?

**Comment by msarahan** [comment]
Will do.

**Comment by kalefranz** [comment]
I'll hold off on merging this for a while.

**Comment by msarahan** [comment]
The file is in your git history.  Go ahead and merge.

**Pull request merged**
