### PR TITLE
Fix detection of cached, but unextracted .conda packages.

### PR DESCRIPTION
**Pull request by asford**
Resolves error when reusing a package cache with both `.conda` and
`.tar.bz2` files. `.conda` files are extracted, then re-downloaded from
source during `conda install` pass.

Occurs because re-extracted `.conda` repodata.json, see
package_cache_data.py 383, is written with an "<unknown>" channel entry,
resulting in a cache miss in `ProgressiveFetchExtract.make_actions_for_record`.
This is due to a failure to resolve the `.conda` package url from
`urls.txt`.

Error can be trivially reproduced by removing the extracted package
directory for an existing .conda sourced package, then reinstalling.

### CODE REVIEW

**Comment by msarahan** [comment]
@asford ignore the bot.  I confirm that you have signed the CLA and will follow up on the bot.

**Comment by msarahan** [comment]
@cla-bot check

**Comment by msarahan** [comment]
Thanks for improving the test setup here.  If you have questions or need help on this, please ping us.  @msarahan or @conda/conda-core

**Comment by asford** [comment]
Great, thanks. 

Any hints on the test discrepancy between my local environment and the CI? I've run through the standard dev setup, but I'm seeing two failures in `master` but my new test is passing.

It looks like the call to [`get_index`](https://github.com/conda/conda/pull/9254/files#diff-f33ecf551927debb48dd2ce1f3ee72e8R286) in the test returning `.conda` records in my environment but `.tar.gz` records in the CI environment.

```
+lexaf@ip-172-31-58-107:/work/home/lexaf/workspace/asford/conda$ source dev/start
+(base) lexaf@ip-172-31-58-107:/work/home/lexaf/workspace/asford/conda$ conda info

     active environment : base
    active env location : /work/home/lexaf/workspace/asford/conda/devenv
            shell level : 1
       user config file : /home/lexaf/.condarc
 populated config files :
          conda version : 4.7.12.post3+5d1ea4853
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /work/home/lexaf/workspace/asford/conda/devenv  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /work/home/lexaf/workspace/asford/conda/devenv/pkgs
                          /home/lexaf/.conda/pkgs
       envs directories : /work/home/lexaf/workspace/asford/conda/devenv/envs
                          /home/lexaf/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12.post3+5d1ea4853 requests/2.22.0 CPython/3.7.4 Linux/4.4.0-1084-aws ubuntu/16.04.6 glibc/2.23
                UID:GID : 9797377:10100
             netrc file : None
           offline mode : False

+(base) lexaf@ip-172-31-58-107:/work/home/lexaf/workspace/asford/conda$ which pytest
/work/home/lexaf/workspace/asford/conda/devenv/bin/pytest
+(base) lexaf@ip-172-31-58-107:/work/home/lexaf/workspace/asford/conda$ pytest tests/core/test_package_cache_data.py
================================================================ test session starts =================================================================
platform linux -- Python 3.7.4, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /work/home/lexaf/workspace/asford/conda, inifile: setup.cfg
plugins: cov-2.7.1, timeout-1.3.3, mock-1.10.4
collected 8 items

tests/core/test_package_cache_data.py ..FF....                                                                                                 [100%]

====================================================================== FAILURES ======================================================================
________________________________________________ test_tar_bz2_in_pkg_cache_doesnt_overwrite_conda_pkg ________________________________________________
Traceback (most recent call last):
  File "/work/home/lexaf/workspace/asford/conda/tests/core/test_package_cache_data.py", line 152, in test_tar_bz2_in_pkg_cache_doesnt_overwrite_conda_pkg
    assert len(pfe.cache_actions) == 0
AssertionError: assert 1 == 0
 +  where 1 = len((CacheUrlAction(url='file:///work/home/lexaf/workspace/asford/conda/tests/data/conda_format_repo/win-64/zlib-1.2.11-h6...363f6c023d7fb3d11fdb4cc8de59b5ad5c6affdf960210dd95a252a3fced2b', size=131285, md5='a46cf10ba0eece37dffcec2d45a1f4ec'),))
 +    where (CacheUrlAction(url='file:///work/home/lexaf/workspace/asford/conda/tests/data/conda_format_repo/win-64/zlib-1.2.11-h6...363f6c023d7fb3d11fdb4cc8de59b5ad5c6affdf960210dd95a252a3fced2b', size=131285, md5='a46cf10ba0eece37dffcec2d45a1f4ec'),) = <conda.core.package_cache_data.ProgressiveFetchExtract object at 0x7f5af4389ad0>.cache_actions
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------

WARNING :: You are testing `conda` with `tmpdir`:-
           /tmp/pytest-of-lexaf/pytest-59/test_tar_bz2_in_pkg_cache_does0/tmpdkd51_kt
           not on the same FS as `sys.prefix`:
           /work/home/lexaf/workspace/asford/conda/devenv
           this will be slow and unlike the majority of end-user installs.
           Please pass `--basetemp=<somewhere-else>` instead.

Downloading and Extracting Packages
zlib-1.2.11          | 128 KB    | ########## | 100%
________________________________________________ test_conda_pkg_in_pkg_cache_doesnt_overwrite_tar_bz2 ________________________________________________
Traceback (most recent call last):
  File "/work/home/lexaf/workspace/asford/conda/tests/core/test_package_cache_data.py", line 208, in test_conda_pkg_in_pkg_cache_doesnt_overwrite_tar_bz2
    assert len(pfe.cache_actions) == 0
AssertionError: assert 1 == 0
 +  where 1 = len((CacheUrlAction(url='file:///work/home/lexaf/workspace/asford/conda/tests/data/conda_format_repo/win-64/zlib-1.2.11-h6...b5900c4a2ca7e0f509ebc344b3508815d7647c86cfb6721a1690365222e55a', size=112305, md5='edad165fc3d25636d4f0a61c42873fbc'),))
 +    where (CacheUrlAction(url='file:///work/home/lexaf/workspace/asford/conda/tests/data/conda_format_repo/win-64/zlib-1.2.11-h6...b5900c4a2ca7e0f509ebc344b3508815d7647c86cfb6721a1690365222e55a', size=112305, md5='edad165fc3d25636d4f0a61c42873fbc'),) = <conda.core.package_cache_data.ProgressiveFetchExtract object at 0x7f5af43ca410>.cache_actions
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------

WARNING :: You are testing `conda` with `tmpdir`:-
           /tmp/pytest-of-lexaf/pytest-59/test_conda_pkg_in_pkg_cache_do0/tmp2_5pvu0a
           not on the same FS as `sys.prefix`:
           /work/home/lexaf/workspace/asford/conda/devenv
           this will be slow and unlike the majority of end-user installs.
           Please pass `--basetemp=<somewhere-else>` instead.

Downloading and Extracting Packages
zlib-1.2.11          | 110 KB    | ########## | 100%
================================================================== warnings summary ==================================================================
conda/_vendor/auxlib/compat.py:37
  /work/home/lexaf/workspace/asford/conda/conda/_vendor/auxlib/compat.py:37: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    return not isinstance(obj, string_types) and isinstance(obj, collections.Iterable)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================= slowest 16 test durations ==============================================================
1.29s call     tests/core/test_package_cache_data.py::test_ProgressiveFetchExtract_prefers_conda_v2_format
0.13s call     tests/core/test_package_cache_data.py::test_conda_in_cache_is_used
0.11s call     tests/core/test_package_cache_data.py::test_instantiating_package_cache_when_both_tar_bz2_and_conda_exist
0.11s call     tests/core/test_package_cache_data.py::test_conda_pkg_in_pkg_cache_doesnt_overwrite_tar_bz2
0.11s call     tests/core/test_package_cache_data.py::test_instantiating_package_cache_when_both_tar_bz2_and_conda_exist_read_only
0.09s call     tests/core/test_package_cache_data.py::test_tar_bz2_in_cache_not_extracted
0.05s teardown tests/core/test_package_cache_data.py::test_instantiating_package_cache_when_both_tar_bz2_and_conda_exist_read_only
0.05s teardown tests/core/test_package_cache_data.py::test_tar_bz2_in_pkg_cache_used_instead_of_conda_pkg
0.05s teardown tests/core/test_package_cache_data.py::test_instantiating_package_cache_when_both_tar_bz2_and_conda_exist
0.05s teardown tests/core/test_package_cache_data.py::test_tar_bz2_in_pkg_cache_doesnt_overwrite_conda_pkg
0.05s teardown tests/core/test_package_cache_data.py::test_conda_in_cache_is_used
0.05s teardown tests/core/test_package_cache_data.py::test_ProgressiveFetchExtract_prefers_conda_v2_format
0.05s teardown tests/core/test_package_cache_data.py::test_conda_pkg_in_pkg_cache_doesnt_overwrite_tar_bz2
0.05s teardown tests/core/test_package_cache_data.py::test_tar_bz2_in_cache_not_extracted
0.03s call     tests/core/test_package_cache_data.py::test_tar_bz2_in_pkg_cache_used_instead_of_conda_pkg
0.03s call     tests/core/test_package_cache_data.py::test_tar_bz2_in_pkg_cache_doesnt_overwrite_conda_pkg
=================================================== 2 failed, 6 passed, 1 warnings in 2.75 seconds ===================================================
```

**Comment by msarahan** [comment]
Yeah, not your fault.  The build environment docker image needs to be updated.  It has an old conda-build (3.17.8).  Conda automatically cripples itself when it detects old conda-build.  By cripple, I mean it forces itself to only use .tar.bz2 files.  It does this because old conda-build falls over if .conda files are present.  We used to have a warning telling people when this happened, but enough people were confused and/or angry about it that we reverted it.  I'll try to update the build image tomorrow and re-cycle the CI's.  I'm pretty sure you're just fine.

**Comment by msarahan** [comment]
retargeted to 4.7.x for bugfix release 4.7.13

**Comment by asford** [comment]
I can confirm that the conda-build version is impacting the new test, downgrading to 3.17.* causes it to fail. I'll wait for to you update the CI images, but I'm still seeing the other two failures locally (`test_*_in_pkg_cache_doesnt_overwrite_*`) on `master`. Don't believe this should block a merge.

While I've your attention @msarahan, is there documentation anywhere on building `.conda` format packages? I'm tried to troll through the `conda build` documentation, but haven't found anything.

**Comment by msarahan** [comment]
@asford building .conda packages isn't terribly useful right now unless you host your own index.  Anaconda.org does not support .conda files yet.  The timeline to do so is not clear, but is definitely long.

Our practice is to build the .tar.bz2 package, then convert it with conda-package-handling: https://github.com/conda/conda-package-handling

If you still want to build .conda files directly, the way to do so is to set this in your .condarc:

```
conda-build:
	pkg_format: 2
```

Since this is not really in use, you should probably expect it to change and possibly break at some point.  We'll try to be careful about that, but mistakes have been known to happen.

**Pull request closed without merging**
