### PR TITLE
Add a channel priority minimization pass

### PR DESCRIPTION
**Pull request by mcg1969**
cc: @mingwandroid @msarahan 

Per our discussion at the last meeting, this adds an additional minimization pass for channel priority. Conda will work a bit harder to pick packages from the highest priority channel. If we decide to give subchannels their own distinct priority, this will cause conda to prefer the highest priority subchannel.

I built this against 4.3 because frankly I know that branch better. But as you can see the changes are very minimal. That suggests it might be worth considering even for 4.3, but even if not, it will be easy to port to 4.4.

### CODE REVIEW

**Comment by mingwandroid** [comment]
4.3 is ideal for me @mcg1969, thank you for working on this.

**Comment by mcg1969** [comment]
Keep in mind that this isn't the only thing that would have to change to make your goals work in 4.3. The channel priority assignment logic itself would have to change, and I am not sure how extensive those changes would be.

**Comment by msarahan** [comment]
Thanks @mcg1969 - do you have any recommendations for integration tests or benchmarking this?

I guess for benchmarking, we could see if it speeds up using our c3i_test channel, as that is our staging area for defaults, and is a much smaller set of things than defaults.  Would that be a meaningful speed test?

**Comment by kalefranz** [comment]
Code changes look fine to me, and I'm :+1: for merging this into 4.3.x.  The code for 4.4.x hasn't changed here, so there shouldn't be major merge conflicts to resolve.

Before we merge, I *do* want additional tests that actually exercise this in `test_resolve.py`.  To do that, we'll need to have multiple "channels" available to `test_resolve.py`, and that'll be quite a bit of extra code to add to this PR.  Luckily, it's mostly done in the 4.4.x branch and some of that test code can just be backported.  I'll volunteer to do that.

**Pull request merged**
