### PR TITLE
Allow not more than one " to preceed conda[-_]

### LINKED ISSUE #7950: Conda Init Bug in v4.6.0b1
While exploring #7881 , I found a small bug in the regex pattern matching at: https://github.com/conda/conda/blob/7a93664267488adc5052efef38614fab537da446/conda/core/initialize.py#L1157-L1166

The regex pattern assumes that I would not have quotes in my already existing value in the registry key. For example, if I have the current value set as...

```
"\path\to\custom\startup.bat" & "\path\to\prev_installation\condabin\conda_hook.bat"
```

... upon `conda init`, it will change the value to:
```
"\path\to\new_installation\condabin\conda_hook.bat"
```

Instead of:
```
"\path\to\custom\startup.bat" & "\path\to\new_installation\condabin\conda_hook.bat"
```

### PR DESCRIPTION
**Pull request by nehaljwani**
Fixes #7950

### CODE REVIEW

**Comment by nehaljwani** [comment]
Fix for failing CI jobs: https://github.com/AnacondaRecipes/repodata-hotfixes/pull/6

**Comment by nehaljwani** [comment]
Looks like now only CB related failures are present.

**Comment by msarahan** [comment]
cycling to re-run CI

**Comment by msarahan** [comment]
I believe the CI failures are not new.  Merging.

**Pull request merged**
