### PR TITLE
Auto update conda env

### LINKED ISSUE #2771: conda update conda doesn't get latest conda-env
It's annoying we even have this problem, but...

    root@default:~ # conda update conda
    Fetching package metadata: ......
    .Solving package specifications: .........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        conda-env-2.5.0            |           py27_0          28 KB
        conda-4.1.2                |           py27_0         198 KB
        ------------------------------------------------------------
                                               Total:         226 KB

    The following NEW packages will be INSTALLED:

        ruamel_yaml: 0.11.7-py27_0

    The following packages will be UPDATED:

        conda:       4.0.5-py27_0 --> 4.1.2-py27_0
        conda-env:   2.4.5-py27_0 --> 2.5.0-py27_0

    Proceed ([y]/n)? y

    Fetching packages ...
    conda-env-2.5. 100% |#########################################################################################| Time: 0:00:00 587.12 kB/s
    conda-4.1.2-py 100% |#########################################################################################| Time: 0:00:00 994.90 kB/s
    Extracting packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    root@default:~ # conda update conda-env
    Fetching package metadata .........
    Solving package specifications: ..........

    Package plan for installation in environment /usr/local:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        conda-env-2.5.1            |           py27_0          26 KB

    The following packages will be UPDATED:

        conda-env: 2.5.0-py27_0 --> 2.5.1-py27_0

    Proceed ([y]/n)? y

    Fetching packages ...
    conda-env-2.5. 100% |#########################################################################################| Time: 0:00:00 569.65 kB/s
    Extracting packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Unlinking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|############################################################################################################| 100%

### PR DESCRIPTION
**Pull request by kalefranz**
fixes #2771 

@mcg1969 Please review?

### CODE REVIEW

**Comment by kalefranz** [comment]
Actually, in #2771, why didn't we pull in the latest conda-env anyway?  Shouldn't the solver have preferred 2.5.1 over 2.5.0?

**Comment by mcg1969** [comment]
LGTM

**Comment by kalefranz** [comment]
@mcg1969, when you get a chance...  Can you help me understand why this is even necessary?  In the output given in #2771, shouldn't it have pulled in conda-env 2.5.1 automatically?

Also, we need to be careful that we're able to back this change out.  Someday, conda-env might not be a dependency of conda.  But in that case we want to be able to update conda without having unsatisfiable dependencies...

**Comment by frol** [comment]
Don't you (@kalefranz @mcg1969) feel like you have just started a bomb? Don't you think that something is completely wrong with dependency solver or the recipe dependency version pinning if such an ugly workaround is necessary? I vote for this change to be reverted ASAP and the issue is solved properly.

/cc @ilanschnell @msarahan

**Comment by msarahan** [comment]
I don't know about a bomb, but I agree that dependency pinning should be what we rely on to make this happen correctly.

**Comment by mcg1969** [comment]
Actually, the proper solution is to merge conda and conda-env. They have no business being separate. But that is not something that is going to happen tomorrow; and in the meanwhile, we need some band-aids.

I'm actually not convinced this particular commit is necessary anymore, since we pulled `conda-env 2.5.0` from the repo, which proved to be somewhat problematic. But it doesn't need to be reverted, either, because it is benign.

Furthermore, the latest versions of the solver _have_ been fixed to prevent problems like this from happening. Previous versions of conda would update dependencies _as little as necessary_ to satisfy dependency requirements. Unfortunately, to obtain this fixed solver, you need to update both conda and conda-env. Hence there's a bit of a bootstrapping problem.

I understand your frustration, @frol, but in fact, and I am certainly not pleased with the bugs we've introduced in the 4.1.x upgrade. But I'm confident that we're taking the right tactic for eliminating them.

Furthermore, starting with 4.2, we are going to be instituting a "conda canary" program not unlike Google's canary program for chrome. This is going to allow us to enlist a far larger cadre of live testers of these "dot-0" updates to conda, and help us weed out these issues before they enter the stable channel, and frustrate users who don't wish to participate in such testing. Our internal unit and internal integration tests are simply nor varied enough to capture the diversity of scenarios our users experience. And while we are improving our test coverage dramatically, I'm not convinced we will truly get the functional coverage we need without the live testing a canary program will provide.

**Pull request merged**
