### PR TITLE
Use `conda-forge::minio-server`

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Instead of implementing a manual download/caching for MinIO we can turn it into a conda package.

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [ ] ~Add / update necessary tests?~
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kenodegard** [comment]
I don't have anything against eliminating MinIO entirely assuming we still get the the same level of coverage

**Comment by jezdez** [comment]
> s3 is http, and conda isn't doing anything s3-specific. Our existing http(s) package server fixture introduced in the last 6 months serves the necessary package files without requiring a large binary or an upload step.

I'm not following, we obviously do a bunch of S3 related things in the [S3 adapter](https://github.com/conda/conda/blob/4a76fea527a729421d895acfca1abfa508b50683/conda/gateways/connection/adapters/s3.py) that are very S3 specific. The e2e test is supposed to make sure we're doing the right thing and not only monkeypatching boto3's session. That would only prove that we know how to use boto3 and not that conda works with a S3-compatible server API.

**Comment by dholth** [comment]
I'm not seeing that much going on in the very short s3.py. We configure boto3 to work with a non-AWS server exactly as we would for minio. These tests do not monkey-patch boto3 except to pass it a different configuration [similar to the conda-package-streaming tests](https://github.com/conda/conda-package-streaming/blob/main/tests/test_s3.py#L12-L19). The [bucket name becomes the first part of the URL](https://github.com/conda/conda/blob/4a76fea527a729421d895acfca1abfa508b50683/conda/gateways/connection/adapters/s3.py#L75), later the s3 adapter copies boto3 response headers.

**Comment by jaimergp** [comment]
The signature monkeypatching can be undone now, btw. See https://github.com/boto/boto3/issues/1375#issuecomment-1699234689.

**Comment by jezdez** [comment]
Let's just go with this approach and then maybe strip out the S3 adapter out of Conda long-term when the #13054 has been merged.

**Review by jezdez — APPROVED** [review]

**Pull request merged**
