### PR TITLE
Fix spaces in the root path

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by msarahan** [comment]
Is this to fix #8384 ?

**Comment by mingwandroid** [comment]
Unfortunately not, no. Without this you get unnecessary (non-existent) entries on PATH if the batch file itself is located in a directory with any spaces in it. Not sure why our tests aren't covering this though, we should probably look to fix that.

**Comment by mingwandroid** [comment]
Though that is fixed (and tested for) in my new PR.

**Comment by msarahan** [comment]
OK.  I think we should just go ahead with your other PR, then?

**Comment by mingwandroid** [comment]
Fine by me either way. I'll keep pushing my changes forward.

**Comment by msarahan** [comment]
superseded by #8406, closing

**Pull request closed without merging**
