### PR TITLE
fix #3060 --clone root --copy exception

### LINKED ISSUE #3060: conda create causes: AttributeError: 'dict' object has no attribute 'add'
Trying to clone the root environment with:
```
conda create --clone root --copy -n myenv2
```
Gives:
```
Traceback (most recent call last):
  File "/opt/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 88, in clone
    index_args=index_args)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/misc.py", line 109, in explicit
    channels.add(channel)
AttributeError: 'dict' object has no attribute 'add'

```

conda info:
```
             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.1
  conda-build version : 1.18.1
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /opt/miniconda  (read only)
  default environment : /opt/miniconda
     envs directories : /home/wiecki/.conda/envs
                        /home/wiecki/envs
                        /opt/miniconda/envs
        package cache : /home/wiecki/.conda/envs/.pkgs
                        /home/wiecki/envs/.pkgs
                        /opt/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

### PR DESCRIPTION
**Pull request by kalefranz**
fixes #3060

@HugoTian I *think* this is the correct fix.  CC @mcg1969

### CODE REVIEW

**Comment by HugoTian** [comment]
@kalefranz , in explicit function, conda/misc.py line 128-129, get_index function in conda/api.py will use this channels variable, and its default value is ()

**Comment by kalefranz** [comment]
Another thing to chat about in person tomorrow :)

**Comment by twiecki** [comment]
Confirmed that it fixes #3060.

**Comment by mcg1969** [comment]
I think the problem here is that I used `{}` instead of `set()`. I'm concerned about using a list here because I don't want repetition in this list, though I suppose it's not the end of the world.

**Comment by kalefranz** [comment]
@mcg1969 I actually tried `set()` first.  And then it failed somewhere else in the code (I think in normalize_urls in config.py) because sets can't be index-accessed.  Does normalize_urls de-dupe?

**Comment by mcg1969** [comment]
Whoa, you're also adding `schannel` instead of `channel`. OK, I'd better think about this

**Comment by kalefranz** [comment]
Yes, because `channel` is guaranteed to be defined.  There's a code path (if/else branch) where it won't be.

And btw, what the #$^@ is the difference between `channel` and `schannel` anyway???

**Comment by mcg1969** [comment]
`schannel` is canonicalized, `channel` is a full URL.

**Comment by mcg1969** [comment]
The distinction preceded me; I tried to preserve it...

**Comment by kalefranz** [comment]
ok that helps

**Comment by kalefranz** [comment]
I think you can pass canonicalized channels to normalize and it will take care of it for you.

**Comment by mcg1969** [comment]
I think you're right

**Comment by kalefranz** [comment]
I could be totally wrong though.  All of this channel code gets my brain tied in knots.

**Comment by mcg1969** [comment]
Why not keep it as a `set`, but in line 128 convert it to a `list`

**Comment by kalefranz** [comment]
That's exactly what I was thinking after you said you wanted it to be a set above.

**Comment by mcg1969** [comment]
I actually like the idea of accumulating the `schannel` values anyway, instead of the longer versions. I think it will work better.

**Comment by mcg1969** [comment]
For instance: if someone changes the address of their Anaconda Cloud server, then the packages from `defaults` will "follow" them to the new server when cloning.

**Comment by mcg1969** [comment]
OK, when I add the `list()` conversion on line 128, I can get it past all the errors. It still crashes in my case, but it's due to a nonexistent URL for a local package.

**Comment by kalefranz** [comment]
> if someone changes the address of their Anaconda Cloud server, then the packages from defaults will "follow" them to the new server when cloning.

That's a really good point.  And could be an interim solution to a huge problem @JeremyEnns pointed out to me recently.

**Pull request merged**
