### PR TITLE
Restore install functionality in install.main (second attempt)

### PR DESCRIPTION
**Pull request by mcg1969**
@mingwandroid @kalefranz @ilanschnell, see: #2756 

Because I've proposed to walk back the removal of `exp_backoff_fn` from the code I thought it would be best to present my fix as a separate PR instead of merge (or worse, force-push) into Ilan's branch.

The most important part of this fix is the _manual_ copy of `urls.txt` from the `_cache` package into its final location. This is necessary because the package cache uses it to deduce the channels associated with the extracted packages. We could remove this if the shell script unpacked `_cache` instead.

I found an interesting way to do much of the testing on this. Ilan gave me a Linux version of the new Miniconda with the faulty install code inside. I ran that script _on my Mac_. Obviously, it failed as soon as it attempted to run the Python binary. But that's _exactly_ where I needed the program to stop so that I could run this modified code!

_One question_. Note the `try/except` block at the top that attempts to import other `conda` modules. If conda is already on your Python path, then these imports will succeed, which prevents you from testing this properly. Changing them to relative imports (which we should do anyway) fixes that. However, _why use a `try` block at all?_ Instead, why not do something like this?

```
if __name__ != `main`:
    from .lock import Locked
    from .utils import win_path_to_unix, url_path
    from .config import remove_binstar_tokens, pkgs_dirs, url_channel
    import random
else:
    # standalone mode
```

### CODE REVIEW

**Comment by ilanschnell** [comment]
I just gave it at try, and it appears to be working now!  The only thing I don't quite understand is why `pkgs/urls.txt` is initially copied.  This should not be necessary because `_cache` is the first package which gets linked.

**Comment by mcg1969** [comment]
@ilanschnell the reason it needs to be copied is that `package_cache()` needs it, and `extracted()` depends on `package_cache()`. So `urls.txt` needs to be in place *before* the list of dists is generated.

This is the same situation with conda constructor, and why I submitted the PR to include `urls.txt` directly into the tarball. Honestly I think that's the way it should be handled here.

**Comment by mcg1969** [comment]
Does the cache tarball have any post-link scripting? If not, then perhaps it could be extracted directly into $PREFIX before install.py is even called.

**Comment by ilanschnell** [comment]
There is no reason to treat `pkgs/urls.txt` special (it wasn't treated special before either).  The only problem was that `pkgs_dir` wasn't global.  I've added `global pkgs_dir` to my original PR https://github.com/conda/conda/pull/2756 and this is also working now.

**Comment by mcg1969** [comment]
@ilanschnell, if you want this to work, then `urls.txt` must be treated specially. I'd _prefer_ that your shell script move it into place before calling install.py, but if you do not wish to do so, this code is necessary.

**Comment by mcg1969** [comment]
I suppose we could override the package-cache functionality so that it overrides the standard determination of the cached package channels. Either way, _something different must be done_ than was done before.

**Comment by ilanschnell** [comment]
No, PR #2756 works fine.  `pkgs/urls.txt` has never been treated special in the past, and there is no reason to treat it special now.  This is not the problem.

**Comment by kalefranz** [comment]
@mcg1969, could you add a new file `tests/test_install_standalone.py`?  Or add something to `test_create.py`?  You've got a better handle right now on the nuances and details of this.

**Comment by mcg1969** [comment]
Ilan, I will not repeat myself again. This is not 4.0.9. This is 4.1. It works differently. Your installer must adapt.

**Comment by ilanschnell** [comment]
@mcg1969 I like the idea of the installer creating `pkgs/urls.txt` beforehand (outside of the conda link process).  While doing this for the shell installers should be very straight forward, it might not be so easy for the Mac OS X `.pkg` installer (or at least I have to dig into the code to see how exactly it works, and would need to be done).

**Comment by mcg1969** [comment]
That would be awesome

**Comment by kalefranz** [comment]
Declining in favor of #2756

**Pull request closed without merging**
