### PR TITLE
Remove outdated test xfails that are now xpass related to the conda-libmamba-solver release

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

These xfails were part of 23.10 before we cut conda-libmamba-solver 23.11. These are obsolete with the latest batch of releases (incl. libmambapy 1.5.3).

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~ 
     
- [X] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Review by jezdez — DISMISSED** [review]

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Comment by jezdez** [comment]
@jaimergp Shouldn't we also apply this to 23.11.x?

**Comment by kenodegard** [comment]
> @jaimergp Shouldn't we also apply this to 23.11.x?

`main` _is_ `23.11.x` since we haven't made it yet

**Comment by jezdez** [comment]
> > Shouldn't we also apply this to 23.11.x?
> 
> `main` _is_ `23.11.x` since we haven't made it yet

Sorry, that was a typo, I meant 23.10.x

**Comment by kenodegard** [comment]
I don't think thats necessary, `xfail`/`xpass` is ok, the problem was the `strict=True` which was already merged into 23.10.x in https://github.com/conda/conda/pull/13289

**Review by kenodegard — APPROVED** [review]

**Review by jezdez — APPROVED** [review]

**Review by beeankha — APPROVED** [review]

**Comment by jaimergp** [comment]
I know this is unrelated but I can't help but notice how some of the tests are really slow with the conda-forge CI o.o

```
1627.25s call     tests/conda_env/test_cli.py::test_update_env_json_output[classic]
1651.34s call     tests/conda_env/test_cli.py::test_set_unset_env_vars_env_no_exist[classic]
2247.37s call     tests/conda_env/test_cli.py::test_update[classic]
```

I can only explain this if somehow `defaults` is _also_ being considered in those tests, with flexible priority, which strains the classic solver quite a bit.

**Pull request merged**
