### PR TITLE
Added support for AWS S3 channels

### PR DESCRIPTION
**Pull request by dedalusj**
Add support for s3 channels.

Any channel URL that uses the s3:// protocol will communicate with S3 through boto.

### CODE REVIEW

**Comment by dedalusj** [comment]
Any chances for this to be accepted and merged?

I'd be happy to restart the pull request from scratch if the feature is deemed useful but the code not up to the job.

**Comment by meawoppl** [comment]
Any movement on this?

**Comment by asmeurer** [comment]
This slipped through the cracks. It needs a merge with master, but if it works, I think it can be merged.

**Comment by dedalusj** [comment]
I test it manually and it works fine. 

I would also be happy to write an integration test but there don't seem to be any in conda at the moment. Also we would need to solve the problem of which S3 account to use and credentials.

Also merged master in it but you may want to rebase the merge if you prefer a different message.

**Comment by meawoppl** [comment]
Thanks!

**Pull request merged**
