### PR TITLE
Respect PEP440 ~= 'Compatible release clause'

### PR DESCRIPTION
**Pull request by mingwandroid**
.. we expand this to >=X.Y.Z,==X.Y.* as per the PEP

### CODE REVIEW

**Comment by mingwandroid** [comment]
conda-build has an implementation of this (seems unused) that I resurrected. It gives different results:

`kubernetes >=11.0.0,<11.1` vs `kubernetes >=11.0.0,==11.0.*`

.. which do we want? In general it seems conda-build has changed to defer to conda in this matter and the old code-path is redundant.

**Comment by chenghlee** [comment]
> conda-build has an implementation of this (seems unused) that I resurrected. It gives different results:
> 
> `kubernetes >=11.0.0,<11.1` vs `kubernetes >=11.0.0,==11.0.*`
> 
> .. which do we want? In general it seems conda-build has changed to defer to conda in this matter and the old code-path is redundant.

If we're going for PEP440 compliance, I would say the latter (`kubernetes >=11.0.0,==11.0.*`).

**Review by chenghlee — APPROVED** [review]
LGTM

**Comment by mingwandroid** [comment]
Thanks! I'll adjust my conda-build PR, together this fixes https://github.com/conda/conda-build/issues/4108

**Pull request merged**
