### PR TITLE
Pkg cache issues

### PR DESCRIPTION
**Pull request by mingwandroid**
@mcg1969 , @groutr I had to make these changes to be able to use conda-build.

Please review. Also, do you know if other projects call `fetch_pkg`? If so I may need to amend the call-sites (if they use any non-default arguments).

### CODE REVIEW

**Comment by mcg1969** [comment]
Are you trying to use the `master` build of `conda`? The `::` separator shouldn't be in a tagged release yet. What was the specific issue you're having? My `mgrant\channelfix` branch is attempting to fix some known issues in `master` and will basically clobber this PR. You might want to test against that branch (without your fixes)

**Comment by mcg1969** [comment]
In particular, we are not intending to use `::` as a filename. It's for internal use only. We do have issues with cache conflicts, but for now we don't want to start introducing weird filenames or subdirectories into the cache.

**Comment by mcg1969** [comment]
Didn't mean to close, it sorry---though I do think we eventually will. But let's make sure the problems you're seeing are addressed somehow.

**Comment by mingwandroid** [comment]
Hi @mcg, yes, I always build from `master` since I'm making changes to `master` for my own purposes (namely MSYS2 integration). Is that not a good idea?

**Comment by mcg1969** [comment]
Oh no, I'm sure internally it's fine. It's only a problem in this case because a recent merge broke master :-) and because I've been actively working on a fix that involves `fetch_pkg` among other things.

**Comment by mcg1969** [comment]
We talked about the problem you're addressing here in the Anaconda team meeting, though, and Kale and I agreed that we shouldn't be changing the cache structure at this point. That means we don't want to mangle the filenames in any way, which means that we're handling cache collisions by removing the older package from the cache. That takes a bit more logic.

**Comment by mingwandroid** [comment]
Ah, I do remember that, but mistook cache structure to relate to some python structure rather than this file layout :-)

I learned a bit more about the internals of Conda so it was useful for me anyway.

Thanks @mcg1969. I'll close this PR and delete the branch when your new logic lands in master.

**Comment by mcg1969** [comment]
I just want to make sure that if someone has to drop back to an older version of `conda` for some reason that the cache still works...

**Comment by mcg1969** [comment]
And I am _very_ glad that you are learning more about the `conda` internals! We need more folks who can make changes like this.

**Comment by mingwandroid** [comment]
No problem!

**Comment by mcg1969** [comment]
Now that `mgrant/channelfix` is passing tests, why don't you see how it handles your work. It's a pretty bug change to `install` in particular.

**Comment by mingwandroid** [comment]
ok will do.

**Comment by mingwandroid** [comment]
I've added some comments to https://github.com/conda/conda/pull/2369/commits/1cba7ae7702b70d1d12cbc73d477f3da4fa62218

Cheers.

**Comment by mcg1969** [comment]
Excellent! I see them. I'll respond when I can

**Pull request closed without merging**
