### PR TITLE
Do not yield osx virtual package when CONDA_OVERRIDE_OSX=""

### PR DESCRIPTION
**Pull request by lesteve**
### Description

I believe this would fix the conda-lock issue https://github.com/conda/conda-lock/issues/408 where the current work-around is to pin conda to 22.9.

It seems like a very similar issue has been fixed for the glibc virtual package in https://github.com/conda/conda/pull/12293 but the issue is still there for the osx virtual package.

In particular the change of behaviour seems very similar to the one mentioned in https://github.com/conda/conda/issues/12267#issuecomment-1407786283:
- in 22.9 if `CONDA_OVERRIDE_OSX=""` no virtual package for osx is exported
https://github.com/conda/conda/blob/60e11b4f1859874c1cb1a3ae324e599e0867a086/conda/core/index.py#L179-L184
- in `main` a virtual package for osx is always exported:
https://github.com/conda/conda/blob/61edfac743a2461a24fafe48b821a99af61b6bd4/conda/plugins/virtual_packages/osx.py#L10-L18
- apparently when such a virtual package is exported it causes issue in conda-lock.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by maresb** [comment]
@lesteve, I think you will need to sign the CLA to move this forward.

**Comment by lesteve** [comment]
On the CLA front, I think I have done what is needed on my side already a few days ago in https://github.com/conda/infrastructure/pull/769.

My understanding is that someone on the conda side needs to review and accept https://github.com/conda/infrastructure/pull/769. Let me know in case this is not fully correct.

**Comment by travishathaway** [comment]
@conda-bot check

**Comment by travishathaway** [comment]
@conda-bot  check

**Comment by travishathaway** [comment]
Hi @lesteve,

Thanks for submitting this pull request. So far this looks like a very reasonable change. We really appreciate you adding a new test for this too 💪. Once the tests finish running (and pass), I will be happy to give my approval. I will also ask at least one more maintainer to look it over too. Once that happens, we'll be happy to merge it 🚀.

Keep an eye on this pull request for updates and be sure to check back for any failing tests.

**Comment by travishathaway** [comment]
One more thing,

I also made a couple of updates to the branch itself (merged from main and fixed a newline issue on the "news" file), so you should do a pull first before doing any more work on it.

**Comment by lesteve** [comment]
Thanks for your answer and fixes to my branch!

> We really appreciate you adding a new test for this too

I already added a test in https://github.com/conda/conda/pull/12715/files#diff-91099116a26413a7fab4604704da4ea5f7a75f280b1e83d53fc86090325cee20, let me know in case you had something in mind. I did something very similar to what was done for a similar issue for glibc in https://github.com/conda/conda/pull/12293

CI is green :tada:, let me know if there is something else I can do to help pushing this forward!

**Comment by lesteve** [comment]
Oops misclick I closed this PR and reopened :facepalm:

**Review by beeankha — COMMENTED** [review]
Thank you for this pull request, @lesteve !

**Review by beeankha — APPROVED** [review]

**Comment by travishathaway** [comment]
@lesteve,

I meant that we appreciated that you already added a test 😅. Believe it or not but some people submit pull requests to conda without tests 🙄.

**Review by travishathaway — APPROVED** [review]
Once we get the green light from tests again. We will merge 🚀

**Comment by lesteve** [comment]
Great to see this one merged, thanks!

**Pull request merged**
