### PR TITLE
Add -Stack switch Enter-CondaEnvironment PowerShell function

### LINKED ISSUE #8216: [4.6.2] Environment stacking in PowerShell is broken!
```
(r-dev) C:\> conda env list
# conda environments:
#
base                     C:\Miniconda3
py-dev                   C:\Miniconda3\envs\py-dev
r-dev                 *  C:\Miniconda3\envs\r-dev

(r-dev) C:\> conda activate --stack py-dev
Enter-CondaEnvironment : A positional parameter cannot be found that accepts argument 'py-dev'.
At C:\Miniconda3\shell\condabin\Conda.psm1:132 char:17
+                 Enter-CondaEnvironment @OtherArgs;
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Enter-CondaEnvironment], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Enter-CondaEnvironment
```

### PR DESCRIPTION
**Pull request by dhirschfeld**
Fixes #8216

### CODE REVIEW

**Comment by dhirschfeld** [comment]
PowerShell doesn't support the `--stack` syntax so with this PR it's either `-stack` or `-Stack` - e.g.
```powershell
C:\> conda activate r-dev
(r-dev) C:\> conda activate -stack py-dev
(py-dev) C:\> $env:PATH -split ';' | select -first 23
C:\Miniconda3\envs\py-dev
C:\Miniconda3\envs\py-dev/Library/mingw-w64/bin
C:\Miniconda3\envs\py-dev/Library/usr/bin
C:\Miniconda3\envs\py-dev/Library/bin
C:\Miniconda3\envs\py-dev/Scripts
C:\Miniconda3\envs\py-dev/bin
C:\Miniconda3\envs\r-dev
C:\Miniconda3\envs\r-dev/Library/mingw-w64/bin
C:\Miniconda3\envs\r-dev/Library/usr/bin
C:\Miniconda3\envs\r-dev/Library/bin
C:\Miniconda3\envs\r-dev/Scripts
C:\Miniconda3\envs\r-dev/bin
C:\Miniconda3\condabin
%SystemRoot%\system32\WindowsPowerShell\v1.0\
C:\Miniconda3
C:\Miniconda3\Library\mingw-w64\bin
C:\Miniconda3\Library\usr\bin
C:\Miniconda3\Library\bin
C:\Miniconda3\Scripts
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
```

**Comment by kalefranz** [comment]
There’s an integration test portion at the bottom of `tests/test_activate.py` that should be pretty straight-forward to extend.

**Comment by dhirschfeld** [comment]
It looks like circle got itself confused, but otherwise the ci is good:
```
tests/test_activate.py::ShellWrapperIntegrationTests::test_powershell_basic_integration PASSED [  6%]
```

**Comment by jjhelmus** [comment]
Looks good, thanks for putting this together @dhirschfeld.

**Comment by dhirschfeld** [comment]
Just as an aside - the stacking capability in conda 4.6 is ***awesome***!

I'm using it to keep separate `py-dev` and `r-dev` environments so that changes in one won't impact the other and to minimise the work the solver has to do.

I use stacking to enable interop between the lanugages with rpy2/reticulate which seems to be working just great.

Other usecases for stacking I envisage is to provide a locked down "default" environment with a "user" environment layered on top. For development my "user" envrironment would just include all my `pip install --no-deps -e .` packages... well, I'm hoping that might work :)

**Comment by kalefranz** [comment]
> well, I'm hoping that might work

So long as there’s no assumption or need to share the same python interpreter across two environments, I see no reason why not.

If you do need to share that default interpreter with the user environment, you can hack around with `PYTHONPATH` and stack the “user” site-packages directory on top of the one in “default”. The “user” python executable would be first on PATH, so you’d need to invoke it via explicit path rather than relying on PATH resolution. Or... you need to figure out how to trick conda into being ok with making and maintain a broken “user” environment with no python in it (but with packages that depend on python).

Interested to see what you come up with.

**Comment by dhirschfeld** [comment]
Well, `rpy2` depends on both python and r packages so for now I've installed direct from the bz2. I think it should work for a locked down environment, but yeah, conda might want to "fix" it if I try updating anything.

**Comment by dhirschfeld** [comment]
For the user layer I'm planning on just pinning the interpreter to the exact version in the default layer - seems cleaner than PYTHONPATH manipulations. Guess I'll see though!

**Pull request merged**
