### PR TITLE
Fixes to symlink_conda issues

### PR DESCRIPTION
**Pull request by asmeurer**
- Use `lexists` instead of `exists`. The former returns True for broken symlinks.
- Don't attempt to symlink conda in the root environment. I believe this can lead to a situation where there is a broken symlink if, e.g., activate does not exist in the root environment, in which case it writes a symlink to itself (which is considered to be a broken symlink). 

I have not fully tested this yet.

### CODE REVIEW

**Comment by tswicegood** [comment]
In theory this seems correct.  Would definitely want to test pretty thoroughly though.  I thought that maybe I had ended up in a state where I had a symlink inside a `conda-env` package I had built, but I can't find one in the package cache, so I don't think that was the case.

**Comment by tswicegood** [comment]
Ok, I can not force an environment where this happens.  If I uninstall conda-env, then try to install something else into root, conda-env gets added back in.

**Comment by asmeurer** [comment]
Manually delete (or set aside) the activate script maybe.

**Comment by tswicegood** [comment]
Yeah -- that would work, @asmeurer.  I'm just trying to figure out how it got to that state in the first place.

**Comment by asmeurer** [comment]
I found another issue that reported this https://github.com/conda/conda/issues/1056. Looks like that was caused by some other issue (that is, I don't think your situation was similar to his).

**Pull request merged**
