### PR TITLE
Make Null False-y w/ Python 3

### PR DESCRIPTION
**Pull request by alanhdu**
Fix https://github.com/conda/conda/issues/3492

### CODE REVIEW

**Comment by alanhdu** [comment]
Our of curiosity, why do we define `Null` instead of just using `None`? Is there some arguments where `None` is an acceptable value that we need to distinguish from "no default passed"? (I could imagine this happening to deal w/ flags overriding `.condarc`, for example).

**Comment by Korijn** [comment]
Seems pointless to me as well... nice find though!

**Comment by alanhdu** [comment]
@codecov-io ... what?

**Comment by kalefranz** [comment]
This is a good catch.

Python doesn't have an "undefined" or "not set" type, and so often values get set to `None`.  Sometimes you need to know if a value was explicitly set to `None`, or if the real intention was "not set" or "undefined".  That's why this was added.  It's used fairly extensively now with argparse, which is probably where you were running into the error.

I'll merge this soon.

**Comment by kalefranz** [comment]
> Are there some arguments where None is an acceptable value that we need to distinguish from "no default passed"? (I could imagine this happening to deal w/ flags overriding .condarc, for example).

Oh, yes, that's exactly one of the use cases.

**Comment by kalefranz** [comment]
superseded by #3524

Needed to point at different branch, and added a test (like I should have done to begin with).

**Comment by Korijn** [comment]
Although I definitely agree with the use case (and see the resemblance with js), the name does not reveal the intent and is very similar to `None` (e.g. `UNKNOWN` or `UNDEFINED` would be clearer), and there is no docstring noting the purpose. 

IMHO, I think it's asking for misinterpretation and is a barrier for devs who wish to contribute fixes (although @alanhdu cleverly figured it out).

**Pull request closed without merging**
