### PR TITLE
Detect masked test errors by setting errtrace, pipefail, errexit

### PR DESCRIPTION
**Pull request by dbast**
Also set the correct shell shebang.

### CODE REVIEW

**Comment by dbast** [comment]
hm. ERROR: file or directory not found: --cov-report xml --cov-report term-missing --cov conda
collecting ... collected 0 items

**Comment by dbast** [comment]
Exit code of previously failure on master (1 failing test) was silently ignored: https://github.com/conda/conda/runs/3232154308#step:3:15879

It is detected now: see e.g. https://github.com/conda/conda/pull/10840/checks?check_run_id=3233496612#step:3:15920

**Comment by dbast** [comment]
Everything is green now and correct red/green CI status reporting.

**Review by jezdez — APPROVED** [review]
Thanks @dbast!

**Pull request merged**
