### PR TITLE
Add macOS to CI

### LINKED ISSUE #10990: Add macOS as a platform to the CI system
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

We need to run the tests regularly on macOS.

### Why is this needed

_No response_

### What should happen?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jezdez**
This is basically a continuation of #10864 but I couldn't get it reliably running on macos and the other PR was already pretty old.

Fix #10990.

### CODE REVIEW

**Comment by jezdez** [comment]
Hey @rchord, this is the PR we talked about regarding macOS support. Sadly we have a very limited number of runners (5), so we should probably reduce the test matrix to only test the latest Python versions for example.

**Comment by jaimergp** [comment]
The failures with `_conda_test_env_activated_when_post_link_executed` corruption seem to do with [this package](https://anaconda.org/conda-test/_conda_test_env_activated_when_post_link_executed/files). I checked the tarballs and the post-link script is indeed not included in the `bin/` directory. Those packages might need to be rebuilt.

**Comment by jaimergp** [comment]
@jezdez Is this coming from another branch we are bypassing? The diff looks immense :/

**Comment by jezdez** [comment]
> @jezdez Is this coming from another branch we are bypassing? The diff looks immense :/

Sorry, this was just a wrong rebase, should be smaller now.

**Review by jaimergp — APPROVED** [review]

**Comment by jaimergp** [comment]
These are the same errors we used to have, but I've debugged a bit more. I still think we should mark them as xfail for now and deal with them in a different PR. I will create issues for those two now.

**Comment by jaimergp** [comment]
Done! Check:

* https://github.com/conda/conda/issues/11127
* https://github.com/conda/conda/issues/11128

The issue numbers have been added to the known-broken reason too.

**Pull request merged**
