### PR TITLE
Ray activation fixes

### PR DESCRIPTION
**Pull request by msarahan**
continuing work on #8324

### CODE REVIEW

**Comment by msarahan** [comment]
There seems to be an extra Library/bin coming in on Windows somehow:

```
-> assert len(start_paths) + num_paths_added == len(end_paths), {'added': extra_paths, 'removed': missing_paths}
(Pdb) start_paths
['/c/Miniconda36-x64/condabin', '/c/Miniconda36-x64', '/c/Miniconda36-x64/condabin', '/c/Program Files/Docker/Docker/Resources/bin', '/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin', '/c/Perl/site/bin', '/c/Perl/bin', '/c/Windows/system32', '/c/Windows', '/c/Windows/System32/Wbem', '/c/Windows/System32/WindowsPowerShell/v1.0/', '/c/Program Files/7-Zip', '/c/Tools/GitVersion', '/c/Tools/NuGet', '/c/Program Files/Microsoft/Web Platform Installer/', '/c/Tools/PsTools', '/c/Program Files/Git LFS', '/c/Program Files/Mercurial/', '/c/Program Files (x86)/Subversion/bin', '/c/Tools/WebDriver', '/c/Tools/Coverity/bin', '/c/Tools/MSpec', '/c/Tools/NUnit/bin', '/c/Tools/NUnit3', '/c/Tools/xUnit', '/c/Program Files/nodejs', '/c/Program Files (x86)/iojs', '/c/Program Files/iojs', '/c/Program Files/Microsoft SQL Server/120/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/120/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio/', '/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/130/Tools/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn/', '/c/Program Files/Microsoft SQL Server/130/DTS/Binn/', '/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn/', '/c/Ruby193/bin', '/c/go/bin', '/c/Program Files/Java/jdk1.8.0/bin', '/c/Program Files (x86)/Apache/Maven/bin', '/c/Python27', '/c/Python27/Scripts', '/c/Program Files (x86)/CMake/bin', '/c/Tools/curl/bin', '/c/Program Files/Microsoft DNX/Dnvm/', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/130', '/c/Program Files/Amazon/AWSCLI/', '/c/Program Files/dotnet/', '/c/Tools/vcpkg', '/c/Program Files (x86)/dotnet/', '/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/140/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/140/DTS/Binn/', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/TestPlatform', '/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn/', '/c/Program Files/erl9.2/bin', '/c/Program Files (x86)/NSIS', '/c/Tools/Octopus', '/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/', '/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code', '/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager', '/c/Program Files/Docker/Docker/resources', '/c/Program Files/LLVM/bin', '/cmd', '/c/Program Files (x86)/Yarn/bin/', '/usr/bin', '/c/Users/appveyor/AppData/Roaming/npm', '/c/Program Files/PowerShell/6/', '/c/Program Files (x86)/nodejs/', '/c/ProgramData/chocolatey/bin', '/c/Users/appveyor/AppData/Local/Microsoft/WindowsApps', '/c/Users/appveyor/.dotnet/tools', '/c/Users/appveyor/AppData/Local/Yarn/bin', '/c/Users/appveyor/AppData/Roaming/npm', '/usr/bin']
(Pdb) end_paths
['/c/Miniconda36-x64', '/c/Miniconda36-x64/Library/mingw-w64/bin', '/c/Miniconda36-x64/Library/usr/bin', '/c/Miniconda36-x64/Library/bin', '/c/Miniconda36-x64/Scripts', '/c/Miniconda36-x64/bin', '/c/Miniconda36-x64/Library/bin', '/c/Miniconda36-x64/condabin', '/c/Miniconda36-x64', '/c/Miniconda36-x64/condabin', '/c/Program Files/Docker/Docker/Resources/bin', '/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin', '/c/Perl/site/bin', '/c/Perl/bin', '/c/Windows/system32', '/c/Windows', '/c/Windows/System32/Wbem', '/c/Windows/System32/WindowsPowerShell/v1.0/', '/c/Program Files/7-Zip', '/c/Tools/GitVersion', '/c/Tools/NuGet', '/c/Program Files/Microsoft/Web Platform Installer/', '/c/Tools/PsTools', '/c/Program Files/Git LFS', '/c/Program Files/Mercurial/', '/c/Program Files (x86)/Subversion/bin', '/c/Tools/WebDriver', '/c/Tools/Coverity/bin', '/c/Tools/MSpec', '/c/Tools/NUnit/bin', '/c/Tools/NUnit3', '/c/Tools/xUnit', '/c/Program Files/nodejs', '/c/Program Files (x86)/iojs', '/c/Program Files/iojs', '/c/Program Files/Microsoft SQL Server/120/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/120/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio/', '/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/130/Tools/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn/', '/c/Program Files/Microsoft SQL Server/130/DTS/Binn/', '/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn/', '/c/Ruby193/bin', '/c/go/bin', '/c/Program Files/Java/jdk1.8.0/bin', '/c/Program Files (x86)/Apache/Maven/bin', '/c/Python27', '/c/Python27/Scripts', '/c/Program Files (x86)/CMake/bin', '/c/Tools/curl/bin', '/c/Program Files/Microsoft DNX/Dnvm/', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/130', '/c/Program Files/Amazon/AWSCLI/', '/c/Program Files/dotnet/', '/c/Tools/vcpkg', '/c/Program Files (x86)/dotnet/', '/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/140/Tools/Binn/', '/c/Program Files/Microsoft SQL Server/140/DTS/Binn/', '/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/Extensions/TestPlatform', '/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn/', '/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn/', '/c/Program Files/erl9.2/bin', '/c/Program Files (x86)/NSIS', '/c/Tools/Octopus', '/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/', '/c/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code', '/c/Program Files/Microsoft SDKs/Service Fabric/Tools/ServiceFabricLocalClusterManager', '/c/Program Files/Docker/Docker/resources', '/c/Program Files/LLVM/bin', '/cmd', '/c/Program Files (x86)/Yarn/bin/', '/usr/bin', '/c/Users/appveyor/AppData/Roaming/npm', '/c/Program Files/PowerShell/6/', '/c/Program Files (x86)/nodejs/', '/c/ProgramData/chocolatey/bin', '/c/Users/appveyor/AppData/Local/Microsoft/WindowsApps', '/c/Users/appveyor/.dotnet/tools', '/c/Users/appveyor/AppData/Local/Yarn/bin', '/c/Users/appveyor/AppData/Roaming/npm', '/usr/bin']
```

**Comment by msarahan** [comment]
I think the extra is because of the old pythons patching that in.  I'll see about tweaking the tests for it.

**Comment by msarahan** [comment]
yes, with run_constrained, that seems like a sane way forward.

**Comment by mingwandroid** [comment]
OK, shall I prepare the recipes and test packages for python 2.7 and 3.6 without `Library\bin` then? Shouldn't take too long, but I won't do it until tomorrow.

**Comment by msarahan** [comment]
superseded by #8406

**Pull request closed without merging**
