### PR TITLE
[WIP] Repo plugin prototype

### PR DESCRIPTION
**Pull request by FFY00**
Per https://github.com/conda/conda/issues/11600#issuecomment-1238462096

> The goal is to provide a design for the plugin data structures and extract the current implementation to what will become the default implementation plugin.

This PR just implements the data structures and prepares the codebase for the plugin system to be able to hook into it.

TODO:

- [X] Implement repodata fetching
- [ ] Implement package fetching

After this, we can open a proper PR against the plugins branch.

### CODE REVIEW

**Comment by beeankha** [comment]
@FFY00 could you please point this PR to the `feature/plugins` feature branch?

**Comment by beeankha** [comment]
(connecting issue https://github.com/conda/conda/issues/11600)

**Comment by FFY00** [comment]
I have purposely not based this on the plugins branch, as that's fast moving, and I didn't want to have to deal with keeping up with it for the prototype. I'll definitely point at the plugins branch when actually proposing an implementation. Does this sound reasonable to you? Or do you want me to change the approach? :sweat_smile:

**Comment by beeankha** [comment]
> I have purposely not based this on the plugins branch, as that's fast moving, and I didn't want to have to deal with keeping up with it for the prototype. I'll definitely point at the plugins branch when actually proposing an implementation. Does this sound reasonable to you? Or do you want me to change the approach? 😅

One reason we might want to point to the feature branch sooner rather than later is so that we can see if everything integrates together well, but I understand not wanting to keep up with a feature branch while things are still in the early stages! 👍

**Comment by FFY00** [comment]
The repodata implementation seems to be working properly now, we just need to port the tests and add some backport imports to get the tests to pass.

**Comment by dholth** [comment]
I'm working on a less dramatic extension of this change at https://github.com/conda/conda/pull/12003 which introduces `gateways.repodata` and should pass tests.

I think it will be necessary to get this working as a not-plugin and then refactor it, again, into a plugin once we have several use cases working nicely.

**Pull request closed without merging**
