### PR TITLE
Merge plugins feature branch into main.

### PR DESCRIPTION
**Pull request by jezdez**
### Description

This PR basically exists to:

a) easily update the feature branch by using GitHub's regular rebase/merge button
b) have a place where we can do a final review

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Review by beeankha — APPROVED** [review]

**Review by travishathaway — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]

**Comment by jaimergp** [comment]
I think the conda recipe at `/recipe` needs to have `pluggy` as a dependency. Otherwise the PR preview builds fail :D [See run here](https://github.com/conda/conda/pull/12043#issuecomment-1298800258).

**Comment by kenodegard** [comment]
@jaimergp pluggy is listed as a dependency, the build failures is related to how conda-build runs `python -m conda` (afaik your isolation PR is the fix we need), this is the same issue that we've encountered when we attempted to remove toolz from vendored

**Comment by dholth** [comment]
Still it seems like there ought to be possible to install pluggy into whichever environment conda build uses to run "python -m conda", before conda-build runs

**Comment by jaimergp** [comment]
Oh, I see @kenodegard, thanks for the clarification. Let's see if we can get https://github.com/conda/conda-build/pull/4604 in!

**Pull request merged**
