### PR TITLE
Removed allow_other_channels from conda docs.

### LINKED ISSUE #7469: Documentation describes non-existent option
It looks like the "allow_other_channels" option was removed (replaced by "whitelist_channels"?). However, there are still multiple places in the documentation that refer to and describe this feature, which is leads to confusion when one wonders why it's not working...

https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#allow-other-channels-allow-other-channels
https://conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html#system-configuration-file

-----

To Do

- [X] Check if allow_other_channels and allowlist_channels are the same option (they aren't quite. allow_other_channels is a Boolean, while allowlist_channels is a list. allow_other_channels seems to have been completely removed from the .condarc, however)
- ~[ ] If so, add allow_other_channels to the alias list for allowlist_channels~
- [ ] Update doc pages listed above

### PR DESCRIPTION
**Pull request by kathatherine**
### Description

Closes #7469. Updated documentation, removing the defunct allow_all_channels command and changing the recommendations in the [Administering a multi-user conda installation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/admin-multi-user-install.html) page.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] ~Add / update necessary tests?~
- [x] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kathatherine** [comment]
@chenghlee Not totally positive if I've gone about rewriting the admin-multi-user-install page correctly. Would appreciate it if you could take a look.

**Review by kenodegard — CHANGES_REQUESTED** [review]
Minor edits, I've checked the instructions locally, and yes it works as expected.

The only problem with the `#!final` syntax is that the user gets no warning as to why their settings are ignored (which I can imagine would be very confusing and frustrating). I'll open a new issue.

**Comment by kenodegard** [comment]
pre-commit.ci autofix

**Review by kenodegard — APPROVED** [review]

**Review by beeankha — APPROVED** [review]
LGTM!

**Pull request merged**
