### PR TITLE
Updates to the conda command help

### PR DESCRIPTION
**Pull request by asmeurer**
CC @kerrywatson1

### CODE REVIEW

**Comment by asmeurer** [comment]
All done here. The website will not be updated until we do a release. I'll do conda-build tomorrow.

**Comment by kerrywatson1** [comment]
Wow, awesome Aaron!

**Comment by asmeurer** [comment]
@kerrywatson1 did you want the uppercase and period rule to apply to the option help, like 

```
-f, --force
              force install (even when  package  already  installed),  implies
              --no-deps
```

or just the descriptions?

**Comment by asmeurer** [comment]
Note that the standard seems to be neither. For instance, 

```
    -h, --help
              show this help message and exit
```

comes directly from argparse, not from us.  But I also see other tools use them (e.g., all the git manpages seem to use capitalization and periods).

**Comment by kerrywatson1** [comment]
There is no set standard for this, so we want to pick a way and be
consistent about it.

I recommend using capitalization and periods because many readers are from
other countries and these are guideposts that help them understand the
content.

Kerry

**Pull request merged**
