### PR TITLE
Allow 'conda update --all python=3' in a Python 2 environment

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by ilanschnell** [comment]
Does this change update Python 2 to Python 3 for the environment you run `conda update --all python=3` ?

**Comment by asmeurer** [comment]
Yes. It already works for Python 3.4 to 3.5 with `conda update --all Python=3.5` but I missed a bit of logic for going from 2 to 3. 

This should be the recommended way to change the python version in an environment because it will only complete the operation if all packages can be updated.

**Comment by kalefranz** [comment]
@mcg1969 Probably should also support and test analogous `conda update --all Python=2.7`

**Comment by kalefranz** [comment]
The new solver logic conda-sorta handles this, but the functionality is different, and I think we need some other tweaks to carry this all the way.

**Comment by mcg1969** [comment]
Yeah, I think now you just do `conda install python=3` and you're good. From there you can do `conda update --all` if you're inclined.

**Comment by asmeurer** [comment]
Does specifying packages with `update --all` still work? If so, I think this PR still fixes a relevant bug.

**Comment by mcg1969** [comment]
in what way is this actually a bug? It was my understanding that `update` doesn't accept version strings, just bare package names.

**Comment by asmeurer** [comment]
IIRC `update` has always allowed version strings.

**Comment by mcg1969** [comment]
I just looked at this recently, and that seemed not to be the case. I'll look for the code

**Comment by mcg1969** [comment]
https://github.com/conda/conda/blame/master/conda/cli/install.py#L145-L148

**Comment by asmeurer** [comment]
I don't see how that line prevents version strings.

**Comment by kalefranz** [comment]
Might not be that line.  @ilanschnell confirmed a while back in conversation that `update` is not allowed to take versions.  Here's current behavior:

    kfranz@0283:~/continuum/conda2 *master ❯ conda install jinja2=2.7
    Fetching package metadata: ....
    Solving package specifications: ...........

    Package plan for installation in environment /Users/kfranz/.conda:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        jinja2-2.7.3               |           py27_1         307 KB

    The following packages will be UPDATED:

        conda:  3.19.3-py27_0 --> 4.0.2-py27_0

    The following packages will be DOWNGRADED:

        jinja2: 2.8-py27_0    --> 2.7.3-py27_1

    Proceed ([y]/n)? n

    (1)kfranz@0283:~/continuum/conda2 *master ❯ conda update jinja2=2.7
    Error: Invalid package name: 'jinja2=2.7'

**Comment by ilanschnell** [comment]
I only confirmed that `conda update` does not allow versions.  Now we are talking about `conda update --all`, which might have had a different behavior for a long time.

**Comment by mcg1969** [comment]
>  I don't see how that line prevents version strings.

Well, the standard approach to version strings _on the command line_ uses equal signs. Unlike other places in the code, the command line arguments aren't preprocessed here to remove those equals signs, so this test will reject any argument that has them.

But Ilan makes a good point about `--all` being distinct.

**Comment by asmeurer** [comment]
OK, well now I don't remember if it ever worked with `--all`, or if that's just what I'm implementing here (but just for `python`). If the latter, it seems there are better ways to update an environment, so you should just update the documentation.

**Pull request closed without merging**
