### PR TITLE
Fix typos in docstring

### PR DESCRIPTION
**Pull request by Anthchirp**
just two trivial things I noted on the website

### CODE REVIEW

**Comment by angloyna** [comment]
@Anthchirp would you be able to bring in the latest conda master to get these tests running? That should unblock this easy fix.

**Comment by Anthchirp** [comment]
CLA signed

**Comment by angloyna** [comment]
@cla-bot check

**Comment by angloyna** [comment]
Excellent. Thanks, we'll wait for the tests and merge this in.

**Pull request merged**
