### PR TITLE
Set show_channel_urls=True as default behaviour.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by ocefpaf** [comment]
:+1:

**Comment by rsignell-usgs** [comment]
:+1: :fireworks:

**Comment by groutr** [comment]
Thanks!

**Comment by ilanschnell** [comment]
I think we should change the default behavior.  When all packages come from the `defaults` channel, which is the case for most users, there is no need to show the channels.  I'm suggesting to (by default) only show the channels, if at least one package comes from something other than `defaults`.

**Comment by pelson** [comment]
> which is the case for most users

Interesting - I have no feeling for whether that is true or not, I guess your miniconda vs anaconda download statistics would be able to tell us that. Either way, it is certainly the case for most *novice* users, so something which helps them out is no bad thing. :+1: to your suggestion if implemented carefully.

**Comment by ilanschnell** [comment]
most users = novice users

**Comment by ilanschnell** [comment]
Here is the implementation of my idea: https://github.com/conda/conda/pull/1900

**Pull request merged**
