### PR TITLE
Refactor pip interoperability tests

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Xref https://github.com/conda/conda/issues/13292

Refactors:
- `test_conda_pip_interop_pip_clobbers_conda`
- `test_conda_pip_interop_conda_editable_package`
- `test_conda_pip_interop_compatible_release_operator`

### Checklist - did you ...

- [ ] ~Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~
     
- [x] Add / update necessary tests?
- [ ] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kenodegard** [comment]
pre-commit.ci autofix

**Comment by kenodegard** [comment]
test failures are resolved by https://github.com/conda/conda/pull/13539 and https://github.com/conda/conda/pull/13544

**Comment by kenodegard** [comment]
@jaimergp is `LibMambaUnsatisfiableError` the equivalent of `PackagesNotFoundError`? or is there some other issue with the test?

See https://github.com/conda/conda/actions/runs/7792807353/job/21254065998?pr=13537

**Comment by jaimergp** [comment]
We don't implement pip interoperability (yet?), so I'm not sure what the expected outcome should be. In some tests, libmamba will fail with Unsatisfiable instead of PackagesNotFound (we infer PackagesNotFound from the error messages when we find a `nothing provides X`, but sometimes libmamba finds another "explanation" for the same issue that can't be classified as PNFPackagesNotFound.

**Review by beeankha — APPROVED** [review]

**Pull request merged**
