### PR TITLE
Allow configuring instrumentation record file location

### PR DESCRIPTION
**Pull request by geremih**
Currently all instrumentation is written to the same file. This makes it harder to look up the records retrospectively and can clobber the same file if you are creating multiple envs.

This is just one possible solution, another one would be to fix the file to be relative to the env (if so, where?).

### CODE REVIEW

**Comment by msarahan** [comment]
I think this is fine - the test failures look like old ones that should now be fixed.  You've signed the CLA on other work.  I'm re-running the tests in the hopes they'll magically fixe themselves, but I'll merge either way.  Thanks, and sorry for the delay.

**Comment by kalefranz** [comment]
I think this PR forgets to call `expanduser()` (or `expand()`) on `~`.

**Comment by geremih** [comment]
@msarahan can we get this merged? wondering if it can still make it into 4.6.0

**Comment by msarahan** [comment]
Sorry, we really, really don't want anything to delay 4.6.0 any further.  We're making last-minute fixes and hoping for a release Monday or Tuesday.  This can go in afterwards.

**Comment by msarahan** [comment]
Thanks for your patience.  Merging.

**Pull request merged**
