### PR TITLE
WIP: Hack local subdir cache

### PR DESCRIPTION
**Pull request by msarahan**
Although #4178 added good support for setting subdir, when it comes time to extract and link packages, there's still work to do.  This PR is almost certainly not the right way to do it.  I hope it's a useful experiment, though, and can contribute towards discussion about what the right way is.

Current issue is that although the download and extraction seem to succeed, they're not going to the right place, and I'm seeing errors like:

```
Traceback (most recent call last):
      File "/home/dev/code/conda/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/dev/code/conda/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/dev/code/conda/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/dev/code/conda/conda/cli/install.py", line 308, in install
        update_deps=context.update_dependencies)
      File "/home/dev/code/conda/conda/plan.py", line 526, in install_actions
        force=force, always_copy=always_copy)
      File "/home/dev/code/conda/conda/plan.py", line 360, in ensure_linked_actions
        elif try_hard_link(fetched_dir, prefix, dist):
      File "/home/dev/code/conda/conda/install.py", line 574, in try_hard_link
        assert isfile(src), src
    AssertionError: /tmp/pytest-of-msarahan/pytest-103/test_cross_compiler0/linux-imx351uc/_cross_libgreeting-1.0-h3473_0/info/index.json
```

CC @mingwandroid

### CODE REVIEW

**Comment by kalefranz** [comment]
AssertionError is always a bug. It's a guard against assumptions you're aware you're making, pointing more to a likely bug higher up in the call stack. I'll investigate.

**Comment by msarahan** [comment]
Sorry if I wasn't clear.  The error I posted here is the error _after_ this PR is applied.  Without this PR, the error you see is 

```
Traceback (most recent call last):
      File "/home/dev/code/conda/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/dev/code/conda/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/dev/code/conda/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/dev/code/conda/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/dev/code/conda/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/dev/code/conda/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/dev/code/conda/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/home/dev/code/conda/conda/install.py", line 800, in extract
        rec = package_cache()[dist]
    KeyError: u'file:///tmp/pytest-of-msarahan/pytest-88/test_cross_compiler0::_cross_libgreeting-1.0-h3473_0'
```

Which makes sense to me, because packages for some arbitrary other subdir should not be ending up in the pkgs folder.  That's a recipe for disaster.  I think transitioning away from a single pkgs folder to one that respects subdir is necessary.

**Comment by kalefranz** [comment]
@msarahan I think I'm working through most of all issues in #4199.  Can we close this PR?

**Comment by msarahan** [comment]
Sure, happy to.

**Pull request closed without merging**
