### PR TITLE
set errorlevel when 'conda run' exits (Resolves #9599)

### LINKED ISSUE #9599: conda run is not preserving exit code
## Current Behavior
`conda run` used to return the correct exit status of the target process, but it doesn't anymore. This was apparently working correctly in conda 4.8.0 but it seems broken since version 4.8.1. `conda run` now erroneously always return the exit status of 0. This is a serious problem as jobs fail silently now.

### Steps to Reproduce
```
$ conda -V
conda 4.8.1
$ conda run -n myenv /usr/bin/true; echo $?
0
$ conda run -n myenv /usr/bin/false; echo $?
ERROR conda.cli.main_run:execute(30): Subprocess for 'conda run ['/usr/bin/false']' command failed.  (See above for error)
0
```

## Expected Behavior
`conda run` should preserve the exit status of the target process, whether the target is `python` or otherwise. It worked correctly with the previous version:
```
$ conda -V
conda 4.8.0
$ conda run -n base /usr/bin/true; echo $?
0
$ conda run -n base /usr/bin/false; echo $?
ERROR conda.cli.main_run:execute(39): Subprocess for 'conda run ['/usr/bin/false']' command failed.  Stderr was:

1
```

## Environment Information
This issue really is independent of the environment as it happens both in various dockerfiles and on MacOS too.

---

@msarahan Please fix this bug considering I see a commit from 25 days that may have introduced it! Adding unit tests would also be wise.

### PR DESCRIPTION
**Pull request by mlline00**
Addresses #9599 by handling the namedtuple returned from conda.gateways.subprocess.subprocess_call.

Also, introduces three new "conda run" unit tests:
- returns an int
- properly returns zero exit codes
- properly returns non-zero exit codes

These three tests fail with conda 4.8.2 and pass with this PR

### CODE REVIEW

**Comment by mlline00** [comment]
Appreciate any tips on how to work through the py37 unit test errors: PermissionError: [Errno 13] Permission denied: '/opt/conda/.tmppn3p2hs2'

The py37 run successfully on my win32 and linux machines (Yes, I just said "It works on my machine")

**Comment by msarahan** [comment]
@cla-bot check

**Comment by mlline00** [comment]
@msarahan Integration tests are complaining a package is not available on the c3i_test2 channel? Anything I can do here?

conda.exceptions.ResolvePackageNotFound: 
  - activate_deactivate_package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/conda/tests/test_activate.py", line 2534, in test_activate_deactivate_modify_path_bash
    self.activate_deactivate_modify_path("bash")
  File "/home/circleci/conda/tests/test_activate.py", line 2522, in activate_deactivate_modify_path
    run_command(Commands.INSTALL, self.prefix2, activate_deactivate_package, "-c", "c3i_test2")
  File "/home/circleci/conda/tests/test_create.py", line 281, in run_command
    result = do_call(args, p)
  File "/home/circleci/conda/conda/cli/conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/circleci/conda/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/circleci/conda/conda/cli/install.py", line 286, in install
    raise PackagesNotFoundError(e._formatted_chains, channels_urls)
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - activate_deactivate_package

Current channels:

  - https://conda.anaconda.org/c3i_test2/linux-64
  - https://conda.anaconda.org/c3i_test2/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by analog-cbarber** [comment]
What is the status of this? Is there actually a problem with the fix or does this just need someone to sign off?

**Comment by mingwandroid** [comment]
We need to review it. Thank you for your contribution. Pinging @kalefranz

**Comment by aachkar-miovision** [comment]
This should also fix https://github.com/conda/conda/issues/8385

**Comment by esc** [comment]
@kalefranz @mingwandroid what can we do to move this forward? Perhaps a first step would be to merge or rebase to get the changes from current master and then to re-run CI? It does not appear as though any of the CI failures are related to this PR.

**Comment by mlline00** [comment]
Rebased PR on master. CI is passing.

**Comment by analog-cbarber** [comment]
Is this going to make it into the next release?

**Comment by analog-cbarber** [comment]
Still hasn't been merged. Can this get into the next release? I am tired of working around this.

**Comment by dietercastel** [comment]
I was wondering what is currently holding back the review? From the looks of it this could solve both #2904 and #9599 that were closed without a fix due to different priorities (understandable). The PR includes tests (both python2 & 3) an seems auto-mergable.

Thanks for the effort @mlline00. I'm rooting for a review! :-)

And thanks conda team & contributors for all your sustained efforts.

**Comment by analog-cbarber** [comment]
Note that the same issue has been fixed in mamba 0.4.2 so you could use that as a workaround. Or you can just use a little script like this:

```python
import sys

try:
    from conda.base.context import context
    from conda.cli.main import generate_parser
    from conda.cli.main_run import execute as run
except ImportError:
    sys.exit('conda not found in {}. Script must be run in base environment.'.format(sys.prefix))

args = ['run'] + sys.argv[1:]
sys.argv[0] = 'conda' # so that -h will show conda
parser = generate_parser()
parsed = parser.parse_args(args)
context.__init__(argparse_args=parsed)
result = run(parsed, parser)
sys.exit(result.rc)
```

**Comment by dietercastel** [comment]
Thanks @chenghlee! :-)

**Pull request merged**
