### PR TITLE
Add powershell activate/deactivate

### PR DESCRIPTION
**Pull request by vmuriart**
Based on @liquidmantis [work](https://github.com/Liquidmantis/PSCondaEnvs)
For issue #626.

### CODE REVIEW

**Comment by vmuriart** [comment]
@msarahan here's the pr for adding the powershell scripts.

**Comment by msarahan** [comment]
Thanks @vmuriart I'll get this is as soon as I can.  I will submit PRs to your branch with my additions to run the tests.  Please keep an eye out.

**Comment by vmuriart** [comment]
@msarahan gave you push access to the repo just in case I miss the `pr` for the fixes.

**Comment by msarahan** [comment]
Thanks, but that's not really necessary. I can pull in your commits on a new branch and open a separate PR if need be, but I'd really rather have you look over my changes.  More eyes => better code.

Just so you know, I need to finish https://github.com/conda/conda/pull/2365 before I can work on this.

**Comment by vmuriart** [comment]
Makes sense. No rush, just wanted to make sure I wasnt holding up :)

**Comment by msarahan** [comment]
Update here: I have taken a look.  The scripts work OK, but do not pass our test suite for a number of reasons.  The PS scripts here are written the way that the old batch scripts were: they have all of the activation logic in the script, none in Conda.  The new scripts change that, so that Conda does things like figuring out where to look for environments.

I am adapting the PS scripts as I have time.

@kalefranz if you'd like, you could probably merge this as-is as a beta-feature.  Otherwise, this might take me another week or two to finish, and I don't want to hold up the 4.1 release.  The fish shell stuff is in the same vein - it does not follow our standard scheme for activate/deactivate, and is not documented.

**Comment by kalefranz** [comment]
Ok @msarahan let's just wait on it then.  Are you going to make a new PR based off of this one I guess?

**Comment by msarahan** [comment]
I'll still plan on submitting a PR against this one. If @vmuriart is unavailable at that time for comment/review, I'll open a separate conda PR.

**Comment by msarahan** [comment]
Current work is here: https://github.com/msarahan/conda/tree/add_powershell

I have gotten pulled away from this, but I hope to get back soon.  If anyone wants to take what I have and run with it, feel free.

**Comment by willyd** [comment]
Has anyone considered using something like: http://evandontje.com/2013/06/06/emulate-the-visual-studio-command-prompt-in-powershell/ ?

Which in this case boils down to:

- Calling the activate batch file
- Writing the environment to stdout with the `& set` command
- Parsing the output from PS and setting the variables using `$env`

This may be a little hackish but you only have to maintain one file avoiding inconsistencies between cmd and PS.

**Comment by msarahan** [comment]
@willyd these are good ideas.  I do stuff like this in conda-build: https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L388-L432

That would probably simplify things here.  When I revisit this, I'll keep this in mind.

**Comment by kalefranz** [comment]
superseded #3175, #3960

**Pull request closed without merging**
