### PR TITLE
fix #5385 add prioritize_channels to conda.exports

### LINKED ISSUE #5385: add prioritize_channels to conda.exports

### PR DESCRIPTION
**Pull request by kalefranz**
fix #5385 

CC @jjhelmus

### CODE REVIEW

**Comment by kalefranz** [comment]
As discussed in standup this morning. The rational is providing an indirection layer so that refactoring in conda doesn't have to break software that depends on conda. The comments added to the code already show where it's being used.

**Comment by stefanseefeld** [comment]
I see. So `constructor` needs this. To be honest I don't think this is a good enough rationale, at least not in the context of our desire to capture all possible use-cases of a future conda API. What does `constructor` need this for ? Is this captured in our list of user stories ? If not, can we add it so we can design this into the next API ?

**Comment by jjhelmus** [comment]
@stefanseefeld I agree that `constructors` needs may not be sufficient to drive this change.  Working out an API for conda, especially one that can be called from any environment is a better solution.  The main functions that `constructor` needs conda for are:

* Fetching channel indexes given a list of channels which may or may not include priories.
* Resolving specs.
* Fetching (Downloading) packages into a particular location.

I think these should be included in the conda API. If they are not already included in the user stories I would be happy help get them included.

**Comment by kalefranz** [comment]
@jjhelmus I think you're just re-implementing that piece of code in constructor, right?  Should I just close this PR?

**Pull request closed without merging**
