### PR TITLE
Allow user-level specification of default channels

### PR DESCRIPTION
**Pull request by tswicegood**
The only way to override the default channels currently is through a system-level RC file.  This adds an additional check that lets the user provide a `default_channels` array.

### CODE REVIEW

**Comment by tswicegood** [comment]
This is an alternate to #1135.  I see no reason why this shouldn't be user configurable by someone who wants to dive into the guts of conda.

**Comment by ilanschnell** [comment]
One can already specify the channels using the `channels` key in the `~/.condarc` file,  So you can say:
```
channels:
  - conda
  - defaults
```
Or am I missing something?

**Comment by tswicegood** [comment]
That thought occurred to me after I opened this.  Let me think on it for a bit and I'll close it unless I come up with a case that needs full control of defaults as `defaults`.

**Comment by asmeurer** [comment]
Right, it was intentionally done that `defaults` has to be added to the channels key in the condarc (if the channels key is present) so that it can be disabled if desired. conda config adds the defaults key by default because that's what most users will want. 

I don't see the need for this pull request. If you want to override the defaults, you should just add different channels to the rc. And if you are provisioning condarc files it's the same.

**Pull request closed without merging**
