### PR TITLE
Update versioneer

### PR DESCRIPTION
**Pull request by groutr**
This updates versioneer from a very old release (over 4 years old) to the latest release.

### CODE REVIEW

**Comment by kalefranz** [comment]
I've spent some time on this topic, and `versioneer` seems like an *awful* lot of code for what it does.  I know the package is incredibly popular at Continuum though.  Can someone explain to me some of the reasons this is a best-in-breed solution?

**Comment by msarahan** [comment]
I don't know.  Seems like there are a few alternatives: setuptools-scm,
https://pypi.python.org/pypi/setuptools-git-version/1.0.3, and more.  I
think the nice thing about versioneer compared to those is that versioneer
isn't needed as a dependency after its initial installation.

Think of it as "vendoring" of a sort (and argue against perhaps with that
logic).

**Comment by kalefranz** [comment]
It is exactly vendoring. And we vendor both versioneer and progressbar now without actually calling it that.  If the tests passed, I'd agree to accept this PR now.  But I'd rather just rip out versioneer altogether. At some point I'll submit a PR to do that for everyone's feedback.

**Comment by ilanschnell** [comment]
I don't see any reason to update versioneer, as long as it works.  Are there any problems with it?

**Comment by kalefranz** [comment]
Going to decline this PR for now.  The auxlib route covers the intent, but depending on how things go, not opposed to going back to versioneer if auxlib continues to create problems.

**Pull request closed without merging**
