### PR TITLE
Allow to use pip requirements.txt syntax in environment files

### LINKED ISSUE #3763: Adding pip flags in environment.yml
I have a dependency on a privately hosted PyPI server. I can pip install it by specifying the address with `--extra-index` when I do a pip install.

However, if I add pip flags under `pip:` in an environment.yml file, I get an error:

```
14:53 $ conda env update
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --index-url http://HOST:8080/  --trusted-host HOST package


CondaValueError: Value error: pip returned an error.
```

Is there a good reason this has to fail? Can the parser just pass the pip flags along?

### LINKED ISSUE #4378: Invalid requirement while trying to use pip options
Hi!

I have in my pip section inside envrionment.yaml file this line
```- rep --install-option='--no-deps'```

while I am trying to update my environment I am getting this error

```Invalid requirement: 'rep --install-option='--no-deps''```

if I do pip -r requirements.txt and I have that line as it is in requirements.txt it works.

### PR DESCRIPTION
**Pull request by sdvillal**
resolves #3763
resolves #4378

Currently the declaration of pip dependencies in conda ```environment.yml``` files is limited to a list of strings that would be accepted in a pip command line. This disallows using pip requirement files or installing pip dependencies in editable mode (unless using lesser known syntax tricks like ```"--editable=my_project"```). Both are use cases I have missed recently and have also been requested elsewhere (e.g. #3763 #4378). This PR enables the full [pip requirement file syntax and features](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) to be used in ```environment.yml``` files. For example:

```yaml
name: advanced-pip-example

dependencies:
  - pip
  - pip:

    # Global options can be tweaked.
    # For example, if you want to use a pypi mirror first:
    - --index-url https://pypi.doubanio.com/simple
    - --extra-index-url https://pypi.python.org/simple
    # (check https://www.pypi-mirrors.org/)

    # Current syntax still works
    - xmltodict==0.10.2

    # Install in editable mode.
    # More natural than - "--editable=git+https://github.com/neithere/argh.git#egg=argh"
    - -e git+https://github.com/neithere/argh.git#egg=argh

    # You could also specify a package in a directory.
    # The directory can be relative to this environment file.
    - -e ./module_to_install_in_editable_mode

    # Use another requirements file.
    # Note that here also we can use relative paths.
    # pip will be run from the environment file directory, if provided.
    - -r another-project-requirements.txt

    # Anything else that pip requirement files allows should work seamlessly...
```

As far as I can tell, these simple changes should not break any existing environment specification.

Also this PR fixes conda not listing pip egg-link dependencies (for example, dependencies installed in editable mode), and adds some integration tests to make sure pip packages are installed correctly (these tests depend on pypi to be up).

If merged, something like this could go to the changelog:
```markdown
### Improvements
* accept all valid pip syntax in environment files (#3969)

### Bug Fixes
* Follow egg links when listing pip packages. Fixes, for
  example, `conda list` on the presence of packages
  installed on editable mode. (#3969)
```

### CODE REVIEW

**Comment by sdvillal** [comment]
I think these failing tests have nothing to do with the changes in this PR.

**Comment by sdvillal** [comment]
I have polished the PR a bit: better description, fixed paths on windows tests, squashed to one commit and changed the target branch to upstream 4.3.x. 

The tests still fail for reasons that have nothing to do with this commit (I think because of recent changes to the packages in anaconda.org). I will trigger again test execution when these problems get fixed.

**Comment by tdhopper** [comment]
@sdvillal Looks like #4145 is merged. I'm eager to get this feature!

**Comment by sdvillal** [comment]
@tdhopper We also need #4169 merged to get the green tick. Will keep an eye and trigger when it gets merged. Even then the PR might not get reviewed anytime soon. I think the admins face a pile of work.

What could be useful is to actually check that _--extra-index_ also works when directly used in the environment yaml (I do not see why it would not). Do you have an example of a public url I could try, so I can add it to the PR description after making sure it does work?

**Comment by tdhopper** [comment]
@sdvillal: I put an index up at http://pythonextraindextest.com.s3-website-us-east-1.amazonaws.com with a package called `exception` that I maintain. Can you try that?

**Comment by sdvillal** [comment]
Thanks @tdhopper, that was useful. I have now updated the PR description and added integration tests to the pull request after confirming that everything seems to work as expected. On the way I have fixed conda not listing pip packages installed on editable mode. Hopefully this makes everything better and easier to review. And hopefully we finally earn that green tick.

In the example and the tests (which are just running that example) I'm using a official pip mirror to show how to change pip index priorities. You can delete your test index if you want to.

**Comment by sdvillal** [comment]
Green tick, ready to merge.

If merged, something like this could go to the changelog:
```markdown
### Improvements
* accept all valid pip syntax in environment files (#3969)

### Bug Fixes
* Follow egg links when listing pip packages. Fixes, for
  example, `conda list` on the presence of packages
  installed on editable mode. (#3969)
```

**Comment by sdvillal** [comment]
Thanks Kale, looking forward to the new release.

**Pull request merged**
