### PR TITLE
Handle NoneType value in split_platform

### PR DESCRIPTION
**Pull request by HugoTian**
Fix issue  #3235

### CODE REVIEW

**Comment by mwiebe** [comment]
Is the test suite in good enough shape that adding a regression test would be easy too?

**Comment by HugoTian** [comment]
@mwiebe , we will add more and more test case in future, and thanks for your advice.

Moreover, do you think we can close your issue #3235 ?

Thanks

**Comment by mwiebe** [comment]
It looks like this will take care of the issue, yeah. Thanks for the fix!

**Comment by kalefranz** [comment]
sucked into and superseded by #3252

**Pull request closed without merging**
