### PR TITLE
fix long shebangs when creating entry points

### PR DESCRIPTION
**Pull request by msarahan**
Installing noarch packages into paths longer than the shebang limit has been broken.  This hopefully fixes it.  It at least fixes it for conda-build, which recently switched the test path to being the full 255-character prefix length.

### CODE REVIEW

**Comment by kalefranz** [comment]
Good catch.  Thanks Mike.

**Comment by kalefranz** [comment]
I'll clean up any failures and get this merged.

**Comment by msarahan** [comment]
Thanks.  Should be mostly good now - just had a unicode issue with the regex.  I think I fixed it with my latest push.

**Comment by msarahan** [comment]
Looks all good on Travis.  Should be good to go.

**Pull request merged**
