### PR TITLE
Dist simplification

### PR DESCRIPTION
**Pull request by mcg1969**
@kalefranz it looks like we're both experimenting with roughly the same thing. But hey, I've already tried doing this 2-3 times already, so why not.

This is not a _removal_ of Dist, just a simplification to channel/distname/w_f_d. To accomplish the simplest such change, I introduce properties to replace most of the missing fields, except `platform` and `base_url`.

### CODE REVIEW

**Comment by mcg1969** [comment]
Next step, obviously, would be to remove the need for those properties. That is, alas, the harder task, which I suspect you're already discovering.

**Comment by kalefranz** [comment]
I'm actually making decent progress. Dist is hooked in pretty deep. This is wayy easier though than initially getting all those dist strings into objects.

**Comment by mcg1969** [comment]
The only thing is: according to my Snakeviz analysis, Dist is simply not the main performance issue, it's IndexRecord generation.

**Comment by mcg1969** [comment]
I saw your comment on the other thread about concerns over changing Dist in 4.3. One of the reasons I broke my performance experiment into three pieces is that we could easily pick only a portion of them. If we don't merge this in 4.3, I don't think we lose much in terms of performance.

**Comment by kalefranz** [comment]
> I saw your comment on the other thread about concerns over changing Dist in 4.3. 

Hey, well, tests pass.  I'm 👍

**Comment by kalefranz** [comment]
Merged into #4474, which at this point won't be 4.3.x.  But I want to keep pushing forward on that PR for a little bit longer and see where we end up.  The direction I'm headed there is to only be making occasional use of the `Dist.parse_dist_name()` static method to maintain old interfaces where we have to.  There's still a lot of work to do though.

**Comment by mcg1969** [comment]
To help compare I've rebased this against #4478, so we can see the difference in footprint. This is a much smaller change. I'm still not convinced either of this or #4474 needs to happen yet. And even if we do, they should go in separate canaries.

**Comment by mcg1969** [comment]
@kalefranz out of curiosity I rebased this to see what it would achieve. This currently fails a conda list test, but no others---and it seems to offer a lot of savings (like 25%, maybe). Python 2.7 finishes in under 20 minutes. 

Might be worth fixing `conda list --json` to make this work. I know why it's happening---because `conda list --json` just dumps the json representation of Dist, which now has a lot fewer fields. Dump a subset of the corresponding IndexRecord instead and you're golden.

**Comment by kalefranz** [comment]
Closing, as conda API work will probably cover this.

**Pull request closed without merging**
