### PR TITLE
CONDA_EXE and CONDA_BAT quoting changed so that they are quoted on use

### PR DESCRIPTION
**Pull request by murrayreadccdc**
CONDA_EXE and CONDA_BAT quoting changed so that they are quoted on use rather than on set.

Tested by installing miniconda 4.5 in a directory with spaces on windows, then updating conda to 4.6. At this point the problems show themselves. You can't run conda anything.
Replace the contents of condabin with these modified files and conda works again.

This problem was initially reported by me at https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/jHyb8uvIOnc

### CODE REVIEW

**Comment by msarahan** [comment]
Excellent!  Thank you!  Can you sign the CLA?  You should be able to see it by clicking the "details" link in the status.  It's a manual process, so once you sign it, I'll do the manual work to get you added.

**Comment by murrayreadccdc** [comment]
The CLA is now signed

**Comment by msarahan** [comment]
Confirmed.  I've done the manual bits to add you to the signers list.  You should be good from now on.  Thank you!

**Comment by msarahan** [comment]
I'm investigating the win CI failures to make sure that they aren't real problems.  I'll plan on pushing commits to your branch if I need to fix anything.

**Comment by msarahan** [comment]
I believe the tests are failing because the extra quoting fixes paths, but breaks the test suite's usage of ``python -m conda`` to run conda.  We need a helper script that calls that and can be a fixed path.

https://github.com/conda/conda/blob/master/tests/test_activate.py#L1150

**Comment by nehaljwani** [comment]
@msarahan I ran all tests with this, which seems to work:
https://github.com/conda/conda/blob/a0b0ea32f30a4691d7603d16402dfd834066910f/tests/test_activate.py#L1150

xref: https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda/builds/22152308/job/gbm6eadr0eay19vy

**Comment by msarahan** [comment]
@nehaljwani that's great!  Please push a commit to this PR to make that change.

**Comment by nehaljwani** [comment]
Timeout, yet again 😭

**Comment by msarahan** [comment]
Relevant tests looked fine. Merging.

**Pull request merged**
