### PR TITLE
Move coverage from setup.cfg to ease debugging

### PR DESCRIPTION
**Pull request by dholth**
### Description

I always run tests in the debugger, in vscode, but `--cov` prevents the debugger from working.

Instead, enable coverage in individual test runner scripts, for CI.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by jezdez** [comment]
We'll need a way to collect coverage data and report about it for people that aren't using VS Code, will this collect and print out coverage reports locally when following the contribution policy?

**Comment by dholth** [comment]
We would have to ask people to say `--cov` or make sure it is in a test script that we also ask them to run.

**Review by jezdez — CHANGES_REQUESTED** [review]
This would require updating to mention the need to specify --cov: https://github.com/conda/conda/blob/main/docs/source/dev-guide/development-environment.md

**Comment by jezdez** [comment]
Oh BTW, I think it would be cool to learn how you're using the VS Code debugger BTW.

**Pull request merged**
