### PR TITLE
Conditional dependencies and package superseding

### PR DESCRIPTION
**Pull request by mcg1969**
Note: this depends on #4118 

This PR builds on conditional specifications to support the concept of one package superseding another.

To unpack this, consider this addition to the test `index.json` file, pasted below. In this scenario,  `conda-env` depends on `conda`. But `conda 2.0` has subsumed the `conda-env` functionality. So we create an _empty_ package `conda-env 2.0` that depends on `conda >=2.0`; and we make `conda-env 2.0` an _optional_ dependency of `conda 2.0`.

So this means that `conda-env` does not _have_ to be installed alongside `conda 2.0`. If `conda-env` is already installed or explicitly requested, it will be upgraded to `conda-env 2.0`.

Now, this is where the `superseded` flag comes in. If `conda` sees that, then `conda-env 2.0` will _not_ be installed if requested by install or upgrade. Instead, conda will indicate that it is being replaced by functionality in conda, like so:
```
The following packages will be UPDATED:

    conda:     1.5.2-py27_0 --> 2.0-py27_0

The following packages will be REPLACED:

    conda-env: 1.0-py27_0   --> conda >=2.0
```
The construction on the right-hand side of the REPLACED instruction is taken directly from the `depends` field of `conda-env`.

```
  "conda-2.0-py27_0.tar.bz2": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "python 2.7*",
      "pyyaml 3.10",
      "conda-env 2.0 (optional)"
    ],
    "name": "conda",
    "requires": [
      "python 2.7",
      "pyyaml 3.10"
    ],
    "version": "2.0"
  },
  "conda-env-1.0-py27_0.tar.bz2": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "conda"
    ],
    "name": "conda-env",
    "requires": [
      "conda"
    ],
    "version": "1.0"
  },
  "conda-env-2.0-py27_0.tar.bz2": {
    "build": "py27_0",
    "build_number": 0,
    "depends": [
      "conda >=2.0"
    ],
    "superseded": true,
    "name": "conda-env",
    "requires": [
      "conda"
    ],
    "version": "2.0"
  },
```

### CODE REVIEW

**Comment by kalefranz** [comment]
@mcg1969, for reference, we should be aware of the following sections of two PEPs.  I just randomly stumbled onto these via reading source code for the `pkginfo` package.  I wasn't aware of them before, and it's another good reference.

## From [PEP-314](https://www.python.org/dev/peps/pep-0314/)

    Provides (multiple use)

      Each entry contains a string describing a package or module that
      will be provided by this package once it is installed.  These
      strings should match the ones used in Requirements fields.  A
      version declaration may be supplied (without a comparison
      operator); the package's version number will be implied if none
      is specified.

      Example: 

          Provides: xml
          Provides: xml.utils
          Provides: xml.utils.iso8601
          Provides: xml.dom
          Provides: xmltools (1.3)

    Obsoletes (multiple use)

      Each entry contains a string describing a package or module
      that this package renders obsolete, meaning that the two packages
      should not be installed at the same time.  Version declarations
      can be supplied.  

      The most common use of this field will be in case a package name
      changes, e.g. Gorgon 2.3 gets subsumed into Torqued Python 1.0.
      When you install Torqued Python, the Gorgon package should be
      removed.
      
      Example:

          Obsoletes: Gorgon

## From [PEP-345](https://www.python.org/dev/peps/pep-0345/#requires-dist-multiple-use)

### Requires-Dist (multiple use)

Each entry contains a string naming some other distutils project required by this distribution.

The format of a requirement string is identical to that of a distutils project name (e.g., as found in the Name: field. optionally followed by a version declaration within parentheses.

The distutils project names should correspond to names as found on the Python Package Index [4] .

Version declarations must follow the rules described in Version Specifiers

Examples:

    Requires-Dist: pkginfo
    Requires-Dist: PasteDeploy
    Requires-Dist: zope.interface (>3.5.0)


### Provides-Dist (multiple use)

Each entry contains a string naming a Distutils project which is contained within this distribution. This field must include the project identified in the Name field, followed by the version : Name (Version).

A distribution may provide additional names, e.g. to indicate that multiple projects have been bundled together. For instance, source distributions of the ZODB project have historically included the transaction project, which is now available as a separate distribution. Installing such a source distribution satisfies requirements for both ZODB and transaction .

A distribution may also provide a "virtual" project name, which does not correspond to any separately-distributed project: such a name might be used to indicate an abstract capability which could be supplied by one of multiple projects. E.g., multiple projects might supply RDBMS bindings for use by a given ORM: each project might declare that it provides ORM-bindings , allowing other projects to depend only on having at most one of them installed.

A version declaration may be supplied and must follow the rules described in Version Specifiers . The distribution's version number will be implied if none is specified.

Examples:

    Provides-Dist: OtherProject
    Provides-Dist: AnotherProject (3.4)
    Provides-Dist: virtual_package


### Obsoletes-Dist (multiple use)
Each entry contains a string describing a distutils project's distribution which this distribution renders obsolete, meaning that the two projects should not be installed at the same time.

Version declarations can be supplied. Version numbers must be in the format specified in Version Specifiers .

The most common use of this field will be in case a project name changes, e.g. Gorgon 2.3 gets subsumed into Torqued Python 1.0. When you install Torqued Python, the Gorgon distribution should be removed.

Examples:

Obsoletes-Dist: Gorgon
Obsoletes-Dist: OtherProject (<3.0)


### Requires-Python
This field specifies the Python version(s) that the distribution is guaranteed to be compatible with.

Version numbers must be in the format specified in Version Specifiers .

Examples:

    Requires-Python: 2.5
    Requires-Python: >2.1
    Requires-Python: >=2.3.4
    Requires-Python: >=2.5,<2.7


### Requires-External (multiple use)

Each entry contains a string describing some dependency in the system that the distribution is to be used. This field is intended to serve as a hint to downstream project maintainers, and has no semantics which are meaningful to the distutils distribution.

The format of a requirement string is a name of an external dependency, optionally followed by a version declaration within parentheses.

Because they refer to non-Python software releases, version numbers for this field are not required to conform to the format specified in PEP 440 : they should correspond to the version scheme used by the external dependency.

Notice that there's is no particular rule on the strings to be used.

Examples:

    Requires-External: C
    Requires-External: libpng (>=1.5)

**Comment by mcg1969** [comment]
I'm sure we can tackle most of these...

**Comment by kalefranz** [comment]
I'm not sure how I feel about the `superseded` flag just yet.  We can get back to that though...

In an ideal world, I'd like the interface to support these new features to simply be two new markers for each element in the `depends` list.  If the element is prepended with `?`, it is an optional dependency.  For example

```
depends:
  - python 2.7*
  - pyyaml 3.10
  - ?conda-env 2.0
```

If the element is prepended with `!`, it is excluded/obsoleted.

```
depends:
  - python 2.7*
  - pyyaml 3.10
  - !conda-env
```

I think that basically covers all use cases.

Unfortunately, if we start putting these extra markers in repodata, I think we'll blow up all previous versions of conda that aren't aware of them.  So we probably need two additional run-time requirement fields, probably most appropriately named `optional` and `excludes`.

**Comment by megies** [comment]
Having a ways to specify optional dependencies would also be great for [obspy](https://github.com/conda-forge/obspy-feedstock). I like how this is handled by apt/deb packaging, [where there exist `Recommends` et al.](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps) for this job.

I could live with both approaches mentioned by @kalefranz, but (without being too much aware of practical implications for conda packaging) I would lean towards having a new section for optional dependencies (rather than adding magic modifiers).

**Comment by jakirkham** [comment]
> Note: this depends on https://github.com/conda/conda/pull/4118

Is this note still accurate? Seems that PR was closed.

**Comment by kalefranz** [comment]
Closing this PR for now.  The first two commits have been brought into #4982.  We'll circle back to the third commit in a future feature release.

**Pull request closed without merging**
