### PR TITLE
Add environment variables to environment.yml files

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
This PR enables creation and export of conda environments that have environment variable created with [`conda env config vars`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=variables#setting-environment-variables).

Tests have been included for this behavior.

Here' an example

## Create and export

First create a new env and set two variables and confirm

```
> conda create -y -n env_with_vars python=3.7
> conda env config vars set DUDE=woah SWEET=yaaa -n env_with_vars
> conda run -n env_with_vars env | grep -E "DUDE|SWEET"
DUDE=woah
SWEET=yaaa
```

When the env is exported the variables are retained in a key called `variables:`

```
> conda env export -n env_with_vars --from-history
name: env_with_vars
channels:
  - defaults
dependencies:
  - python=3.7
variables:
  DUDE: woah
  SWEET: yaaa
prefix: /Users/adefusco/Development/Conda/conda/devenv/envs/env_with_vars
```

And also with the full dependency spec

```
> name: env_with_vars
channels:
  - defaults
dependencies:
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1g=h1de35cc_0
  - pip=20.2.2=py37_0
  - python=3.7.7=hf48f09d_4
  - readline=8.0=h1de35cc_0
  - setuptools=49.6.0=py37_0
  - sqlite=3.32.3=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
variables:
  DUDE: woah
  SWEET: yaaa
prefix: /Users/adefusco/Development/Conda/conda/devenv/envs/env_with_vars
```

## Create from yaml

The environment.yml spec will allow variables to be set when the env is created.

```yaml
# environment.yml
name: new_env
dependencies:
  - python=3.8
variables:
  DUDE: woah
  SWEET: yaaa
```

Confirm that the variables have been set.

```
> conda env create -f environment.yml
> conda run -n new_env env | grep -E "DUDE|SWEET"
DUDE=woah
SWEET=yaaa
```

### CODE REVIEW

**Comment by chenghlee** [comment]
Closing & re-opening this PR to trigger new CI checks.

**Review by chenghlee — APPROVED** [review]
LGTM

**Comment by Florents-Tselai** [comment]
What happens when you don't want to store certain ENV_VARS in Git or want to separate between dev and production. Is there any recipe for an "if not already defined use this" implementation? 

In prod for example these can be injected via `systemd`, but in dev, they should be there

**Comment by AlbertDeFusco** [comment]
This is a very good point and perhaps anaconda-project can help. I'd like to continue to this discussion.

https://anaconda-project.readthedocs.io/en/latest/user-guide/tasks/work-with-variables.html

This recent PR defines env var priority ordering in anaconda-project and will be part of the next release

https://github.com/Anaconda-Platform/anaconda-project/pull/286

**Pull request merged**
