### PR TITLE
Add support for client TLS certificates 

### PR DESCRIPTION
**Pull request by kalefranz**
@bluekeyes any objection to what I've done here? Splitting the map into two root-level keys?

### CODE REVIEW

**Comment by kalefranz** [comment]
If merged, supersedes #3393.

**Comment by kalefranz** [comment]
@bluekeyes I'm guessing completing that clahub form isn't going to be so easy for you?

**Comment by bluekeyes** [comment]
:+1:, this looks good to me. Sorry about the CLA delay, I've been waiting for my employer's legal team to review before I sign; I'll follow up with them today.

**Comment by kalefranz** [comment]
Please *do* keep trying to get that CLA clearance.  I understand your position, and I've basically already completely rewrote your contribution.  But when I merge you *will* be on the conda contributor list, and it'll make my life easier if you can get that approved :)

**Comment by kalefranz** [comment]
Since this is just an extra config option, I'm merging it for conda 4.2.6, which is going into the defaults channel tomorrow.

**Comment by bluekeyes** [comment]
Great, thank you - I just signed the the CLA, so let me know if you need anything else there.

**Pull request merged**
