### PR TITLE
Make sure conda does not use polyglot shebangs

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Minimum work to fix https://github.com/conda/conda/issues/11885 and close https://github.com/conda/conda/issues/11893.

More robust solution long-term available at https://github.com/conda/conda/pull/11995.

Basically we prevent `conda` from using the polyglot shebang approach with two checks:

* If conda-build is being used and the executable is inside `$PREFIX`, we are most probably packaging `conda`. Do nothing and let prefix replacement handle that at install time (`replace_long_shebang()` right above our function)
* If somebody uses `conda init --install` outside conda-build (there's no reason to, but :shrug:), we ensure they end up with a `#!/usr/bin/env python` shebang by calling the function with a new flag.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [X] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
Ready for review but I want to check the canaries that come out of this PR once #12047 is addressed.

**Review by jezdez — APPROVED** [review]

**Review by beeankha — APPROVED** [review]

**Review by jezdez — APPROVED** [review]

**Comment by jaimergp** [comment]
I asked about the canaries because I wanted to review how the entry points were being rendered 😬

**Comment by kenodegard** [comment]
conda-build 3.23.0 is on defaults now, we'll get the canary builds on the main branch shortly

**Comment by jaimergp** [comment]
Awesome, the test changes in the recipe should reveal the shebangs properly. So we just need to check the logs.

**Pull request merged**
