### PR TITLE
Support other scripts in profile.d

### PR DESCRIPTION
**Pull request by isuruf**
One candidate here is mamba which would allow reactivating
mamba installations.

### CODE REVIEW

**Comment by wolfv** [comment]
This would be very helpful

**Comment by jezdez** [comment]
Hey @isuruf, thanks for the pull request!

This seems like an unwanted opening of the activation functionality to me and like a bit of an anti-pattern for security and maintenance reasons. Glob'ing for files with a wildcard and running them during init would make it harder to debug environments because of users dropping files in the `etc/profile.d`, whether they want it or not.

You didn't really elaborate on the use case in this pull request so far, but in the referenced https://github.com/mamba-org/mamba/issues/1035 it's mentioned that this isn't a Conda issue and would be best solved in Mamba by implementing `mamba shell init` to keep the wrapping nature of mamba. I'm a bit worried about adding features to Conda to work around issues in Mamba's implementation, generally speaking.

But I may be missing something obvious though, so please elaborate and extend the code with tests so I understand the reasoning for the patch better. 

BTW, if this is a new feature request that is only partially related to the Mamba issue mentioned, I'd be interested in co-writing a short CEP for this if you're interested, so we can figure out if that's a good format for those things. All optional of course, this is pretty new after all.

**Comment by isuruf** [comment]
> This seems like an unwanted opening of the activation functionality to me and like a bit of an anti-pattern for security and maintenance reasons. Glob'ing for files with a wildcard and running them during init/activation would make it harder to debug environments because of users dropping files in the etc/profile.d, whether they want it or not.

I don't think this makes the security issues worse. For eg: if the user drops a file in `etc/conda/activate.d/` it'll get executed.
The only difference between `etc/profile.d` and `etc/conda/{,de}activate.d` is the time they are executed. `etc/conda/{,de}activate.d` gets executed when an environment is `{,de}activated` while `etc/profile.d` gets executed when the shell session starts regardless of whether conda is set to activate automatically or not.

> You didn't really elaborate on the use case in this pull request so far, but in the referenced mamba-org/mamba#1035 it's mentioned that this isn't a Conda issue and would be best solved in Mamba by implementing mamba shell init to keep the wrapping nature of mamba. I'm a bit worried about adding features to Conda to work around issues in Mamba's implementation, generally speaking.

I don't think it's a Mamba issue. I think it's a limitation of Conda that it only allows custom scripts at environment activation time and doesn't allow custom scripts at shell session start. If you disagree I can move this code to mamba too.

> BTW, if this is a new feature request that is only partially related to the Mamba issue mentioned, I'd be interested in co-writing a short CEP for this if you're interested, so we can figure out if that's a good format for those things.

I don't think there is any package other than Mamba that would benefit from this

**Comment by wolfv** [comment]
The problem in mamba is the following:

- the environment has to be re-activated after an "install" command to properly execute activation scripts, `hash` the binaries on the PATH etc.
- activation is a "shell"-function and has to live inside the context of the shell, which is why `conda` is actually a shell-function (if you check `which conda` one can see that)
- in order to get these shell functions, conda has a `init` function that adds some text to the `~/.bashrc` and similar files
- there are several other ways to extend the shell, but none would be sufficient for mamba's use-case:
  - one can have an activation script, but that would only work in the currently active environment and after activation -- however `mamba` needs to work from other environments than the base env, too
  - one could place a `mamba.sh` function in the `condabin` folder, that would perform some shell tricks, but it's not enough either because the file would not be "sourced" but rather executed

From the mamba side we could implement a `init` function, but that would mean that we'd write out a slightly different block to the `.bashrc` function. I think this solution here is actually much cleaner because it doesn't require us to write to a different shell block and cleanly extends what conda is already doing.

**Comment by jezdez** [comment]
> > This seems like an unwanted opening of the activation functionality to me and like a bit of an anti-pattern for security and maintenance reasons. Glob'ing for files with a wildcard and running them during init/activation would make it harder to debug environments because of users dropping files in the etc/profile.d, whether they want it or not.
> 
> I don't think this makes the security issues worse. For eg: if the user drops a file in `etc/conda/activate.d/` it'll get executed.
> The only difference between `etc/profile.d` and `etc/conda/{,de}activate.d` is the time they are executed. `etc/conda/{,de}activate.d` gets executed when an environment is `{,de}activated` while `etc/profile.d` gets executed when the shell session starts regardless of whether conda is set to activate automatically or not.

Yeah, but that would extend the relevant attack surface quite a bit and I'm not convinced that the presented use case warrants this. The potential use for malicious scripts like cryptominers or -lockers is real if all it takes is to drop a shell script somewhere on the filesystem - no additional step needed to activate it.

> > You didn't really elaborate on the use case in this pull request so far, but in the referenced [mamba-org/mamba#1035](https://github.com/mamba-org/mamba/issues/1035) it's mentioned that this isn't a Conda issue and would be best solved in Mamba by implementing mamba shell init to keep the wrapping nature of mamba. I'm a bit worried about adding features to Conda to work around issues in Mamba's implementation, generally speaking.
> 
> I don't think it's a Mamba issue. I think it's a limitation of Conda that it only allows custom scripts at environment activation time and doesn't allow custom scripts at shell session start. If you disagree I can move this code to mamba too.
>
> > BTW, if this is a new feature request that is only partially related to the Mamba issue mentioned, I'd be interested in co-writing a short CEP for this if you're interested, so we can figure out if that's a good format for those things.
> 
> I don't think there is any package other than Mamba that would benefit from this

Okay, this is a new feature request, that only Mamba would profit from and that increases the maintenance burden and security footprint for Conda. I'm sorry but this needs rethinking, maybe we can find a way that reduces the chance for abuse?

**Comment by jezdez** [comment]
> The problem in mamba is the following:
> 
> * the environment has to be re-activated after an "install" command to properly execute activation scripts, `hash` the binaries on the PATH etc.
> * activation is a "shell"-function and has to live inside the context of the shell, which is why `conda` is actually a shell-function (if you check `which conda` one can see that)
> * in order to get these shell functions, conda has a `init` function that adds some text to the `~/.bashrc` and similar files
> * there are several other ways to extend the shell, but none would be sufficient for mamba's use-case:
>   
>   * one can have an activation script, but that would only work in the currently active environment and after activation -- however `mamba` needs to work from other environments than the base env, too
>   * one could place a `mamba.sh` function in the `condabin` folder, that would perform some shell tricks, but it's not enough either because the file would not be "sourced" but rather executed
> 
> From the mamba side we could implement a `init` function, but that would mean that we'd write out a slightly different block to the `.bashrc` function. I think this solution here is actually much cleaner because it doesn't require us to write to a different shell block and cleanly extends what conda is already doing.

Thanks for the details, this is very helpful @wolfv!

While the implementation can be cleaner, it's a whole different question if it's also a good idea 😬 When looking at this feature as a way to solve Mamba's activation problem alone I totally agree with you, but I'm also taking into account how it would impact our ability to maintain a safe software for Conda's users. I fully acknowledge that Mamba's problem is real of course.

I'll think about it a bit more, taking [CEP-2](https://github.com/conda/ceps/pull/1) into account. E.g. shell activation might be better solved by providing hooks for 3rd party tools to extend Conda's default behavior instead of glob'ing.

Maybe it could be something to bring multisheller and [pluggy](https://pluggy.readthedocs.io)/[HookMan](https://github.com/ESSS/hookman) together? I know, this sounds bigger than this small feature :lolsob:

**Comment by wolfv** [comment]
I think at the point where a random software can place a file inside your base environment you've "lost already" -- that software could just as well write to your `~/.bashrc` directly.
Any conda package can install arbitrary executables, run post-link scripts to do arbitrary things on your system (with user permissions, at least), or install activation scripts already.

In my opinion the only proper way of getting more _security_ is by sandboxing conda environments in something like a Docker container -- I have been looking quite a bit at Flatpak for this, and systemd-nspawn.

We could also make it explicit to install these additional files. So that the user has to call `mamba init` (not `conda init`). And `mamba init` internally would call the shell init functions with an extra argument for a folder with additional scripts.

**Comment by wolfv** [comment]
I've started some additional work to support `mamba shell init` in this PR here: https://github.com/mamba-org/mamba/pull/1078

For now (until this PR here is merged), I am planning to run `conda shell init`, and then modify the `.bashrc` file (and others) to add `. $ROOT_PREFIX/etc/profile.d/mamba.sh` right before 

```
if [ -f "/Users/wolfvollprecht/micromamba/etc/profile.d/mamba.sh" ]; then
   . "/Users/wolfvollprecht/micromamba/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<
```

That's more hacky than the approach in this PR but I think we can move faster that way :)
And conda can still overwrite this since conda init will just completely remove the block between

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
...
# <<< conda initialize <<<
```

**Comment by mbargull** [comment]
I understand the motivation and don't disagree that conda/mamba should (given the state, i.e., simultaneous installation of both in users' installs) acknowledge the existence/operation of "another" package manager for the same base installation. If each of them added a way to enable the other's shell init code to be invoked (well, and both should then make sure to not step on each other's toes, i.e., not do the same stuff twice/differently).

However, I don't believe `. etc/profile.d/*.sh` is a good idea. We should rather make that more explicit and have a `etc/conda/init`/`etc/conda/shell` or similar folder for this (`etc/profile.d/conda.sh` could then `. etc/conda/shell/*.sh` or something so that a `. etc/profile.d/conda.sh` is possible in backwards-compatible way).
It's not necessarily a question of "security" but just that `etc/profile.d/` could host some unexpected scripts. Bare in mind that we do package some low level packages at conda-forge and those could ship some `etc/profile.d/some-init-script.sh` (if their installation scripts expect to be installed into `/` and we don't prevent them to drop things into `etc/profile.d`) -- and those scripts might not be suitable to be sourced multiple times in an interactive shell session; `/etc/profile`/`/etc/profile.d` is meant for login shells after all.

**Comment by mbargull** [comment]
> I'll think about it a bit more, taking [CEP-2](https://github.com/conda/ceps/pull/1) into account. E.g. shell activation might be better solved by providing hooks for 3rd party tools to extend Conda's default behavior instead of glob'ing.

It is certainly worthwhile to think about what requirements could come up that a sourcing `etc/conda/shell/*.sh` could not easily satisfy. E.g., could there be some dependency (and would we allow that -- maybe rather not, because it makes things complicated) like `mamba.sh` has to be executed after `conda.sh` which can only be handled to a degree by globs/file naming. If there would be such (potential) requirements, then even more explicit hooks might be necessary, yes.

> Maybe it could be something to bring multisheller and [pluggy](https://pluggy.readthedocs.io)/[HookMan](https://github.com/ESSS/hookman) together? I know, this sounds bigger than this small feature :lolsob:

NB: What has to be kept in mind is that certain parts of `conda` *have to be fast* to not lessen the all-day user experience. Shell initialization and activation is one such prime candidate. We wouldn't want a user's shell startup to be delayed by half a second or so. E.g., when being sourced, `conda.sh` should not invoke `python` at all and even a `conda activate` (esp. if the users have `conda activate base` in their shell init scripts) should not do any time-consuming things (e.g., we invested work to make the `shell.* activate` reasonably fast by ensuring not to import slow-to-import modules etc.)

**Comment by wolfv** [comment]
The application I have in https://github.com/mamba-org/mamba/pull/1078 will first run conda init, and then inject some additional code into the `bashrc` file. This means that mamba users should run `mamba init`.
I think for most cases that'll be fine. A bit annoying for CI systems and stuff, but they probably don't suffer that much anyways from the current bug in mamba since they use `mamba create` more than `mamba install`, or run `mamba install` in another shell session.

**Comment by isuruf** [comment]
> However, I don't believe . etc/profile.d/*.sh is a good idea. 

Sure. We can do `/etc/conda/init.d/` instead. Not a huge issue.

**Pull request closed without merging**
