### PR TITLE
default_channels from the cli

### PR DESCRIPTION
**Pull request by quasiben**
Add capability to add default_channels from the cli

### CODE REVIEW

**Comment by ilanschnell** [comment]
The `default_channels` are only relevant for a "system" condarc file.  Allowing to change them will be confusing to most users because this will normally not have any effect.

**Comment by quasiben** [comment]
I made another change to handle `system` condarc.  I'd probably prefer to system_rc_list_keys instead, thoughts ?

**Comment by ilanschnell** [comment]
Great

**Comment by amccarty** [comment]
@ilanschnell any updates on when a release including this PR will happen? Have an anaconda cluster customer waiting on it.

**Comment by ilanschnell** [comment]
It is merged, so depending on the level of urgency, I could do a release whenever.

**Comment by amccarty** [comment]
@ilanschnell Let's consider this urgent please. Thanks!

**Pull request merged**
