### PR TITLE
colorama fix

### PR DESCRIPTION
**Pull request by cjmartian**

### CODE REVIEW

**Comment by chenghlee** [comment]
Looks good to me.

**Comment by mlline00** [comment]
This merge broke the Windows test suite on AppVeyor.  The tests are throwing "Invalid code page" when trying to activate the environment with dev-init.bat:

python -m conda init cmd.exe --dev
rm -rf C:\Miniconda\Lib\site-packages\conda-4.8.3-py2.7.egg-info
rm -rf C:\Miniconda\Lib\site-packages\conda
rm -rf C:\Miniconda\Lib\site-packages\conda_env
now run  > .\dev-init.bat
CALL dev-init.bat
Invalid code page
Command exited with code 1

**Comment by mlline00** [comment]
Also looks like it broke the linux flake8 tests on circleci:

#!/bin/bash -eo pipefail
/opt/conda/bin/flake8 --statistics
./conda/activate.py:644:82: E231 missing whitespace after ','
1     E231 missing whitespace after ','

Exited with code exit status 1
CircleCI received exit code 1

**Comment by mlline00** [comment]
@cjmartian @chenghlee Have either of you noted the comments above about how this PR broke the test suite? Should I open an issue on the topic?

**Comment by cjmartian** [comment]
I think I should be able to take a look at this today

**Comment by mcg1969** [comment]
@cjmartian 
The bad news: we ended up reverting this PR... :-(
The good news: we've fixed the AppVeyor CI so it will be possible to verify this in the future.
That said, this PR as designed wouldn't have passed CI because of the "Invalid code page" issue, and one other thing: adding PYTHONIOENCODING to the environment was breaking some other tests. That's fixable, certainly, but it would be necessary to modify the tests.

**Pull request merged**
