### PR TITLE
conda initialize

### PR DESCRIPTION
**Pull request by kalefranz**
toward #6507

### CODE REVIEW

**Comment by mbargull** [comment]
Hi Kale,
I only took a quick peek here and there in the changeset, but was wondering what the general state of this PR is. When do you want this to be done and when would you want this to be reviewed?

**Comment by kalefranz** [comment]
It passed! Finally have a baseline passing commit :)

I think it's ready to start working with and reviewing.  There are some chunks that don't have built out functionality yet.  Specifically 

```python
    if shells & {'fish', }:
        if for_user:
            raise NotImplementedError()
        if for_system:
            raise NotImplementedError()

    if shells & {'tcsh', }:
        if for_user:
            raise NotImplementedError()
        if for_system:
            raise NotImplementedError()

    if shells & {'powershell', }:
        if for_user:
            raise NotImplementedError()
        if for_system:
            raise NotImplementedError()
```

But at this point, I'd rather us focus on getting the functionality that's already here correct first.  And then we can build the rest out in a future PR.  This PR looks pretty huge already.  Although the meat of it is really just two new files... `conda/core/initialize.py` and `tests/core/test_initialize.py`.

Oh, and definitely part of this work is spending time on improving `CONTRIBUTING.md`, so don't skip that.

**Comment by kalefranz** [comment]
Here's the rendered version of the current `CONTRIBUTING.md` in this PR:
https://github.com/kalefranz/conda/blob/cbadd4835176679d672ef0abb6fd0715d4101dbb/CONTRIBUTING.md

If people can't tell, I'm pretty excited about all the implications of this PR.  I think the concepts basically represents the completion of the work started in #5044.  Well, at least the completion of the phase 1.  I consider https://github.com/conda/conda/issues/6820 phase 2.

**Comment by kalefranz** [comment]
After several demos and lots of discussion, I believe consensus is that this PR is pretty difficult to review because of its size, and that the best way to review the behavior is via a preview release of conda.  Moving forward with merging this so that we can have a conda 4.6.0alpha1 for users to interact with and give feedback on.

**Comment by mbargull** [comment]
Yeah, still didn't find the time to completely review. I *might* get to take a look at it on this weekend. I guess it's fine to just add review comments to this PR then?

**Comment by kalefranz** [comment]
Absolutely yes!

**Pull request merged**
