### PR TITLE
[docs] Update manage-environments.rst

### PR DESCRIPTION
**Pull request by chbrandt**
Applied some formatting in section "activating an environment":
* emphasis to keywords
* add 'note' to install related recommendations

### Description

In "Activating an environment" section of "Managing environments" chapter,
two paragraphs have important information -- that actually relates to *install* --
that I thought should have more attention (with 'note' blocks, for instance).

Other adjustments include *emphasis* in keywords, use of "quotes",
and the move of a paragraph (from below) that was a bit detached.

- NOTE: I also suggest the paragraphs I put under '..note::', should be moved to
the Installation page (and refer to it in "activating environment").

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Review by jezdez — CHANGES_REQUESTED** [review]
Thanks for the patch, this seems to be rendering in an odd way though: https://continuumio-conda-docs--12835.com.readthedocs.build/projects/conda/en/12835/user-guide/tasks/manage-environments.html

CleanShot 2023-07-04 at 13 09 40@2x

**Review by kathatherine — CHANGES_REQUESTED** [review]
Let me know if you have questions about my suggestions or need help with the note spacing. GitHub wouldn't let me suggest changes on all the lines that needed it. Thanks!

**Comment by chbrandt** [comment]
Ouch... this was ugly. Thanks @kathatherine for the suggestions. Am fixing now.

**Comment by chbrandt** [comment]
Text is being rendered properly now (https://continuumio-conda-docs--12835.com.readthedocs.build/projects/conda/en/12835/user-guide/tasks/manage-environments.html#activating-an-environment).

`pre-commit` test is failing for a reason I cannot identify (in trailing-whitespace).

**Comment by kathatherine** [comment]
pre-commit.ci autofix

**Pull request merged**
