### PR TITLE
Encode repodata to utf-8 while caching

### PR DESCRIPTION
**Pull request by geremih**
Encodes cached repodata as UTF-8 to handle unicode characters gracefully.
(for python2)

### CODE REVIEW

**Comment by msarahan** [comment]
Could you please refresh this with the latest master code, or alternatively retarget it to the 4.5.x branch?  I don't think the test fails are related, but I want to make sure.

**Comment by geremih** [comment]
@msarahan Tests are passing now.

**Comment by nehaljwani** [comment]
@geremih Could you sign the Conda CLA please?

**Comment by msarahan** [comment]
He has.  We need to process it, but this is OK to go in in the meantime.

**Comment by msarahan** [comment]
@geremih my apologies it has taken so long to work with the CLA stuff.  I have added you, and will now merge this PR.  Thanks for your patience.

**Pull request merged**
