### PR TITLE
Document channel::package syntax for environment.yml files

### PR DESCRIPTION
**Pull request by ReveStobinson**
### Description

Adds documentation requested in #11890.

Documented `channel::package` syntax for dependency specification in a `note:` in the **Sharing an Environment** section of `docs/source/user-guide/tasks/manage-environments.rst`. Also added `news` file, but it may not be needed for a change of this magnitude.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by beeankha** [comment]
@conda-bot check

**Review by beeankha — DISMISSED** [review]

**Review by chenghlee — DISMISSED** [review]

**Comment by travishathaway** [comment]
Hi @ReveStobinson,

Thank for you very much for this contribution. This additional example helps reiterate the fact that this is possible to do within `environmnet.yml` config files.

I made some slight changes to what you had proposed (I hope this is okay! 😅). I couldn't help but notice that this "admonition" ("note" box) appears right next to another one.  To help reduce visual clutter and to make it easier for the reader, I have combined the two into a single box and also added paragraph headers for each. I think the end product is slightly better.

Please checkout the preview on this pull request to let us know what you think. If we don't hear back soon, we will go ahead and merge this pull request.

Cheers ✌️,

--
Travis from the conda team 🐍

**Review by travishathaway — APPROVED** [review]

**Review by jezdez — APPROVED** [review]

**Comment by James-Leslie** [comment]
Hi there,
What if a package needs to use multiple channels?

For example, the `datasets` package from huggingface would usually be installed with (taken from bottom of [this page](https://huggingface.co/docs/datasets/installation)): 
```bash
conda install -c huggingface -c conda-forge datasets
```

How would I specify this in my `.yml` file?

```yml
name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - huggingface::transformers
  - huggingface::datasets
  - pytorch::pytorch
```

**Comment by ReveStobinson** [comment]
@James-Leslie **TL;DR,** your `.yml` file looks correct.
> Hi there, What if a package needs to use multiple channels?
> 
> For example, the `datasets` package from huggingface would usually be installed with (taken from bottom of [this page](https://huggingface.co/docs/datasets/installation)):
> 
> ```shell
> conda install -c huggingface -c conda-forge datasets
>```

A single package _on its own_ won't ever need multiple channels to install, but its dependencies might, which is what I understand is the case in the example you gave from the Huggingface docs. In this case that was fairly obvious, and your `environment.yml` was indeed correct.

I _could_ forsee an issue in a slightly different (seemingly unlikely?) case where you might not know which of the two channels your packages comes from. As I see it, this would mostly affect highly specific packages only available on smaller channels.

### Example

Consider a fictional package called `frog_stuff`, which is maintained by one University professor who never checks his email. His install documentation is one line:

> Use conda to install `frog_stuff` with the following command: `conda install -c bioconda -c paulscherrerinstitute frog_stuff`. 

You might not know which channel `frog_stuff` is actually hosted on, so you don't know which channel to put in `channel` and which to put before `::frog_stuff`.  If `frog_stuff is only on one of these two channels, one combination will invariably error out.

Typically, you'd be able to figure out fairly easily which channel holds the dependencies, and which holds the "base" package (as you did with `huggingface::datasets`). In a less obvious case like `frog_stuff`, the context clues aren't there, so your best bet is probably either searching both channels for the package in question, or simple trial and error.

**Comment by James-Leslie** [comment]
Hi @ReveStobinson (great username - I always enjoy swapping letters around like that 😂) thanks very much for that helpful response.

Would you be able to help me in defining the `.yml` file for including the `pytorch-cuda=11.7` package?

It has similar conda installation instructions:
```bash
conda install pytorch-cuda=11.7 -c pytorch -c nvidia
```

My understanding is that the `pytorch-cuda` package comes from the `pytorch` channel, but its dependencies all come from the `nvidia` channel.

So if I were to specify `pytorch::pytorch-cuda`, how does conda know where to get the dependencies that come from the `nvidia` channel? Should I add `nvidia` to the list of channels?

**Comment by ReveStobinson** [comment]
@James-Leslie 
> So if I were to specify `pytorch::pytorch-cuda`, how does conda know where to get the dependencies that come from the `nvidia` channel? Should I add `nvidia` to the list of channels?

**Yes!** Sorry for the late reply, but this is exactly the use case where I discovered this undocumented syntax that prompted this PR. 

`pytorch-cuda` comes from the `pytorch` channel, but it will also install a ton of libcuda and cudnn-type stuff for you, and some of those dependencies (or possibly their most up-to-date versions) are hosted on the `nvidia` channel. So, you would indeed just specify `- nvidia` in your `channels:` list at the top of your `.yml` file.

**Pull request merged**
