### PR TITLE
Performance improvements for conda run - avoiding Popen.communicate().

### LINKED ISSUE #8386: conda run swallows stderr output
## Current Behavior

If the command executed with `conda run` prints something to stderr, that output is not shown. If it prints a lot, then it freezes.

### Steps to Reproduce

First, create `test.py` with the following contents:
```python
import sys
print('x' * int(sys.argv[1]), file=sys.stderr)
```

Then:
```
>conda run -n base python test.py 1
[nothing is printed]
>conda run -n base python test.py 10000
[nothing is printed _and_ the command freezes]
```

## Expected Behavior

All stderr output from the command should be passed unaltered to `conda`'s own stderr.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\Users\[redacted]\AppData\Local\Continuum\miniconda3
            shell level : 1
       user config file : C:\Users\[redacted]\.condarc
 populated config files :
          conda version : 4.6.7
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\[redacted]\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\[redacted]\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\[redacted]\.conda\pkgs
                          C:\Users\[redacted]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[redacted]\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\[redacted]\.conda\envs
                          C:\Users\[redacted]\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\[redacted]\AppData\Local\Continuum\miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.6.7                    py37_0    defaults
conda-env                 2.6.0                         1    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.4.2            py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
openssl                   1.1.1b               he774522_0    defaults
pip                       18.1                     py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                h8c8aaf0_6    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults

```
</p></details>

### PR DESCRIPTION
**Pull request by gilescope**
Fixes #8386. Manally confirmed works on OSX.

### CODE REVIEW

**Comment by gilescope** [comment]
Have signed the cla, but bot is probably a bit slow off the mark...

**Comment by gilescope** [comment]
AssertionError: assert ('channel-4::...84d3e_0', ...) == ('channel-4::c...84d3e_0', ...)
  At index 18 diff: 'channel-4::idna-2.7-py37_0' != 'channel-4::cryptography-vectors-2.3-py37_0'

I don't know what the above test failure is, but that one test failed for me locally when I'd cloned master and hadn't changed anything, so hopefully someone will fix it and I can just rebase this branch.

**Comment by soapy1** [comment]
@gilescope thanks for the contribution! looks like the test failures are not related to your change. fwiw, working on fixing those https://github.com/conda/conda/pull/9410

@cla-bot check

**Comment by soapy1** [comment]
sorry, clicked the wrong button

**Comment by msarahan** [comment]
Thanks @gilescope!  If I read this correctly, this should also no longer capture stdout/stderr, which will help people see progress.

**Pull request merged**
