### PR TITLE
Enable s390x support in cpuinfo

### PR DESCRIPTION
**Pull request by ravigumm**
This is in continuation to add support for s390x done in https://github.com/conda/conda/pull/9933

### CODE REVIEW

**Comment by ravigumm** [comment]
@chenghlee Would you please review and provide your comments ? Thanks

**Comment by chenghlee** [comment]
@cla-bot check

**Comment by jjhelmus** [comment]
@cla-bot check

**Comment by ravigumm** [comment]
@cla-bot check

**Comment by ravigumm** [comment]
This PR is related to https://github.com/conda/conda/issues/9791

**Pull request merged**
