### PR TITLE
fix conda pip list on windows, see PR #2056

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by kalefranz** [comment]
@msarahan or @groutr can you manually QA this on windows and confirm it works as expected?

**Comment by kalefranz** [comment]
@msarahan, @groutr going to go ahead and merge this. I think it's correct. But let's do a quick test on windows before we actually publish the next release.

**Comment by 3kwa** [comment]
It does not work on Windows! See https://github.com/conda/conda/pull/2264 for a fix

**Comment by ilanschnell** [comment]
@kalefranz why was this merged without any testing on Windows?

**Pull request merged**
