### PR TITLE
Provide activate/deactivate functionality on Windows to match Unix (using batch files instead of symlinks)

### PR DESCRIPTION
**Pull request by wulmer**
Hi, as a follow-up to https://github.com/conda/conda/pull/885 I have added the discussed poor-man-symlink (=batch file) implementation to  oddodood's scripts. @asmeurer: Is this like you thought it should be?

### CODE REVIEW

**Comment by wulmer** [comment]
@asmeurer What is the status of this PR? What is missing for a merge?

**Comment by asmeurer** [comment]
Man, sorry for taking forever with this. 

I seem to remember there was some issue with this (and I was glad I hadn't merged it yet). I'll see if I can dig up what it was. Something that doesn't work if the root environment isn't on the PATH maybe.

**Comment by asmeurer** [comment]
I remembered it! It's because currently on Windows we ship the msvc redistributable package, but it isn't packaged as a conda package, it's installed with the installer. This works fine presently becaues the root environment is always on the PATH, but breaking that will break things (see https://github.com/ContinuumIO/anaconda-issues/issues/214).

**Comment by asmeurer** [comment]
And derp, I see I even cross referenced that issue here already. 

So, sadly, we will need to hold off on merging this until we get that fixed.

**Comment by wulmer** [comment]
Ok, no problem. But what would be a possible solution to the dilemma of https://github.com/ContinuumIO/anaconda-issues/issues/214 and this #913 ? I would like to help but I don't have a clue what could be a good solution:

1. Keep the root environment on the PATH ? This goes totally against this PR.
2. Put those additional DLLs into a separate directory in the root env and keep that directory on the PATH ? This could be easily done outside of this PR as it only removes two root env folders from PATH:  `/` and `/Scripts`.
3. Copy the MSVC redistributable DLLs to each environments directory? 
4. ... ?

**Comment by asmeurer** [comment]
@tswicegood you should be aware of this PR, since your changes are causing merge conflicts with it, and I don't want @wulmer's work to go to waste.

**Comment by asmeurer** [comment]
@wulmer the solution is for us to create a package with the redistributable package and make it a dependency of our python package. CC @ilanschnell

**Comment by msarahan** [comment]
Bumping this due to bump in #661 - I would like to fix this.

I can create a windows redistributable package, and have each python version track appropriately.  Is there anything else that needs to be done for this PR?

**Comment by asmeurer** [comment]
This actually doesn't affect powershell as far as I know. 

This PR was broken when activate was moved to conda-env. It would be great to finish it, though.

**Comment by wulmer** [comment]
What would be the correct way to implement this PR after the split of conda and conda-env? I have looked through the code and it seems that it should be possible to reimplement the changes to the activate scripts together with the necessary changes in the conda/conda-env backend script solely in the conda-env repository. 

But it seems that all the tests for the activate mechanism are still in the conda repository? How is the recommended setup to do changes on the conda-env codebase while running tests from the conda repository? I am a bit confused and I wonder what would happen when I submit a PR for the conda-env repo which cannot be tested as the tests are in another repo?

Can someone of the core team please shed some light on the correct way for modifying the activate mechanism inside conda-env ?

**Comment by msarahan** [comment]
@wulmer Thanks for raising this, and for your patience.  Indeed, the split between Conda and conda-env is sub-optimal.  Long-term, we will be reconciling this by unifying them.  In the short term, please submit your PR against the conda-env repository.  I will review and merge it there, and see if any additional tests can be added there.

**Comment by asmeurer** [comment]
In particular, the activate scripts are in conda-env, but the Python code should stay in conda itself, since that is already where it is for the current Unix activate scripts.

**Comment by kalefranz** [comment]
Going to close for now. Should be covered in #1727.  If it's not, feel free to update and re-open.

**Pull request closed without merging**
