### PR TITLE
Merge conda-env into conda

### PR DESCRIPTION
**Pull request by tswicegood**
This brings the entire history of the https://github.com/conda/conda-env project into conda under the module namespace `conda.env`.

## Tasks
* [x] Test on Linux (Travis CI)
* [ ] Test on Windows

### CODE REVIEW

**Comment by tswicegood** [comment]
@ilanschnell this code also removes the `_conda-functions` code.

**Comment by asmeurer** [comment]
If I have comments on conda env itself should I make them here or should we merge this first and then make new issues?

**Comment by asmeurer** [comment]
Well I'll just comment here, so I don't forget. You can decide whether these need to be done before the merge or not.

**Comment by asmeurer** [comment]
Please use options from the cli.common module when possible. In particular, use the various `prefix` functions like `add_parser_prefix` to add the `-n` option so that the conda env commands act like all the other conda commands.

**Comment by tswicegood** [comment]
@asmeurer there was a conscious decision not to use `--prefix` in the context of environments and only support named environments.  The reason is that we can't list things like random prefixes.  Using the name only ensures that we know where the environment we're creating is.  We talked about this last fall in one of the meetings where `--prefix` becomes something that's meant as an internal plumbing tool and not something someone should actively used.

FWIW, I've considered deprecating `-n` and `--name` in favor of using regular arguments.  This comes straight from the user-experience of typing `conda env remove -y -n some-env` and how weird it looks to mix letters commonly associated with yes and no in the same command.

**Comment by asmeurer** [comment]
So I guess we should move the discussion of this to a new issue. 

My personal experience was that `conda env export` didn't work, because it required me to name the environment (I expected it to just export my current environment). 

I see your point for `--prefix`, though I think you'll get a lot of requests to add it anyway.

**Comment by amfarrell** [comment]
To jump in on the issue of depreciating --name, I think there is a better argument in favor of it: having syntax more closely match semantics.

The current,  syntax `conda create --name envname package name` is odd to someone unfamiliar with it. The primary thing that the command does is create an environment. Its name (or location/prefix) is central to the purpose of the command, but isn't a primary argument. At the same time, conceptually, installing a particular package into that environment is actually not a necessary part of creating an environment, so it should be an option.

The current syntax runs counter to unix conventions because
* --name is an "option" that isn't actually optional.
* `conda create` isn't a single operation but two: create and install.

Compare:
`conda env create fedex --name rainforest` which reads as "invoke conda environment tool to create (with 'fedex') something named rainforest"
 `conda env create rainforest --install fedex` which reads as "invoke conda environment tool to create 'rainforest' and install 'fedex'"

**Comment by asmeurer** [comment]
It is odd the first time you see it, but it's very consistent as all the commands use `-n` in the same way, so you don't even have to think. It's also useful because the only effective difference between `conda install` and `conda create` is that `install` fails if the environment doesn't exist, so I think it's good to have to two commands be formatted exactly the same.

**Comment by amfarrell** [comment]
I think that consistency comes at the expense of good semantics for each command and it is unwise to carry it into the new semantic territory of `conda env`.

If a user knows that `conda create` really means `conda create_env`, then it is obvious that `--name` refers to the name of the env being created. However, consider `conda package --name`. A reasonable person reading seeing that command without knowing that it is an analogy to `conda create` could easily guess that `--name` referred to the name of a package, not the name of an environment. Or `conda update --name`, which could refer to the name of a something to be updated to or from. Or `conda install --name`, which could refer to an alias that you want to give the newly installed package. For all of these commands besides `conda create`, a better name for that option would be `--env`. The meaning of `conda install pygment --env tundra` (or `conda install pygment --env /afs/lab-common/tundra`) is slightly more clear than `conda install pygment --name tundra. 

Is it worth changing things now? Maybe not. A lot of old shell scripts would need to be edited on a lot of user machines.
But `conda env` is conceptually a new space whose users want to deal primarily with manipulating environments and there is no reason to carry the `--name` convention onto what is currently free soil. A user typing `conda env update` knows that they are dealing with environments and expects to give the name of an environment.

**Comment by amfarrell** [comment]
> The only effective difference between `conda install` and `conda create` is that...
The fact that they are almost the same command is semantically odd because that means they are really `conda install` and `conda create_env_then_install` and there is no command that is semantically equivalent to `conda create_env`

**Comment by asmeurer** [comment]
BTW I've never seen anyone spell out `--name`.

**Comment by tswicegood** [comment]
Clearing out old notices.  @asmeurer I use `--name` [all the time in scripts][1] as it's more descriptive for folks that have to read them after me.

[1]: https://github.com/conda/conda-env/blob/master/.binstar.yml#L25

**Comment by amfarrell** [comment]
Isn't using the long form for options generally good practice in shell scripts? Exceptions of course for super-common ones like `ls -la`, `ln -s`, `sl -a` etc or lost-causes like `tar -cvvx`

**Comment by tswicegood** [comment]
@amfarrell yes, from my perspective.

**Comment by kalefranz** [comment]
Pretty old PR. Going to close for now.

**Pull request closed without merging**
