### PR TITLE
Improve fall-back version comparison, second attempt

### PR DESCRIPTION
**Pull request by ukoethe**
This is an improved version of PR https://github.com/conda/conda/pull/1591 (which was withdrawn). It implements a simple version ordering scheme. Version strings are parsed as follows:
Version strings are parsed as follows:
* they are first split into components at '.'
* each component is split again into runs of numerals and non-numerals
* subcomponents containing only numerals are converted to integers

Example:

    1.2g.beta15.rc  =>  [[1], [2, 'g'], ['beta', 15], ['rc']]
     
The resulting lists are compared lexicographically, where the following
rules apply for each pair of corresponding subcomponents:
* integers are compared numerically
* strings are compared lexicographically
* if the subcomponents have different types, strings are smaller than integers
* if a subcomponent has no correspondent, the missing correspondent is treated as integer 0.

The resulting order is:

       0.4
    == 0.4.0     # due to 0-padding
     < 0.4.1.rc
     < 0.4.1
     < 0.5a1
     < 0.5b3
     < 0.5
     < 0.9.6
     < 0.960923
     < 1.0
     < 1.0.4a3
     < 1.0.4b1
     < 1.0.4
     < 1996.07.12

### CODE REVIEW

**Comment by asmeurer** [comment]
Some related issues: 

- https://github.com/conda/conda/issues/1107 (PEP 440)
- https://github.com/conda/conda/issues/915 (inconstancy with version comparison fallback)

https://github.com/conda/conda/issues/915 is the issue that this should purport to fix. I'm unsure if it really does though. In order to do so, the ordering given here would need to be a superset of the PEP 386 ordering (i.e., there shouldn't be two versions that compare one way under verlib and another way under this scheme). 

I haven't looked closely yet, so I can't say if this is the case or not.

**Comment by ukoethe** [comment]
Ok, I've further improved the version handling to move it as close to PEPs 386/440 as possible:
* string comparisons are now case-insensitive
* epochs are handled correctly

A few differences remain:
* PEP 440 treats `c` and `rc` as identical, whereas the proposed code doesn't. Thus, `1.1.1c1 == 1.1.1rc1` in PEP 440, but `1.1.1c1 < 1.1.1rc1` in my code. In think it is best to handle this case by requiring _self-consistent_ version numbering, i.e. any given package must stick to either `c` or `rc`. The documentation should be extended to say so explicitly.
* PEP 440 allows a separator to be inserted before the prerelease letter, so that `1.1-a1 == 1.1_a1 == 1.1a1 == 1.1.a1`. In contrast, the present proposal has `1.1-a1 < 1.1_a1 < 1.1a1 < 1.1.a1`. Again, this is best handled by requiring self-consistency.
* The present proposal doesn't ignore a leading `v`. I don't see any justification for silently treating `v1.1 == 1.1`.
* PEP 440 requires special treatment of the string `.post` which signifies post-release versions. In contrast to normal string components, `post` is considered to be greater than any number. I suggest that the documentation should say explicitly that this special behavior is only available for conforming version strings.

BTW, the documentation should be extended to explain the difference between conforming and non-conforming version strings to begin with.

Finally, there is no way to design a PEP 440 compatible versioning scheme that handles 'openssl' correctly, because 'openssl' occasionally comes with conforming version strings but requires them to be ordered differently. I therefore added explicit special treatment of 'openssl'.

Please remember that this PR is not meant to solve the versioning problem once and for all (this is beyond my competence and time constraints). I just want to improve the fall-back for non-conforming version strings.

**Comment by ukoethe** [comment]
In this commit, I also changed ver_eval() to use the new fall-back. 

I'd also like to add a word of explanation for the 'openssl' special case: The official project files to build Python 2.7 on Windows (see `<python_src>/PCbuild/pcbuild.sln`) compile openssl along with the rest of the Python core in order to allow Python to open 'https:' URLs. For this to work, the openssl sources must be located in a specific directory, and I created a recipe 'openssl-src-for-python' which takes care of this. Package 'openssl-src-for-python' has the same version number as the contained openssl itself, requiring the special case. If you don't like this, I can remove it from the PR and create a workaround outside of conda, such as renaming `1.0.1  =>  1.0.1_` (this works because `_ < a`).

**Comment by ukoethe** [comment]
Well, after finding the `1.0.1  =>  1.0.1_` work-around for openssl, I didn't like the openssl special case anymore and reverted it.

**Comment by asmeurer** [comment]
>  I think it is best to handle this case by requiring self-consistent version numbering,

This is a good point. The way the code is currently designed, versions are only compared against each other, so one comparison might be PEP compliant and another for the same package might fallback.

**Comment by asmeurer** [comment]
By the way, `-` is not allowed in conda package versions.

**Comment by asmeurer** [comment]
Is it correct that alpha, beta, and rc don't need to be special-cased because they are already in the right order?

**Comment by ukoethe** [comment]
> one comparison might be PEP compliant and another for the same package might fallback

Exactly, but if the versioning is self-consistent, both methods will yield correct results.

> By the way, - is not allowed in conda package versions

I just mentioned it for completeness.

 > Is it correct that alpha, beta, and rc don't need to be special-cased because they are already in the right order?

Yes. However, alpha and a are different in my scheme. This is again a case for self-consistency.

**Comment by asmeurer** [comment]
I think this is good. I need to look closer before merging, since it changes a relatively important part of the code. 

I also agree that some better documentation around versioning would definitely be a good thing to have as well.

**Comment by ukoethe** [comment]
Great, thanks!

**Comment by ukoethe** [comment]
I added more tests which revealed a bug: the fall-back was only called when the primary comparison raised a `TypeError`. This did not happen when _both_ version numbers were non-conforming, because `normalized_version()` then returned two strings whose comparison would never fail.

The error is fixed in the latest commit.

**Comment by ukoethe** [comment]
I just notived an interesting coincidental property of the new versioning scheme: One can use `*` as a universal placeholder in version comparison. For example:

      match('1.1a', '>=1.1')   => False
      match('1.1a', '<1.1')    => True

but

      match('1.1a', '>=1.1*')  => True
      match('1.1a', '<1.1*')   => False

**Comment by asmeurer** [comment]
Yeah, `*` is part of the [version spec](http://conda.pydata.org/docs/spec.html#package-match-specifications).

**Comment by asmeurer** [comment]
Can we also make [this](https://github.com/conda/conda/pull/1585) change here? As you can see from the failing Travis tests on that PR, just making that change in master breaks things.

**Comment by ukoethe** [comment]
> Yeah, * is part of the version spec. 

If I understand correctly, `*` could only be used in match expressions so far. Now it also works in relational expressions.

> Can we also make [this](https://github.com/conda/conda/pull/1585) change here?

Unfortunately, I don't understand what the failing test is supposed to do...

**Comment by asmeurer** [comment]
> If I understand correctly, * could only be used in match expressions so far. Now it also works in relational expressions.

Oh I see. Should the spec document be updated then? 

> Unfortunately, I don't understand what the failing test is supposed to do...

I think it has to do with 1.0rc1 comparing less than 1.0.

**Comment by asmeurer** [comment]
That is, it's supposed to compare less than, and with that workaround it does, but without it it doesn't. I wonder if moving to PEP 440 would fix this.

**Comment by ukoethe** [comment]
One could also try to unify all version handling in a single class. However, this requires a much better test than the present one. Ideally, one would use a list of all packages on the binstar server, along with their available versions sorted by the current algorithm (that is, one sorted version list per package). Is it difficult to produce such a file?

**Comment by asmeurer** [comment]
For all of binstar I don't know. It's easy to get them for just repo.continuum.io though.

**Comment by ukoethe** [comment]
Here are some results: I downloaded all package descriptions from the default channel via

    conda search --json > packages.json

This gave me 379 packages with a total of 5793 versions. I then sorted the versions for each package using `resolve.Package.__lt__` from the current official conda distribution. This changed the order relative to `packages.json` for four packages (in all cases, `rc` was considered bigger than the corresponding release version):
* spyder
* spyder-app
* astropy
* iopro

Then I replaced `verlib.NormalizedVersion` in class `Package` with `SimpleVersionOrder`, i.e. the constructor now reads
```python
    # self.norm_version = normalized_version(self.version)
    self.norm_version = SimpleVersionOrder(self.version)
```
Now, in *all* cases the order in `packages.json` was preserved after sorting.

How can we repeat this experiment for more exotic packages from non-default channels? (I consider this necessary because the default channel doesn't use fancy version numbers and is very self-consistent.)

**Comment by ukoethe** [comment]
Sorry, I made a mistake (I worked on the wrong branch). Both the official and modified `Package` classes preserve the order.

**Comment by asmeurer** [comment]
Some of the versions on anaconda.org are so esoteric that they should probably not be supported. Off the top of my head, `bokeh` and `blaze` would be good to check, since I know that they upload a log of nightly packages there.

**Comment by asmeurer** [comment]
My channel (`asmeurer`) also has a pretty wide variety of packages, although most of them are only going to have one or two versions.

**Comment by ukoethe** [comment]
After a lot of experimentation, I created a test package `sort` on channel `ukoethe-test` that perhaps shows the essentials of the problem. The package has 24 versions, and standard conda orders them as follows:
```
> conda search --override-channels -c ukoethe-test sort
Fetching package metadata: ..
sort    1.1.0a1      0  ukoethe-test  <--
        1.1.a1       0  ukoethe-test    | ?
        1.1a1        0  ukoethe-test    |
        1.1.0dev1    0  ukoethe-test  <--
        1.1.dev1     0  ukoethe-test
        1.1dev1      0  ukoethe-test
        1.1.0rc1     0  ukoethe-test
        1.1rc1       0  ukoethe-test
        1.1          0  ukoethe-test
        1.1.0        0  ukoethe-test
        1.1.0post1   0  ukoethe-test
        1.1.post1    0  ukoethe-test
        1.1.2a1      0  ukoethe-test
        1.1.2dev1    0  ukoethe-test
        1.1.2rc1     0  ukoethe-test
        1.1.2        0  ukoethe-test
        1.1.11a1     0  ukoethe-test
        1.1.11dev1   0  ukoethe-test
        1.1.11rc1    0  ukoethe-test
        1.1.11       0  ukoethe-test
        1.1.rc1      0  ukoethe-test  <-- ?
        1.1.11post1  0  ukoethe-test
        1.1.2post1   0  ukoethe-test
        1.1post1     0  ukoethe-test
```
Some versions are clearly not placed where I expected (e.g. `'a'` vs `'dev'`, `'1.1.rc1'`). Do you really want `SimpleVersionOrder` to reproduce this behavior?

FWIW, I created a variant of `SimpleVersionOrder` that handles `dev` and `post` specially (not yet part of this PR). It agrees with conda's standard order on all packages from channels 'default', 'asmeurer', 'blaze', and 'bokeh', except for a few early blaze versions where `'_'` was used to indicate development versions (standard conda messes up here). On the above test data, this variant gives the order:
```
1.1dev1-0    
1.1a1-0      
1.1rc1-0     
1.1.0dev1-0  == 1.1.dev1-0   
1.1.0a1-0    == 1.1.a1-0     
1.1.0rc1-0   == 1.1.rc1-0    
1.1.0-0      == 1.1-0      
1.1.0post1-0 == 1.1.post1-0  
1.1.2dev1-0  
1.1.2a1-0    
1.1.2rc1-0   
1.1.2-0      
1.1.2post1-0 
1.1.11dev1-0 
1.1.11a1-0   
1.1.11rc1-0  
1.1.11-0     
1.1.11post1-0
1.1post1-0  
```

**Comment by ukoethe** [comment]
Instead of `1.1 == 1.1.0`, `SimpleVersionOrder` could also implement the rule `1.1 < 1.1.0` (and likewise `1.1.a1 < 1.1.0a1` etc.):
```
   1.1dev1-0    
   1.1a1-0      
   1.1rc1-0     
   1.1.dev1-0   
   1.1.a1-0     
   1.1.rc1-0    
   1.1-0        
   1.1.post1-0  
   1.1.0dev1-0  
   1.1.0a1-0    
   1.1.0rc1-0   
   1.1.0-0      
   1.1.0post1-0 
   1.1.2dev1-0  
   1.1.2a1-0    
   1.1.2rc1-0   
   1.1.2-0      
   1.1.2post1-0 
   1.1.11dev1-0 
   1.1.11a1-0   
   1.1.11rc1-0  
   1.1.11-0     
   1.1.11post1-0
   1.1post1-0   
```

**Comment by ukoethe** [comment]
The rule `1.1 < 1.1.0` has the big advantage that different filenames always lead to different version numbers (including build numbers and build strings).

**Comment by asmeurer** [comment]
I think 1.1 and 1.1.0 is another instance of self-consistency. It wouldn't really make sense for a package to have both. So I wouldn't worry too much about what conda does there. Either == or < sounds fine. Note that two versions being equal is handled just fine by conda (if the solver can't find a single newest version, it will print a warning to the user).

**Comment by ukoethe** [comment]
Since `SimpleVersionOrder` appears to agree with `verlib.NormalizedVersion` on conforming version strings, I phased out the latter entirely (and renamed `SimpleVersionOrder  => VersionOrder`).

**Comment by ukoethe** [comment]
I finally added support for local versions separated by `+` since they are needed in channel `jakirkham`.

BTW, the current code implements the convention `1.1 == 1.1.0` because it was already assumed in your existing tests.

**Comment by asmeurer** [comment]
Where does PEP 440 fit into this? Does it support everything it does?

**Comment by ukoethe** [comment]
It certainly supports most of it, but I didn't check every detail. Is there a test suite for PEP 440 where one can get examples for the corner cases?

**Comment by asmeurer** [comment]
I think https://github.com/pypa/packaging/blob/master/tests/test_version.py is the test suite of the "official" implementation.

**Comment by ukoethe** [comment]
There are indeed some differences to PEP 440 because it defines a number of equivalences that this PR doesn't define or defines differently:

PEP 440                                          |    this PR
-----------------------------------------------|---------------------------------------------------------
`a == alpha`, `b == beta`, `c == rc`  |   these strings are all different
`1.2.a3 == 1.2a3`                             |  `1.2.a3 == 1.2.0a3`

These differences have no consequences when versioning is self-consistent. For completeness, here is the order of `VERSIONS` from https://github.com/pypa/packaging/blob/master/tests/test_version.py for both rules:

PEP 440  |  this PR
-------------|-----------
`1.0.dev456`            |  (`1.0dev456` would go here)
`1.0a1`                 |  `1.0a1`
`1.0a2.dev456`          |  `1.0a2.dev456`
`1.0a12.dev456`         |  `1.0a12.dev456`
`1.0a12`                |  `1.0a12`
`1.0b1.dev456`          |  `1.0b1.dev456`
`1.0b2`                 |  `1.0b2`
`1.0b2.post345.dev456`  |  `1.0b2.post345.dev456`
`1.0b2.post345`         |  `1.0b2.post345`
`1.0c1.dev456`          |  `1.0c1.dev456`
`1.0c1`                 |  `1.0c1`
`1.0rc2`                |
`1.0c3`                 |  `1.0c3`
                        |  `1.0rc2` (`rc > c`)
                        |  `1.0.dev456` (`== 1.0.0dev456`)
`1.0`                   |  `1.0` (`== 1.0.0`)
`1.0.post456.dev34`     |  `1.0.post456.dev34` (`== 1.0.0post456.0dev34`)
`1.0.post456`           |  `1.0.post456`
`1.1.dev1`              |  `1.1.dev1`
                        |  `1.2.r32+123456`
                        |  `1.2.rev33+123456` (`== 1.2.0rev33+...`)
`1.2+123abc`            |  `1.2+123abc` (`== 1.2.0+... > 1.2.0rev33+...`)
`1.2+123abc456`         |  `1.2+123abc456`
`1.2+abc`               |  `1.2+abc`
`1.2+abc123`            |  `1.2+abc123`
`1.2+abc123def`         |  `1.2+abc123def`
`1.2+1234.abc`          |  `1.2+1234.abc`
`1.2+123456`            |  `1.2+123456`
`1.2.r32+123456`        |
`1.2.rev33+123456`      |

**Comment by asmeurer** [comment]
You can remove the rc -> .dev99999 hack now, right?

**Comment by asmeurer** [comment]
If those really are the only differences between this and PEP 440 that seems fine. It's probably not hard to make them exactly the same, but I'm not too worried about issues that only come up with versions that aren't self-consistant.

**Comment by asmeurer** [comment]
And just to clarify, this fixes https://github.com/conda/conda/issues/915 right? I didn't see any tests for invalid versions like 14.3.1.post26.g9d75ca2.

**Comment by ukoethe** [comment]
> You can remove the rc -> .dev99999 hack now, right? 

I had already removed it in https://github.com/ilastik/conda/commit/b303df82d06349c6b2c3536cc23fc1319c1b3c9d. Regarding correctness, all I can say is that the Travis tests succeed. (BTW, the AppVeyor tests seem to be broken - they always stall while unpacking Miniconda.)

> And just to clarify, this fixes #915 right? I didn't see any tests for invalid versions like 14.3.1.post26.g9d75ca2.

I just added this case to the test suite, and it works. This was to be expected, because invalid versions no longer exist (except for obvious errors). `14.3.1.post26.g9d75ca2` is parsed into `[[0], [14], [3], [1], [0, inf, 26], [0, 'g', 9, 'd', 75, 'ca', 2]]` (the leading 0 is the epoch) and can be compared by the rules I describe in detail in the doc string of `VersionOrder`.

**Comment by asmeurer** [comment]
Oh I didn't notice that it was removed when I looked at the diff but I see it now.

**Comment by asmeurer** [comment]
OK, let's give this a go then.

**Comment by ukoethe** [comment]
Yeah!

**Comment by ukoethe** [comment]
Please have a look at the follow-up PR https://github.com/conda/conda/pull/1644

**Comment by asmeurer** [comment]
I just found a pretty serious issue with this branch. Underscores are not handled correctly. This means that all the packages in the R channel are not being ordered right. A basic example is:

```
In [6]: VersionOrder('0.17_3') > VersionOrder('0.17')
Out[6]: False
```

We have to use underscores in the r channel because the R packages use dashes, but dashes are not allowed in conda versions.  An underscore should be treated the same as a `.` for ordering purposes. 

Also, in the future, can you be more careful about removing trailing whitespace from your files before committing?

**Comment by ukoethe** [comment]
>An underscore should be treated the same as a . for ordering purposes.

So why don't you just use . if they are the same anyway? The underscore character is very precious (the only non-letter treated as a letter in virtually all languages) and shouldn't be wasted for redundant functionality. FWIW, since the R language uses $ as separator between objects and members (foo.bar in Python becomes foo$bar in R), this would be a much better choice if an additional separator were really needed.

**Comment by ukoethe** [comment]
... of course, $ doesn't easily work in filenames.

**Comment by asmeurer** [comment]
I don't know why R packages use a dash in their version numbers, but they do. I wanted to keep the numbers distinct and readable as their source versions, hence I replaced dashes with underscores. 

I think that since conda versions don't allow dashes, which would be the most ideal for many use-cases, the underscore is the best replacement. And at any rate, it's already in wide use (not just from the r channel either, as I've recommended it to other people as well).

**Comment by ukoethe** [comment]
OK, turning `_` into a separator is easy. However, it kills my suggested solution for openssl to replace `1.0.2` with `1.0.2_`. To solve this problem, one could allow string components to start with `@`, to the effect that these strings are considered greater than numbers, i.e.

    1.2.3dev4 < 1.2.3a1 < 1.2.3 < 1.2.3@a1 < 1.2.3post1

openssl versions would thus be replaced according to `1.0.2a  =>  1.0.2@a`. The letter `@` (meaning 'after' in this context) is one of the few characters in the ASCII set that can be used here without creating conflicts in either version string analysis or the shell (alternatives are `%`, `~` and perhaps `$`; I also considered `^` but it can't be used because it is the DOS shell's escape character). This proposal is also compatible with PEP 440.

**Comment by ukoethe** [comment]
Well, a simpler work-around for openssl (already supported by the current design) would be

    1.0.1  <  1.0.1post.a  <  1.0.1post.b  <  1.0.2

I like this better than the proposal "translate openssl's j, k etc into .post0, .post1 " from https://github.com/conda/conda/issues/1107#issuecomment-78780745, because than you'll never be sure if `1.0.1post1` means `a` or `b` without looking it up.

**Comment by ukoethe** [comment]
See https://github.com/conda/conda/pull/1652

**Pull request merged**
