### PR TITLE
remove encoding pragma (not needed in Python 3)

### PR DESCRIPTION
**Pull request by dholth**
### Description

Configure pre-commit to remove encoding-pragma; utf-8 is default in Python 3

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Review by jezdez — APPROVED** [review]
I think this is a good idea, but I'd be interested what @conda-core thinks about it?

**Comment by kenodegard** [comment]
Looks good to me, will need to run pre-commit CI before merging

**Comment by dholth** [comment]
I was surprised to see the pragma magically appear on a new Python file, then I found the existing "add the pragma" setting.

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Review by jezdez — APPROVED** [review]

**Comment by kenodegard** [comment]
We should remove the pre-commit pragma hook now

**Comment by dbast** [comment]
maybe we could even activate the pyupgrade pre-commit hook (as in conda-build) and get rid of more, like the future imports etc, it also would have removed the encoding pragma.

**Comment by jezdez** [comment]
> maybe we could even activate the pyupgrade pre-commit hook (as in conda-build) and get rid of more, like the future imports etc, it also would have removed the encoding pragma.

Yeah, most likely, would it only run pyupgrade on changed files in CI?

**Comment by kenodegard** [comment]
https://github.com/conda/conda/pull/11903

**Pull request merged**
