### PR TITLE
reduce redundant sys call during file copying

### PR DESCRIPTION
**Pull request by kalefranz**
supersedes #6410
target is 4.4.x

### CODE REVIEW

**Comment by kalefranz** [comment]
Single error in `main test py36` is 502 BAD GATEWAY.

**Comment by nouiz** [comment]
That kind of error is probably a temporary error. Can you try to just restart that test run?

**Comment by kalefranz** [comment]
Definitely just temporary. Was just waiting in appveyor to finish before merging.

**Comment by nouiz** [comment]
thanks for the quick review/merge. Do you have time to rapidly check this issues from me? https://github.com/conda/conda/issues/6403

Mostly, I'm not able to have a good development environment for conda, so it make it harder for me to work on it.

**Pull request merged**
