### PR TITLE
Expose kernel version as `__linux` virtual pkg version

### PR DESCRIPTION
**Pull request by chenghlee**

### CODE REVIEW

**Comment by chenghlee** [comment]
@BastianZim: extended your PR to expose the kernel version as the `__linux` virtual package's version. Does that work for you?

**Comment by BastianZim** [comment]
@chenghlee Yes, of course. I just need the package to be available for restricting noarch packages. Thanks for asking!

**Comment by BastianZim** [comment]
By the way, do you already have an ETA for 4.10?

**Comment by chenghlee** [comment]
> By the way, do you already have an ETA for 4.10?

Sometime around the end of March; early April at the latest.

**Review by dbast — APPROVED** [review]

**Pull request merged**
