### PR TITLE
Remove unnecessary conditional

### PR DESCRIPTION
**Pull request by yuvipanda**
Both the 'if' and 'else' sides seem to be doing the same thing

### CODE REVIEW

**Comment by yuvipanda** [comment]
I've signed that form now I think

**Comment by kenodegard** [comment]
@anaconda-issue-bot check

**Review by beeankha — APPROVED** [review]

**Comment by beeankha** [comment]
Thank you for this contribution, @yuvipanda !

**Comment by yuvipanda** [comment]
Thank you for the merge, @beeankha!

**Pull request merged**
