### PR TITLE
Remove vendored six.py and dependencies on it.

### PR DESCRIPTION
**Pull request by erykoff**
### Description

This is an attempt to remove the vendored six.py and update remaining compatibility dependencies on it.

The tricky thing is that some of the six functions are exported for use in (e.g.) conda-build:  https://github.com/conda/conda-build/blob/main/conda_build/conda_interface.py#L71-L72 I have updated these for py3 only, but this may not be the best option; feedback welcome.  It may be worthwhile to add a deprecation to exported `iteritems()`?

Also, I would not be shocked if the first run through CI with this PR doesn't work.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation?

### CODE REVIEW

**Comment by dholth** [comment]
Thank you!

**Comment by erykoff** [comment]
Any idea on the failed macos test?

**Comment by dholth** [comment]
We'll be able to take a look Monday.

**Review by travishathaway — APPROVED** [review]

**Review by dholth — APPROVED** [review]
Thanks!

**Pull request merged**
