### PR TITLE
Fix path_to_url "string index out of range" error

### PR DESCRIPTION
**Pull request by yuvalreches**

### CODE REVIEW

**Comment by mingwandroid** [comment]
Can you explain why it is valid to pass a PATH of length 0?

**Comment by yuvalreches** [comment]
> Can you explain why it is valid to pass a PATH of length 0?

@mingwandroid it is actually not possible :)
The scenario we are facing is having the path to be `/`, length 1, then we hit `IndexError: string index out of range`
This is obviously as `path[1]` doesn't exist, only `path[0]` does exist.

**Comment by msarahan** [comment]
@yuvalreches has signed the CLA.  That should not block this PR.  The Py27 fail is my fault from another PR.  This PR is green.

**Comment by msarahan** [comment]
Thanks @yuvalreches

**Pull request merged**
