### PR TITLE
enable binary prefix replacement on windows

### PR DESCRIPTION
**Pull request by kalefranz**
@msarahan putting this in 4.2.  Any objections with the last commit?

supersedes #3224

### CODE REVIEW

**Comment by msarahan** [comment]
Your add-on is fine.  Any reason why this can't go into 4.1, though?  I thought we agreed on that in Thursday's meeting.  If people start producing packages with these pip exe's, you are essentially requiring that they have conda 4.2 to correctly install those packages.  Depending on how well this canary process works, that may leave people in a hard place.

CC @csoja

**Comment by kalefranz** [comment]
Because this is a new feature, not a bug fix.  "add support for" kind of gives that away.  Conda 4.2 is available right now as a canary release.  This is actually going in 4.2.2.  I'm adding this to 4.2 because it's not out of canary yet, and there's more than two weeks of canary left for 4.2.

**Comment by msarahan** [comment]
OK.  I don't appreciate your snark, but I respect your opinion, and hope that this decision works out OK for our users.

**Comment by kalefranz** [comment]
There wasn't any snark intended.  Sorry if what I said came across that way.  We can chat in person or on video if you'd like.

**Comment by minrk** [comment]
When can we expect this that ~all conda users have a release with this? As I understand, I'm basically blocked on updating any conda-forge packages until this propagates, due to https://github.com/conda/conda/pull/3224

**Comment by kalefranz** [comment]
@minrk For conda-forge users, since conda-forge is now packaging conda itself, the answer is whenever the feedstock is updated. https://github.com/conda-forge/conda-feedstock

I'd have no objections to the conda-forge community updating before canary is released into defaults.  For 4.2 (currently at 4.2.3), that date is Aug 28.

**Comment by kalefranz** [comment]
@msarahan Thoughts?

**Comment by msarahan** [comment]
We (@pelson, @jakirkham, @ericdill and I) discussed this at the Conda-forge meeting on Friday.  We are OK with it, but as it is still considered a pre-release (based on the github designation), we would also put it into some kind of pre-release label on the conda-forge channel.  There is currently no standard pre-release methodology, though.  In the meeting, no one had strong enough interest in pre-releases to author a proposal for this.  If anyone here wants to author that proposal, conda-forge welcomes it.  We have small precedent in https://github.com/conda-forge/python-feedstock/pull/45, but agreed that some accepted proposal needs to precede any further pre-release packaging.

CC @pelson @jakirkham @ericdill

**Comment by kalefranz** [comment]
Ok. Up to you guys. The pre-release tag for 4.2.x will come off the latest 4.2.x release on Aug 28, when it will also be made available in defaults.

**Pull request merged**
