### PR TITLE
Use `_ENVEXE` to init/activate devenv

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

When adding new dependencies (e.g. pluggy) the base install is unable to invoke `init` on the devenv. Unfortunately, this means our devenv will no longer be nicely labeled when activated and is instead [mis]labeled as base.

<table>
<tr>
<th>Previously</th>
<th>Now</th>
</tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

Resolves issues @beeankha identified in #11435

### Checklist - did you ...

- [X] ~Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/master/news/TEMPLATE)) for the next release's release notes?~
     
- [X] ~Add / update necessary tests?~
- [X] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by FFY00** [comment]
> When adding new dependencies (e.g. pluggy) the base install is unable to invoke `init` on the devenv.

Can you elaborate on this?

**Comment by kenodegard** [comment]
> > When adding new dependencies (e.g. pluggy) the base install is unable to invoke `init` on the devenv.
> 
> Can you elaborate on this?

This is all coming from how we've engineered the `devenv` for local testing purposes where we are initializing non-base environments and treating them as the base environment. Previously we were effectively doing the following:

```bash
$ cd <conda source code dir>
$ bash miniconda.sh -bfp ./devenv/$(uname) > /dev/null
$ ./devenv/$(uname)/bin/conda create -n devenv --file ./tests/requirements.txt
$ eval "$(./devenv/$(uname)/bin/conda init --dev bash)" > /dev/null
$ ./devenv/$(uname)/bin/conda activate devenv
(devenv) $
```

Since we are invoking from the source code dir we will attempt the `import pluggy` before the `devenv` is activated. There's two fixes for this:
1. run `conda init` using `devenv`'s `conda`, this is the current proposal here and keeps everything correctly siloed
2. in addition to installing `./tests/requirements.txt` into `devenv` also install it into the the `base` env, this is messier as we're "hacking" the base env

**Comment by FFY00** [comment]
Okay. We could make the import soft-fail if you think that is a better approach, there is no technical reason why we couldn't do that.

**Comment by kenodegard** [comment]
Naw let's leave the code clean, this `devenv` is just a hack for easier local testing.

**Review by beeankha — APPROVED** [review]
Thanks for looking into this issue and making this change, @kenodegard !

**Pull request merged**
