### PR TITLE
Add virtual packages to be considered in the solver

### LINKED ISSUE #9896: cudatoolkit run constrain on __cuda not used for solve
## Current Behavior

Recently we added a repodata patch to `cudatoolkit` to constrain its version based on the `__cuda` virtual package's version ( https://github.com/AnacondaRecipes/repodata-hotfixes/pull/81 ) (IOW the max version of CUDA the GPU driver will support). However it seems this isn't respected when installing `cudatoolkit`. Instead one needs to prod `conda` a bit to get it to consider `__cuda`.

### Steps to Reproduce

Running the following does not take into account the `__cuda` version supported.

<details>
<summary>

```
conda create -d -n test_cuda cudatoolkit
```

</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/miniforge/envs/test_cuda

  added / updated specs:
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    cudatoolkit-10.2.89        |       hfd86e86_0       539.3 MB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         4.0 MB
    ------------------------------------------------------------
                                           Total:       551.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.2.89-hfd86e86_0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0



DryRunExit: Dry run. Exiting.
```

</details>

However adding `__cuda` to the install spec does work.

<details>
<summary>

```
conda create -d -n test_cuda __cuda cudatoolkit
```

</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/miniforge/envs/test_cuda

  added / updated specs:
    - __cuda
    - cudatoolkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.1.243       |       h6bb024c_0       513.2 MB
    ------------------------------------------------------------
                                           Total:       513.2 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.1.243-h6bb024c_0



DryRunExit: Dry run. Exiting.
```

</details>

Interestingly we also observe compiler runtime packages installed in the first case, but not in the second. Unclear on why that happens, but may also be related to the same issue.

## Expected Behavior

When installing `cudatoolkit` or really anything that depends on `cudatoolkit`, `__cuda` should be factored into the solve.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /datasets/jkirkham/miniconda
            shell level : 1
       user config file : /home/nfs/jkirkham/.condarc
 populated config files : /home/nfs/jkirkham/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.27
       base environment : /datasets/jkirkham/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
          package cache : /datasets/jkirkham/miniconda/pkgs
                          /home/nfs/jkirkham/.conda/pkgs
       envs directories : /datasets/jkirkham/miniconda/envs
                          /home/nfs/jkirkham/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-76-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 10124:10004
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/nfs/jkirkham/.condarc <==
channels:
  - conda-forge
  - defaults
  - nvidia
show_channel_urls: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /datasets/jkirkham/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
beautifulsoup4            4.9.0            py37hc8dfbb8_0    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.19.2           py37hc8dfbb8_0    conda-forge
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.9.2                he1b5a44_0    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.7.0            py37h8f50634_1    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
ripgrep                   12.0.1               h516909a_1    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
soupsieve                 1.9.4            py37hc8dfbb8_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.45.0             pyh9f0ad1d_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge
```
</p></details>

### PR DESCRIPTION
**Pull request by ericpre**
This is an attempt to be fix #9896 and this issue should also applied to all virtual packages. I don't know if this is the right approach but adding virtual packages to `specs_map` seems to work!

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Eric! 😀

cc @beckermr

**Comment by beckermr** [comment]
Thanks @jakirkham!

**Comment by ericpre** [comment]
Two tests are failing because of a change in the reported error message changed and is now different from the expected one. Once it is confirmed that the approach is right, I can look into fixing it.

**Comment by beckermr** [comment]
@jjhelmus @kalefranz @chenghlee any comments here?

**Comment by mcg1969** [comment]
This looks good but it strikes me we should have a test for this.

**Comment by ericpre** [comment]
I added a test and adapted two other tests. Appveyor is having hiccups (tests are passing fine but appveyor says `Command exited with code 7`!) and other than it should be good now.

**Comment by jakirkham** [comment]
Would it be possible to get another review of this?

**Pull request merged**
