### PR TITLE
resolve #5081 make pinned packages optional dependencies

### LINKED ISSUE #5081: Make pinned packages optional/constrained dependencies
In the conda 4.3 feature branch, make the `get_pinned_specs()` function in `conda/plan.py` return `MatchSpec` objects with the `optional=True` flag.

Make sure (by writing extra unit tests) that the `conda.cli.common.spec_from_line()` function is both working correctly and being used correctly.

Package pinning configuration was recently implemented within condarc files via https://github.com/conda/conda/pull/4921/files.  Reviewing that PR would be a good place to start.

### PR DESCRIPTION
**Pull request by stefanseefeld**
resolves #5081 

Add a failing test to measure progress in implementing support for optional pinning in 4.4.x

### CODE REVIEW

**Comment by kalefranz** [comment]
I think the windows test failures are somehow related to https://github.com/conda/conda/issues/5301#issuecomment-302212550.  For reference, on win-64 the repodata in pkgs/free looks something like

```
    "openssl-1.0.2k-vc9_0.tar.bz2": {
      "build": "vc9_0",
      "build_number": 0,
      "date": "2017-01-26",
      "depends": [],
      "features": "vc9",
      "license": "Apache-style",
      "license_family": "Apache",
      "md5": "7ef8a05a562aa659ce39c3566eecb2b3",
      "name": "openssl",
      "size": 4596891,
      "version": "1.0.2k"
    },

    "python-2.7.9-1.tar.bz2": {
      "build": "1",
      "build_number": 1,
      "date": "2014-12-18",
      "depends": [],
      "license": "PSF",
      "md5": "2d923491e9179bc0c6a4b272c4759ccb",
      "name": "python",
      "size": 19878836,
      "space_anchor": true,
      "track_features": "vc9",
      "version": "2.7.9"
    },
```

This problem is orthogonal to what's being addressed in the current PR.  I'm fine with either solution of (1) changing the package hierarchy used in the test, or (2) just marking the test xfail on windows.

**Comment by stefanseefeld** [comment]
(I'm trying to locate the failure in the very noisy output on AppVeyor. I assume it's https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda/build/1.0.4116/job/gqlku08blh6uwdhp#L816 ?)
I'm not quite sure what specifically in the above repodata you cite would cause this. Can you elaborate ? I'm fine with an `xfail` so long as we clearly comment so we'll remember in the future why we xfailed this, and can remove it once the problem is properly addressed (such as by changing to a test-only channel).

**Comment by kalefranz** [comment]
I always set `strict=True` as an xfail parameter.

Features are really confusing.  https://github.com/ContinuumIO/anaconda-issues/issues/1760 will resolve the test failure on windows.

**Comment by kalefranz** [comment]
> I'm trying to locate the failure in the very noisy output on AppVeyor

Debug output is pretty chatty, and trace even more so.  There's just a lot happening.  It's all useful needed at different points in time.

Easiest way to find what you were looking for is just do a search/find on the page and look for "traceback".

**Comment by kalefranz** [comment]
Actually, the debug output has gotten a LOT more chatty recently, so I take back a bit of what I said.  There are a lot of warnings in the debug output all the sudden.  I don't know if it has to do with recent changes in logging setup, or if there's something going on with a new release of a dependency somewhere.

**Comment by stefanseefeld** [comment]
ah, right, so Python is being pulled in as the feature-provider on Windows. Yeah, I'll adorn this test with an xfail on Windows.

**Comment by mbargull** [comment]
(Sorry, off topic, re logging:
>There are a lot of warnings in the debug output all the sudden. I don't know if it has to do with recent changes in logging setup

Probably those warnings were previously suppressed since `initialize_root_logger` had been implicitly called and set root's level to `ERROR` (from the default `WARNING`). The warnings stem from outside `'conda'`-logger domain, i.e., `'tests'`, and thus get handled by the root logger.
So now everything (with some exceptions until #5405 is ported to `4.4.x`) works as intended and those warnings are visible and can be fixed 😄 (or, as a last resort, if they're somehow not fixable, they may explicitly suppressed via filters or setting non-root logger level).)

**Pull request merged**
