### PR TITLE
Add flake8-variables-names to pre-commit

### PR DESCRIPTION
**Pull request by kenodegard**
### Description

Since we don't like having single char variables let's add a linter for that!

FYI since this isn't related to `conda` itself I haven't included a news file, let me know if you feel differently!

cc @jezdez 

### Checklist - did you ...

- [X] ~Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/master/news/TEMPLATE)) for the next release's release notes?~
     
- [X] ~Add / update necessary tests?~
- [X] ~Add / update outdated documentation?~

### CODE REVIEW

**Comment by kenodegard** [comment]
Grrr, I keep forgetting that Pre-Commit CI runs flake8 on the entire codebase. In that case idk if we want this ATM...

**Comment by jezdez** [comment]
> Grrr, I keep forgetting that Pre-Commit CI runs flake8 on the entire codebase. In that case idk if we want this ATM...

So this checker makes me really happy, and think it's okay for pre-commmit to run these for all of the codebase. Might as well just fix the errors?

**Review by jezdez — APPROVED** [review]
Let's fix the found errors and never look back. 👍🏻

**Comment by kenodegard** [comment]
Between @jezdez and myself we have now attempted to step through this a few times and each time we've been overwhelmed by the number of modifications necessary to satisfy flake8-variables-names.

We've decided to not add this check for the time being and will rather rely on code reviews to gradually enforce this desired policy.

**Pull request closed without merging**
