### PR TITLE
Test fetch

### PR DESCRIPTION
**Pull request by HugoTian**
add test cases for fetch module

### CODE REVIEW

**Comment by kalefranz** [comment]
Hey Tian I'm concerned about the amount of time a couple of these tests take.  I haven't reviewed the code yet though.  If you look at the timing, 

84.12s call     tests/test_fetch.py::TestFetchRepoData::test_fetchrepodate_connectionerror
84.07s call     tests/test_fetch.py::TestDownload::test_download_connectionerro

**Comment by kalefranz** [comment]
Still too long :(

https://travis-ci.org/conda/conda/jobs/144257036#L890

    =========================== slowest 5 test durations ===========================
    509.03s call     tests/test_fetch.py::TestFetchRepoData::test_fetchrepodate_connectionerror
    508.99s call     tests/test_fetch.py::TestDownload::test_download_connectionerror
    39.14s call     tests/test_cli.py::TestJson::test_search
    32.31s call     tests/test_create.py::IntegrationTests::test_install_features
    25.71s call     tests/test_create.py::IntegrationTests::test_create_install_update_remove

**Comment by kalefranz** [comment]
@HugoTian Cancelling Travis-CI again.  We can't have these two tests taking almost 10 minutes each.  Just not worth it.

https://travis-ci.org/conda/conda/jobs/144494984#L889

    =========================== slowest 5 test durations ===========================
    508.99s call     tests/test_fetch.py::TestDownload::test_download_connectionerror
    508.93s call     tests/test_fetch.py::TestFetchRepoData::test_fetchrepodate_connectionerror
    41.21s call     tests/test_cli.py::TestJson::test_search
    29.46s call     tests/test_create.py::IntegrationTests::test_install_features
    24.75s call     tests/test_create.py::IntegrationTests::test_create_install_update_remove
    ================= 32 tests deselected by "-m 'not installed'" ==================

**Comment by HugoTian** [comment]
@kalefranz , I actually do not know why it takes so long on travis CI. If I test on my machine, it will finish in 3 seconds.  Generally, I create a download from a not routable ip 10.0.0.0, so that it will leads to connection error. Maybe I will try other methods

**Pull request merged**
