### PR TITLE
Throw away stderr when calling pip list

### PR DESCRIPTION
**Pull request by groutr**
This causes weird console coloring issues on windows.
We could redirect it to STDOUT and just ignore when we parse it, or we can just throw it away from the beginning.

### CODE REVIEW

**Comment by asmeurer** [comment]
But this will mask any legitimate errors with pip.

**Comment by groutr** [comment]
If there is a better way to fix this, let me know.
The other solution, of redirecting stderr to stdout and then ignoring this specific message would allow pip to still raise errors it encounters when actually doing the task of listing installed packages.

**Comment by asmeurer** [comment]
We should figure out what is causing the color issue.

**Comment by asmeurer** [comment]
We should call pip with the `--disable-pip-version-check` flag (with a fallback for older versions of pip that don't have that flag).

**Pull request merged**
