### PR TITLE
Avoid warning when environment variables have the same value of OS ones

### PR DESCRIPTION
**Pull request by dariocurr**
### Description

I believe that the environment variable overwriting WARNING should be printed only if the environment variables are really different from those specified in the OS

Note: another option would be to still send the message, but on `stdout` and not on `stderr`.

I have encountered this behavior dealing with the python extension of vscode, which as soon as has a message on `stderr`, forwards it, making itself unusable

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes? No since I didn't open an issue and I found in the folder just issue-based news names
     
- [x] Add / update necessary tests?
- [x] Add / update outdated documentation? No since I didn't find any documentation about this behaviour, just the printed log

### CODE REVIEW

**Comment by dariocurr** [comment]
> We require contributors to sign our [Contributor License Agreement](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement) and we don't have one on file for @dariocurr.
> 
> In order for us to review and merge your code, please e-sign the [Contributor License Agreement PDF](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement). We then need to manually verify your signature. We will ping the bot to refresh the PR status when we have confirmed your signature.

Done It

**Comment by beeankha** [comment]
@anaconda-issue-bot check

**Review by dholth — DISMISSED** [review]

**Comment by beeankha** [comment]
@conda-bot check

**Comment by beeankha** [comment]
(there's a ton of linter error fixes included in my "fix test failures" commit, which is why the `test_activate.py` diff looks much larger now) 

@dariocurr I was going to suggest these as changes for you to make, but the line ranges were outside of what you had already changed on the PR so I decided to directly make these edits and then push them myself instead. Let's see how the CI tests do after this!

**Comment by dariocurr** [comment]
Perfect, thank you. Ready to go?

**Review by dholth — APPROVED** [review]

**Review by travishathaway — APPROVED** [review]

**Comment by dariocurr** [comment]
Thank you @beeankha! It's a pleasure!

**Comment by dariocurr** [comment]
I checked and this hasn't been released yet. We at [buildnn](https://github.com/buildnn) would love to use it. When do you plan to release it?

**Pull request merged**
