### PR TITLE
(DNM) Use conda-libmamba-solver rc for libmamba v2

### PR DESCRIPTION
**Pull request by jaimergp**
### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

Checking benchmarks to shed light on the slowdowns at https://github.com/conda/conda/pull/11612

### CODE REVIEW

**Comment by jaimergp** [comment]
I'm taking a look here. All the regressions are happening in the [`tests_subcommands`](https://codspeed.io/conda/conda/branches/jaimergp:benchmark-libmamba-v2) module. Other benchmarked solver tests like [`test_solve_1`](https://codspeed.io/conda/conda/branches/jaimergp:benchmark-libmamba-v2) do not show any regression.

Regardless, I took a look with different profilers, and finally found that `pyinstrument` is able to pin-point the difference.

Once installed in your environment (`conda install pyinstrument`), you can do `pyinstrument -m conda create --dry-run ca-certificates --offline` to obtain results like the ones below. I'm running this on a Macbook M1, which means the repodata is `osx-arm64`. On `linux-64` the repodata is bigger so it might show even bigger differences.

For v1:

```
v1

  _     ._   __/__   _ _  _  _ _/_   Recorded: 11:36:45  Samples:  340
 /_//_/// /_\ / //_// / //_'/ //     Duration: 1.928     CPU time: 0.859
/   _/                      v5.0.0

Program: conda create --dry-run ca-certificates --offline

1.922 <module>  conda/__main__.py:1
└─ 1.922 main  conda/cli/main.py:91
      [26 frames hidden]  conda, requests, urllib3, importlib
         1.589 LibMambaSolver.solve_for_diff  conda/core/solve.py:183
         └─ 1.589 LibMambaSolver.solve_final_state  conda_libmamba_solver/solver.py:135
            ├─ 0.704 SolverInputState.__init__  conda_libmamba_solver/state.py:165
            │  └─ 0.703 inner  conda/deprecations.py:114
            │        [10 frames hidden]  conda, multiprocessing, selectors
            │           0.673 poll.poll  <built-in>
            ├─ 0.615 LibMambaIndexHelper.__init__  conda_libmamba_solver/index.py:114
            │  └─ 0.596 LibMambaIndexHelper._load_channels  conda_libmamba_solver/index.py:303
            │     └─ 0.589 LibMambaIndexHelper._json_path_to_repo_info  conda_libmamba_solver/index.py:258
            ├─ 0.183 Spinner.__exit__  conda/common/io.py:455
            │     [4 frames hidden]  conda, threading, <built-in>
            ├─ 0.057 LibMambaSolver._notify_conda_outdated  conda_libmamba_solver/solver.py:1047
            │  └─ 0.041 LibMambaIndexHelper.search  conda_libmamba_solver/index.py:381
            │     └─ 0.041 PyCapsule.find  <built-in>
            └─ 0.028 LibMambaSolver._solving_loop  conda_libmamba_solver/solver.py:318
               └─ 0.027 LibMambaSolver._solve_attempt  conda_libmamba_solver/solver.py:394
         0.064 import_module  importlib/__init__.py:73
         └─ 0.062 <module>  conda_libmamba_solver/__init__.py:1
            └─ 0.061 <module>  conda_libmamba_solver/solver.py:1
               └─ 0.034 <module>  libmambapy/__init__.py:1
                  └─ 0.033 create_dynamic  <built-in>

To view this report with different options, run:
    pyinstrument --load-prev 2024-11-16T11-36-45 [options]
```

For v2:

```
v2

  _     ._   __/__   _ _  _  _ _/_   Recorded: 11:37:43  Samples:  341
 /_//_/// /_\ / //_// / //_'/ //     Duration: 2.559     CPU time: 1.962
/   _/                      v5.0.0

Program: conda create --dry-run ca-certificates --offline

2.555 <module>  conda/__main__.py:1
└─ 2.555 main  conda/cli/main.py:91
      [24 frames hidden]  conda, importlib, requests, urllib3
         2.180 LibMambaSolver.solve_for_diff  conda/core/solve.py:183
         └─ 2.180 LibMambaSolver.solve_final_state  conda_libmamba_solver/solver.py:131
            ├─ 1.798 decorated  conda/common/io.py:83
            │  ├─ 1.769 LibMambaSolver._collect_all_metadata  conda_libmamba_solver/solver.py:258
            │  │  └─ 1.769 LibMambaIndexHelper.__init__  conda_libmamba_solver/index.py:155
            │  │     └─ 1.768 LibMambaIndexHelper._load_channels  conda_libmamba_solver/index.py:268
            │  │        └─ 1.762 LibMambaIndexHelper._load_repo_info_from_json_path  conda_libmamba_solver/index.py:368
            │  │           └─ 1.762 PyCapsule.add_repo_from_repodata_json  <built-in>
            │  └─ 0.029 LibMambaSolver._solving_loop  conda_libmamba_solver/solver.py:297
            │     └─ 0.029 LibMambaSolver._solve_attempt  conda_libmamba_solver/solver.py:345
            ├─ 0.181 Spinner.__exit__  conda/common/io.py:455
            │     [4 frames hidden]  conda, threading, <built-in>
            ├─ 0.167 SolverInputState.__init__  conda_libmamba_solver/state.py:159
            │  └─ 0.166 inner  conda/deprecations.py:114
            │        [11 frames hidden]  conda, multiprocessing, selectors, <b...
            └─ 0.032 LibMambaSolver._notify_conda_outdated  conda_libmamba_solver/solver.py:971
         0.079 import_module  importlib/__init__.py:73
         └─ 0.077 <module>  conda_libmamba_solver/plugin.py:1
            └─ 0.056 <module>  conda_libmamba_solver/repoquery.py:1
               └─ 0.038 <module>  libmambapy/__init__.py:1
                     [2 frames hidden]  libmambapy, <built-in>

To view this report with different options, run:
    pyinstrument --load-prev 2024-11-16T11-37-43 [options]
```

If you compare them side by side, you can see that the solving steps (`_solving_loop`) simply takes 0.03 seconds in both cases. However, the repodata loading steps (`LibMambaIndexHelper.__init__`) balloon from 0.6s to 1.7s. We are loading _offline_ for pre-cached JSONs, yet it takes longer for libmamba v2. This uncovered a bug in conda-libmamba-solver where we were not using SOLV files in offline mode, which I'll fix now.

However, the benchmarks do not run in offline mode, so there must be something else going on 🤔 For now let's see if the proposed fix alleviates the benchmark concerns.

**Comment by jaimergp** [comment]
I tried again but with `--platform=linux-64` so the repodata loading times are more evident: 

v1:

```

  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:23:36  Samples:  320
 /_//_/// /_\ / //_// / //_'/ //     Duration: 2.564     CPU time: 1.778
/   _/                      v5.0.0

Program: conda create --dry-run --platform linux-64 ca-certificates

2.559 <module>  conda/__main__.py:1
└─ 2.558 main  conda/cli/main.py:91
      [23 frames hidden]  conda, requests, urllib3, importlib
         2.240 LibMambaSolver.solve_for_diff  conda/core/solve.py:183
         └─ 2.240 LibMambaSolver.solve_final_state  conda_libmamba_solver/solver.py:135
            ├─ 1.828 LibMambaIndexHelper.__init__  conda_libmamba_solver/index.py:114
            │  └─ 1.807 LibMambaIndexHelper._load_channels  conda_libmamba_solver/index.py:303
            │     ├─ 1.211 LibMambaIndexHelper._json_path_to_repo_info  conda_libmamba_solver/index.py:258
            │     └─ 0.595 result_iterator  concurrent/futures/_base.py:612
            │           [3 frames hidden]  concurrent, threading
            │              0.595 lock.acquire  <built-in>
            ├─ 0.135 SolverInputState.__init__  conda_libmamba_solver/state.py:165
            │  └─ 0.135 inner  conda/deprecations.py:114
            │        [11 frames hidden]  conda, multiprocessing, selectors, <b...
            ├─ 0.113 Spinner.__exit__  conda/common/io.py:455
            │     [4 frames hidden]  conda, threading, <built-in>
            ├─ 0.095 LibMambaSolver._solving_loop  conda_libmamba_solver/solver.py:318
            │  └─ 0.094 LibMambaSolver._solve_attempt  conda_libmamba_solver/solver.py:394
            │     └─ 0.072 LibMambaSolver._setup_solver  conda_libmamba_solver/solver.py:383
            └─ 0.063 LibMambaSolver._notify_conda_outdated  conda_libmamba_solver/solver.py:1047
               └─ 0.055 LibMambaIndexHelper.search  conda_libmamba_solver/index.py:381
                  └─ 0.055 PyCapsule.find  <built-in>
         0.046 import_module  importlib/__init__.py:73
         └─ 0.046 <module>  conda_libmamba_solver/__init__.py:1
            └─ 0.044 <module>  conda_libmamba_solver/solver.py:1

To view this report with different options, run:
    pyinstrument --load-prev 2024-11-16T12-23-36 [options]
```

v2:

```
  _     ._   __/__   _ _  _  _ _/_   Recorded: 12:24:31  Samples:  294
 /_//_/// /_\ / //_// / //_'/ //     Duration: 2.634     CPU time: 2.171
/   _/                      v5.0.0

Program: conda create --dry-run --platform linux-64 ca-certificates

2.631 <module>  conda/__main__.py:1
└─ 2.631 main  conda/cli/main.py:91
      [23 frames hidden]  conda, requests, urllib3, importlib
         2.333 LibMambaSolver.solve_for_diff  conda/core/solve.py:183
         └─ 2.333 LibMambaSolver.solve_final_state  conda_libmamba_solver/solver.py:131
            ├─ 2.025 decorated  conda/common/io.py:83
            │  ├─ 1.928 LibMambaSolver._collect_all_metadata  conda_libmamba_solver/solver.py:258
            │  │  └─ 1.928 LibMambaIndexHelper.__init__  conda_libmamba_solver/index.py:155
            │  │     └─ 1.928 LibMambaIndexHelper._load_channels  conda_libmamba_solver/index.py:268
            │  │        ├─ 1.696 LibMambaIndexHelper._load_repo_info_from_json_path  conda_libmamba_solver/index.py:368
            │  │        │  └─ 1.696 PyCapsule.add_repo_from_native_serialization  <built-in>
            │  │        └─ 0.231 LibMambaIndexHelper._fetch_repodata_jsons  conda_libmamba_solver/index.py:330
            │  │           └─ 0.231 result_iterator  concurrent/futures/_base.py:612
            │  │                 [4 frames hidden]  concurrent, threading, <built-in>
            │  └─ 0.097 LibMambaSolver._solving_loop  conda_libmamba_solver/solver.py:297
            │     └─ 0.097 LibMambaSolver._solve_attempt  conda_libmamba_solver/solver.py:345
            │        └─ 0.096 PyCapsule.solve  <built-in>
            ├─ 0.135 SolverInputState.__init__  conda_libmamba_solver/state.py:159
            │  └─ 0.134 inner  conda/deprecations.py:114
            │        [11 frames hidden]  conda, multiprocessing, selectors, <b...
            ├─ 0.112 Spinner.__exit__  conda/common/io.py:455
            │     [4 frames hidden]  conda, threading, <built-in>
            └─ 0.061 LibMambaSolver._notify_conda_outdated  conda_libmamba_solver/solver.py:971
               └─ 0.054 LibMambaIndexHelper.search  conda_libmamba_solver/index.py:540
                  └─ 0.054 PyCapsule.find  <built-in>
         0.042 import_module  importlib/__init__.py:73
         └─ 0.041 <module>  conda_libmamba_solver/plugin.py:1
            └─ 0.031 <module>  conda_libmamba_solver/repoquery.py:1

To view this report with different options, run:
    pyinstrument --load-prev 2024-11-16T12-24-31 [options]
```

Again v2 SOLV loaders seem to be slightly slower than v1's. See these lines showing a 400ms slowdown, which would be enough to explain what Codspeed is reporting.

```
# v1
  1.211 LibMambaIndexHelper._json_path_to_repo_info  conda_libmamba_solver/index.py:258

# v2
  1.696 LibMambaIndexHelper._load_repo_info_from_json_path  conda_libmamba_solver/index.py:368
```

I don't think we can do much about it since we can't control much of what happens over in libmamba C++ land. I'll let the team know.

**Comment by jjerphan** [comment]
[As of 2.0 JSON files are parsed using `simdjson`](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html#libmamba-c), which might introduce regressions in some cases.

**Comment by jaimergp** [comment]
> [As of 2.0 JSON files are parsed using `simdjson`](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html#libmamba-c), which might introduce regressions in some cases.

I'm observing the regression with SOLV files, not JSON ones (it's `PyCapsule.add_repo_from_native_serialization` being profiled).

**Pull request closed without merging**
