### PR TITLE
`activate`/`deactivate` with install prefix

### PR DESCRIPTION
**Pull request by njalerikson**
A preliminary idea that appears to work correctly and address the issues raised after #3175 was merged.

Prepends the `$CONDA_INSTALL_PREFIX` value to all of the `activate`/`deactivate` (and related) scripts that previously assumed that the scripts could be found on the user's `$PATH`.

As a helpful bonus this fix may result in an option for `activate`/`deactivate` unittests to not require conda to be installed (and instead just set the `$CONDA_INSTALL_PREFIX` environment variable prior to running the unittests).

### CODE REVIEW

**Comment by wulmer** [comment]
Hm... I am not sure if I understand the workflow here. It is clear to me that if I use `python setup.py develop` or `python setup.py install`, the activate scripts are changed to use a fixed path for finding `conda`.

But what happens when I install `conda` as conda package? The conda package contains the activate scripts, but what will be set as CONDA_INSTALL_PREFIX in the activate scripts? Will it have been replaced to the conda location when having run `python setup.py install` during the conda build step, or will it be left to use an environment variable `%CONDA_INSTALL_PREFIX%` ? I assumed the latter, but where is this environment variable defined? Will it be set by the installer?

**Comment by njalerikson** [comment]
Ah I was falsely assuming that `build` extended the `install`. How wrong that assumption was. I'll have to go learn more about the build process.

**Comment by mingwandroid** [comment]
I got bitten pretty badly today by some changes I made to my bootstrap scripts to accommodate for https://github.com/conda/conda/pull/3175

The problem was that `$CONDA_PREFIX/bin` was on my `PATH` (the accommodation) so I did not have build environment isolation so the `conda` `gcc` package I had installed into my root environment was being used instead of the system's GCC. The previous behaviour of activating the build environment would have resulted in the root environment being scrubbed from `PATH` giving us environmental isolation.

This meant my builds were all wrong since if you use conda's `gcc` you also need to use conda's `libgcc` (I want to use neither, but this is just one example of how this change causes the wrong stuff to leak into builds).

This prevents anything approaching reproducible builds and I must again object to this change in behaviour. If some shells cannot be supported with the old way of activating then IMHO we should not compromise the activation procedure and environment under which `conda/conda-build` operate by attempting to bend over backwards to support them.

I have taken a quick look at the code, and it seems that the `csh/tcsh` code-path requires `bash` anyway (and also `awk` and `ps`). I expect that people who use shells other than `bash` may attempt to not even have that installed. I also think that the assumption that `awk` and `ps` are installed (and specific versions of them too, with more bending over to accommodate a plurality of versions *) is not ideal.

It seems to me that all this complication could all be done away with by providing `activate.tcsh` and `deactivate.tcsh` scripts that use ($_) since `tcsh` seems to be the only shell that does not provide the minimum amount of compatibility/emulation with/of `bash` that would be required to launch a shell-specific script (on its own, without the need of `bash` and `awk` and `ps`). If other shells are similarly brain damaged then they need custom scripts too.

* a relatively minor point, I don't get the `Cygwin/mingw-w64/MSYS2` `ps` distinctions. They all use the same `ps` executable; or are you trying to support the old `mingw.org/msys` software?

**Comment by njalerikson** [comment]
@mingwandroid assuming this PR can be made to work it will be able to restore the ability to remove `root`. I personally have a limited understanding of the `conda build` process so I admit that some of #3175 changes may not be ideal in that regard.

Yes I assume that any sane Linux developer from the 21st century is on an OS that has access to `bash`, `awk`, and `ps`. None of these assumptions should be outlandish as mainstream systems come with these as a default since most system processes depend on one or more of those. Even on the HPC systems I work on where `csh` is the system/user default (legacy reasons), `bash` is still available to the user as is `ksh`, `zsh`, and `ash` (yay for pre-`dash`).

At some point I assume someone will try to convert the various helper codes into python. I don't really have an excuse for why I didn't code up those in python originally.

> It seems to me that all this complication could all be done away with by providing activate.tcsh and deactivate.tcsh scripts that use ($_) since tcsh seems to be the only shell that does not provide the minimum amount of compatibility/emulation with/of bash that would be required to launch a shell-specific script (on its own, without the need of bash and awk and ps). If other shells are similarly brain damaged then they need custom scripts too.

I am not sure what you mean by providing additional custom scripts...do you mean that `bash` users call `. activate` and `csh` users call ```source "`which activate.csh`"```...? Users can already do this with the current design, users can completely ignore the `activate`/`deactivate` top-level scripts that sniff the system and does the shell detection with the extra dependencies (`bash`, `awk`, and `ps`).

So for those users who for example only have `csh`, no `bash` or `awk` or `ps`, can simply activate by directly sourcing: ```source "`which activate.csh`"```. `bash` users can similarly just say `. activate.sh`.

And technically I wouldn't harp on any of the shells as being any more or less POSIX compliant, even `bash` breaks certain POSIX rules (they may be obscure rules but they are still broken). Again keep in mind that as I added more and more supported shells I didn't continuously sacrifice functionality. I added more shell support because adding it changed very little code, it was mainly just adding the appropriate check clause to the `whichshell.awk` script.

Again the ability to detect a sourced script's path is not something that is defined in POSIX so it is not at all surprising that the solutions for that problem is hit and miss.

From my testing with the three Linux on Windows solutions (ignoring Windows 10's Ubuntu on Windows) all of the environments have `ps` however they are not identical and do not return equivalent content. Again this should possibly be rewritten as a conda function so this confusion may be easily resolved.

When I say Cygwin I am referring to -> https://www.cygwin.com/
When I say MinGW I am referring to -> http://www.mingw.org/
When I say MSYS I actually mean MSYS2 (since MinGW is MSYS) which refers to -> http://msys2.github.io/

**Comment by mingwandroid** [comment]
I'm not really interested in POSIX compliance, only functionality.

> bash users can similarly just say . activate.sh.

The crux here is that I *need* to be able to supply activate.sh with a full PATH and cannot rely on it being in my PATH environment variable (it must not be), are you saying that is already possible? If so, great, but can we rename activate.sh to activate so that existing workflows do not break?

Given you do so much processing (and call `ps`), I'm not sure why you can't use `lsof` on Linux and Mac to get the full paths of the sourced scripts while you are at it? I agree that it should be rewritten using Python and if you do that then you can use `psutil` to help you out.

MinGW is *not* MSYS, and MinGW.org and MSYS are not worth supporting since they do not support 64-bit software and are barely maintained. MinGW.org (the GCC/G++ compiler) is to some extent, but it was in a broken state for about 1.5 years: https://sourceforge.net/p/mingw/bugs/2108/. MSYS is unsupported, the forum has been closed for a few years, is insecure and very buggy => try running make in parallel or doing any serious computing with it). We should not encourage it when there is a far better alternative in MSYS2 which can be installed via the conda defaults channel and is also the basis of Git for Windows.

**Comment by njalerikson** [comment]
Right this second no, none of the ways to call `activate` (`activate.sh` or `activate.csh`) will work without conda's `bin` being on the user's `PATH`. This PR would change that...

I do not see any value in dismissing any of Cygwin/MinGW/MSYS/MSYS2 since including them is a minor extra. I also don't care if they are stripped out either. I don't use Windows and if required would much rather just use Ubuntu on Windows. Just coding up CMD.EXE and PowerShell was more than enough for me.

Using `lsof` would be great if there was a way to actually utilize the information that was collected there. The path to these files needs to be identified in `activate`/`deactivate` in order to properly call the `whichshell*` scripts. Internally to the `*activate.{csh.sh}` scripts I would need the path in order to call `conda` and the `envvar_cleanup*` scripts. This is a lot of path prefixes that need to be resolved. This can either be done with the executables being on `PATH` or with something liek the solution proposed in this PR.

**Comment by mingwandroid** [comment]
This PR does that, but by introducing more state, `CONDA_INSTALL_PREFIX` that is also not acceptable.

Regarding MSYS1, It is exactly the same that we do not support Windows XP or OSX 10.6. It is not you who will have to field bugs from people trying to build software using Conda on MSYS. As one of the original MSYS2 developers I know exactly how broken and insecure it is.

**Comment by njalerikson** [comment]
This PR doesn't really introduce `CONDA_INSTALL_PREFIX`. The value is set up as a variable* however the intention is for setuptools to perform a post-install that steps through and replaces all `CONDA_INSTALL_PREFIX` values with the appropriate installation prefix.

If you install this PR via `python setup.py [install|develop]` then all of the `CONDA_INSTALL_PREFIX` values will vanish. The current issue is that I have yet to find a good way to do a post install/copy process when conda has been built/packaged as a dist.

*In theory this variable will allow you to use the conda package without installing it and simply configuring the `CONDA_INSTALL_PREFIX`. In practice this shouldn't be done, this should only be considered for simplifying the unittesting.

**Comment by njalerikson** [comment]
@kalefranz I know there are conflicts that needs addressing with this and the other related PRs (#3960, #3987, #4018). I have lacked the stamina to address these conflicts as I do not see any current move towards using the code from #3175 in any of the stable releases of conda. I also see that you have been working on your own version of multi-shell support.

Please let me know what we can do to work together to get this all sorted out and resolve the many related tickets concerning multi-shell support. My team continues to need shell support (csh/tcsh) that is unresolved by any of the recent changes made to 4.3 or 4.4 and we are starting to suffer internally due to a conda install that is almost a year old. We have not updated as our install was hacked to support our csh/tcsh needs and as I'm sure you know/remember that multi-shell support is not a simple change.

@thoth291

**Comment by kalefranz** [comment]
Hey Ken, I feel bad that it's been so long since I've gotten to spend time on this.  The problem with all of this was that the framework underneath, basically all of `conda/cli/activate.py`, needed an overhaul.  And without that first, all of this shell wrapper code on top was having to do *way* too much work.

That framework code is done now though.  It's in https://github.com/conda/conda/pull/5044.  And that PR I think does an okay job of laying out how to write these wrappers for other shells (it's only tested against bash and zsh so far).  That's the way forward though.  Now we can take all of the shell code you wrote for all of the other shell compatibility, and use the python guts that are in #5044.

**Comment by kalefranz** [comment]
Closing, per #5183.  This code isn't dead.  Just needs tweaking for the new #5044 framework.

**Pull request closed without merging**
