### PR TITLE
Support for pinning Lua by default

### PR DESCRIPTION
**Pull request by alexbw**
This pull request is a small accompaniment for a larger PR in the `conda-build` repo here: https://github.com/conda/conda-build/pull/719

This pull request pins Lua versions by default, because Lua releases, like Python, do not occur often, but when they do, they often break packages.

### CODE REVIEW

**Comment by ilanschnell** [comment]
Thanks for the PR.  Trying to determine the default Lua version by using a subprocess seems slow and brittle, and is probably not something we want to be doing in conda.  In particular because only very few people use Lua, but all conda users are going to be affected by this change.  As far as I'm concerned, conda (unlike conda-build) should not have any features hard-coded to support special languages.  My point of view is that conda is a language (which includes Python) agnostic package manager.  Conda-build, on the other hand, may (and does) contain special code to support all sorts of commonly used scenarios.

**Comment by alexbw** [comment]
Thanks for the comment. Should I hard-code the Lua version? Use of Lua in
conda-build will be severely hampered without some kind of auto-pinning.
Also, the default version does not appear to be actually used, and just
serves as a placeholder to preserve the format of the iterator, so perhaps
the subprocess call can be removed entirely?

**Comment by alexbw** [comment]
Turns out everything but the default version of Python is unused in the "pinning" section of `plan.py`, so I removed it. This PR is now effectively single line change that will pin only Lua, hopefully that's minimal enough to merge.

**Comment by ilanschnell** [comment]
It seems a bit strange to me that it should be necessary to set a default version to `None`, but I certainly wouldn't have a problem merging this one line change anymore.

**Comment by alexbw** [comment]
I can set it to whatever's most innocuous, but I need something to not
break the iterator:
https://github.com/conda/conda/pull/1934/files#diff-d89048bb7f0ea8668934e579b409f994R340
.
Alternatively, I can comment that line to explain why None is used.
If None is fine, then the merge would be appreciated!

**Comment by ilanschnell** [comment]
If you add a small comment why `None` is used, them I'm happy to merge your PR.  Thanks

**Comment by alexbw** [comment]
Done

**Pull request merged**
