### PR TITLE
tests: Filter urllib3 retry warning log messages

### PR DESCRIPTION
**Pull request by mbargull**
### Description

Some tests like those in tests.cli.test_subcommands assert that there is no output on stderr.
If urllib3 retries a connection, it logs a warning message which lets those tests fail.

refs:
    - https://github.com/conda/conda-libmamba-solver/pull/358#issuecomment-1793574369

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by mbargull** [comment]
NB: No entry in `news` created since this isn't a "news-worthy" internal change. Though, feel free to amend this, if needed.

There is certainly ground to argue if such change should be made even more general (i.e., not just in testing code but also `conda` itself; possibly with turning this from a `warning` into `info`) or more specific (i.e., not `autouse=True` for the whole tests suite).
I don't have a strong opinion on that; feel free to change this PR as needed.

**Comment by mbargull** [comment]
Unrelated test failure:
`FAILED tests/plugins/subcommands/doctor/test_cli.py::test_conda_doctor_happy_path_verbose`
Maybe a concurrency issue since this only happens on a subset of jobs? :
- [linux (defaults, 3.8, unit, 1)](https://github.com/conda/conda/actions/runs/6773092909/job/18407153861?pr=13284#logs)
- [linux (defaults, 3.9, unit, 1)](https://github.com/conda/conda/actions/runs/6773092909/job/18407160993?pr=13284#logs)
- [linux (defaults, 3.10, unit, 1)](https://github.com/conda/conda/actions/runs/6773092909/job/18407163976?pr=13284#logs)
```
=================================== FAILURES ===================================
_____________________ test_conda_doctor_happy_path_verbose _____________________
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/opt/conda/lib/python3.10/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/conda/lib/python3.10/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/opt/conda/lib/python3.10/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/opt/conda/lib/python3.10/site-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/conda/lib/python3.10/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/opt/conda-src/tests/plugins/subcommands/doctor/test_cli.py", line 22, in test_conda_doctor_happy_path_verbose
    assert not err  # no error message
AssertionError: assert not "ERROR conda.plugins.subcommands.doctor.health_checks:check_envs_txt_file(37): /home/test_user/.conda/environments.txt could not be accessed because of the following error: [Errno 2] No such file or directory: ''\n"
```

**Comment by jaimergp** [comment]
> AssertionError: assert not "ERROR conda.plugins.subcommands.doctor.health_checks:check_envs_txt_file(37): /home/test_user/.conda/environments.txt could not be accessed because of the following error: [Errno 2] No such file or directory: ''\n"


This is fixed in 23.10 I think, via #12984. Once that branch is reconciled with `main`, you shouldn't see it here.

**Comment by jezdez** [comment]
I've opened #13291 to make sure this works in a more focused way.

**Comment by mbargull** [comment]
closing in favor of gh-13291

**Pull request closed without merging**
