### PR TITLE
System condarc location update (#13297)

### PR DESCRIPTION
**Pull request by samhaese**
### Description

Addresses issue #13297:
- References to "root directory" are now replaced with "system conda directory"
- An explanation of system conda directory is included in the multi-user administration page
- ~~The default system .condarc location is no longer the base environment~~

### Checklist - did you ...

- [X] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [X] Add / update outdated documentation?

### CODE REVIEW

**Comment by samhaese** [comment]
pre-commit.ci autofix

**Comment by travishathaway** [comment]
@conda-bot check

**Review by ForgottenProgramme — CHANGES_REQUESTED** [review]
Hey, @samhaese!
Thank you for submitting this PR. :)
Could you please rename your news file to: `13297-system-condarc-location`  i.e. remove the `.txt` extention ?

**Review by mbargull — CHANGES_REQUESTED** [review]
This would a big breaking change.
`conda config --system ...` always meant the installation's own configuration file.
This change would break a couple of setups, e.g.,
- multiple Conda installations on the same machine with different configurations,
- "packing up" pre-configured installations (e.g., restoring installations in CI caches).

While I agree that `--system` is an unfortunate naming (personally, I'd prefer something like `--base` for the current one and have `--system` like you suggested), it is not a change that can be done with a considerable deprecation phase, if at all.

**Comment by kenodegard** [comment]
@mbargull agreed, thoughts on adding a new argument instead? `--global` or `--universal`?

**Comment by samhaese** [comment]
I removed the change to the default system condarc path.  Instead, I added new language to the docs to clarify that there is a difference between a system-level and installation-level configuration, and that administrators of a multi-user installation should use system-level if they want to enforce #!final.

**Comment by samhaese** [comment]
pre-commit.ci autofix

**Pull request closed without merging**
