### PR TITLE
fixes xonsh activation and tab completion bugs

### PR DESCRIPTION
**Pull request by scopatz**
This fixes the issues brought up in https://github.com/xonsh/xonsh/issues/3269

### CODE REVIEW

**Comment by scopatz** [comment]
Ready for review @conda-core (CC @msarahan @mingwandroid @jjhelmus @kalefranz). I think that the errors are unrelated to the code here

**Comment by melund** [comment]
This reminds me that I made PR some time ago to this place as well. It were supposed to fix some Windows issues but I forget about again. 

#8246

I am not sure the fixes are all relevant any more, but maybe you could port a few fixes from it, now you have a new PR open.

For example 

```
self.pathsep_join = ';'.join if on_win else ':'.join
```

I also recall that the function `native_path_to_unix` returned cygwin style paths (`/c/Program files/`) but maybe that is fixed.

**Comment by scopatz** [comment]
@melund - do you mind if we try to fix that one up separately? It would be great to get this one in as it is :wink:

**Comment by soapy1** [comment]
LGTM! Not sure why the rest of the ci won't kick off....... pushing this up to a new branch to let all the other ci run too

**Comment by scopatz** [comment]
Thanks @soapy1!

**Comment by scopatz** [comment]
Uggh I pushed a flake fix and all of the CI broke again

**Pull request merged**
