### PR TITLE
merge conda-env into conda

### PR DESCRIPTION
**Pull request by kalefranz**
Put the whole thing in a `conda-env` directory for now to preserve commit history.  TBD what best structure is for the combined repo going forward.

### CODE REVIEW

**Comment by mcg1969** [comment]
A thousand thumbs up.

We're going to want to be very careful with conda recipes here. We need to make sure that upgrading to this unified conda properly removes the standalone `conda-env` package, and that downgrading brings it back. I believe this is going to require creating an empty `conda-env` package, probably version `2.6` or something like that, and making sure that it depends on `conda >= 4.x` (whatever the version is that includes this unification).

**Comment by kalefranz** [comment]
CC @ilanschnell

**Comment by mcg1969** [comment]
When I properly implement `optional` dependencies, this will be a perfect test case: we'll do `conda-env >=2.6 (optional)`. This will tell the solver: `conda-env` doesn't _have_ to be installed, but if it is, it must be this "empty" version.

**Comment by kalefranz** [comment]
Be careful the with word `optional` here. It's not a user-available optional, like `pip` has.  You mean "solver-internal."

**Comment by mcg1969** [comment]
Sure, we'll figure that out.

**Pull request merged**
