### PR TITLE
Updating contributing docs

### PR DESCRIPTION
**Pull request by travishathaway**
This PR is directly related to this open issue I created: https://github.com/conda/conda/issues/11376

The ultimate goal here is just getting to the contributing guide to a form where it's a little more user friendly.

We will be returning to update this once more, especially once everything with our governance planning is set.

One big change I introduced to this PR is layout related. On large screens, the docs become really hard to read because the text stretches across the entire screen. I have proposed a simple CSS fix to address this. It limits the width of the screen to no more than 80 characters wide, which is prime reading width.

Here's what the before and after look like:

**Before**

Screenshot 2022-04-05 at 16 33 41

**After**

Screenshot 2022-04-05 at 16 33 47

### CODE REVIEW

**Comment by travishathaway** [comment]
Just FYI, there is an issue I've found already with a broken link. Currently trying to resolve this.

**Review by kenodegard — APPROVED** [review]
Looks good!

**Review by jezdez — APPROVED** [review]
Super good!

**Review by beeankha — APPROVED** [review]
Great changes! 🎉

**Pull request merged**
