### PR TITLE
Dont modify Function:prompt when "changeps1" is false in PowerShell

### PR DESCRIPTION
**Pull request by dennispg**
Proposed fixes for #8213

### CODE REVIEW

**Comment by msarahan** [comment]
I confirm that you've signed the CLA.  Thanks for working on this.  We're incredibly busy through next week with AnacondaCon, but we'll look forward to reviewing this with you soon.

**Comment by msarahan** [comment]
@dennispg thanks for this PR.  It looks like a format string needs more arguments now.  Can you please take a look at the tests on circle CI and see if you can address them?  If you need help, please feel free to ask.

**Comment by dennispg** [comment]
So during deactivate there are some env vars that get unset.. After I added this change I noticed that with `changeps1` sometimes some of those vars which would have been set are not. But the deactivate tries to happily remove them anyways, so I added a check to be sure it is set before unsetting.

Now the automated tests seem to have some assumptions made as well about what vars are set and not, and I'm not sure how to make the asserts match up.

**Comment by dennispg** [comment]
Hi @msarahan, I rolled back the checks I put in to check for the env variables before trying to unset.. I think there is still some bug in that process, but I can't figure out the right way to sort out the tests without some assistance.

But it is probably best left to a new and separate issue.. This limited change should serve the purpose of only modifying the global prompt function when actually changing the prompt.

**Comment by msarahan** [comment]
LGTM.  Thanks!

**Pull request merged**
