### PR TITLE
Don't hardlink Windows entrypoint executables for noarch packages

### PR DESCRIPTION
**Pull request by mparry**
This is the simple fix that I suggested for #9976

### CODE REVIEW

**Comment by jjhelmus** [comment]
@cla-bot check

**Comment by mingwandroid** [comment]
The lack of being able to delete hardlinks when another instance has of open is common across all windows file io.

Personally I would prefer hardlinks to optional on windows in condarc..

**Comment by mparry** [comment]
> The lack of being able to delete hardlinks when another instance has of open is common across all windows file io.

Sure, but it only really matters for binaries here, I think, because of the way those files are locked.

> Personally I would prefer hardlinks to optional on windows in condarc..

As described in detail in the associated issue, noarch packages with entrypoints seem to be a bit broken on Windows currently. It doesn't seem very desirable to have to override an option in condarc to make them work reliably?

**Comment by mingwandroid** [comment]
Windows issues with file locking extend beyond hardlinks, stub executables etc (any dll can cause the same problem). They are orthogonal. Conda aggressively uses hardlinks and I don't think we should special case the entry point scripts.

**Comment by mingwandroid** [comment]
Brokenness needs fixing though. I'm not saying otherwise.

**Comment by mparry** [comment]
> Windows issues with file locking extend beyond hardlinks, stub executables etc (any dll can cause the same problem). They are orthogonal. Conda aggressively uses hardlinks and I don't think we should special case the entry point scripts.

The entry point executable is a bit of a special case though, in the sense that it's the only thing that is breaking installation/upgrades of noarch packages.

I don't disagree with your general point, but I think perhaps this PR is a short-term pragmatic solution, and could be replaced later with a more comprehensive change (if desired). I'm happy to update the change to add a comment or a TODO to this effect, if that would help.

**Comment by travishathaway** [comment]
This pull request has become stale and is therefore being closed. Please re-open if you would like to continue development on this.

**Pull request closed without merging**
