### PR TITLE
Add support for the linux-aarch64 platform

### LINKED ISSUE #5125: Incorrectly detected arch on aarch64
As per the title, conda currently only knows about the usual x86, x86_64 and armv7l architectures. Since aarch64 systems are compatible with armhf binaries, conda just needs to alias 'aarch64' to 'armv7l'.

The only hitch involved in approaching the problem via such an alias is that the armhf linker (ld-linux-armhf) may not be installed - its a rare situation currently, since most ARM systems opt for a 64bit kernel/32 bit userspace due to the rarity of 64 bit ARM binaries. The user (with sudo privileges) would need to install the linker in such a situation.

See [PR 4809](https://github.com/conda/conda/pull/4809) for implementation.

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #5125

### CODE REVIEW

**Comment by jjhelmus** [comment]
This is a different, more direct approach to fixing #5125 than #4809.  I've built a minimal aarch64 installer and some [basic packages](https://anaconda.org/aarch64_gbox/) using this patch and did not run into any issue.

**Comment by kalefranz** [comment]
targeting 4.3.x via #5190

**Comment by elehcim** [comment]
Hi @jjhelmus, could you point me to how to create a conda installer for aarch64, or it is not possible for non-Continuum people? Thanks. I could try [your packages](https://anaconda.org/aarch64_gbox/) and produce others that I need. My team owns an NVIDIA Jetson TX1 and for our purposes it would be very nice to have a conda package manager on it.

**Comment by jjhelmus** [comment]
@elehcim It should be possible to create an aarch64 installer using [constructor](https://github.com/conda/constructor).  

Please note that the packages in the `aarch64_gbox` channel are my own personal packages, there is no support for them from Continuum.  Additionally, those packages where build to target a Rockchip RK3368 based system with a particular flavor of Linux.  I do not know if they would work on other aarch64 platforms.

**Pull request closed without merging**
