### PR TITLE
Adding an option for conda to not update dependencies

### PR DESCRIPTION
**Pull request by asmeurer**
This is unfinished. 

Fixes https://github.com/conda/conda/issues/337.

**TODOs**:

- [x] Handle the max_only case.
- [x] Add a command line and .condarc option.
- [x] Breaks when installed packages can't be found

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess this is ready for beta testing by interested parties.

**Comment by hhuuggoo** [comment]
nice! btw is there a binstar build somewhere that has this?  Or should i install from source?

**Comment by asmeurer** [comment]
There are no builds. Just install from source or use PYTHONPATH if you want to test.

**Comment by ijstokes** [comment]
It isn't clear what the last TODO means: this is what currently happens and it needs to be fixed?  Or this behavior needs to be implemented?  If the latter, then don't you mean "returns an error" instead of "breaks"?

Also, it isn't clear to me that `--no-update-dependencies` is the same thing as my proposed `--minimal`.  If the flag does what it says, then how is this different from `conda update --no-deps foo`? Or maybe that option doesn't exist.

The idea with `--minimal` was that dependencies would only be updated if the currently installed version didn't satisfy the dependency.  IOW, all deps should be satisfied, the only question is whether they can be satisfied by the current (possibly older) version already installed.

**Comment by ijstokes** [comment]
@asmeurer what can I do to help this get merged?  It sounds like it might only need some testing, which I'm happy to do.  LMK.

**Comment by asmeurer** [comment]
Testing this would be great. The easiest way is to checkout the branch and use 

```
PYTHONPATH=. conda install ...
```

**Comment by asmeurer** [comment]
I guess I didn't document what this does. It works like this. Say you have numpy 1.9.0 and Python 2.7.7 and you run `conda update numpy`. With the current conda, this will update numpy to 1.9.2 and Python to 2.7.10. In this branch, if you run `conda update --no-update-dependencies numpy`, it will update numpy to 1.9.2, but leave Python at 2.7.7. Ditto everywhere if you replace `conda update` with `conda install`. The code assumes that the packages that you specify explicitly at the command line should be updated, and the packages that aren't specified should be updated as little as possible. 

More generally, if the package(s) specified at the command line requires an update of a dependency, it will try to update it "as little as possible" (using [this](https://github.com/conda/conda/pull/1358/files#diff-52a8935af92ea699b0cbb5feb84c19a2R406) version ordering). 

This is different from `--no-deps`, which just installs the one package without touching dependencies, even if that means that the dependencies are not satisfied. For example, `conda create -n test scipy --no-deps` will create an environment with *just* scipy (no python, numpy, etc.). Its primary use is for troubleshooting/fixing issues.

**Comment by hhuuggoo** [comment]
@asmeurer what do you need right now before this gets merged?  do you need us to test it out and confirm that it does what we think it should?

**Comment by asmeurer** [comment]
Yeah, that would definitely help.

**Comment by bkreider** [comment]
Is this the .condarc key: update_dependencies?  

Should the documentation be part of this PR or is that a separate issue?

**Comment by hhuuggoo** [comment]
@asmeurer not sure if this is quite right:

```
$ conda install pandas=0.14.1 python=2.7.8
Fetching package metadata: ....
Solving package specifications: ..................
Package plan for installation in environment /opt/anaconda/envs/futurestest:

The following NEW packages will be INSTALLED:

    pandas: 0.14.1-np18py27_0

Proceed ([y]/n)? n

$ conda install pandas=0.14.1 --no-update-deps
Fetching package metadata: ....
Solving package specifications: ............
Package plan for installation in environment /opt/anaconda/envs/futurestest:

The following NEW packages will be INSTALLED:

    pandas: 0.14.1-np18py27_0

The following packages will be UPDATED:

    python: 2.7.8-1 --> 2.7.10-0         

Proceed ([y]/n)? n

$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.13.0-176-ge882a04
  conda-build version : 1.12.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
```

**Comment by asmeurer** [comment]
Python itself is special here, because conda always injects it into the specs (to make sure that the Python version of the packages is correct).

**Comment by hhuuggoo** [comment]
Ah OK thanks.  For me getting upgraded on python within 2.7 is no biggie

**Comment by asmeurer** [comment]
I noticed that I used Python in my example above. So that's wrong. Python will always be updated, but it should be the only such package. You can easily keep it downgraded by pinning it.

**Comment by hhuuggoo** [comment]
hey fwiw I've been using this for a few weeks - seems to work as advertised so far?  I like it!

**Comment by asmeurer** [comment]
Cool. I still need to add some tests, then this can be merged.

**Comment by asmeurer** [comment]
OK, I've added tests. Will merge once Travis passes.

**Comment by asmeurer** [comment]
Documentation PR https://github.com/conda/conda-docs/pull/195

**Pull request merged**
