### PR TITLE
fix #3962 add ProxyError message for bad configurations

### LINKED ISSUE #3962: Cannot install packages after fresh install
Hi there,
I keep getting this error message, whenever I try to install any package after a fresh miniconda install.
Any help would be very much appreciated.
Thanks in advance!

--

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/pichama3/miniconda3  (writable)
    default environment : /home/pichama3/miniconda3
       envs directories : /home/pichama3/miniconda3/envs
          package cache : /home/pichama3/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/pichama3/miniconda3/bin/conda install snakemake`

    Traceback (most recent call last):
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/pichama3/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
        conn = self._new_conn()
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/home/pichama3/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 66, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

### PR DESCRIPTION
**Pull request by kalefranz**
fix #3962

### CODE REVIEW

**Comment by nehaljwani** [comment]
FWIW, I opened an issue with requests at https://github.com/requests/requests/issues/4353

**Comment by kalefranz** [comment]
I thought about opening an issue with requests also, but it wasn't clear to me that it was a bug in requests.  I traced the code paths, and with the first pass I couldn't pinpoint where the `None` value was coming from for `host`.  Looking at how conda is setting that `proxies` value, I don't *think* it's possible that the cause here is how conda is implementing its use of requests.  But I could be wrong.

**Comment by kalefranz** [comment]
I did search the `requests` and `urllib3` github repos and issues trackers, and I didn't see anything that matched.  Maybe we should look at the `pip` issue tracker, because they'd probably have the same reports.

**Comment by kalefranz** [comment]
https://stackoverflow.com/questions/46260169/python-locationvalueerror-no-host-specified
https://stackoverflow.com/questions/46053826/pip-exception-attributeerror-nonetype-object-has-no-attribute-startswith

**Comment by kalefranz** [comment]
@nehaljwani Given requests/requests#4353, do you think we should proceed with this for now?  Unfortunately, we're having quite a few issues filed where this is a problem.

**Comment by kalefranz** [comment]
OK, let's hold to see if upstream can raise something more descriptive in this case.  Like maybe https://github.com/requests/requests/blob/master/requests/exceptions.py#L36

**Comment by kalefranz** [comment]
Wonder when requests is going to be released again... 🤔

**Comment by kalefranz** [comment]
Sure wish requests would cut a release so we could close this issue...

**Comment by kalefranz** [comment]
@nehaljwani I think we can include this in the next feature release now!

**Pull request merged**
