### PR TITLE
Add `conda-env` entrypoint

### PR DESCRIPTION
**Pull request by jakirkham**
Adds an entrypoint for `conda-env` to `setup.py`.

### CODE REVIEW

**Comment by jakirkham** [comment]
So I already signed the CLA for `conda-build`. Do I really need to go back through that process here too?

**Comment by kalefranz** [comment]
Nope. You're fine on the CLA @jakirkham.  Thanks for the PR.  And sorry for the headache those merges caused this morning that you cleaned up.

**Comment by kalefranz** [comment]
That's weird.  We have the entry point in the conda recipe.
https://github.com/conda/conda/blob/master/conda.recipe/meta.yaml#L24

I guess that explains some of it?

**Comment by jakirkham** [comment]
> Nope. You're fine on the CLA @jakirkham.

Ok, thanks.

> Thanks for the PR. And sorry for the headache those merges caused this morning that you cleaned up.

No worries.

I have also been eager to see `conda`/`conda-env` upgraded at conda-forge. It seemed like everyone was ok to see those merged; so, was unclear on why the merge hadn't already happened.

Fortunately these were all easy issues to tackle. To be honest not upgrading itself can land us in just as much hot water if not more. ( https://github.com/conda-forge/conda-forge.github.io/issues/252 )

> That's weird. We have the entry point in the conda recipe.

Yeah, I noticed that when making this PR. Do you know if this was just an oversight then or if there was some reason this wasn't changed? 😕

**Comment by kalefranz** [comment]
> Yeah, I noticed that when making this PR. Do you know if this was just an oversight then or if there was some reason this wasn't changed? 

I think it was an oversight in the conda-forge meta.yaml and an oversight in this repo's setup.py.  What better argument for having a single source of truth?

Personally, I think conda-build should be able to fully build a conda package from a setup.py file, while looking for relevant meta.yaml information to augment and/or override what's already specified in setup.py.

**Comment by jakirkham** [comment]
Couldn't agree more.

**Pull request merged**
