### PR TITLE
Fixes #5125. Added aarch64 bypass to armv7l (backwards compatible)

### LINKED ISSUE #5125: Incorrectly detected arch on aarch64
As per the title, conda currently only knows about the usual x86, x86_64 and armv7l architectures. Since aarch64 systems are compatible with armhf binaries, conda just needs to alias 'aarch64' to 'armv7l'.

The only hitch involved in approaching the problem via such an alias is that the armhf linker (ld-linux-armhf) may not be installed - its a rare situation currently, since most ARM systems opt for a 64bit kernel/32 bit userspace due to the rarity of 64 bit ARM binaries. The user (with sudo privileges) would need to install the linker in such a situation.

See [PR 4809](https://github.com/conda/conda/pull/4809) for implementation.

### PR DESCRIPTION
**Pull request by H-Plus-Time**
in lieu of explicit aarch64 builds. Currently armv7l conda variants install and bundled packages work correctly, but the install channel is incorrectly set to ```linux-32``` or ```linux-64``` (depending on the output of ```getconf LONG_BIT```. A number of systems found in the wild opt to set this to 32, while aarch64 graphical libs remain somewhat unstable). aarch64 has no issues running armv7l and armv6l binaries.

### CODE REVIEW

**Comment by goanpeca** [comment]
@H-Plus-Time thanks for the work, is this solving a particular open issue at the moment?

If not, could you create it and attach it to the description with

`Fixes #NNN` ?

Thanks!

**Comment by kalefranz** [comment]
@mingwandroid Any input either way?

**Comment by mingwandroid** [comment]
IMHO the new CONDA_SUBDIR or CONDA_SUBDIRS config var should be used for this. You can put `conda_subdir: linux-armv7l` in `~/.condarc` already and get this behaviour therefore this is not needed.

I'd like to be able to remove these names and use more descriptive ones too but that's for another day.

**Comment by kalefranz** [comment]
#5187 is more consistent with the current approach right now.  Agree with @mingwandroid in general.  We need to be careful about adding anymore subdirs and making the ability to change to a more comprehensive subdir naming scheme even harder.

**Pull request closed without merging**
