### PR TITLE
maint: update macos install guide

### PR DESCRIPTION
**Pull request by thermokarst**
This changeset moves the Catalina `conda init` message up into the `note` directive just above, which I think helps clarify the intent of the message a bit. While I was at it I made some of the other shell script notes a bit more generic, and applied code formatting to the list of flags.

Regarding the CLA, I have attempted to sign the CLA in two different browsers, but for some reason I can't get past the signature field - the form won't allow me to submit because it considers the signature field empty (even though it isn't). Please let me know what you need from me to get the CLA on file.

Thanks!

### CODE REVIEW

**Comment by jezdez** [comment]
> This changeset moves the Catalina `conda init` message up into the `note` directive just above, which I think helps clarify the intent of the message a bit. While I was at it I made some of the other shell script notes a bit more generic, and applied code formatting to the list of flags.

That makes sense to me, thanks for opening the PR!

> Regarding the CLA, I have attempted to sign the CLA in two different browsers, but for some reason I can't get past the signature field - the form won't allow me to submit because it considers the signature field empty (even though it isn't). Please let me know what you need from me to get the CLA on file.

Oh noes, this is critical, thanks for bringing this up. We recently updated the CLA and something must have gone wrong.

@chenghlee Can you take a look at this please?

**Comment by chenghlee** [comment]
@thermokarst I've fixed [the CLA form](https://anaconda.na2.echosign.com/public/esignWidget?wid=CBFCIBAA3AAABLblqZhAzPD8JNseGxXBNSY55tQ9ZE65FLEa2B-rUNAEYEjfxph-KGE3uSbu0fvR5cTRRCnY*&hosted=false); please try signing it now? Sorry about the inconvenience!

**Comment by thermokarst** [comment]
Thanks @chenghlee (and @jezdez)! Signed and submitted, it worked like a charm.

**Comment by jezdez** [comment]
@anaconda-issue-bot check

**Review by jezdez — APPROVED** [review]

**Review by chenghlee — APPROVED** [review]

**Pull request merged**
