### PR TITLE
Fix/info on locked files

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
This is an experiment on printing more information about windows permissions error on attempted extraction of tarfiles to the pkgs dir.  This is aimed at helping anaconda-build.  

Edit 2/3/2016: This PR is ready to merge.  It affects nothing other than diagnostic printing when windows encounters a permissions error trying to unpack a tarfile.

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
An example of the diagnostic printing can be found here:
[https://anaconda.org/psteinberg/myorg.package1/builds/55/0](https://anaconda.org/psteinberg/myorg.package1/builds/55/0)

**Comment by msarahan** [comment]
I see that this is potentially helpful information to you, but it is also very hard to sort through (as a non-oriented person) and perhaps scary to non-technical people.  Is there a way to dump it to a file by default, and print text directing people to that file (for them to copy/paste when filing an issue, perhaps?)  Or perhaps only enable this extra output with some command-line switch?

**Comment by mcg1969** [comment]
I have to agree: I would not want this to be output by default. I vote for some sort of command-line facility to enable diagnostics. Perhaps `conda` could _recommend_ this command-line option if it sees this kind of error; i.e., "Conda encountered a permissions issue when attempting to unpack <xyz>. To view a verbose log of the errors encountered, re-run this command with the `--diagnostic` option."

**Comment by PeterDSteinberg** [comment]
I see your points @mcg1969  and @msarahan .  I think the best option is to dump it to a file without a command line switch and then do a one-line notification it has been written to file.  The idea of restarting the process with a different flag is kind of difficult for CI settings where it would be better to have some artifact that could be viewed later.

**Comment by mcg1969** [comment]
But in CI environments, couldn't you just supply the `--diagnostic` flag (or one better-named) at the outset? No need to restart the process.

**Comment by PeterDSteinberg** [comment]
@mcg1969 Of course!  Ok I'll do that.  Will change it this afternoon.

**Comment by kalefranz** [comment]
@PeterDSteinberg can you rebase against master to then trigger tests again?

**Comment by kalefranz** [comment]
@PeterDSteinberg Can you rebase against master, and then fix the couple-or-so test failures?

**Comment by kalefranz** [comment]
@PeterDSteinberg bump

**Comment by kalefranz** [comment]
@PeterDSteinberg I'm going to close this PR for now.  Feel free to reopen it if you think it's worthwhile to fix the merge conflicts.

**Pull request closed without merging**
