### PR TITLE
Fix boto3 initialization race condition

### PR DESCRIPTION
**Pull request by hajapy**
Fixes https://github.com/conda/conda/issues/8993

### CODE REVIEW

**Comment by msarahan** [comment]
This looks fine to me.  I'm calling it a night, but will merge in the morning.  I don't see any reason why this would break tests, but good to wait anyway.

The CLA thing is manual.  I confirmed that you have signed it, and I'll do the work to get that set up.  You can ignore that failing status here.

**Comment by msarahan** [comment]
Ah, I forgot: Thanks!

**Comment by hajapy** [comment]
Not sure I understand the failures here and how they could be related to these changes.

**Comment by msarahan** [comment]
all good.  Failures are unrelated.  Thanks again.

**Comment by hokira** [comment]
@msarahan Hi, we're experiencing this issue now and would like to try 4.7.11 to fix this issue. Is there a way to download the latest one? It seems the latest one from the below page still gives 4.7.10, which doesn't include this fix:

https://docs.conda.io/en/latest/miniconda.html

Thanks!

**Comment by forrestwaters** [comment]
@hokira you can get it from the conda-canary channel for now: https://www.anaconda.com/what-conda-canary/

```
conda config --add channels conda-canary
conda update conda
```

**Comment by hokira** [comment]
Yes, that worked, thanks! Also it seems the latest download link now points to 4.7.11, I guess you updated it as well, thank you.

**Pull request merged**
