### PR TITLE
specify --basetemp

### PR DESCRIPTION
**Pull request by dholth**
### Description

The tests warn against having this on a separate filesystem. Does this pass more quickly?

### CODE REVIEW

**Comment by dholth** [comment]
The tests should actually run `conda info` to find the writeable directory, not `/opt/conda`, and check if it is linkable. But `/tmp/` fails that test too.

**Comment by jezdez** [comment]
@dholth Not sure if this is still something you intend to work on, do you know what we'd need to do to have a good base temp directory?

**Comment by dholth** [comment]
IIRC the error message may be wrong. When running under docker the source code is on a readonly shared filesystem and everything else isn't.

**Comment by jezdez** [comment]
@dholth Let's see if mounting /tmp as a tmpfs helps?

**Comment by jezdez** [comment]
Okay, let's close it out then. Thanks for the context Daniel!

**Pull request closed without merging**
