### PR TITLE
cleanup setup.py

### PR DESCRIPTION
**Pull request by kalefranz**
Do not merge until @ilanschnell can add the `--old-and-unmanageable` flag to the conda build recipes.

### CODE REVIEW

**Comment by ilanschnell** [comment]
I don't think there is any good reason for adding `setuptools` as a build dependency to this project.  However, I respect that @kalefranz is the new lead developer.

**Comment by kalefranz** [comment]
I'm going to go ahead and merge this. @groutr let's iterate and improve on the conda build recipe in a separate PR.

**Comment by ilanschnell** [comment]
Another unfortunate consequence of always using setuptools is that `pycosat`, `pyyaml` and `requests` are now build dependencies (as well as runtime dependencies), whereas previously `python` was the only build dependency.

**Comment by kalefranz** [comment]
Yeah that's interesting. Help me understand the "unfortunate consequence"
part. Let's chat tomorrow.

On Thu, Feb 25, 2016 at 11:25 PM, Ilan Schnell <notifications@github.com>
wrote:

> Another unfortunate consequence of always using setuptools is that pycosat,
> pyyaml and requests are now build dependencies (as well as runtime
> dependencies), whereas previously python was the only build dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/pull/2081#issuecomment-189118738>.
>



-- 
*Kale J. Franz, PhD*
*Conda Tech Lead*
*kfranz@continuum.io <kfranz@continuum.io>*
*@kalefranz <https://twitter.com/kalefranz>*

<http://continuum.io/> <http://continuum.io/>
<http://continuum.io/>
221 W 6th St | Suite 1550 | Austin, TX 78701

**Comment by ilanschnell** [comment]
Yeah, I'll be happy to.

**Pull request merged**
