### PR TITLE
WIP Use Cirrus Labs CI runners.

### PR DESCRIPTION
**Pull request by jezdez**
### Description

(not a draft on purpose)

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by dholth** [comment]
Context please.

**Comment by jezdez** [comment]
Ignore for now, this is me trying to implement https://github.com/apps/cirrus-runners with Anaconda IT

**Comment by jezdez** [comment]
I've reached out to Cirrus support to figure out why the macOS jobs are waiting for a runner

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Comment by jezdez** [comment]
@kenodegard I just saw #13292, can you take anything from here for that?

**Comment by kenodegard** [comment]
@jezdez you tell me, if you think this PR is close to being merged then I suggest just leaving them here (since they're necessary here?) and documenting that these tests have been updated in the epic, if this PR is likely to hang out for a while I suggest we extract the test_create.py changes into a separate PR so we can benefit sooner

**Comment by jezdez** [comment]
pre-commit.ci autofix

**Pull request closed without merging**
