### PR TITLE
Test on 3.11rc1

### PR DESCRIPTION
**Pull request by jezdez**
### Description

This is basically a continuation of #11481 to get the ball rolling again on 3.11 support.

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Review by dholth — APPROVED** [review]
LGTM

**Comment by kenodegard** [comment]
It appears that we depend on several not `noarch: python` packages which will need to be rebuilt for Python 3.11.

See e.g., `conda search --info anaconda-client`:

Screen Shot 2022-09-29 at 11 09 45 PM

**Comment by EwoutH** [comment]
Python [3.11.0rc2](https://www.python.org/downloads/release/python-3110rc2/) is also available and currently the latest release candidate version!

**Comment by soumendrak** [comment]
[Python 3.11.0](https://www.python.org/downloads/release/python-3110/) stable version released.

**Comment by johnnynunez** [comment]
any news?

**Comment by jezdez** [comment]
Closing in favor of 12256

**Pull request closed without merging**
