### PR TITLE
resolve #6900 don't record conda skeleton environments in environments.txt

### LINKED ISSUE #6900: don't record conda skeleton environments in environments.txt
## Current Behavior

I was checking my environments by doing `conda env list` and I getting following 

```
# conda environments:
#
base                  *  C:\Users\aksha\Anaconda3
                         C:\Users\aksha\Anaconda3\conda-bld\skeleton_1516066110828\_h_env
                         C:\Users\aksha\Anaconda3\conda-bld\skeleton_1516068338359\_h_env
dj2                      C:\Users\aksha\Anaconda3\envs\dj2
ml35                     C:\Users\aksha\Anaconda3\envs\ml35
spikes                   C:\Users\aksha\Anaconda3\envs\spikes
test                     C:\Users\aksha\Anaconda3\envs\test
```

I am not sure what  `C:\Users\aksha\Anaconda3\conda-bld\skeleton_1516066110828\_h_env` and `C:\Users\aksha\Anaconda3\conda-bld\skeleton_1516068338359\_h_env`. No idea how this was created.

What are they? 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```     
active environment : None
       user config file : C:\Users\aksha\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.2.2
         python version : 3.6.4.final.0
       base environment : C:\Users\aksha\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\aksha\Anaconda3\pkgs
                          C:\Users\aksha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\aksha\Anaconda3\envs
                          C:\Users\aksha\AppData\Local\conda\conda\envs
                          C:\Users\aksha\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
None
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\aksha\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0    defaults
alabaster                 0.7.10           py36hcd07829_0    defaults
anaconda-navigator        1.6.9            py36hc720852_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.1                    py36_0    defaults
astropy                   2.0.3            py36hfa6e2cd_0    defaults
attrs                     17.4.0                   py36_0    defaults
authy                     2.1.5                     <pip>
autopep8                  1.3.3                     <pip>
babel                     2.5.3                    py36_0    defaults
backports                 1.0              py36h81696a8_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    defaults
beautifulsoup4            4.6.0            py36hd4cc5e8_1    defaults
bitarray                  0.8.1            py36hfa6e2cd_1    defaults
bkcharts                  0.2              py36h7e685f7_0    defaults
blaze                     0.11.3           py36h8a29ca5_0    defaults
bleach                    2.1.2                    py36_0    defaults
bokeh                     0.12.13          py36h047fa9f_0    defaults
boto                      2.48.0           py36h1a776d2_1    defaults
boto3                     1.4.7                     <pip>
botocore                  1.7.32                    <pip>
bottleneck                1.2.1            py36hd119dfa_0    defaults
bzip2                     1.0.6                hbe05fcf_4    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py36hfe50d7b_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.4           py36hfa6e2cd_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
click                     6.7              py36hec8c647_0    defaults
cloudinary                1.8.0                     <pip>
cloudpickle               0.5.2                    py36_1    defaults
clyent                    1.2.2            py36hb10d595_1    defaults
colorama                  0.3.9            py36h029ae33_0    defaults
comtypes                  1.1.4                    py36_0    defaults
conda                     4.4.10                   py36_0    defaults
conda-build               3.2.2                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h065de53_0    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
contextlib2               0.5.5            py36he5d52c0_0    defaults
coverage                  4.4.2                     <pip>
cryptography              2.1.4            py36he1d7878_0    defaults
curl                      7.58.0               h7602738_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cython                    0.27.3           py36h22f4c84_0    defaults
cytoolz                   0.9.0            py36hfa6e2cd_0    defaults
dask                      0.16.1                   py36_0    defaults
dask-core                 0.16.1                   py36_0    defaults
datashape                 0.5.4            py36h5770b85_0    defaults
decorator                 4.2.1                    py36_0    defaults
distlib                   0.2.5            py36h51371be_0    defaults
distributed               1.20.2                   py36_0    defaults
Django                    2.0.1                     <pip>
django-filer              1.2.8                     <pip>
django-mptt               0.8.7                     <pip>
django-phonenumber-field  1.3.0                     <pip>
django-polymorphic        1.0.2                     <pip>
django-storages           1.6.5                     <pip>
docutils                  0.14             py36h6012d8f_0    defaults
easy-thumbnails           2.4.2                     <pip>
entrypoints               0.2.3            py36hfd66bb0_2    defaults
et_xmlfile                1.0.1            py36h3d2d736_0    defaults
fastcache                 1.0.2            py36hfa6e2cd_2    defaults
feedparser                5.2.1                     <pip>
filelock                  2.0.13           py36h20000bf_0    defaults
flask                     0.12.2           py36h98b5e8f_0    defaults
flask-cors                3.0.3            py36h8a3855d_0    defaults
freetype                  2.8              vc14h17c9bdf_0  [vc14]  defaults
futures                   3.1.1                     <pip>
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.2.2            py36h342a76c_0    defaults
git-url-parse             1.0.2                     <pip>
glob2                     0.6              py36hdf76b57_0    defaults
graphene                  2.0.1                     <pip>
graphene-django           2.0.0                     <pip>
graphql-core              2.0                       <pip>
graphql-relay             0.4.5                     <pip>
greenlet                  0.4.12           py36ha00ad21_0    defaults
h5py                      2.7.1            py36he54a1c3_0    defaults
hdf5                      1.10.1               h98b8871_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h047fa9f_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py36h148d497_1    defaults
imageio                   2.2.0            py36had6c2d2_0    defaults
imagesize                 0.7.1            py36he29f638_0    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipython                   6.2.1            py36h9cf0123_1    defaults
ipython_genutils          0.2.0            py36h3c5d0ee_0    defaults
iso8601                   0.1.12                    <pip>
isort                     4.2.15           py36h6198cc5_0    defaults
itsdangerous              0.24             py36hb6c5a24_1    defaults
jdcal                     1.3              py36h64a5255_0    defaults
jedi                      0.11.1                   py36_0    defaults
jinja2                    2.10             py36h292fed1_0    defaults
jmespath                  0.9.3                     <pip>
jpeg                      9b               vc14h4d7706e_1  [vc14]  defaults
jsonschema                2.6.0            py36h7636477_0    defaults
jupyter_client            5.2.2                    py36_0    defaults
jupyter_console           5.2.0            py36h6d89b47_1    defaults
jupyter_core              4.4.0            py36h56e9d50_0    defaults
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libcurl                   7.58.0               h7602738_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.34               h79bbb47_0    defaults
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]  defaults
libtiff                   4.0.9                h0f13578_0    defaults
libxml2                   2.9.7                h79bbb47_0    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.21.0           py36he0b0552_0    defaults
locket                    0.2.0            py36hfed976d_1    defaults
lockfile                  0.12.2           py36h0468280_0    defaults
lxml                      4.1.1            py36hef2cd61_1    defaults
lzo                       2.10                 h6df0209_2    defaults
m2-msys2-runtime          2.5.0.17080.65c939c               3    defaults
m2-patch                  2.7.5                         2    defaults
Markdown                  2.6.9                     <pip>
markupsafe                1.0              py36h0e26971_1    defaults
matplotlib                2.1.2            py36h016c42a_0    defaults
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.11           py36hfa6e2cd_0    defaults
mistune                   0.8.3                    py36_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
mkl-service               1.1.2            py36h57e144c_4    defaults
mock                      2.0.0                     <pip>
mpmath                    1.0.0            py36hacc8adf_2    defaults
msgpack-python            0.5.1            py36he980bc4_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.4.9            py36he44c36e_0    defaults
navigator-updater         0.1.0            py36h8a7b86b_0    defaults
nbconvert                 5.3.1            py36h8dc0fde_0    defaults
nbformat                  4.4.0            py36h3a5bc1b_0    defaults
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h76d52bb_0    defaults
nose                      1.3.7            py36h1c3779e_2    defaults
numba                     0.36.2          np114py36h12cb543_0    defaults
numexpr                   2.6.4            py36h30784b8_0    defaults
numpy                     1.14.0           py36h4a99626_1    defaults
numpydoc                  0.7.0            py36ha25429e_0    defaults
odo                       0.5.1            py36h7560279_0    defaults
olefile                   0.45.1                   py36_0    defaults
openpyxl                  2.4.10                   py36_0    defaults
openssl                   1.0.2n               h74b6da3_0    defaults
packaging                 16.8             py36ha0986f6_1    defaults
pandas                    0.22.0           py36h6538335_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py36h3ef6317_1    defaults
parso                     0.1.1            py36hae3edee_0    defaults
partd                     0.3.8            py36hc8e763b_0    defaults
path.py                   10.5             py36h2b94a8f_0    defaults
pathlib2                  2.3.0            py36h7bfb78b_0    defaults
patsy                     0.5.0                    py36_0    defaults
pbr                       3.1.1                     <pip>
pep8                      1.7.1                    py36_0    defaults
phonenumberslite          8.8.4                     <pip>
pickleshare               0.7.4            py36h9de030f_0    defaults
Pillow                    4.3.0                     <pip>
pillow                    5.0.0            py36h0738816_0    defaults
pip                       9.0.1            py36h226ae91_4    defaults
pkginfo                   1.4.1            py36hb0f9cfa_1    defaults
pluggy                    0.6.0            py36hc7daf1e_0    defaults
ply                       3.10             py36h1211beb_0    defaults
progress                  1.3              py36hbeca8d3_0    defaults
promise                   2.1                       <pip>
prompt_toolkit            1.0.15           py36h60b8f86_0    defaults
psutil                    5.4.3            py36hfa6e2cd_0    defaults
psycopg2                  2.7.3.1                   <pip>
py                        1.5.2            py36hbcfbabc_0    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pycrypto                  2.6.1            py36hfa6e2cd_7    defaults
pycurl                    7.43.0.1         py36h74b6da3_0    defaults
pyflakes                  1.6.0            py36h0b975d6_0    defaults
pygments                  2.2.0            py36hb010967_0    defaults
pylint                    1.8.2                    py36_0    defaults
pyodbc                    4.0.22           py36h6538335_0    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pypandoc                  1.4                      py36_0    defaults
pypandoc                  1.4                       <pip>
pyparsing                 2.2.0            py36h785a196_1    defaults
pyqt                      5.6.0            py36hb5ed885_5    defaults
pysocks                   1.6.7            py36h698d350_1    defaults
pyspin                    1.1.1                     <pip>
pytables                  3.4.2            py36h71138e3_2    defaults
pytest                    3.3.2                    py36_0    defaults
pytest-cov                2.5.1                     <pip>
pytest-mock               1.6.3                     <pip>
pytest-runner             3.0                       <pip>
python                    3.6.4                h6538335_1    defaults
python-dateutil           2.6.1            py36h509ddcb_1    defaults
pytz                      2017.3           py36h1d3fa6b_0    defaults
pytz                      2017.3                    <pip>
pywavelets                0.5.2            py36hc649158_0    defaults
pywin32                   222              py36hfa6e2cd_0    defaults
pywinpty                  0.5              py36h6538335_1    defaults
pyyaml                    3.12             py36h1d1928f_1    defaults
pyzmq                     16.0.3           py36he714bf5_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.3.1            py36hb8717c5_0    defaults
release-exporter          1.0.3                     <pip>
requests                  2.18.4           py36h4371aae_1    defaults
requests-toolbelt         0.8.0                     <pip>
restructuredtext-lint     1.1.2                     <pip>
rope                      0.10.7           py36had63a69_0    defaults
rstcheck                  3.1                       <pip>
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults
Rx                        1.6.0                     <pip>
s3transfer                0.1.11                    <pip>
scikit-learn              0.19.1           py36h53aea1b_0    defaults
scipy                     1.0.0            py36h1260518_0    defaults
seaborn                   0.8.1            py36h9b69545_0    defaults
send2trash                1.4.2                    py36_0    defaults
setuptools                38.4.0                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
simplejson                3.11.1                    <pip>
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
singlemodeladmin          0.7                       <pip>
sip                       4.18.1           py36h9c25514_2    defaults
six                       1.11.0                    <pip>
six                       1.11.0           py36h4db2310_1    defaults
snowballstemmer           1.2.1            py36h763602f_0    defaults
sortedcollections         0.5.3            py36hbefa0ab_0    defaults
sortedcontainers          1.5.9                    py36_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1    defaults
sqlalchemy                1.2.1            py36hfa6e2cd_0    defaults
sqlite                    3.22.0               h9d3ae62_0    defaults
statsmodels               0.8.0            py36h6189b4c_0    defaults
sympy                     1.1.1            py36h96708e0_0    defaults
tabulate                  0.8.2                     <pip>
tblib                     1.3.2            py36h30f5020_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h2698cfe_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   4.5.3                    py36_0    defaults
tqdm                      4.19.4                    <pip>
traitlets                 4.3.2            py36h096827d_0    defaults
twine                     1.9.1                     <pip>
typing                    3.6.2            py36hb035bda_0    defaults
unicodecsv                0.14.1           py36h6450c06_0    defaults
Unidecode                 0.04.21                   <pip>
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py36h3d5aa90_0    defaults
webencodings              0.5.1            py36h67c50ae_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.30.0           py36h6c3ec14_1    defaults
whitenoise                3.3.1                     <pip>
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
win_unicode_console       0.5              py36hcdbd4b5_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xlrd                      1.1.0            py36h1cb58dc_1    defaults
xlsxwriter                1.0.2            py36hf723b7d_0    defaults
xlwings                   0.11.5                   py36_0    defaults
xlwt                      1.3.0            py36h1a4751e_0    defaults
yaml                      0.1.7            vc14hb31d195_1  [vc14]  defaults
zict                      0.1.3            py36h2d8e73e_0    defaults
zlib                      1.2.11               h8395fce_2    defaults
```
</p></details>

### PR DESCRIPTION
**Pull request by kalefranz**
resolve #6900

### CODE REVIEW

**Comment by jjhelmus** [comment]
Failing tests seem to be related to some stability issues with pypi.io:

```
conda.exceptions.CondaHTTPError: HTTP 503 BACKEND IS UNHEALTHY for url <https://pypi.io/packages/source/c/conda_version_test/conda_version_test-0.1.0-1.tar.gz>
```

**Comment by kalefranz** [comment]
I'm seeing a failure related to the new numpy also.  Investigating now...

**Comment by jjhelmus** [comment]
> I'm seeing a failure related to the new numpy also. Investigating now...

I have not build nomkl versions of numpy 1.14.1, that might be the cause

**Comment by kalefranz** [comment]
Yeah something happened with this latest numpy I release I'm thinking...

for `conda create -n blarg python=2 numpy nomkl` we get

`# packages in environment at /var/folders/cp/7r2s_s593j7_cpdtxxsmct880000gp/T/d5e1 ñôçêßá:
#
# Name                    Version                   Build  Channel
ca-certificates           2017.08.26           ha1e5d58_0
certifi                   2018.1.18                py27_0
intel-openmp              2018.0.0             h8158457_8
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1                  hb4e282d_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
mkl                       2018.0.1             hfbd8650_4
ncurses                   6.0                  hd04f020_2
nomkl                     1.0                           0
numpy                     1.14.1           py27h8a80b8c_1
openssl                   1.0.2n               hdbc3d79_0
pip                       9.0.1            py27h1567d89_4
python                    2.7.14              hde5916a_29
readline                  7.0                  hc1231fa_4
setuptools                38.5.1                   py27_0
sqlite                    3.22.0               h3efe00b_0
tk                        8.6.7                h35a86e2_3
wheel                     0.30.0           py27h677a027_1
zlib                      1.2.11               hf3cbc9b_2
```

**Comment by kalefranz** [comment]
I think we've always had this problem... I just tried with conda 4.3.27, and we basically get the same result.  So, for the `nomkl` feature to work correctly for us, any package that's ever had that feature attached always need to be released with a `nomkl` version, when the mkl version is released.

**Comment by jjhelmus** [comment]
Conda will prefer a higher version of a numpy package over a `nomkl` version even when the feature is active.  This has been true for quite some time.  Currently numpy 1.14.1 is available but the latest `nomkl` is 1.14.0.  

So yes, we always need to release the mkl and nomkl packages in sync.

**Comment by kalefranz** [comment]
merging based on @goanpeca's review

**Pull request merged**
