### PR TITLE
Handle empty lines in package info RECORD file reader

### LINKED ISSUE #9074: conda list broken after flit install --pth-file
## Current Behavior

    Traceback (most recent call last):
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 133, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 162, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 72, in load
        self._load_site_packages()
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\core\prefix_data.py", line 277, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\gateways\disk\read.py", line 257, in read_python_record
        paths_tups = pydist.get_paths()
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\pkg_formats\python.py", line 261, in get_paths
        records = tuple(process_csv_row(row) for row in record_reader if row[0])
      File "C:\Users\maxim\Anaconda3\envs\project\lib\site-packages\conda\common\pkg_formats\python.py", line 261, in <genexpr>
        records = tuple(process_csv_row(row) for row in record_reader if row[0])
    IndexError: list index out of range

`$ C:\Users\maxim\Anaconda3\envs\project\Scripts\conda-script.py list`

### Steps to Reproduce

```
conda activate myenv
cd project
flit install --pth-file
conda list
```
This raises the error printed above.

`conda remove project`  raises the following error:
```
PackagesNotFoundError: The following packages are missing from the target environment:
  - project
```

Executing `pip uninstall project` fixes `conda list`.

## Expected Behavior

`conda list` should list all the packages available in the active environment, including those in development mode installed with *flit* (I guess?). However, the problem might come from *flit*.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\Users\maxim\Anaconda3\envs\project
            shell level : 2
       user config file : C:\Users\maxim\.condarc
 populated config files : C:\Users\maxim\Anaconda3\envs\project\.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.1
       base environment : C:\Users\maxim\Anaconda3\envs\project  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\maxim\Anaconda3\envs\project\pkgs
                          C:\Users\maxim\.conda\pkgs
                          C:\Users\maxim\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\maxim\Anaconda3\envs\project\envs
                          C:\Users\maxim\.conda\envs
                          C:\Users\maxim\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\maxim\Anaconda3\envs\project\.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #9074

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-166)

### CODE REVIEW

**Comment by angloyna** [comment]
@cla-bot check

**Comment by flying-sheep** [comment]
No idea why this failed, doesn’t seem to be because of me. Timeout?

**Comment by angloyna** [comment]
@flying-sheep , yeah, don't worry; the appveyor tests have been timing out

**Comment by travishathaway** [comment]
It appears that this has been addressed and this pull request is no longer necessary:

https://github.com/conda/conda/issues/9074#issuecomment-1139411442

**Pull request closed without merging**
