### PR TITLE
Updated the regexp to handle subcommands with a '-'.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by pelson** [comment]
Any comments on whether this will be merged? It is a nice simple one.

**Comment by msarahan** [comment]
I would like to merge this, but I don't understand any potential ramifications.  Can you explain it just a bit to me?  What additional functionality does this provide?

**Comment by pelson** [comment]
> Can you explain it just a bit to me? What additional functionality does this provide?

Yes, of course. I'm writing a tool which has a dash in the name, which I'd like to be able to call with conda. Right now, I could create a CLI called ```conda-execute``` which can be invoked with conda as ``conda execute``. I want to do the same thing for another tool I'm writing which contains a ``-`` in the name itself - I was expecting to be able to write a CLI called ```conda-my-command``` which is invoked as ```conda my-command```. This PR allows that behaviour.

**Comment by msarahan** [comment]
Cool.  multi-word commands, with conda as a "prefix."  I'm +1.  Is there a quick test that could be added?  With a test, I'll merge.  Otherwise, I want one more positive opinion from some other contributor.

**Comment by pelson** [comment]
> With a test, I'll merge. Otherwise, I want one more positive opinion from some other contributor.

I like the motivator. It'll be easy to test, so I'll try to take a look shortly.

**Comment by kalefranz** [comment]
@msarahan I think we're ok on this one. Going to go ahead and merge.

**Pull request merged**
