### PR TITLE
Fix typo in `conda create` help

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by travishathaway** [comment]
@conda-bot

**Comment by travishathaway** [comment]
@dandv , Thank for the typo fix submission! Can you please sign our contributor license agreement? I notice that your GitHub username still does not appear under the list we have here: https://github.com/conda/infra/blob/main/.clabot

Again, thanks for helping improve conda!

**Comment by dandv** [comment]
Sorry, I was on mobile and signing was a clusterf**k :) (as in, seriously
mobile-friendly). Signing now.

**Comment by travishathaway** [comment]
@conda-bot check

**Review by travishathaway — APPROVED** [review]
Looks good. Thanks again!

**Pull request merged**
