### PR TITLE
resolve #6642 quiet UI if conda logger off for level ERROR

### LINKED ISSUE #6642: The --quiet flag seems to have changed with conda 4.4 and conda-build

### PR DESCRIPTION
**Pull request by kalefranz**
resolve #6642 

This PR to be merged following https://github.com/conda/conda/pull/6616, which comprises the first two commits in this PR.

### CODE REVIEW

**Comment by kalefranz** [comment]
Appveyor tests *do* pass.  See https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda/build/1.0.5612

Appveyor and github are out of sync here regarding the origin branch.

**Comment by kalefranz** [comment]
Apparently this PR breaks a specific conda-build test.  Investigating now...

**Comment by kalefranz** [comment]
Now this PR is easy to review!

**Comment by nehaljwani** [comment]
Although I don't see any progress bars while using conda-build during any installation phase, I don't see any harm caused by this PR. Merging.

**Comment by mbargull** [comment]
I don't see reason for/benefit from this change. One thing is that the commit messages states "off for level ERROR" but the changes actually imply that only for `> ERROR`, e.g., `CRITICAL`, the output is suppressed. The other thing is that the [original issue](https://github.com/conda/conda-build/issues/2604) was for `conda-build 3.2.0` but I believe `--quiet` was fixed for `conda-build 3.3.0` in https://github.com/conda/conda-build/pull/2645.

**Comment by kalefranz** [comment]
@msarahan At this point, should we merge this or just close it?  The purpose of the PR was for conda-build.

**Comment by msarahan** [comment]
Conda-build is now setting the context's quiet attribute, so I think this can be closed.  Thanks for working on it.

**Pull request closed without merging**
