### PR TITLE
Support channel append/prepend, handle duplicates better

### PR DESCRIPTION
**Pull request by mcg1969**
cc: @jreback

Any conda installation with no `.condarc` or with no `channels:` key should allow this:
```
conda config --remove channels defaults
conda config --add channels conda-forge
```
That's because, _logically_, a nonexistent `channels` key should be treated like `['defaults']`.

Furthermore: if I do this
```
conda config --add channels conda-forge
conda config --add channels defaults
```
It should *not* cause an error, because now _channel ordering matters_.

Finally. We need
```
conda config --add channels conda-forge
conda config --append channels defaults
```
so that we can allow channels to be placed at the end of the channel list.

### CODE REVIEW

**Comment by mcg1969** [comment]
```
0203-mgrant:conda mgrant$ conda config --add channels test
0203-mgrant:conda mgrant$ conda config --add channels test
Warning: test already in channels, moving to the front
0203-mgrant:conda mgrant$ conda config --append channels test
Warning: test already in channels, moving to the back
0203-mgrant:conda mgrant$ more ~/.condarc
channels:
  - defaults
  - test
```

**Comment by mcg1969** [comment]
```
0203-mgrant:conda mgrant$ rm ~/.condarc
0203-mgrant:conda mgrant$ conda config --remove channels defaults
0203-mgrant:conda mgrant$ conda config --remove channels defaults
```

**Comment by kalefranz** [comment]
The first PR to break 70%!!!!!!

**Comment by kalefranz** [comment]
LGTM

**Pull request merged**
