### PR TITLE
Changing raises to inherit CondaError, Move custom exceptions to exceptions.py

### PR DESCRIPTION
**Pull request by dorzel**

### CODE REVIEW

**Comment by dorzel** [comment]
@kalefranz My work so far on moving custom exceptions and modifying raises. Not sure how to get rid of  the first 6 commits, as you merged them in one of your branches I believe.

**Comment by dorzel** [comment]
@kalefranz rebased and force pushed, fixed now

**Comment by dorzel** [comment]
changed test for test_create_install_update_remove, for installing constructor in a root environment. It should have thrown an error but did not, due to changes to constructor. Modified to version 1.0 to again have an error.

**Comment by kalefranz** [comment]
Hope this is no longer WIP.  LGTM
Going to merge.

**Pull request merged**
