### PR TITLE
fix fish activate script for conda 4.1

### LINKED ISSUE #2680: conda 4.1 breaks fish integrations
The new version does not work with fish at all. While the .fish script is finally there in the bin directory, it does not seem to kick in, since the new activate.py command is messing with it. How is it supposed to work?

This is the error I get:

```
$ conda activate myenv
Traceback (most recent call last):
  File "/home/jrodriguez/.local/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/jrodriguez/.local/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/home/jrodriguez/.local/anaconda/lib/python3.5/site-packages/conda/cli/activate.py", line 119, in main
    shelldict = shells[shell]
KeyError: 'myenv'
```

Meanwhile, I had to downgrade to conda 4.0 with `conda install conda=4.0`. Thank you!

### PR DESCRIPTION
**Pull request by msarahan**
Closes #2680 

CC @kalefranz

### CODE REVIEW

**Comment by aldanor** [comment]
@msarahan Looks great, thanks for fixing. Minor nit: why change the formatting though? :( It was a bit easier to see imo when just the environment path itself was highlighted and parens weren't.

**Comment by aldanor** [comment]
Also, if I do `conda activate ./env` it shows `((env))` in the prompt. Are the double parens intentional too?.. Is this meant to be just the last component of the full path that shows up?

**Comment by msarahan** [comment]
@aldanor sorry for the unwanted side effects.  I agree with your comment about the formatting, but I'm swamped with too many other more urgent issues right now to get into it.  I think @kalefranz would welcome a PR to change the formatting back, if you have time to do so.

The double parens are/were intentional.  They were there because we used to change prompt by adding and removing content.  This meant some kind of regex for removing content.  Single parens were too confusing - many prompts treat parens specially, not literally.  That said, double parens are no longer necessary, because we now do (backup ps1)->(change ps1)->(restore backup).  #2796 changes this to single parens by default, but also makes things more readily customizable.  Thanks for your ping here - it reminds me that I need to polish the fish scripts in that PR.

**Comment by msarahan** [comment]
@aldanor, scratch that, I'll just revert the formatting as part of polishing #2796

**Comment by aldanor** [comment]
@msarahan Thanks! I think it was fairly clean previously, `(foo)` indicated that you are using a global env, while `(/a/b/c/foo)` indicated that you are using a local env, with a full path to it. Arguably, you could shorten the full path the same way as fish shortens the current working directory in the prompt, but that's more of a possible cosmetic enhancement.

Let me know if you need any help with anything about it :panda_face:

**Comment by msarahan** [comment]
https://github.com/conda/conda/pull/2796/commits/edda10873fa8dc32e710ed7df23b7374352c20c8

I think that really just reverts most of the changes I made.  One thing that that PR changes is that ```conda ..activate``` returns only the new path component(s) to add.  The stuff about CONDA_DEFAULT_ENV affects fish less, because your scripts already had their own way of doing things.

**Pull request merged**
