### PR TITLE
always add cmd folder scripts in meta.yaml

### PR DESCRIPTION
**Pull request by msarahan**
I think this takes the place of the data_files stuff in setup.py.  This needs testing before the stuff from #1727 makes it into a release.

Ping @kalefranz for awareness

### CODE REVIEW

**Comment by ilanschnell** [comment]
`cmd` is a Windows term.  The Unix scripts should be in `bin`.  I'm fine with everything being in `bin` also.

**Comment by msarahan** [comment]
You are missing the point.  The point is that there needs to be (and now is) a separate folder that holds only the activate and deactivate scripts. This provides a way for people to activate and the use conda-based software, while avoiding most shadowing, which we are currently very bad about.

The cmd folder name doesn't matter. It can be anything - just not anything where other scripts or binaries are installed. Bin is this inappropriate on Linux, and scripts is inappropriate on Windows.

**Comment by kalefranz** [comment]
How about `libexec`?

**Comment by kalefranz** [comment]
@msarahan I might actually be missing something here too...

On unix, are we still going to be using `source activate foo` for now?  And if so, doesn't `activate` still need to be on `PATH`?

**Comment by kalefranz** [comment]
@msarahan  Also on this PR, we need to symlink `activate`, `deactivate`, and `conda` to `./bin` on Unix, correct?  Anything else?

**Comment by msarahan** [comment]
@kalefranz @ilanschnell I think this does what you want.  I went with the ```exec``` folder name.  I did not include deactivate as a link, because by definition, you must have activated in order to deactivate, and in doing so, you will have it on PATH.

This PR changes nothing about having to ```source``` activate on Unix and on Unix shells on Windows.

I have very little time over the next two weeks (AppStarter deadline).  If you need to change this PR, feel free to copy the branch and push it forward yourselves.

With these changes, the installers now need work to add the option to add only the exec folder to PATH.  I can do that at some point after the next 2 weeks.

**Comment by kalefranz** [comment]
@msarahan, for the failing windows tests...

    CalledProcessError: Command '['bash', '-l', '-c', 'ln -sf "/C/miniconda/cmd/activate" 

Just need to change `cmd` to `exec`?

**Pull request merged**
