### PR TITLE
Add Python 3.10 as a test target.

### LINKED ISSUE #10991: Run tests on Python 3.10
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Now that Python 3.10 is out we should be testing Conda regularly on it.

### Why is this needed

_No response_

### What should happen?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jezdez**
Fix #10991.

### CODE REVIEW

**Review by beeankha — APPROVED** [review]
:shipit:

**Comment by jezdez** [comment]
There are still some legitimate issues on Windows for this to merge.

**Comment by jezdez** [comment]
So trying this out more on a local Windows machine, I'm seeing the same error popping up as #11072 as a popup window (!) and preventing for example the `test_compile_pyc_sys_python` test to pass. I'm now wondering if all the other tests are red herrings of that particular issue.

**Comment by jezdez** [comment]
@beeankha All works!!!!

**Pull request merged**
