### PR TITLE
[conda clean] Filter out unwritable package caches

### PR DESCRIPTION
**Pull request by groutr**
Continued from #4426

### CODE REVIEW

**Comment by groutr** [comment]
I think we should consider having `rm_rf` raise exceptions when it fails rather than returning True/False.  I didn't change it here since it very likely will break other parts of conda.  Returning True/False encourages patterns like:
```
if rm_rf(directory):
    # yay? I succeeded!
    pass   # what else would I do?
else:
    # um something went wrong, but I'm clueless.
```

**Comment by groutr** [comment]
Another question I have is why PackageCache.all_writeable can raise an error.  If there are no writable caches, would it be better to return an empty sequence?  It seems like its intended usage is a sequence of packages to iterate through and perform some operations.  But since it can raise  error, it makes it cumbersome to use like
```
for pc in PackageCache.all_writable():
    ...
```
If there is no objection, I'm pretty sure it is safe to remove the exception raising.

**Comment by groutr** [comment]
@kalefranz Can I get some input on my last two comments?

**Comment by groutr** [comment]
Ping @kalefranz

**Comment by kalefranz** [comment]
superseded by #4620

**Comment by kalefranz** [comment]
> Another question I have is why PackageCache.all_writeable can raise an error. If there are no writable caches, would it be better to return an empty sequence?

There are several places that make the assumption of having at least one writable package cache.  It's something we could think about relaxing, but when I wrote that I wanted it to be an explicit error.

**Comment by kalefranz** [comment]
> I think we should consider having rm_rf raise exceptions when it fails rather than returning True/False.

I think I agree with you here.  Looking into it now...

**Comment by kalefranz** [comment]
Actually that return value is only for convenience.  All the various IOErrors and OSErrors are indeed raised as appropriate.  At least that's what I'm seeing in the code.  Are you seeing otherwise @groutr?

**Comment by kalefranz** [comment]
Back around the 4.1 timeframe we had a TON of trouble with this logic.  We *are* logging at info level when the path is actually not removed.  Before we change the logic here, I'd like to understand a few examples where it's still causing a problem.  Bottom line though, any error within `rm_rf` except `ENOENT` should be bubbled up and out.

**Pull request closed without merging**
