### PR TITLE
Add bash_completion for the conda command

### PR DESCRIPTION
**Pull request by tartansandal**
Implements the feature requested in #635. 

I'm not sure about integration (filesystem location, init) and where this should be documented.  Any advice most appreciated.

### CODE REVIEW

**Comment by tartansandal** [comment]
I'm thinking this code code could be appended to or sourced from `conda/shell/etc/profile.d/conda.sh`, perhaps with an appropriate guard to ensure $BASH_COMPLETION_VERSINFO is defined.

**Comment by kalefranz** [comment]
> I'm thinking this code code could be appended to or sourced from `conda/shell/etc/profile.d/conda.sh`

This should be wired into the output of `conda shell.bash hook`, but not `conda shell.posix hook`.

**Comment by tartansandal** [comment]
> This should be wired into the output of `conda shell.bash hook`, but not `conda shell.posix hook`.

Ah thanks. Will have a dig around to see how to do that :-) 

As a side note, I plan to close this PR once I get all this sorted, and resubmit a clean squashed PR.  Hopefully figure out why the CI builds are failing too.

**Comment by tartansandal** [comment]
> This should be wired into the output of `conda shell.bash hook`, but not `conda shell.posix hook`.

So subclassing `PosixActivator` from `conda/activate.py` is what you are proposing. Setting `self.hook_source_path` to an alternative file might work, though it is complicated by the need to source he POSIX script as well. This could cause problems with system-wide installs. I'm a little worried about the impact of `/etc/profile.d/`. Hmmm...
I'll pull apart the installer an see if I can come up with a sensible plan.

**Comment by tartansandal** [comment]
Just returned from that rabbit hole.  More complicated than I had hoped.  All I need to do now is write some tests :-)

**Comment by tartansandal** [comment]
This PR has been rebased into https://github.com/conda/conda/pull/9158.

**Comment by kalefranz** [comment]
> So subclassing `PosixActivator` from `conda/activate.py` is what you are proposing.

Yes, exactly. It was always part of the original intent that someday someone would come by and do exactly what you’re doing. By that, I mean the abstractions should be there so that it’s pretty straight forward to add in both bash completions and zsh completions. Apparently you’ve found that’s not the case.

If you’ve closed this PR out of frustration, that’s unfortunate. Might be Tuesday, but I intend to look at where you got hung up and figure out a solution. Conda needs completions for bash, and I’d like to see this move forward.

**Comment by tartansandal** [comment]
I've not abandoned the PR, just rebased it into a single commit. Got all
the tests running so I think this may be complete now. Hopefully that PR
can serve as a guide for someone who wants to implement zsh completion.

**Pull request closed without merging**
