### PR TITLE
Fix speed regression in build times

### PR DESCRIPTION
**Pull request by Bezier89**
Isolated the offending change from @msarahan PR https://github.com/conda/conda/pull/9030. Fixes https://github.com/conda/conda/issues/9082.

### CODE REVIEW

**Comment by msarahan** [comment]
We'll have to see how this works.  A lot of the changes in that PR were for the purpose of making the hints more helpful, and also to help the "freezing" be smarter.  Feeding the already-reduced index in here may hinder the former goal, but messing up the latter goal is fine - whatever path is fastest is the right one.  Thanks for the effort, either way.

**Comment by Bezier89** [comment]
@msarahan Is there a recommended alternative? Doubling of build times seems pretty egregious, especially just for better debug messages. At the very least, it could be behind a flag, and if you pass `--debug` (or whatever you deem appropriate) then it uses the new, slow behavior.

**Comment by msarahan** [comment]
I agree that the speed hit is too much for any convenience offered by the better hints.  We will keep looking at it.

**Comment by Bezier89** [comment]
@msarahan Thanks. FYI if we look at the conda-build test suite the slowdown is more like 3-4x. To put some hard numbers on it...

[conda-build test run before PR 9030](https://circleci.com/gh/conda/conda/20163?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
========================== slowest 20 test durations ===========================
93.09s call     tests/test_variants.py::test_inner_python_loop_with_output
69.96s call     tests/test_api_build.py::test_only_r_env_vars_defined
56.47s call     tests/test_subpackages.py::test_subpackage_recipes[python_test_dep]
48.37s call     tests/test_subpackages.py::test_toplevel_entry_points_do_not_apply_to_subpackages
45.61s call     tests/test_api_skeleton.py::test_pypi_with_version_inconsistency
35.83s call     tests/test_api_build.py::test_recipe_builds[r_test_import]
34.01s call     tests/test_variants.py::test_detect_variables_in_build_and_output_scripts
31.03s call     tests/test_api_build.py::test_build_with_activate_does_activate
27.86s call     tests/test_api_build.py::test_empty_package_with_python_and_compiler_in_build_barfs
26.39s call     tests/test_variants.py::test_build_run_exports_act_on_host
22.90s call     tests/test_api_build.py::test_recipe_builds[always_include_files_glob]
22.30s call     tests/test_api_build.py::test_setup_py_data_in_env
20.58s call     tests/test_api_build.py::test_run_exports
19.99s call     tests/test_cli.py::test_inspect_prefix_length
19.66s call     tests/test_subpackages.py::test_activation_in_output_scripts
19.23s call     tests/test_subpackages.py::test_subpackage_recipes[split_packages_hash_resolution]
19.17s call     tests/test_subpackages.py::test_subpackage_hash_inputs
18.19s call     tests/test_api_build.py::test_recipe_builds[source_setup_py_data]
17.64s call     tests/test_api_build.py::test_cmake_generator[3.6-64]
17.07s call     tests/test_api_build.py::test_recursion_layers
= 8 failed, 430 passed, 10 skipped, 1 xfailed, 429 warnings in 1102.00 seconds =
```

[conda-build test run from PR 9030](https://circleci.com/gh/conda/conda/20300?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link): 

```
========================== slowest 20 test durations ===========================
349.70s call     tests/test_variants.py::test_inner_python_loop_with_output
183.80s call     tests/test_subpackages.py::test_subpackage_recipes[python_test_dep]
168.35s call     tests/test_variants.py::test_build_run_exports_act_on_host
146.27s call     tests/test_api_build.py::test_recipe_builds[always_include_files_glob]
141.71s call     tests/test_api_build.py::test_run_exports
135.34s call     tests/test_subpackages.py::test_subpackage_recipes[split_packages_hash_resolution]
129.45s call     tests/test_subpackages.py::test_toplevel_entry_points_do_not_apply_to_subpackages
127.86s call     tests/test_api_build.py::test_only_r_env_vars_defined
115.47s call     tests/test_api_build.py::test_setup_py_data_in_env
112.40s call     tests/test_api_build.py::test_build_with_activate_does_activate
110.99s call     tests/test_variants.py::test_serial_builds_have_independent_configs
107.07s call     tests/test_api_build.py::test_recursion_layers
100.41s call     tests/test_api_skeleton.py::test_pypi_with_version_inconsistency
95.90s call     tests/test_api_build.py::test_env_creation_fail_exits_build
91.41s call     tests/test_subpackages.py::test_merge_build_host_applies_in_outputs
83.17s call     tests/test_subpackages.py::test_activation_in_output_scripts
82.81s call     tests/test_variants.py::test_get_package_variants_from_file
82.78s call     tests/test_api_build.py::test_disable_pip
78.20s call     tests/test_api_build.py::test_empty_package_with_python_in_build_and_host_barfs
76.51s call     tests/test_subpackages.py::test_subpackage_variant_override
= 8 failed, 430 passed, 10 skipped, 1 xfailed, 428 warnings in 3841.38 seconds =
```

Some recent conda-build test runs (after PR 9030):
[Exhibit A](https://circleci.com/gh/conda/conda/20465?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
`= 8 failed, 430 passed, 10 skipped, 1 xfailed, 426 warnings in 4313.98 seconds =`

[Exhibit B](https://circleci.com/gh/conda/conda/20635?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
`= 8 failed, 430 passed, 10 skipped, 1 xfailed, 430 warnings in 4411.45 seconds =`


[conda-build test run with my proposed change](https://circleci.com/gh/conda/conda/20643?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):


```
========================== slowest 20 test durations ===========================
69.05s call     tests/test_variants.py::test_inner_python_loop_with_output
47.33s call     tests/test_api_skeleton.py::test_pypi_with_version_inconsistency
44.41s call     tests/test_api_build.py::test_only_r_env_vars_defined
43.84s call     tests/test_subpackages.py::test_subpackage_recipes[python_test_dep]
39.83s call     tests/test_subpackages.py::test_toplevel_entry_points_do_not_apply_to_subpackages
37.17s call     tests/test_api_build.py::test_recipe_builds[r_test_import]
31.10s call     tests/test_api_build.py::test_build_with_activate_does_activate
28.68s call     tests/test_api_build.py::test_empty_package_with_python_and_compiler_in_build_barfs
25.13s call     tests/test_variants.py::test_detect_variables_in_build_and_output_scripts
25.13s call     tests/test_variants.py::test_build_run_exports_act_on_host
23.41s call     tests/test_api_build.py::test_recipe_builds[always_include_files_glob]
21.10s call     tests/test_api_build.py::test_setup_py_data_in_env
19.76s call     tests/test_subpackages.py::test_subpackage_variant_override
19.75s call     tests/test_subpackages.py::test_activation_in_output_scripts
18.71s call     tests/test_subpackages.py::test_subpackage_recipes[split_packages_hash_resolution]
18.52s call     tests/test_api_build.py::test_recipe_builds[unicode_in_meta]
18.23s call     tests/test_api_build.py::test_cmake_generator[3.6-64]
16.45s call     tests/test_cli.py::test_inspect_prefix_length
16.17s call     tests/test_api_build.py::test_recipe_builds[source_setup_py_data]
16.09s call     tests/test_subpackages.py::test_subpackage_hash_inputs
= 8 failed, 430 passed, 10 skipped, 1 xfailed, 429 warnings in 957.36 seconds ==
```

**Comment by soapy1** [comment]
@Bezier89 I submitted a PR to your branch https://github.com/Bezier89/conda/pull/2 it fixes the tests without changing the original assertions. I'm running some tests against them to ensure that this fixes the conda-build slowness. I would feel better about this PR getting merged if the tests weren't relaxed.....

**Comment by Bezier89** [comment]
Thanks @soapy1, went ahead and merged.

**Comment by soapy1** [comment]
oh no! sorry @Bezier89 broke a couple more tests. I'm working on a fix

**Pull request merged**
