### PR TITLE
Add versions to conda env

### PR DESCRIPTION
**Pull request by jerowe**
I originally opened this here:

https://github.com/conda/conda-env/pull/271

There is already versioning in conda envs, now it is a date time string, but I would like for it to explicit.

There are some failing tests, but I think they are the same tests that are failing in conda main.

https://travis-ci.org/conda/conda/jobs/173095724

### CODE REVIEW

**Comment by jerowe** [comment]
@kalefranz, could you take a look at this? I'm not sure why the tests are failing, and if it has to do with my changes or with the main conda.

**Comment by jerowe** [comment]
I also had this PR open at conda_env https://github.com/conda/conda-env/pull/272, and I'd like to get it in, but I need to get more familiar with these tests.

**Comment by kalefranz** [comment]
I know it's been a few days.  Doesn't mean we're ignoring this PR at all.  In fact, we really appreciate it.  I plan to review it and merge it in before we release 4.3.0.

**Comment by kalefranz** [comment]
I must have replied in the wrong place somewhere else.  These three test failures are time bombs.  Rebasing against master should fix all three failures.

**Comment by jerowe** [comment]
No worries. I had other things on my plate since I opened this in conda env anyways.

After this I will spam you with adding a summary spec! ;-)

**Comment by kalefranz** [comment]
@jerowe since we don't have any new tests written into this PR yet, can you start by pasting one ore more examples of using this?  Both the config files and the commands you need to run to exercise it.

**Comment by jerowe** [comment]
@kalefranz, real or contrived? I have plenty of them!

h2. Conda Env Yaml File

What I have now is this:

```
name: gencore_variant_detection_1.0
```

What I want is this:

```
name: gencore_variant_detection
version: 1.0
```

Then it would be:

```
conda env upload -f gencore_variant_detection-1.0.yml nyuad-cgsb
```
h2. Anaconda API 

When I run

```
anaconda show nyuad-cgsb/gencore_variant_detection_1.0
```
I get

```
Using Anaconda API: https://api.anaconda.org
Name:    gencore_variant_detection_1.0
Summary: Environment file
Access:  public
Package Types:  env
Versions:
   + 2016.10.11.1133
```

What I want

```
anaconda show nyuad-cgsb/gencore_variant_detection
```

```
Using Anaconda API: https://api.anaconda.org
Name:    gencore_variant_detection_1.0
Summary: Environment file
Access:  public
Package Types:  env
Versions:
   + 1.0
```

Also, I keep seeing multiuser conda environments coming up. I have those too. I deploy them with environment modules using the [easybuild](https://github.com/hpcugent/easybuild). I have a [PR[(https://github.com/hpcugent/easybuild-easyblocks/pull/950) in with easybuild .

gencore - modules

It looks like conda wants to move in a direction where it is supporting multiuser environments. I am very interested in how this will happen. Is it going to be an environment modules kind of deal?

**Comment by jerowe** [comment]
@kalefranz , I also really want summary and label keys. Summaries and labels are already supported through the anaconda api. 

Would those be of interest? If so, should I try for this PR or another one?

**Comment by kalefranz** [comment]
Ohhhhhh.  The first time I read through this, I thought you were after something completely different.  I think I understand now though.

The anaconda server/repo/cloud/.org team is different than this one, so we'd have to make a separate PR to anaconda-client (https://github.com/Anaconda-Platform/anaconda-client) and/or file a feature request for anaconda cloud/.org (https://github.com/Anaconda-Platform/support/issues) if the functionality isn't already implemented.  If it is though, that makes this all a lot easier :)

> real or contrived?

I'm fine with contrived, as long as it's functional and something I can incorporate into an integration test.  Good test cases exercise the bounds and edge cases of what you want.  *Complete* examples are good, because I do want to use them for tests.

Tests are incredibly important to me.  When a PR has tests that come along with it, it's much easier for me to click the merge button without having to contribute additional work to it.  Here's the reality: I trust that you're a competent person and your code works right now with the rest of the code that's surrounding it.  I don't consider tests accompanying the PR important to prove that the new feature works as intended.  Tests are important so that, someday when I change some other random part of the conda code that is six hops away from your feature, I can be sure that I'm not going to break your feature going forward.  Or when my code change does, I'm alerted that I've broken something, and I can go back and fix it.

> It looks like conda wants to move in a direction where it is supporting multiuser environments

Yes!!! Coming in 2016! (I promise.)

> Would those be of interest?

If you want them, they're worthy of consideration.

> If so, should I try for this PR or another one?

I just typed "Let's make it one PR if it's touching the same code."  I think I've changed my mind.  Let's get one of these through, and then add-ons should be easier.

I've got to be honest; I haven't spent much time with conda-env either before I started working on the conda project or in the last several months since I've been with Continuum.  It's something I absolutely intend to spend a substantial amount of time with, but the core conda code needs the higher priority at the moment.  In the meantime, you and @Korijn seem to be some of the most involved users of conda-env that are also capable of contributing code.  I genuinely appreciate all the help I can get :)

> `conda env upload`

This has always seemed out of place to me actually.  Is there an `anaconda env upload` or something equivalent?  I honestly don't know.  But it fits better with the `anaconda` command, because it's exclusively using the anaconda cloud/server/.org api.

The difference between conda and anaconda is REALLY confusing to outsiders, I know.  I'm planning on writing a blog post about it soon.

**Comment by jerowe** [comment]
@kalefranz , lets break this down. ;-) I'll add in a few sentences of my understanding, just to see if we're on the same page.

## Conda Env - General 

As I understand it, conda-env in general defines a set of specs for distributing  composable groups of software, or as I like to call them, software stacks. Each piece of conda env is using a different part of the conda and/or anaconda_client functionality. The install is using conda install, the export is using conda list, the upload is using anaconda_client.binstar, etc. I'm not entirely clear on the difference between anaconda and conda either, except that anaconda_client deals with anaconda cloud, and conda is a package manager. ;-)

## Conda Env Upload Functionality

The conda env upload functionality is simply a wrapper around the anaconda client. The code itself is making calls to anaconda_client.binstar. The functionality I have proposed (versions, summaries, labels) already exist in the anaconda API. I would like to add them to the conda-env specs. This is why I open PRs to get versions, labels, prefixs in. I could, theoretically, just make a call to the anaconda_client api, but I like having the additional functionality and defined specs in conda-env. More importantly, so do my users. ;-)

## Tests

I completely agree. TDD for life! I want to sit down and have a chance to understand the tests better. I'm not really a python developer, but I would like to improve, and right now my biggest hurtle is really getting into tests!

**Comment by jerowe** [comment]
I forgot to add in Multiuser functionality.

Technically, conda does not need any additional functionality to support multiuser environments. It just needs a bootstrap method to clean up file permissions.

I have my cluster with my main anaconda

```
/opt/anaconda2
```

`/opt/anaconda2` (at least in our setup, your mileage may vary ;-) ) should be read only, to users, and read/write to an admin.

The user needs to get /opt/anaconda2/bin in their path somehow. We use modules.

```
#Create directories
mkdir -p $HOME/software

#Initialize conda variables
conda config --add channels bioconda --add channels r
conda config --add create_default_packages setuptools
conda config --set allow_softlinks False
conda config --set always_copy True
conda config --add envs_dirs $HOME/.conda/envs

#User can take advantage of the /opt/anaconda, and can create their own envs
#Create environment
conda create -p $HOME/software/my_analysis
source activate $HOME/software/my_analysis
conda install -y necessary_packages

#Finish with this environment
source deactivate
```

**Comment by jerowe** [comment]
@kalefranz , I've had to update an internal application we have that builds software stacks with conda-env, and I spent a lot of time in the codebase this last week.

I have several ideas for refactoring. As it stands, there is some redundant code within conda-env. Some of the functionality written in conda-env was added into anaconda-client at some point, and should probably derive from there. I already made two such changes in this pull request. These were 

* replaced  the deprecated binstar_client.utils.get_binstar with binstar_client.utils.get_server_api
* replaced custom code for deriving user/package with the corresponding code in anaconda-client

In addition, I would like to refactor classes conda-env.utils.binstar.BinstarSpec, conda-env.utils.uploader.Uploader to avoid duplicate code. I think what would make the most sense would be to have a base BinstarSpec, and classes Uploader and Downloader that both inherit from BinstarSpec. Additionally, there are a few duplicates attributes between Uploader and conda-env.env.Environment, so Uploader should inherit from both Environment and BinStarSpec.

It would also be awesome if Environment was expanded with options for anything that is supported in anaconda-client. These would be summary, labels, user versioning. I'm not sure if it makes sense to explicitly defined dependencies in the anaconda-client, since they are already defined as a function of the environment.

**Comment by jerowe** [comment]
@kalefranz , I see there is lots of activity in conda!

How is this PR looking? I would really like to add labels and summary as well.

**Comment by jerowe** [comment]
There have been quite a lot of changes to the conda/conda-env codebase, so I'm closing this to reopen.

**Pull request closed without merging**
