### PR TITLE
Support CUDA detection on WSL

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Support CUDA detection on WSL. We are just adding a known location for `libcuda.so`, which corresponds to the WSL path (WSL is detected as Linux).

Closes https://github.com/conda/conda/issues/11615
Closes https://github.com/conda/conda/issues/11488

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/master/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by kenodegard** [comment]
Should probably include a news snippet?

**Comment by XuehaiPan** [comment]
`libcuda.cuInit()` won't success when `CUDA_VISIBLE_DEVICES` is set to empty string. We need to unset it before calling `cuInit()`.

**Comment by jaimergp** [comment]
> Should probably include a news snippet?

Added!


> `libcuda.cuInit()` won't success when `CUDA_VISIBLE_DEVICES` is set to empty string.

Thanks! Probably worth fixing in a separate PR!

**Comment by jaimergp** [comment]
pre-commit.ci autofix

**Comment by jaimergp** [comment]
pre-commit.ci autofix

**Comment by jaimergp** [comment]
@kenodegard I think this is good to merge now!

**Pull request merged**
