### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by alanhdu**

### CODE REVIEW

**Comment by alanhdu** [comment]
I've doubled-checked that `conda-env` and `conda-build` don't use any of the code here. Let me know if there are other projects that use this code that I don't know about.

**Comment by kalefranz** [comment]
@ilanschnell Can you review at your convenience?

**Comment by msarahan** [comment]
win_batlink might actually be important, even if it is currently unused.  We have sporadic permissions issues on Windows associated with trying to move/remove files that are in use.  This batlink creation here is one good workaround, and I don't know why it isn't used.

**Comment by ilanschnell** [comment]
Yeah!  Please remove the dead code.

**Comment by ilanschnell** [comment]
I particular I'm happy about the `app_` functions in `conda.api` being finally removed!

**Comment by kalefranz** [comment]
I want to hold merging this PR until right after we release `4.1.0` so that we have some time working with it.

@msarahan re `win_batlink`, if it's not used right now, can always come back and add it back in.

**Comment by kalefranz** [comment]
Actually, `4.1.0` could be another week off, with another release candidate, so this is probably a good time to merge.

**Comment by ilanschnell** [comment]
Why doesn't this PR not also remove `conda.api.app_get_index()` and `conda.api.app_is_installed()`?

**Comment by kalefranz** [comment]
@alanhdu did you come across a use for those functions somewhere?  @ilanschnell is also a big fan of removing dead code 😄

**Comment by ilanschnell** [comment]
I've created https://github.com/conda/conda/pull/2374/files, which removes more dead code.

**Pull request merged**
