### PR TITLE
Add Package object for loading and representing meta data

### PR DESCRIPTION
**Pull request by tswicegood**
Simple refactoring of code with one new piece of functionality: `conda install --offline` now treats legacy packages without a `depends` attribute as having an empty `depends` as originally discussed in https://github.com/ContinuumIO/anaconda-issues/issues/236.

### CODE REVIEW

**Comment by tswicegood** [comment]
Moving the test fixes over to #1079.  Hopefully that gets resolved so this can be merged with a clean test.

**Comment by tswicegood** [comment]
@ilanschnell @teoliphant @asmeurer do you guys have any thoughts on this change?  It addresses the issue raised in https://github.com/ContinuumIO/anaconda-issues/issues/236 around empty `depends` and provides the start to a tested `Package` object that can be used to provide a Python representation of a conda package.

**Comment by ilanschnell** [comment]
Why is it necessary to have a new `Package` object?  There is already such in object in `conda.resolve`.

**Comment by tswicegood** [comment]
@ilanschnell `conda.resolve.Package` has two issues:

* It's in the wrong place.  `conda.resolve` is not an immediately obvious place for a model object to be located.  Case in point, I didn't realize it was there until I searched through the code after writing this to see if I had duplicated something.  Thinking in terms of the Python API, things should be placed where they logically fit.  The current implementation seems to be there because it's only used inside `conda.resolve`.
* The current object provides comparison overrides to simplify comparing two packages.  That's useful, but isn't relevant to what this is solving.  As I noted [here][1], the plan is to refactor that code to use `conda.packages.Package` instead of duplicating the code, but that shouldn't stand in the way of this.

Having a `conda.packages` module provides a place to store all of the Python APIs related dealing with packages.  Note `from_file` in this PR which adds the ability to load a package from a given file and raises a `CondaException` sub-class when it fails.  Further enhancements that I can think of are loading from a `tar.bz2` file and a `from_package_cache('some_package')` function just off the top of my head.  Neither of those are relevant to this change, however, so I didn't add them.

[1]: https://github.com/conda/conda/pull/1076/files#diff-52a8935af92ea699b0cbb5feb84c19a2R157

**Comment by teoliphant** [comment]
@tswicegood I am generally not going to be in favor of just adding new objects to solve issues.   However, in this case, since we already have a "misplaced" package object, we should instead create a Package object in the right place as you have done --- and use it to solve the problem.   We *do* need to later remove the conda.resolve.Package object (as you have noted in the *TODO* which is helpful.  @ilan do you have further comments?  If not, let's merge this.

**Comment by ilan** [comment]
You have a typo in the address. You want ilan schnell.

On Wed, Jan 7, 2015 at 8:28 AM, Travis E. Oliphant <notifications@github.com

**Comment by ilanschnell** [comment]
At this point, since the original objective (to add the missing `depends` key, if not present) was fixed in https://github.com/conda/conda/commit/ccb98040fced94256c7a7f2a6a2cd07dff62eabd, this PR is only about refactoring.  So why not refactor it the right way, i.e. extend the existing Package object with the missing functionality, instead of refactoring (the refactor) again later.

**Comment by pzwang** [comment]
I am confused by this discussion.

@teoliphant You seem to basically agree with multiple aspects of what @tswicegood has done, but preface it all by disagreeing philosophically with the approach? (or cautioning that in general you are -1 on using objects to communicate modularity in code, but agree with it here? or just stating that you don't like Java-style code where everything has to be an object? :-)  From my reading of the code, the existing `resolve.Package` object is really a mechanism for the resolver internals - i.e. it could just be as suitably named `resolve._Package` or even created as an inner class of `resolve.Resolve`.  Outside of dependency resolution, this `Package` class is not used at all inside conda to communicate conda's idea of "a package"; that is done by just passing dictionaries around.

@ilanschnell I think there is no reason not to extend the current Package class, *if* it gets moved out into its own module.  Looking over `conda/tests/`, the only tests are for the resolver, but the Package class itself needs basic tests to validate that a correct and coherent Package object is presented to the rest of the code, under all the circumstances that might exist in the wild.  This `depends` key thing is just one example of the kinds of things that might arise in the future.

**Comment by tswicegood** [comment]
Sorry guys -- was out yesterday and am just getting back to this.

*Note: I'm using "package" to refer to the concept of a package -- it's means to be abstract.  If you see `Package`, it refers to the object created in this PR.

To echo @pzwang's comments, I'm not sure I follow @teoliphant.  Let's set aside that `Package` is defined as an object and looking at it more abstractly, I'm not sure I see a reason to dislike creating a data structure that can concretely be called a package.  Encapsulation of this sort along with testing of those data structures is what allows a programmer to know that a structure they can reason about it in certain ways.  In Python, I know that I can do `"foo" in some_dict` when I have a dictionary; that I can slice lists when I have a list; and in this case that a `Package` always has an array of dependencies.  The plan is to take that further to define explicitly the behavior and data structures relevant to a `Package`, but those can be added as needed.

Currently, there is no defined data structure that represents a package.  The closest thing is that we assume that `index.json` files in a certain place have certain characteristics, so if we load them we have something we can infer is a package.  The original issue I opened showed a case where that data was incorrect which lead to the issue that @ilanschnell patched.  Which brings me to that patch.

ccb98040fced94256c7a7f2a6a2cd07dff62eabd introduces another issue: now there are two different versions of a package inside conda.  There are the five different places where an `index.json` file is opened and loaded via `json.load`.  Four of those code paths are going to have `depends` based on what's in the file.  One, however, will always have `depends`.  This separate code path means that we can't verify that a package really is a package without checking first.

This PR does *not* solve that problem yet, but it's meant to serve as a foundation to build toward removing that code duplication.  In attempting to strategically refactor, my goal isn't to solve each problem entirely on the first go.  Instead, I'm focusing on issues as they arise and addressing the underlying issue.  @ilanschnell is correct, ccb98040fced94256c7a7f2a6a2cd07dff62eabd solves the explicit issue that was caused in one explicit code path, but at the expense additional technical debt (we have to keep track of which code path the package information comes from to know what information it contains).  This PR strikes at the root cause -- the lack of a custom data structure that is verifiably a package.

(Note: posting without edits so I can jump on this call -- may edit later)

**Comment by teoliphant** [comment]
@pzwang @tswicegood My point is just that don't assume because I'm fine with this refactoring of the Package object that I will support *all* changes that introduce new objects.   Generally, I prefer procedural approaches with existing objects unless introducing the object adds real mental value that multiple programmers agree on --- and I will be pretty picky about whether it adds value or not.   

To be clear, in conda, I think there are still opportunities to add objects that will have real and defensible mental value (environment objects, for example) for future maintainers.     

In this case, there is *already* and object and you are just refactoring it, so I'm not opposed at all.  However,  @ilanschnell fixed the actual issue with a simpler change and so converts this PR into a refactoring of the Package class --- and so it's arguable that the refactoring should be finished so that we don't have two Package objects.

**Comment by tswicegood** [comment]
> Generally, I prefer procedural approaches with existing objects unless introducing the object adds real mental value that multiple programmers agree on --- and I will be pretty picky about whether it adds value or not.
> 
> To be clear, in conda, I think there are still opportunities to add objects that will have real and defensible mental value (environment objects, for example) for future maintainers.

I feel as though I made a pretty good argument for why having something as fundamental as a package defined as an object is a good thing here.  If you feel my argument is lacking, I would love an opportunity to discuss that.

> However, @ilanschnell fixed the actual issue with a simpler change and so converts this PR into a refactoring of the Package class --- and so it's arguable that the refactoring should be finished so that we don't have two Package objects.

I do want to call attention to the timing of that fix in case it was overlooked.  The commit was done the day after this PR was opened and brought to @ilanschnell's attention.  He fixed it underneath this code without any input, or even notification that it had happened.  If not for that duplication of effort after this was already working, there would not be a fix.  It's hard to address systemic problems through refactoring (in this case, "what constitutes a package?") if band-aids are going to be put on each isolated case as a light is shown on it.

**Pull request closed without merging**
