### PR TITLE
Core solve cleanup 2

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by jakirkham** [comment]
So what should we be using [instead of `conda.config.subdir`]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/6495ba546d6c136c434b83a4fde9eba5e02b107e/recipe/upload_or_check_non_existence.py#L84 )?

**Comment by jakirkham** [comment]
cc @msarahan (in case there is a `conda-build` interface we could use here).

**Comment by kalefranz** [comment]
Anything you need should be in `conda.exports`, including the `context` object.

**Comment by kalefranz** [comment]
So use `context.subdir` or `context.subdirs`

**Comment by jakirkham** [comment]
Ok, I think we have workarounds in flight for this. So feel free to ignore.

**Comment by jakirkham** [comment]
Sorry I think our comments got interleaved, but GitHub is only showing me them now (possibly because I closed my laptop at some point between talks?). Definitely appreciate the suggestions @kalefranz. If you are interested, here are the PRs we used to solve this issue ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/97 ) ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/8 ). If anything sticks out to you, please feel free to let us know.

**Comment by kalefranz** [comment]
Just looked at those two PRs.  I guess that works too, as long as @msarahan has no objections.

During the whole `import pip` fiasco, I made https://github.com/conda/conda/issues/7059.  Directly relevant here.  `import conda` *is* supported!

**Pull request merged**
