### PR TITLE
Remove package and bundle

### PR DESCRIPTION
**Pull request by kalefranz**
This functionality has been labelled EXPERIMENTAL for some time.  I think it's a valuable feature for some people, but it more appropriately belongs in conda-build.

@msarahan Would you like me to create PRs within conda-build for this code?  I'm guessing there's a lot of code that I've ripped out here that conda-build actually uses...

### CODE REVIEW

**Comment by msarahan** [comment]
@kalefranz no thanks.  These look like they deal with things at the environment level.  Conda build deals pretty strictly with the package level, and I'd like to keep it that way if possible.  Otherwise, it will be even more tied into conda/conda-env, or worse, will grow its own independent logic for environments.

If @csoja or any higher up has other directions that push conda-build in this direction, I'll reconsider.  For now, I think it might be best to dsicuss this with the Anaconda Project team, and see where it fits.

**Comment by kalefranz** [comment]
Yeah I'll go back and look at what's in here again. 

The reason it seemed like it belongs in conda-build to me is all the logic with *building* tarballs. I guess that's where I made the distinction. I'll take another look though.

**Comment by asmeurer** [comment]
The `-w`, `-r`, and `-u` flags were all useful. Are those being replicated somewhere else?

**Comment by ijstokes** [comment]
@kalefranz and @msarahan I regularly used the `conda package` feature.  I found it to be a simple way to install stuff manually into a conda environment (typically autoconf-based compiled things) following the code's `INSTALL.TXT` file, and then when I was done and it was working I could package it all up into a conda package with this command.  This seems like a good capability to give people as an alternative to creating a formal recipe for a particular package.

**Comment by vogxn** [comment]
The `bundle` command was very handy to export a packaged binary environment and distribute it across jobs running in an MR like framework. I was using this feature with a distributed hadoop job. Unfortunately this does not work anymore. I checked that `conda build` does not have an equivalent `bundle` subcommand. A raw export using `tar` is not capable of skipping source files and git repos in the managed conda environment that was done by `conda bundle`. 

Is there an alternate way to perform this? Or am I better off patching my conda with the bundle subcommand here?

**Comment by kalefranz** [comment]
For now, go ahead an patch.  Also consider submitting a pull request to conda-build if you want to.  Of course, @msarahan will require tests, which were never written; you'd have to write them yourself.

@msarahan has expressed willingness to merge a PR for `conda bundle` since it has to do with tarball creation.

For the record, `conda package` is back in conda proper.

**Pull request merged**
