### PR TITLE
Enable support for loongarch64.

### PR DESCRIPTION
**Pull request by liuxiang88**
Signed-off-by: liuxiang <liuxiang@loongson.cn>

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by willliu** [comment]
@jezdez  Dear Janis, last year when I attempted to modify py-cpuinfo, I encountered some uncertainties about the some details, so I halted the processes. 

Now @liuxiang88 is the Loongson company's official person, please abandon my pull request https://github.com/conda/conda/pull/10866, and let @liuxiang88  take over this issue and update https://github.com/workhorsy/py-cpuinfo/pull/166 as well. 

Also, @loongson-zn is the Loongson company's official person as well to clear some doubts.

**Comment by travishathaway** [comment]
@liuxiang88,

Support for Loong architecture has been added in py-cpuinfo:

https://github.com/workhorsy/py-cpuinfo/pull/194

**Comment by Duanexiao** [comment]
现在有miniconda loogarch64的安装包吗?

**Comment by jezdez** [comment]
> 现在有miniconda loogarch64的安装包吗?

No, there isn't one since support has not been merged yet.

**Comment by jezdez** [comment]
For the record, this is blocked by a missing release of the py-cpuinfo package we use.

**Comment by cheungxi** [comment]
> For the record, this is blocked by a missing release of the py-cpuinfo package we use.

In py-cpuinfo pinned issue，" cannot currently afford to donate any time to work on this project"
https://github.com/workhorsy/py-cpuinfo/issues/213

**Pull request closed without merging**
