### PR TITLE
Handle both file-based channels and explicit file-based URLs

### PR DESCRIPTION
**Pull request by mcg1969**
See #2805, #2781. 

@kalefranz, we need to find a way to add an integration test for file-based channels.

### CODE REVIEW

**Comment by mcg1969** [comment]
@jarondl, @jjhelmus, this is almost done. I've successfully improved the integration testing to create a new channel on the fly and attempt an install from there. @kalefranz check it out

**Comment by jarondl** [comment]
Looks very good

**Comment by kalefranz** [comment]
This needs rebased since we changed some logic on repodata.json out from underneath it.  @mcg1969 I doubt you're up and working on this.  I'm going to rebase and rewrite history.  Hopefully you don't have commits that aren't yet pushed.

**Comment by mcg1969** [comment]
Thanks for the rebase. I don't tend to keep local commits around; GitHub is too good of a backup system not to use it.

**Pull request merged**
