### PR TITLE
Improve fall-back comparison when version strings do not conform to PEP 386

### PR DESCRIPTION
**Pull request by ukoethe**
This PR resolves problem B in issue https://github.com/conda/conda/issues/1590 and possibly https://github.com/conda/conda/issues/915.

### CODE REVIEW

**Comment by asmeurer** [comment]
Can you add a few tests for the function?

**Comment by ukoethe** [comment]
Is there an exisiting test I can extend (I haven't found any), or do I have to write it from scratch?

**Comment by asmeurer** [comment]
I just mean tests for `version_to_list`, so that I can visually see that it does what it says it does.

**Comment by ukoethe** [comment]
Argh, they changed comparison semantics in Python 3. Good you asked for a test!

**Comment by ukoethe** [comment]
I retracted this PR in favor of improved PR https://github.com/conda/conda/pull/1601

**Pull request closed without merging**
