### PR TITLE
Use `splitlines` to break up multiple lines

### PR DESCRIPTION
**Pull request by jakirkham**
Continuation of the work here ( conda/conda-build#516 ) except with `conda` proper.

### CODE REVIEW

**Comment by jakirkham** [comment]
@asmeurer, do you have any feedback on this or is it ready to be merged?

**Comment by jakirkham** [comment]
Tried to trick appveyor into restarting as it seemed to hang for a week.

**Comment by asmeurer** [comment]
AppVeyor only runs one build at a time unfortunately.

**Comment by asmeurer** [comment]
It does seem to be broken, though.  Shame.

**Comment by jakirkham** [comment]
Fortunately, this time, there was a log. However, I don't know how helpful it is.

**Comment by asmeurer** [comment]
That non-log is exactly why I'm saying it's broken. Somehow it started but nothing happened.  Maybe our Miniconda installers are broken?

**Comment by asmeurer** [comment]
But they are the old installers. I don't see how they could have broke.

**Pull request merged**
