### PR TITLE
Don't add back orphan_precs that already exist

### PR DESCRIPTION
**Pull request by soapy1**
Addresses https://github.com/conda/conda/issues/8831

### CODE REVIEW

**Comment by msarahan** [comment]
What was the symptom here?  It's a good fix, but I'm not sure how the problem manifested itself?

**Comment by soapy1** [comment]
I was able to reproduce the problem when I was updating my packages while alternating between channels. So something like:
```
<fresh install>
$ conda update conda-build -c conda-forge
$ conda update --all
```

resulting in an inconsistent env. As part of conda's recovery from this it removes that prec, does the solve and then adds it back. Except when it was adding it back, it was also adding all of it's dependencies that have already been solved for in the update solve. So, conda was thinking that it was gong to newly install a bunch of packages instead of updating. This caused the record action to try to create some new prefix records for these thought-to-be-newly-but-actually-not package. So this assert https://github.com/conda/conda/blob/master/conda/core/prefix_data.py#L91 was triggered

**Comment by msarahan** [comment]
Ah!  Good hunting!  Can you add a bit to the end of that assert to describe the bad condition, so that we know which assertion is failing better next time?

``assert prefix_record.name not in self._prefix_records, "Prefix record insertion error: a record with name %s already exists in the prefix.  This is a bug in conda. 
 Please report it at https://github.com/conda/conda/issues" % prefix_record.name``

Aside from that, is there a simple enough reproducer of the failure to add a test?

**Comment by soapy1** [comment]
Can do! I'm still trying to figure out a representative test case. I was thinking of calling solve with a ssc that has some add_specs_back_map

**Pull request merged**
