### PR TITLE
misc.py windows exception fix

### PR DESCRIPTION
**Pull request by bradsaracik**
Attempted a clone on Windows and had an exception on 243:`os.symlink(os.readlink(src), dst)`,
> "AttributeError: ‘module’ object has no attribute ‘symlink’"

April 2015 github entry on corresponding code suggested the fix adopted here (replace with try, except and windows code) https://github.com/gcodeforks/apptrace/issues/8

I confirm the clone on Windows worked. I cannot foresee any other issues.
Note: First github pull request, so please let me know if I can do anything clearer/better

### CODE REVIEW

**Comment by mbargull** [comment]
Looks like the proper workarounds are already in `conda.gateways.disk.link` but just weren't used here:
 * https://github.com/conda/conda/blob/4.4.10/conda/gateways/disk/link.py#L348
 * https://github.com/conda/conda/blob/4.4.10/conda/gateways/disk/link.py#L72

Can you import them at https://github.com/conda/conda/blob/4.4.10/conda/misc.py#L23 and then use those? Also, you should target the `4.4.x` branch as detailed here: https://github.com/conda/conda/pull/6855#issuecomment-364130047.

**Comment by mbargull** [comment]
Oh, regarding the retargeting to `4.4.x`, you of course don't need to cherry pick any commit if you just add a new one.

**Comment by bradsaracik** [comment]
submitted #6870 to replace this, because I did master:misc.py in web github and I just didn't trust how to switch to 4.4.
Sorry for any inconvenience

**Comment by kalefranz** [comment]
superseded by #6870

**Pull request closed without merging**
