### PR TITLE
activate.bat: Set codepage to CP_ACP

### PR DESCRIPTION
**Pull request by mingwandroid**
@kalefranz, @csoja would like a test Miniconda release containing this change. This is an attempt to fix https://github.com/ContinuumIO/anaconda-issues/issues/1410. If you would prefer not to merge it then I'll make a local patch for conda for @ilanschnell to try out.

### CODE REVIEW

**Comment by kalefranz** [comment]
@mingwandroid What's your confidence at this point for having this in the next conda patch release?

**Comment by mingwandroid** [comment]
I've had one positive report, no negative reports. Not a brilliant sample!

Hard to call at this point. I'd love more feedback since I asked about 6 people for some!

**Comment by kalefranz** [comment]
merged via #4760

**Comment by methane** [comment]
This patch doesn't work on some codepages. Even worth, it breaks Python 3.6+.
https://bugs.python.org/issue33865

**Pull request merged**
