### PR TITLE
Add conda recipe for building a conda package of conda

### PR DESCRIPTION
**Pull request by tswicegood**
*<< insert yo dawg reference here >>*

I want to create a dev channel on binstar.org for conda releases so pushes to master can be pushed into a channel for early adopters.  The first step toward that is getting a reproducible way to build conda with conda build.  This PR starts that process, but it's not finished.

## Outstanding Issues
* [x] Get scripts to install correctly
* [ ] Ensure proper build on Windows
* [ ] Ensure proper build on OS X

### CODE REVIEW

**Comment by tswicegood** [comment]
Note, the vast majority of these commits are related to working around issues on binstar to work there *and* to test.  Unfortunately, it doesn't look like binstar supports passing environment variables correctly to build / test commands, so I've had to revert to simply `conda build --no-test`.

@srossross if you have any ideas on how I might be able to get `CONDA_BUILD_TEST=1 conda build ...` to work properly on the various platforms, I'd love to hear your ideas.

**Comment by tswicegood** [comment]
@ilanschnell something odd is happening and I'm not sure what to do about it.  Currently the output from `conda build` shows that `activate`, `deactivate`, and `conda` are setup properly.  However, when I unpack the package tarball that's created the only directories present are `lib` and `info`.

Would you mind taking a look at the build script and telling me if I've missed something specific?  I've copied the stdout into [this gist][1] if that's helpful.

[1]: https://gist.github.com/tswicegood/ff68679858703c799b4b

**Comment by ilanschnell** [comment]
Hmm, not sure all these scripts are created by `setup.py` there is nothing special going on here.  The only thing I can think of is that maybe these files (or symlinks) already exist before running the `build.sh`, such that conda-build does not recognize them as new files.

**Comment by tswicegood** [comment]
@ilanschnell just popped back over here to say exactly that.  Talked with @asmeurer on chat and that was the conclusion.  Inside conda-build when it creates the environment to install into `conda` is going to be symlinked in, which means it's going to be in the original list of files.  I think we'll have to modify `conda-build` for this to work.

**Comment by tswicegood** [comment]
Ok -- I've verified that the symlinks for the various script files are overwritten in `~/anaconda/envs/_build/bin`.  Going to play modifications to `conda-build` that allow you to specify files to always include regardless of whether they were there at the start.

**Pull request closed without merging**
