### PR TITLE
Locking for activate and deactivate scripts [WIP]

### PR DESCRIPTION
**Pull request by johanneskoester**
Once ready, this should solve https://github.com/conda-forge/r-base-feedstock/issues/67.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Missing dependencies are added to conda-forge now: https://github.com/conda-forge/staged-recipes/pull/8552

**Comment by kalefranz** [comment]
1. What is the performance impact? `conda activate` needs to be VERY fast because it's typically executed for every new terminal a user opens. Anything over about 500 ms is a total non-starter for most users.
2. Not only does this introduce a new external dependency, it's a notoriously fragile namespace dependency. In general I'm a fan of the `flufl.lock` library, but from my recollection it needs to be evaluated for Windows systems, and it should be vendored if moving forward in this direction.

**Comment by kalefranz** [comment]
Is there any way to accomplish the same goal without affecting ALL users, whether they actually need the feature or not. In general activation shouldn't need to have side effects like writing to disk, and therefore there shouldn't be any concurrency issues. The general case is explicitly designed that way. However certain activation scripts do have side effects. Maybe the locking is best handled on a case-by-case basis for those specific packages that actually need it? Seems unfair to impart that cost on all users whether they need to feature or not.

**Comment by mingwandroid** [comment]
Please stop talking about performance until you have correctness addressed.

**Comment by msarahan** [comment]
As I mentioned here:

https://github.com/conda-forge/r-base-feedstock/issues/67#issuecomment-502523856

I think that Ray is correct here.  Where there are activation scripts that execute arbitrary shell scripts, we must default to safety (locking).  We can and should provide a way for packages to indicate that they are safe, though.  Having the JSON activation would go a long way towards safety by default, but there's manual metadata we can add before then.

**Comment by travishathaway** [comment]
This pull request has become stale and is therefore being closed. Please re-open if you would like to continue development on this.

**Pull request closed without merging**
