### PR TITLE
conda xontrib

### LINKED ISSUE #5160: conda xontrib xonsh wrapper
Make a wrapper for xonsh.

### PR DESCRIPTION
**Pull request by kalefranz**
supersedes #4227
resolves #5160

### CODE REVIEW

**Comment by kalefranz** [comment]
@scopatz giving this a try under the new framework.  Pretty simple so far.

Right now I'm writing a single temporary file that's being sourced as a whole.  Was having problems getting everything working, and this was the first that actually stuck.

Now that I have it working though, I'll try to separate out setting and unsetting environment variables along with sourcing individual files (i.e. no more temporary file).

**Comment by kalefranz** [comment]
This code is ready to go, at least as an intermediate solution.  (We still need to stop doing the write-to-file part; it's a future TODO.)  Merging now so I can bring this code in to other working branches.

**Comment by scopatz** [comment]
Thanks @kalefranz! I really appreciate it

**Comment by kalefranz** [comment]
Absolutely!  I know it's been a long time coming.  I'm really hoping to release 4.4.0 (it might be beta0 or rc0) into canary on Monday.

This was really just my best effort first take.  I'm guessing there are plenty of improvements that could be made to the conda.xsh file.

**Comment by scopatz** [comment]
Understood, I'll try put in PRs for things I think can be improved :)

**Pull request merged**
