### PR TITLE
Use markdown links for issue numbers in changelog

### PR DESCRIPTION
**Pull request by groutr**
It makes reading about issues/PRs much more friendly.

cc: @kalefranz

### CODE REVIEW

**Comment by kalefranz** [comment]
Hey Ryan, have you seen https://github.com/conda/conda/releases ?

I try to keep that maintained.  And we're starting to do better with tagging so we can eventually make our changelog updates more automated.  In the meantime, actually maintaining these links for new entries is sure a lot of extra copy paste work for me :-|

**Comment by groutr** [comment]
@kalefranz  I am aware of it.

There was zero copy/paste involved in this PR.  All that is needed is an editor that can do regex find & replace.

**Comment by groutr** [comment]
ping @kalefranz, what is the state of this PR?

**Comment by kalefranz** [comment]
Yeah, let's go with it.  Except I just tried pulling it back to 4.3.x so it can be merged up appropriately, and there are more merge conflicts than I'd like to deal with.  Can you checkout the 4.3.x branch, apply your script, and then make a PR with the 4.3.x target?  Then we'll merge it up and do the same thing for 4.4.x, and then master?

**Comment by kalefranz** [comment]
@groutr I'm going to decline this PR.  But checkout the 4.3.x branch, run your script on that changelog, and make a PR with 4.3.x as the target.  Then we'll merge it up to master.  And take care of the additional changelog entries along the way.

If you have a sed command or something else that can idempotently be ran against the changelog, that would also be very helpful for me :)

**Comment by groutr** [comment]
@kalefranz Alright.  I'll commit a script to the utils directory.

**Pull request closed without merging**
