### PR TITLE
fix #5298 record has 'build', not 'build_string'

### LINKED ISSUE #5298: Conda does not respect exact matchspecs
Really strange here, but I've followed this as far as I can in conda-build, and I think it's in conda.

I have these specs:

```
ipdb> sub_build_ms_deps
[MatchSpec('openssl 1.0.2k 1'), MatchSpec('zlib 1.2.8 3'), MatchSpec('bzip2 1.0.6 3'), 
MatchSpec('ncurses 5.9 10'), MatchSpec('curl 7.52.1 0'), 
MatchSpec('llvm 4.0.0 h95a1600_0'), MatchSpec('cmake 3.6.3 0'), 
MatchSpec('xz 5.2.2 1'), MatchSpec('expat 2.1.0 0')]
```

These get fed into conda's install_actions function here: https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L655

```
ipdb> n
> /home/msarahan/conda-build/conda_build/build.py(1042)build()
   1041                     index, index_timestamp = get_build_index(m.config, m.config.build_subdir)
-> 1042                     build_actions = environ.get_install_actions(m.config.build_prefix, index,
   1043                                                                 sub_build_ms_deps, m.config,
```

Now I'm not 100% certain that the package exists in repodata yet.  I know that it does on disk, but not sure about in-memory.  It should, but I'm not certain.

My confusion is why with that matchspec for llvm in particular, build string h95a1600, should I *ever* be given a non-matching build string?

```
ipdb> build_actions
defaultdict(<type 'list'>, {u'op_order': ('CHECK_FETCH', 'RM_FETCHED', 'FETCH', 'CHECK_EXTRACT', 'RM_EXTRACTED', 'EXTRACT', 'UNLINK', 'LINK', 'SYMLINK_CONDA'), 'SYMLINK_CONDA': ['/home/msarahan/miniconda2'], 'PREFIX': '/home/msarahan/miniconda2/conda-bld/llvm_1494542025512/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla', 
'LINK': [
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'bzip2-1.0.6-3', name=u'bzip2', version=u'1.0.6', build_string=u'3', build_number=3, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'expat-2.1.0-0', name=u'expat', version=u'2.1.0', build_string=u'0', build_number=0, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'local', dist_name=u'llvm-4.0.0-heefb760_0', name=u'llvm', version=u'4.0.0', build_string=u'heefb760_0', build_number=0, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'ncurses-5.9-10', name=u'ncurses', version=u'5.9', build_string=u'10', build_number=10, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'openssl-1.0.2k-1', name=u'openssl', version=u'1.0.2k', build_string=u'1', build_number=1, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'xz-5.2.2-1', name=u'xz', version=u'5.2.2', build_string=u'1', build_number=1, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'zlib-1.2.8-3', name=u'zlib', version=u'1.2.8', build_string=u'3', build_number=3, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'curl-7.52.1-0', name=u'curl', version=u'7.52.1', build_string=u'0', build_number=0, with_features_depends=None, base_url=None, platform=None), 
Dist(_Dist__initd=True, channel=u'defaults', dist_name=u'cmake-3.6.3-0', name=u'cmake', version=u'3.6.3', build_string=u'0', build_number=0, with_features_depends=None, base_url=None, platform=None)]})
```

Note the relevant bit in the install actions:  ```dist_name=u'llvm-4.0.0-heefb760_0', ```

This is with conda 4.3.17.

### PR DESCRIPTION
**Pull request by kalefranz**
fix #5298

@mcg1969 Could this be the cause (and fix) for #5298?

### CODE REVIEW

**Comment by kalefranz** [comment]
CC @msarahan It's not too late to get this into Anaconda 4.4.

**Comment by msarahan** [comment]
Good find.  Sorry I didn't see that when I was mucking around in there.

**Comment by mcg1969** [comment]
This just affects the prioritization order for packages that have already matched. I don't think it will fix match failures.

**Comment by kalefranz** [comment]
> This just affects the prioritization order for packages that have already matched. I don't think it will fix match failures.

That might be enough, and the actual cause of #5298.  I added extra tests assuming the cause was a match spec failure, but that wasn't the case.

**Pull request merged**
