### PR TITLE
Allow profile.d/conda.sh to pass if set -eu on

### PR DESCRIPTION
**Pull request by ColemanTom**
As no default value for PS1 is defined, if a script has `set -eu` enabled, sourcing conda.sh
will cause a failure. This change provides a default empty string value for PS1.

I believe this addresses https://github.com/conda/conda/issues/8186

### CODE REVIEW

**Comment by ColemanTom** [comment]
> We require contributors to sign our Contributor License Agreement, and we don't have one on file for @ColemanTom. In order for us to review and merge your code, please e-sign the PDF at https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement. We then need to manually verify your signature. We will ping the bot to refresh the PR status when we have confirmed your signature.

This was signed prior to submitting the merge request.

**Comment by jezdez** [comment]
@anaconda-issue-bot check

**Comment by jezdez** [comment]
> > We require contributors to sign our Contributor License Agreement, and we don't have one on file for @ColemanTom. In order for us to review and merge your code, please e-sign the PDF at https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement. We then need to manually verify your signature. We will ping the bot to refresh the PR status when we have confirmed your signature.
> 
> This was signed prior to submitting the merge request.

The CLA signature needs a manual review step, so that's why this was flagged as unsigned earlier.

**Comment by ColemanTom** [comment]
> @anaconda-issue-bot check

The windows test failed, I'm guessing there is flakiness in the tests? Can they be rerun? This change should have had no impact to the failed test.

**Comment by ColemanTom** [comment]
> > @anaconda-issue-bot check
> 
> The windows test failed, I'm guessing there is flakiness in the tests? Can they be rerun? This change should have had no impact to the failed test.

Windows tests failed again. Can the pipeline be rerun?

**Review by jezdez — APPROVED** [review]
LGTM

**Pull request merged**
