### PR TITLE
alternate for #3362 ftp timeout

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by kalefranz** [comment]
@mingwandroid How about this instead of #3362?

We can also hard-code that `None` value to 10 if you'd prefer...

**Comment by mingwandroid** [comment]
Hi @kalefranz, I picked 10 after reading http://docs.python-requests.org/en/master/user/advanced/

> It's a good practice to set connect timeouts to slightly larger than a multiple of 3, which is the default TCP packet retransmission window.

.. because it seems to me that setting `timeout = None` would lead to hanging CI systems :

> If the remote server is very slow, you can tell Requests to wait forever for a response, by passing None as a timeout value and then retrieving a cup of coffee.

**Comment by mingwandroid** [comment]
Sorry, I just saw your comment, yes please, 10 seems prudent.

**Comment by mingwandroid** [comment]
Thanks.

**Pull request merged**
