### PR TITLE
Avoid the Windows file lock by moving files to a trash directory

### LINKED ISSUE #1001: Avoid the Windows file lock
An idea to avoid the file lock is to move files (which I believe Windows allows) that can't be deleted into some trash directory, which is deleted on future runs of conda. We could do this automatically on a file-by-file basis.

### PR DESCRIPTION
**Pull request by asmeurer**
This lets you update Python, pycosat, and psutil in the root environment. 

Conda moves all files that it can't delete to a trash directory. Conda attempts to clear the trash directory every time it links a package.  This typically will not actually work until the next time conda is run.

Preliminary tests indicate this is working, but obviously it needs a lot more testing.  If you do test, I highly recommend installing a new Miniconda, as the risk of borking your existing installation is still high. 

Fixes #1001.

### CODE REVIEW

**Comment by asmeurer** [comment]
Known issue: a lot of "access is denied" errors are printed to the screen on installation.

**Comment by asmeurer** [comment]
TODO:

- [ ] Test envs dirs stuff
- [ ] Put the trash in the prefix, not the envs dir (negates the above)
- [ ] See if rm_rf does partial deletions
- [ ] Access is denied errors
- [ ] Use `tasklist /m` somehow?

**Comment by asmeurer** [comment]
An error I got changing Python versions:

```

C:\Users\Aaron Meurer\Documents\GitHub\conda>"C:\Users\Aaron Meurer\Miniconda3
-test\Scripts\conda.exe" install python=3
Fetching package metadata: ......
Solving package specifications: .......
Package plan for installation in environment C:\Users\Aaron Meurer\Miniconda3-te
st:

The following packages will be UPDATED:

    conda:     3.8.4-py27_0 defaults --> 3.8.4-py34_0 defaults
    conda-env: 2.0.2-py27_0 defaults --> 2.0.2-py34_0 defaults
    pycosat:   0.6.1-py27_0 defaults --> 0.6.1-py34_0 defaults
    python:    2.7.9-1      defaults --> 3.4.2-1      defaults
    pyyaml:    3.11-py27_0  defaults --> 3.11-py34_0  defaults
    requests:  2.5.1-py27_0 defaults --> 2.5.1-py34_0 defaults

Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Aaron Meurer\Miniconda3-test\Scripts\conda-script.py", line 4,
in <module>
  File "c:\users\aaron meurer\documents\github\conda\conda\cli\main.py", line 20
2, in main
    args_func(args, p)
  File "c:\users\aaron meurer\documents\github\conda\conda\cli\main.py", line 20
7, in args_func
    args.func(args, p)
  File "c:\users\aaron meurer\documents\github\conda\conda\cli\main_install.py",
 line 46, in execute
    install.install(args, parser, 'install')
  File "c:\users\aaron meurer\documents\github\conda\conda\cli\install.py", line
 412, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "c:\users\aaron meurer\documents\github\conda\conda\plan.py", line 498, i
n execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "c:\users\aaron meurer\documents\github\conda\conda\instructions.py", lin
e 134, in execute_instructions
    getLogger('progress.update').info((arg, state['i']))
  File "C:\Users\Aaron Meurer\Miniconda3-test\lib\logging\__init__.py", line 116
0, in info
  File "C:\Users\Aaron Meurer\Miniconda3-test\lib\logging\__init__.py", line 127
9, in _log
  File "C:\Users\Aaron Meurer\Miniconda3-test\lib\logging\__init__.py", line 128
9, in handle
  File "C:\Users\Aaron Meurer\Miniconda3-test\lib\logging\__init__.py", line 132
9, in callHandlers
  File "C:\Users\Aaron Meurer\Miniconda3-test\lib\logging\__init__.py", line 757
, in handle
  File "c:\users\aaron meurer\documents\github\conda\conda\console.py", line 47,
 in emit
    progress.update(n)
  File "c:\users\aaron meurer\documents\github\conda\conda\progressbar\__init__.
py", line 283, in update
    self.fd.write(self._format_line() + '\r')
LookupError: unknown encoding: cp437

```

I don't know if this is a bug in conda or if it's due to pulling out DLLs from under Python.

**Comment by asmeurer** [comment]
I have no idea how to fix these mock tests.

**Comment by asmeurer** [comment]
Annoyingly, the above error is only triggered if you don't use `--debug`.

**Comment by asmeurer** [comment]
I've only seen it happen when moving from Python 2 to Python 3. Unfortunately, this is something that people try to do.

**Comment by asmeurer** [comment]
Heh, so catching LookupError on that line fixes it. I'm still quite concerned, though.

**Comment by ilanschnell** [comment]
I just gave it a try on Windows XP, it updated from Python 2.7.7 to 2.7.9 without any problems.  Great!

**Comment by asmeurer** [comment]
Anyway, don't merge at least until all of [these](https://github.com/conda/conda/pull/1133#issuecomment-73159998) are checked off.

**Comment by ilanschnell** [comment]
Yes, testing is critical here, because otherwise people are likely to hose their installations.

**Comment by almarklein** [comment]
> I just gave it a try on Windows XP, it updated from Python 2.7.7 to 2.7.9 without any problems. Great!

This does not necessarily mean that it works. The current behavior was (or at least has been at some point) that if during updating a package, a file could not be overwritten, that it was silently ignored.

**Comment by almarklein** [comment]
Looking forward to have this functionality BTW: it means users of Pyzo can safely update packages from inside the shell!

**Comment by asmeurer** [comment]
Right, we should look at changing that behavior. In the mean time, you should test this with `conda --debug`, which will show all errors and warnings.

**Comment by Maggie-M** [comment]
I've managed to set up the environment and went through the steps Aaron describes [here](https://github.com/conda/conda/issues/583#issuecomment-36263639).  I can confirm that it seems to be fixed.  I haven't yet been able  to cover any of the other checkboxes listed in the pull request (I would need more information about what to do).

Also, is there a testing plan for conda documented anywhere that covers all the bases?

**Comment by asmeurer** [comment]
I think for this PR the different bases would just be admin vs. non-admin install, and probably different Windows versions.

**Comment by Maggie-M** [comment]
I've managed to complete the testing from the first checkbox (test envs dirs stuff), and I didn't run into any issues.  It all seems to be working correctly.

**Comment by asmeurer** [comment]
This is pretty much ready for merging. I have left the `win_ignore_root` in for now (so conda still won't update Python in the root environment), as I'd like to make sure there are no other issues with this before we potentially break people's installations. I'd also like to eventually move this logic to `rm_rf` and use that everywhere instead of `unlink`, but that's a future TODO.

**Comment by ilanschnell** [comment]
Looks great.  Thanks for the effort Aaron.

**Comment by almarklein** [comment]
@asmeurer Does this apply to any package with binary modules, or only to Python, pycosat, and psutil? (Going to test this in a minute, but would like to know whether it's intended to work.)

**Comment by ilanschnell** [comment]
This applies to any packages, which contain files that are opened by a process and then not closed.  So yes, any package with binary modules, but it could also be any other file which is open.

**Comment by almarklein** [comment]
Awesome :)

**Pull request merged**
