### PR TITLE
Enabling "conda run" to display real time output for the subprocess

### PR DESCRIPTION
**Pull request by gabrielcnr**
This enables the command `conda run` to display the live output from the subprocess's stdout and stderr, in real time.

The current behaviour-- which prints the stdout and stderr only after the process has finished --remains unchanged. 

The `conda run` command now can take a flag `--live-stream` which would flip the behaviour to provide the real time output.

I believe this is related to: https://github.com/conda/conda/issues/9412

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hi @chenghlee, could you please take a look on this PR?

**Review by mingwandroid — APPROVED** [review]
LGTM. I'd probably say it should be the default to be honest with you. Also, can you handle stdin here? Seems like it should be possible.

**Comment by gabrielcnr** [comment]
I think this should be the default too. I didn't make it, because I wasn't sure if would be desirable to break the current behaviour, so I opted for keeping it backwards compatible. But I guess the impact of the change is not big.
As for the stdin, I think we can address that in a separate PR in the future. What do you think @mingwandroid, @marcelotrevisani ?

**Comment by marcelotrevisani** [comment]
> I think this should be the default too. I didn't make it, because I wasn't sure if would be desirable to break the current behaviour, so I opted for keeping it backwards compatible. But I guess the impact of the change is not big.
> As for the stdin, I think we can address that in a separate PR in the future. What do you think @mingwandroid, @marcelotrevisani ?

I agree that @mingwandroid suggestion can be addressed after as the modification to also support the stdin will be a bit more complicated to implement. And I also agree with @mingwandroid that it should be the default behaviour.

**Comment by gabrielcnr** [comment]
Thanks for the feedback @marcelotrevisani and @mingwandroid. As part of this PR, can you please confirm if I should:

1) make `True` the default option for the `--live-stream` flag
or
2) remove the `--live-stream` flag entirely, but keep the live stream behaviour as the new default behaviour
or
3) nothing

Please let me know and I will happily make the changes. Thank you.

**Comment by marcelotrevisani** [comment]
> Thanks for the feedback @marcelotrevisani and @mingwandroid. As part of this PR, can you please confirm if I should:
> 
> 1. make `True` the default option for the `--live-stream` flag
>    or
> 2. remove the `--live-stream` flag entirely, but keep the live stream behaviour as the new default behaviour
>    or
> 3. nothing
> 
> Please let me know and I will happily make the changes. Thank you.

I believe that is a question for @chenghlee or @mingwandroid 
But anyways we could try to merge it as it is and next release we can let it as a default, but I believe @chenghlee is leading the conda releases so he should know what is the best decision for conda in this case

**Comment by marcelotrevisani** [comment]
just one thing, could you please resolve the conflicts with your PR?

**Comment by chenghlee** [comment]
> > Thanks for the feedback @marcelotrevisani and @mingwandroid. As part of this PR, can you please confirm if I should:
> > 
> > 1. make `True` the default option for the `--live-stream` flag
> >    or
> > 2. remove the `--live-stream` flag entirely, but keep the live stream behaviour as the new default behaviour
> >    or
> > 3. nothing
> > 
> > Please let me know and I will happily make the changes. Thank you.
> 
> I believe that is a question for @chenghlee or @mingwandroid
> But anyways we could try to merge it as it is and next release we can let it as a default, but I believe @chenghlee is leading the conda releases so he should know what is the best decision for conda in this case

For now (i.e., the 4.9.0 release), let's just leave it as is (i.e., option 3 -- do nothing), since this is a new behavior and I want to avoid any surprises for current users.

I agree that that `--live-stream` should be the default, but we should roll that change into the 5.0.0 release, where we're planning on making a bunch of other default behavior changes. 5.0.0 is currently scheduled for late 2020-Q4/early 2020-Q1, and that should give us enough time for users to test out this feature and for us to announce upcoming major changes.

**Comment by chenghlee** [comment]
Once I'll unbreak the CI system, I'll review and merge this PR. Expect that to happen sometime later today.

**Comment by jonashaag** [comment]
Pardon the naive question but what is the point of `--live-stream` when we have `--no-capture-output`?

**Pull request merged**
