### PR TITLE
fix millisecond timestamps

### PR DESCRIPTION
**Pull request by kalefranz**

### CODE REVIEW

**Comment by msarahan** [comment]
sorry, this seems very dangerous to me.  What happens in 2019 when real timestamps get affected like this?

what actual issue does having the timestamps cause?  If it's just that you don't like it, I'm sorry.  I need actual examples of something this breaks.

**Comment by kalefranz** [comment]
No, I'm sorry. This is exactly the type of thing that our team gets in trouble for with going against what the majority of people would consider a standard.  The name of the field is "timestamp".  It's an integer.  It "looks" like a unix timestamp, going by the first couple numbers, which don't often change.  So plug it into https://www.unixtimestamp.com/index.php, for example, which is the second timestamp convertor that google comes up with for me.  You get something in year 49302.  WTF.  (The first timestamp convertor according to google does give you the correct answer, but with the "assuming this timestamp is in milliseconds" caveat".)

What does it break?  Python.  Specifically `datetime.fromtimestamp()`.

Please, let's fix it now before it *is* too late.

**Comment by kalefranz** [comment]
I've fixed the 2019 cutoff issue.  That would have indeed been bad.  But the year 9999 works just fine I think.

**Comment by msarahan** [comment]
Please step down from your soapbox.  This was a mistake, and I regret it.  The timestamp field was created as nothing more than a sorting key for tiebreaking.  You are now using it for a more public-facing detail - building the package list.  That's separate from conda's representation.  I'm fine with this solution, but because of the potential confusion in changing format, I will not support changing conda-build to output timestamps in any way other than they are now.

**Comment by kalefranz** [comment]
repodata.json is very much public facing Mike.  Can we at least fix keep the fix in the `conda index` command?

**Comment by msarahan** [comment]
sure, that's fine.  I'm just not going to change the actual stored data in the package.  You can reinterpret any way you want.  but the index.json file needs to stay the same, for sanity's sake.

**Comment by dhirschfeld** [comment]
Just jumping in here from ContinuumIO/anaconda-issues#7469 but also because the timestamp issue just came up again for me.  I think the time a package is built is a very valuable piece of information, especially when debugging.

As a user I would like to be able to see or easily find out the time any particular package was built ...which makes the current implementation somewhat problematic because not only is the current timestamp not human-readable but it's got a difficult-to-discover magic factor of 1000 difference from the obvious (to an experienced dev) unix timestamp.

I'm fine which the timestamp value being kept as-is but I think it would be very useful if the output of `conda info <package_name>` did the conversion behind the scenes to output a human readable timestamp.

I think the timestamp info is that useful that I'd also like a `--with-timestamp` argument to `conda list` which would include the converted/human-readable timestamp in the output.

Not high-priority but I'm happy to open separate issues to track them if they're considered reasonable/feasible feature requests.

**Pull request merged**
