### PR TITLE
Use `python_site_packages_path` when specified

### LINKED ISSUE #14053: `noarch: python` packages are not importable when installed with the experimental free-threading Python 3.13 build
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Installing `noarch: python` packages in an environment with a free-threading version of Python 3.13 results in the package contents not being available for import. 

```
❯ conda create -n bug -c ad-testing/label/py313_nogil python=3.13.0b4 pip --yes
Channels:
 - ad-testing/label/py313_nogil
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jhelmus/mc/envs/bug

  added / updated specs:
    - pip
    - python=3.13.0b4


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-arm64::bzip2-1.0.8-h80987f9_6
  ca-certificates    pkgs/main/osx-arm64::ca-certificates-2024.7.2-hca03da5_0
  expat              pkgs/main/osx-arm64::expat-2.6.2-h313beb8_0
  libcxx             pkgs/main/osx-arm64::libcxx-14.0.6-h848a8c0_0
  libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_1
  ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0
  openssl            pkgs/main/osx-arm64::openssl-3.0.14-h80987f9_0
  pip                ad-testing/label/py313_nogil/osx-arm64::pip-24.1.2-py313_0
  python             ad-testing/label/py313_nogil/osx-arm64::python-3.13.0b4-h99e199e_nogil_0
  python_abi         ad-testing/label/py313_nogil/osx-arm64::python_abi-3.13-4_cp313t
  readline           pkgs/main/osx-arm64::readline-8.2-h1a28f6b_0
  sqlite             pkgs/main/osx-arm64::sqlite-3.45.3-h80987f9_0
  tk                 pkgs/main/osx-arm64::tk-8.6.14-h6ba3021_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  xz                 pkgs/main/osx-arm64::xz-5.4.6-h80987f9_1
  zlib               pkgs/main/osx-arm64::zlib-1.2.13-h18a0788_1



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate bug
#
# To deactivate an active environment, use
#
#     $ conda deactivate


❯ conda activate bug
❯ python --version
Python 3.13.0b4
❯ python -c "import pip; print(pip.__version__)"
24.1.2

❯ conda install -c defaults -c conda-forge imagesize --yes
Channels:
 - defaults
 - conda-forge
 - ad-testing/label/py313_nogil
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jhelmus/mc/envs/bug

  added / updated specs:
    - imagesize


The following NEW packages will be INSTALLED:

  imagesize          pkgs/main/noarch::imagesize-1.3.0-pyhd3eb1b0_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

❯ python -c "import imagesize"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import imagesize
ModuleNotFoundError: No module named 'imagesize'

```

The issue here is that the `noarch: python` package is installed into `<PREFIX>/lib/python3.13/site-packages` but the free-threading libraries are expected in `<PREFIX>/lib/python3.13t`, see python/cpython#121103:

```
❯ ls ~/mc/envs/bug/lib/python3.13t/site-packages
README.txt           pip                  pip-24.1.2.dist-info

❯ ls ~/mc/envs/bug/lib/python3.13/site-packages
__pycache__               imagesize-1.3.0.dist-info imagesize.py
```

### Conda Info

```shell
active environment : base
    active env location : /Users/jhelmus/mc
            shell level : 1
       user config file : /Users/jhelmus/.condarc
 populated config files : /Users/jhelmus/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.0
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.0=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Users/jhelmus/mc  (writable)
      conda av data dir : /Users/jhelmus/mc/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jhelmus/mc/pkgs
                          /Users/jhelmus/.conda/pkgs
       envs directories : /Users/jhelmus/mc/envs
                          /Users/jhelmus/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.13 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3 aau/0.4.4 c/. s/. e/.
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/jhelmus/.condarc <==
add_pip_as_python_dependency: False
changeps1: False
ssl_verify: True
report_errors: False

==> envvars <==
allow_softlinks: False
```

### Conda list

```shell
A mess, not related to this bug :smile:
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jjhelmus**
I'm putting this up as an example and for discussion. More work is needed for a complete implementation, especially given that this one breaks backwards compatibility in various function.

### Description

When the `python` package in an environment specifies a `python_site_packages_path` in its repodata entry, use that path to install `noarch: python` packages.  

Note that this currently only works with the classic solver as libmamba/conda-libmamba-solver does not yet understand this field. 

Close #14053.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jjhelmus** [comment]
An example of this:
```
❯ conda create -n example -c jjhelmus/label/sp_path -c conda-forge python=3.99.90 imagesize --solver classic --yes
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jhelmus/workspace/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/example

  added / updated specs:
    - imagesize
    - python=3.99.90


The following NEW packages will be INSTALLED:

  imagesize          conda-forge/noarch::imagesize-1.4.1-pyhd8ed1ab_0 
  python             jjhelmus/label/sp_path/noarch::python-3.99.90-0 



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate example
#
# To deactivate an active environment, use
#
#     $ conda deactivate

❯ tree /Users/jhelmus/workspace/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/example
/Users/jhelmus/workspace/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/example
├── conda-meta
│   ├── history
│   ├── imagesize-1.4.1-pyhd8ed1ab_0.json
│   └── python-3.99.90-0.json
└── sample_path
    └── from_the_file
        └── index_json
            ├── imagesize
            │   ├── __init__.py
            │   └── imagesize.py
            └── imagesize-1.4.1.dist-info
                ├── INSTALLER
                ├── LICENSE.rst
                ├── METADATA
                ├── RECORD
                ├── REQUESTED
                ├── WHEEL
                ├── direct_url.json
                └── top_level.txt

7 directories, 13 files
```

The `python` package used here was created with conda-build that includes the change from conda/conda-build#5502.

**Review by jezdez — APPROVED** [review]

**Comment by jjhelmus** [comment]
In ea89bc0 I added unit test to validate the noarch: python packages get installed into the path specified by the `python_site_packages_path` field. This uses one of the sample, empty packages made in conda/conda-build#5502 which is in my channel on anaconda.org. I'd be in favor or a more robust solution for testing if there are any suggestions.

**Comment by jezdez** [comment]
@jjhelmus You're right, we're trying to move away from relying on hosted pacakges, and have added [`test_recipes_channel`](https://github.com/conda/conda/blob/015d49aa28f1113ddfabcf7ec157dd02aca9ab3c/tests/conftest.py#L38-L50) pytest fixture (which is used in [a number of places](https://github.com/search?q=repo%3Aconda%2Fconda+test_recipes_channel+path%3A%2F%5Etests%5C%2F%2F&type=code)) that points the tests to the `tests/test-recipes` directory, in which we basically store slimmed down variants of packages for testing purposes, that we converted in #12879.

Could you add a custom python package to the directory and rely on it in your test?

cc @kenodegard since you may thoughts on this one

**Comment by jjhelmus** [comment]
> Could you add a custom python package to the directory and rely on it in your test?

This is exactly what I was looking for. I'll update the PR to use this fixture and add the necessary packages. Thanks much.

**Comment by jjhelmus** [comment]
Test was updated to use the `test_recipes_channel` pytest fixture with two embedded packages.

**Comment by jjhelmus** [comment]
The single failing test, `FAILED tests/core/test_solve.py::test_solve_1[libmamba]` looks unrelated to this change.

**Review by beeankha — APPROVED** [review]

**Comment by jjhelmus** [comment]
In order for this field to be usable with the `libmamba` solver, libmamba-conda-solver needs to pass this field, see conda/conda-libmamba-solver#560. This in turn requires mamba to support this field (mamba-org/mamba#3558) which mamba-org/mamba#3579 is a start of.

**Comment by jezdez** [comment]
@jaimergp do you feel like this should be bumped to January to wait for the CLS implementation?

**Comment by jaimergp** [comment]
Not sure if we want to wait two months "just in case". There's a chance that the mamba folks release that sooner than the January release, and in that case users would only need to update the libmamba version (I assume conda-libmamba-solver would be compatible with the new field by then; if it's not yet, then the necessary PR would be trivial). All of this makes me think that no, it's not necessary.

That said:

- The mamba PR is targeting v2, which is not even on `defaults` yet (is there a request already up?).
- Do we want libmamba v1 (and thus conda-libmamba-solver <=24.9) compatibility?

**Comment by jezdez** [comment]
> Not sure if we want to wait two months "just in case". There's a chance that the mamba folks release that sooner than the January release, and in that case users would only need to update the libmamba version (I assume conda-libmamba-solver would be compatible with the new field by then; if it's not yet, then the necessary PR would be trivial). All of this makes me think that no, it's not necessary.

I concur, let's merge this, since it would only start to work if we add the field anyways

> 
> That said:
> 
> * The mamba PR is targeting v2, which is not even on `defaults` yet (is there a request already up?).

I just opened the package update request

> * Do we want libmamba v1 (and thus conda-libmamba-solver <=24.9) compatibility?

My guess is that this won't be possible, since the mamba team unlikely will want to add new features to 1.x right?

**Review by jezdez — APPROVED** [review]

**Pull request merged**
